### ISSUE TITLE
左/右位移沒有解釋UB的情況

### ISSUE THREAD

**Issue by Voileexperiments** [OI-wiki/OI-wiki#1019]
[this](https://github.com/24OI/OI-wiki/blob/master/docs/math/bit.md):

> !!! warning 我们平常写的除法是向 0 取整，而这里的右移是向下取整（注意这里的区别），即当数大于等于 0 时两种方法等价，当数小于 0 时会有区别，如： $-1 \div 2 = 0$ , 而 $-1 >> 1 = -1$

C++標準裡左/右位移(`x << y`/`x >> y`)僅對於`x`為**非負數**且結果可表示時有定義值,不然是UB: https://stackoverflow.com/a/8416000

在UB下編譯器可以假設`x`為非負數而進行優化, 例如有`foo(int x) { if (x >= 0) printf("Kaboom!"); int y= x<<4; }`, 在-O2以上`foo(-1);`會導致`"Kaboom!"`: https://godbolt.org/z/haY9UN

這代碼也同理:

```
int mulTwo(int n) {  // 计算 n*2
  return n << 1;
}
```

signed type的左位移在結果把1左移到sign bit或以左位置時也是UB

**Comment by Ir1d** [comment]
谢谢！这个问题之前没注意到
不过我好像并没能 Kaboom……
另外搜了下，http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1905.pdf P99 好像说的是 implementation-defined，以及，https://stackoverflow.com/questions/7622/are-the-shift-operators-arithmetic-or-logical-in-c 提到大部分是 arithmetic shift

以及 Shift amount < 0 or ≥ word size 的时候 ub 我觉得的确需要注明上去，思考一下怎么写 :thinking:

**Comment by Voileexperiments** [comment]
> upd: http://eel.is/c++draft/expr.shift 这里似乎意思是新版里已经规定了（？

> The behavior is undefined if the right operand is negative, or greater than or equal to the range exponent of the promoted left operand.

**Comment by Ir1d** [comment]
我说负数的左移右移好像已经定义了

**Comment by kawa-yoiko** [comment]
同不能 kaboom，而且一个操作的 ub 不同于函数开头的 `assert()`，即使编译器定义「左操作数为负时程序崩溃」，也并不会因此假设此前 `x >= 0` 条件必须成立。

另外[补码写进 C/C++ 标准也是最近才提出来](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0907r4.html)，这么说大家都是随手就 ub 了呢……

可以说所有在算法竞赛中使用的编译器 (Clang, GCC, MSVC) 对于有符号数都执行逻辑左移和算术右移，所有竞赛平台也都采用补码表示有符号数。这么看来就没有太大必要去避免 `>>` 了吧…… Wiki 上写一句「本文假设这种定义，它与算法竞赛和绝大多数实际情况相符」这样的就行。

个人意见仅作参考啦。

**Comment by Voileexperiments** [comment]
我覺得UB還是提示一下好,不小心寫出OB導致segfault需要幫忙debug的情況看過不少了(

就算隨手UB沒kaboom,這種習慣還是不好的

**Comment by kawa-yoiko** [comment]
嗯嗯，开头或者什么地方提一下，大家知道就好了嘛…… 毕竟是个挺特别的 ub……
