### ISSUE TITLE
加个 Reference 或者「前置知识」

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1037]
有道理...其实我一直觉得应该加个 Reference 或者「前置知识」的...

_Originally posted by @Marcythm  in https://github.com/24OI/OI-wiki/issues/1028#issuecomment-469681731_

**Comment by abc1763613206** [comment]
附议

**Comment by StudyingFather** [comment]
+1

这样梳理知识应该就更方便了（

**Comment by yizr-cnyali** [comment]
+2
应该能避免在**OI-Wiki**上自学的时候盲目乱搞,造成不必要的时间损耗

**Comment by partychicken** [comment]
+3

所以前置知识都要加些什么？

**Comment by huhaoo** [comment]
> +3
> 
> 所以前置知识都要加些什么？

update时自己填写？

**Comment by GavinZhengOI** [comment]
+4

**Comment by cmpute** [comment]
我在写内容的时候经常会想如果看到这不懂怎么办，因此如果不在文中使用链接的话，还是很有必添加前置知识说明的，否则会极大影响学习效率。

**Comment by Enter-tainer** [comment]
支持（是不是应该写进 meta 里？（等一个有空的好心人））

**Comment by ouuan** [comment]
（不是在文章开头说一下就好了吗）
