### ISSUE TITLE
add finger tree, 2-3 tree

### ISSUE THREAD

**Issue by Voileexperiments** [OI-wiki/OI-wiki#1039]
- 希望添加的是什么？
^

- 英文叫什么？
^

- 有什么参考资料？
https://zhuanlan.zhihu.com/p/30589105

不會finger tree qaq

**Comment by Enter-tainer** [comment]
补充一些资料链接：

[原论文链接](http://www.staff.city.ac.uk/~ross/papers/FingerTree.pdf)
[一些例子](http://www.staff.city.ac.uk/~ross/papers/FingerTree.html)

虽然我也没学会就是了
