### ISSUE TITLE
add 可追溯化数据结构

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#1041]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
可追溯化数据结构

- 英文叫什么？
Retroactive Data Structures

- 有什么参考资料？
WC2019的营员交流课件以及kczno1的集训队论文

issue 标题请写为 'add ' + 要添加的内容

**Comment by WAAutoMaton** [comment]
该算法至今在算法竞赛中出现过例题，根据 OI Wiki 现行方针予以关闭

若今后出现应用可新开 issue 或重新开启本 issue
