### ISSUE TITLE
Searching problem

### ISSUE THREAD

**Issue by Tiger3018** [OI-wiki/OI-wiki#1069]
- 是出现了什么问题？（最好截图）

搜索结果若是某部分的简介，会链接到 `/xxx/index/` 导致 404

- 如何复现？

请搜索“简介”二字。

**Comment by ChungZH** [comment]
已复现！

**Comment by frank-xjh** [comment]
This a feature,not a bug!!!

**Comment by Ir1d** [comment]
感谢反馈，我找到问题是出在哪了
等过几天有空了就修

**Comment by ChungZH** [comment]
> 
> 
> This a feature,not a bug!!!

😂 😂 😂

**Comment by Planet6174** [comment]
> 感谢反馈，我找到问题是出在哪了
> 等过几天有空了就修

催更（

**Comment by CBW2007** [comment]
> > 感谢反馈，我找到问题是出在哪了
> > 等过几天有空了就修
> 
> 催更（

催更*2

**Comment by Ir1d** [comment]
现在应该已经修复了.. 如果有问题麻烦清除浏览器缓存试试..
当然这个 elasticsearch 经常自己崩坏 :new_moon_with_face: ，有时候搜不到东西可能是 els 自己 down 了..
