### ISSUE TITLE
add 线段树的一些变种

### ISSUE THREAD

**Issue by YZircon** [OI-wiki/OI-wiki#1167]
- 希望添加的是什么？
就是一些线段树的变种,比如超哥线段树、zkw线段树和吉司机线段树之类的

**Comment by StudyingFather** [comment]
@yizr-cnyali 这个赞同（

**Comment by yizr-cnyali** [comment]
> 这个不叫变种吧。。。？李超线段树可能更接近「变种」一点？
> 但是 zkw 线段树本质上没有多大区别啊。。。segment tree beats 也没有超出「线段树」的范围啊？就是对一类特殊操作的解决方法吧？

我的意思大概就是把这一类的东西加进去  
zkw线段树确实不像是变种。。。 
总之就是这个意思  
具体实现的话我觉得可以把区别不打的放在线段树那一页  
然后能算是变种的再新开
@TrisolarisHD

**Comment by TrisolarisHD** [comment]
嗯 资磁

**Comment by WAAutoMaton** [comment]
李超线段树，吉司机线段树目前已加入 OI-Wiki

zkw 线段树作为一种卡常技巧，加入 wiki 的必要性不显著，若后续认为仍有必要加入可新开 issue

因此本 issue 已完成使命
