### ISSUE TITLE
编辑器页面分拆

### ISSUE THREAD

**Issue by abc1763613206** [OI-wiki/OI-wiki#1229]
idea来自Telegram[群内](https://t.me/OIwiki)讨论，具体优劣可继续讨论。
```
Trisolaris HD, [24.05.19 22:50]
[回复 Ir1d XD+]
是...我想拆成子页面
Shuhao Zhang, [24.05.19 22:50]
分拆是个好方案
Trisolaris HD, [24.05.19 22:50]
[回复 [New86]asfr |abc1763613206]
好像听到有人在说我
Shuhao Zhang, [24.05.19 22:50]
目前的情况是这个页面实在太长了
Ir1d XD+, [24.05.19 22:51]
[回复 Trisolaris HD]
拆！
```

**Comment by abc1763613206** [comment]
Arbiter 那里内容太多了，要不要和编辑器一样拆掉？

_Originally posted by @abc1763613206 in https://github.com/OI-wiki/gitment/issues/68#issuecomment-496839623_

**Comment by abc1763613206** [comment]
另外分拆后的页面要不要整理到一个文件夹里去？

**Comment by abc1763613206** [comment]
还有新页面的Issue还没有人建

**Comment by yizr-cnyali** [comment]
> Arbiter 那里内容太多了，要不要和编辑器一样拆掉？
> 
> _Originally posted by @abc1763613206 in [OI-wiki/gitment#68 (comment)](https://github.com/OI-wiki/gitment/issues/68#issuecomment-496839623)_
评测工具要拆的话我今晚去搞吧 @abc1763613206
