### ISSUE TITLE
树状数组页面代码格式混乱

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/OI-wiki#1250]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
树状数组页面代码格式混乱，大括号时而换行，时而不换行。
https://github.com/24OI/OI-wiki/blob/master/docs/ds/bit.md#L72

- 你是否正在着手修复？
没有
- 如何复现？

**Comment by Ir1d** [comment]
Thx，我觉得还是抽空跑一下 clang-format 比较好，等放假我重写一下 lint 规则吧

**Comment by partychicken** [comment]
fixed
