### ISSUE TITLE
新高三选手打算鸽掉的内容

### ISSUE THREAD

**Issue by Planet6174** [OI-wiki/OI-wiki#1252]
我，Planet6174，高三了  
挖的坑，填了，简单的，一半 ~~居然排在 Contribute 榜第九 感人至深~~  
比较耗时的，估计，一年内，搞不了

康康有没有哪位小可爱能来填了我挖的坑 qwq

- [x] [OI Wiki - DFS 序](https://oi-wiki.org/graph/dfs-order/)：在写这个之前可能先得把 LOJ 上 DFS 序系列题修一遍，目前的数据还是区分不开较快的树剖和较慢的正解；还要填上树上差分 2 的坑
- [x] 树形背包这个……坐等 ouuan 搬运 Ta 的博客
- [x] [欧拉图](https://oi-wiki.org/graph/euler/)：补充一些例题
- [x] [置换群](https://oi-wiki.org/math/permutation-group/)：也是一个基础内容 ~~我之前拿去出给小学生做~~
- [x] [Catalan 数](https://oi-wiki.org/math/catalan/)：本来想搬运[我儿时写的博文](https://www.cnblogs.com/P6174/p/7299691.html)，但是感觉还需要再写一点 Catalan 数与生成函数、与 DP 结合的内容
- [ ] 线段树与离线询问结合的问题，代表题 [【清华集训 2014】mex](http://www.tsinsen.com/A1513)，这种题挺常见的，不过这部分内容是放【线段树】里还是新开一个页面？

**Comment by Ir1d** [comment]
@Planet6174 Catalan 数 我可以 handle（鸽到暑假
树型背包 要 at 一下 @ouuan

**Comment by TrisolarisHD** [comment]
您...您是 2017 级的？（目瞪口呆.webp

**Comment by Great-designer** [comment]
欧拉图已经有了。线段树与离线询问结合的问题，不知 #4275 算不算
