### ISSUE TITLE
四边形不等式优化 作者缺失

### ISSUE THREAD

**Issue by zyf0726** [OI-wiki/OI-wiki#1253]
我是四边形不等式优化页面的主要贡献者，但是DP优化这一节的结构调整之后，我就不在贡献者列表里了，能否手动添加一下，谢谢！

Update optimization.md #1054

================================

首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

- 你是否正在着手修复？

- 如何复现？

issue 标题请写为 要汇报的主要内容

**Comment by Ir1d** [comment]
hi, 感谢反馈～
由于 github 特性，目前页面移动之后统计信息会出问题。
我们计划是日后（不晚于今年暑期）改成手工维护。
如果比较急迫，可以参考 #1192 在页面下方注明一下

ref: #480

**Comment by Ir1d** [comment]
Hi，已经手动添加了～ thx
