### ISSUE TITLE
add Lucas&exLucas

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#1255]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

卢卡斯定理及其扩展

- 英文叫什么？

Lucas & exLucas

- 有什么参考资料？

还没找到...

issue 标题请写为 'add ' + 要添加的内容

**Comment by 1170300206** [comment]
We've tried to add this #1417
