### ISSUE TITLE
add wronganswer

### ISSUE THREAD

**Issue by bhuztez** [OI-wiki/OI-wiki#1265]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

wronganswer是OJ客户端

首先，可以借助wronganswer把例题解答提交到CI，确保解答是能AC的

其次，因为wronganswer特别支持现在本地编译成汇编再提交到OJ。这样，就不用考虑代码兼容不同OJ不同版本编译器了。scl可以变成一个真正意义上的库。

最后，有很多题的结果是有浮点数的，为了在本地测试时方便和标准答案对比，而不用每个题都写个格式解析。根据ANSI escape code，我们可以在本地运行时，输出一些终端上看不到的提示字符，wronganswer根据这些提示，就知道接下来要比较的是浮点数，最小浮点误差是多少。

- 英文叫什么？

wronganswer 

- 有什么参考资料？

https://github.com/bhuztez/wronganswer

**Comment by diauweb** [comment]
此项目似乎已经不见了，大概可以close了
