### ISSUE TITLE
add min-max容斥

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#1266]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

min-max容斥

- 英文叫什么？

min-max inclusion exclusion principle

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by TrisolarisHD** [comment]
@StudyingFather 考虑一下 https://blog.trisolaris.top/notes/max-min-identity/ 加几道例题？（菜鸡自荐.webp
