### ISSUE TITLE
add min_25筛&洲阁筛

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#1273]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
min_25筛&洲阁筛

- 英文叫什么？

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by TrisolarisHD** [comment]
@StudyingFather 考虑一下 https://blog.trisolaris.top/notes/prefix-sum-of-multiplicative-functions/ 加几道例题？（菜鸡自荐*2

**Comment by TrisolarisHD** [comment]
@TrisolarisHD （我本来打算暑假搬的

**Comment by TrisolarisHD** [comment]
现在 min25 筛已经有了，这个要 close 吗？还是等一个洲阁筛（

**Comment by StudyingFather** [comment]
@TrisolarisHD 等洲阁筛放上去再说吧（

**Comment by Early0v0** [comment]
我来写洲阁筛了（
