### ISSUE TITLE
add Bell Number

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1275]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
Bell Number

- 英文叫什么？
Bell Number

- 有什么参考资料？

http://mathworld.wolfram.com/BellNumber.html
https://en.wikipedia.org/wiki/Bell_number
https://blog.csdn.net/winycg/article/details/70233717

issue 标题请写为 'add ' + 要添加的内容

**Comment by StudyingFather** [comment]
added in #2427.
