### ISSUE TITLE
add 二次剩余

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1277]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
二次剩余

- 英文叫什么？
quad-residue

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by ShaoChenHeng** [comment]
我目前正在编写这个内容．
