### ISSUE TITLE
搜索栏无法搜索？

### ISSUE THREAD

**Issue by XZJIsme** [OI-wiki/OI-wiki#1290]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x ] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

搜索栏无法搜索：
<img src="http://chuantu.xyz/t6/702/1562290501x992245975.png">

- 你是否正在着手修复？
False

- 如何复现？

issue 标题请写为 要汇报的主要内容

**Comment by abc1763613206** [comment]
已复现，感谢！
![image](https://user-images.githubusercontent.com/30773956/60694600-31c89480-9f11-11e9-89d1-e7bf71d8b4f7.png)

**Comment by Ir1d** [comment]
@abc1763613206 现在好了吧.. 重启了 els.. 强刷一下康康？

**Comment by Ir1d** [comment]
@Ir1d 感觉目前的方案有点问题啊.. 我再想想办法

**Comment by jyeric** [comment]
现在仍然无法搜索

**Comment by abc1763613206** [comment]
> @jyeric 现在仍然无法搜索    

经过调试，目前境内访问搜索服务器已经恢复正常。     
![image](https://user-images.githubusercontent.com/30773956/60722997-040d3b00-9f65-11e9-91ab-61066e447cbb.png)       

如果您仍无法搜索，请尝试关闭您所使用的代理工具。

**Comment by XZJIsme** [comment]
> > @jyeric 现在仍然无法搜索
> 
> 经过调试，目前境内访问搜索服务器已经恢复正常。
> ![image](https://user-images.githubusercontent.com/30773956/60722997-040d3b00-9f65-11e9-91ab-61066e447cbb.png)
> 
> 如果您仍无法搜索，请尝试关闭您所使用的代理工具。

似乎依旧无法使用，如图所示？
![image](https://ws3.sinaimg.cn/large/005BYqpgly1g4p91ud1n3j30p808zmzc.jpg?referrer=https://cdn.sinaimg.cn.52ecy.cn)

**Comment by abc1763613206** [comment]
> > > @jyeric 现在仍然无法搜索
> > 
> > 
> > 经过调试，目前境内访问搜索服务器已经恢复正常。
> > ![image](https://user-images.githubusercontent.com/30773956/60722997-040d3b00-9f65-11e9-91ab-61066e447cbb.png)
> > 如果您仍无法搜索，请尝试关闭您所使用的代理工具。
> 
> 似乎依旧无法使用，如图所示？
> ![image](https://camo.githubusercontent.com/abc9d13efc37596f375fc03c57ac9c01d817f28f/68747470733a2f2f7773332e73696e61696d672e636e2f6c617267652f30303542597170676c793167347039317564316e336a3330703830387a6d7a632e6a70673f72656665727265723d68747470733a2f2f63646e2e73696e61696d672e636e2e35326563792e636e)

> @XZJIsme 如果您仍无法搜索，请**尝试关闭您所使用的代理工具。**   


![image](https://user-images.githubusercontent.com/30773956/60723811-49cb0300-9f67-11e9-894f-41821a58c3aa.png)

**Comment by XZJIsme** [comment]
> > > > @jyeric 现在仍然无法搜索
> > > 
> > > 
> > > 经过调试，目前境内访问搜索服务器已经恢复正常。
> > > ![image](https://user-images.githubusercontent.com/30773956/60722997-040d3b00-9f65-11e9-91ab-61066e447cbb.png)
> > > 如果您仍无法搜索，请尝试关闭您所使用的代理工具。
> > 
> > 
> > 似乎依旧无法使用，如图所示？
> > ![image](https://camo.githubusercontent.com/abc9d13efc37596f375fc03c57ac9c01d817f28f/68747470733a2f2f7773332e73696e61696d672e636e2f6c617267652f30303542597170676c793167347039317564316e336a3330703830387a6d7a632e6a70673f72656665727265723d68747470733a2f2f63646e2e73696e61696d672e636e2e35326563792e636e)
> 
> > @XZJIsme 如果您仍无法搜索，请**尝试关闭您所使用的代理工具。**
> 
> ![image](https://user-images.githubusercontent.com/30773956/60723811-49cb0300-9f67-11e9-894f-41821a58c3aa.png)

我这个开的直连模式，不过退出了也没有用，我手机上也试过了？也许是代理工具修改了我的某些配置致使的？

**Comment by WAAutoMaton** [comment]
@XZJIsme 同样在不使用代理的情况下仍然无法使用搜索功能（ERR_CONNECTION_RESET）

**Comment by jyeric** [comment]
境内仍然无法使用
![网站Network图片](https://i.loli.net/2019/07/06/5d2099b9a55f998248.png)
直接访问页面
![直接访问图片](https://i.loli.net/2019/07/06/5d2099daaa09d26547.png)

**Comment by Ir1d** [comment]
@jyeric 嗯。。应该是炸了。。不用花时间试了。。谢谢反馈

**Comment by PersicaMoe** [comment]
同样遇到此锅，所以现在是都没法搜索吗

**Comment by jyeric** [comment]
@Ir1d @abc1763613206 我找到错误的原因了，在google chrome和firefox会因为hsts preload的原因，直接访问443端口。提示：链接已重置。而使用IE浏览器可以访问80端口时就可以找到锅了。
页面提示：
![图片地址：https://i.loli.net/2019/07/09/5d2491dfad30178940.png](https://i.loli.net/2019/07/09/5d2491dfad30178940.png)

**Comment by Ir1d** [comment]
感谢诸位关注，目前已经找到了修复办法，等待 https://github.com/OI-wiki/mkdocs-material/pull/16 和 https://github.com/OI-wiki/OI-wiki/pull/1311 通过之后就可以修复啦 :tada:
