### ISSUE TITLE
将数论、组合数学、抽象代数、线性代数、数值算法独立

### ISSUE THREAD

**Issue by FFjet** [OI-wiki/OI-wiki#1327]
组合数学内含概率期望，生成函数
抽象代数内含群论、环论、域论的基础知识（便于看懂类似`整式递推数列`这类文章
数论内含复数、高精度、初等数论等基础知识

**Comment by ouuan** [comment]
（为什么这东西还在计划里）

感觉现在在数学板块找东西更加困难了..

**Comment by ouuan** [comment]
尤其是“基础知识”和“常用算法与应试技巧”这两个分类很迷。

**Comment by Ir1d** [comment]
或者可以搞个 数学 - 杂项的分类（
