### ISSUE TITLE
add+Dev-c++ IDE、Guide（简介-工具软件-编辑工具）

### ISSUE THREAD

**Issue by luoguyuntianming** [OI-wiki/OI-wiki#1356]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
编辑工具Devc++和Guide（北航）

- 英文叫什么？
Dev-c++、Guide

**Comment by CBW2007** [comment]
这两个难道不是傻瓜级IDE吗？不需要开页面介绍吧......

**Comment by CBW2007** [comment]
而且最主要的是：这俩是集成开发环境，不是（狭义上的）编辑器啊。

**Comment by ChungZH** [comment]
我觉得不用介绍了（

**Comment by cmpute** [comment]
个人感觉IDE要么不介绍，要么就多介绍几个，code blocks，vs什么的，而且放到新的分类底下与编辑器区分一下
