### ISSUE TITLE
lint 规则有误

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1358]
![image](https://user-images.githubusercontent.com/10709657/61180737-65ac6400-a64d-11e9-9030-a8f00c8e426e.png)

docs/ds/stl/bitset.md

**Comment by sshwy** [comment]
![QAQ](https://hexo-source-1257756441.cos.ap-chengdu.myqcloud.com/2019/07/15/112017.png)

这个bot好有个性的

**Comment by Ir1d** [comment]
```
???+warning "关于函数式线段树" **函数式线段树** 是指使用函数式编程思想的线段树。在函数式编程思想中，将计算机运算视为数学函数，并避免可改变的状态或变量。不难发现，函数式线段树是[完全可持久化](/ds/persistent/#_2)的。
```

指定标题的话就会 parse 出问题.. docs/ds/persistent-seg

**Comment by Ir1d** [comment]
这一组问题我改好了，待现有 pr 合并完之后再改 bot，免得冲突了..

**Comment by Ir1d** [comment]
我思考了一下， `, ` 变成 `,` 的问题貌似可以把空格换成一个·或者别的可见字符，去掉空格是 remark-lint 自带的操作，感觉我们也不是必须要把这个 feature 去掉，就先这样吧（x
