### ISSUE TITLE
讨论：统一对数组元素的表示方式

### ISSUE THREAD

**Issue by Prurite** [OI-wiki/OI-wiki#1364]
现在常用的表示数组元素方式有以下几种：

```
不作特殊处理：对于 a\[i\]\[j\] 和 b\[k\] ……
用内联代码：对于 `a[i][j]` 和 `b[k]`……
用LaTeX+方括号：对于 $a[i][j]$ 和 $b[k]$ …… （多数人使用）
用LaTeX+下标：对于 $a_{i,j}$ 和 $b_k$ ……
```

效果如下：
![image](https://user-images.githubusercontent.com/44775584/61201850-5219ff80-a718-11e9-9f6b-3b3e42efe379.png)

个人倾向于使用第 4 种，因为表示数组元素时往往涉及数学公式，而使用下标相比方括号更和谐也更符合 LaTeX 的书写风格，在此开 issue 与各位讨论。也希望在有结果后将此条加入 contributing guidelines，作为规范。

upd1: 修正键入错误

**Comment by Alpha1022** [comment]
倾向第四种, too.

**Comment by Ir1d** [comment]
```
公式中尽量避免中括号而多使用下标。即 $a_{i,j,k}$ 而不是 $a[i][j][k]$。在公式中下标较复杂的情况下建议改用多元函数（$f(i,j,k)$）或内联代码格式
```
