### ISSUE TITLE
add 最小瓶颈路

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1388]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

最小瓶颈路，感觉加在 mst 下面就 ok 的样子

- 英文叫什么？

- 有什么参考资料？

baidu(?

https://blog.csdn.net/li1615882553/article/details/79843891

issue 标题请写为 'add ' + 要添加的内容

**Comment by ouuan** [comment]
#1450

**Comment by ouuan** [comment]
原来 #1450 是瓶颈生成树不是最小瓶颈路...
