### ISSUE TITLE
关于log是否加底数

### ISSUE THREAD

**Issue by sshwy** [OI-wiki/OI-wiki#1392]
话说写算法复杂度之类的时侯log到底加不加底数2之类的。是写成$\log n$还是$\log_2n$。如果写成$\log n$需不需要在wiki的某个角落声名一下OI的log底数默认是2QAQ

**Comment by TrisolarisHD** [comment]
@sshwy 需要啊需要啊

**Comment by Ir1d** [comment]
我觉得不需要加底数，一般底数是啥不影响复杂度的分析吧，如果有迷惑的地方加一下也无妨
找个角落声明一下似乎不错的样子，于是放哪里呢？

**Comment by yizr-cnyali** [comment]
OI中底数默认是2,但是如果是初学者可能会不知道这一点吧?

**Comment by sshwy** [comment]
要不在《复杂度》里加上 @Ir1d
