### ISSUE TITLE
Latex公式编号和目录重叠

### ISSUE THREAD

**Issue by sshwy** [OI-wiki/OI-wiki#1397]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

Latex公式编号和目录重叠

https://hexo-source-1257756441.cos.ap-chengdu.myqcloud.com/2019/07/20/215712.png

- 你是否正在着手修复？

不造咋修

- 如何复现？

https://deploy-preview-1395--oi-wiki.netlify.com/math/combination/#_14

**Comment by Ir1d** [comment]
其实是 feature.. 故意让它溢出去的..（为了手机上舒服）
叠了貌似有点难受.. 得想想办法

**Comment by TrisolarisHD** [comment]
@sshwy 在 github 上用 emoji 不是更好吗（
拒绝「/wn」从我做起.webp

**Comment by sshwy** [comment]
那么问题来了。emoji的无奈？

**Comment by Enter-tainer** [comment]
http://docs.mathjax.org/en/latest/options/input-processors/TeX.html#configure-tex

这个 TagIndent 选项有帮助吗
