### ISSUE TITLE
「更新历史」页面跳转有误

### ISSUE THREAD

**Issue by MingqiHuang** [OI-wiki/OI-wiki#1403]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

点击页面中的「更新历史」页面会跳转到 Page Not Found 页面。

- 你是否正在着手修复？

是。

- 如何复现？

例：[SAM][https://oi-wiki.org/string/sam/]，更新历史页面为 <https://github.com/OI-wiki/OI-wiki/commits/master/docs//string/sam.md.md>

看起来似乎是多了 `.md` 与一个斜线的锅。

issue 标题请写为 要汇报的主要内容

**Comment by Ir1d** [comment]
是哒
