### ISSUE TITLE
Latex displaystyle 使用场景问题

### ISSUE THREAD

**Issue by sshwy** [OI-wiki/OI-wiki#1409]
Latex displaystyle 可以把行内公式展成行间公式的形式，更易读。但在行内使用多了会破环段落完整性。所以这玩意该啥时候用？

个人感觉，如果行内分数的分子分母较复杂的时侯可以用，或者binom上下项较复杂的时侯。但一个段落的分数（binom）要么全部行内，要么全部displaystyle。

（（（

那么还有一个问题，就是是否需要把这个添加到给你站格式统一的计划 @Ir1d

**Comment by Enter-tainer** [comment]
我个人的习惯是：
- 分数使用 dfrac，即全部使用displaystyle
- 巨算符使用displaystyle，如\sum, \prod

不知道大家是怎么操作啊qwq

**Comment by TrisolarisHD** [comment]
@Enter-tainer 我也差不多

**Comment by sshwy** [comment]
建议尽量避免行间sum，prod

**Comment by Xeonacid** [comment]
@sshwy 简单的（比如 $\sum a_i）还是可以的吧🌚

**Comment by sshwy** [comment]
> @sshwy 简单的（比如 $\sum a_i$）还是可以的吧

如果只带下界的sum或者不带上下界sum我也赞同。同时带上下界的看着有点挤～

**Comment by TrisolarisHD** [comment]
@Xeonacid 但是带球和指标的就不好看了呀 ～

**Comment by Ir1d** [comment]
感觉可以写到 wiki of wiki 里 :thinking: 手工统一有点费劲的样子.. 工作量看起来很大
