### ISSUE TITLE
add LCT进阶

### ISSUE THREAD

**Issue by hsfzLZH1** [OI-wiki/OI-wiki#1410]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

LCT 进阶

 主要为 LCT 维护子树信息，生成树（边），双连通分量的内容

- 英文叫什么？

**lct-beats**

（？？？）

（参见 segment-tree-beats ）

- 有什么参考资料？

https://www.cnblogs.com/flashhu/p/9498517.html

**Comment by TrisolarisHD** [comment]
@hsfzLZH1 连通，，，
