### ISSUE TITLE
LCT 页面代码与描述混乱

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/OI-wiki#1448]
首先，十分欢迎你花钱（？）来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 是出现了什么问题？（最好截图）

https://oi-wiki.org/ds/lct/ LCT 页面

文中定义的函数名字与代码中用到的不符（主要是大小写不一样），且建树中的代码风格（数组）与全文的代码风格（指针）不一致。在 建树 中，分裂 和 合并 又被讲了一次（而且写的并不是很详细）

- 你是否正在着手修复？

否

**Comment by Enter-tainer** [comment]
我把 Treap 的锅接走吧... LCT 还得靠你萌啊qwq🤔

**Comment by sshwy** [comment]
现在还哪里混乱丫。。。我跟着wiki学一遍感觉挺顺畅
要不close了
