### ISSUE TITLE
bot 无法处理缩进后的代码

### ISSUE THREAD

**Issue by hsfzLZH1** [OI-wiki/OI-wiki#1456]
某些数据结构题的代码过长，需要折叠在 ??? note 中，但是此时 bot 无法对这些代码进行排版。

我看自己的压行代码都会觉得难受

**Comment by Enter-tainer** [comment]
@hsfzLZH1 是否可以将代码扔到Git库里，然后在文章里留下一个链接？

**Comment by hsfzLZH1** [comment]
> 
> 
> @hsfzLZH1 是否可以将代码扔到Git库里，然后在文章里留下一个链接？

感觉给链接不如提供一个折叠的代码框好。。现在的样式也挺不错的。

这是 bot 的问题吧

**Comment by Ir1d** [comment]
对的 是 bot 的问题，我在 lint 那个 issue 下面记了

**Comment by abc1763613206** [comment]
@Enter-tainer 往problemset库里扔快照吧

**Comment by ouuan** [comment]
现在应该没有这个问题了吧？

**Comment by Ir1d** [comment]
嗯嗯，而且折叠功能 @Enter-tainer 也写好了，等一个良辰吉日部署
