### ISSUE TITLE
luogu 题目链接问题

### ISSUE THREAD

**Issue by hsfzLZH1** [OI-wiki/OI-wiki#1457]
luogu 现在强制使用了新版题目界面，使用链接到旧版题目界面时会自动跳转到新版题目界面，但是不知道什么时候会挂掉，所以需要把以前的 luogu 题目链接改成新版题目界面。

**Comment by Ir1d** [comment]
我觉得不会挂吧，那么多链接一下子就死链了（🌚

**Comment by Enter-tainer** [comment]
@Ir1d 这个问题理论上应该提给luogu？（雾

**Comment by Ir1d** [comment]
我的建议是，工作量比较大，不是很必要，如果有天挂了的话再说，是修链接还是换 oj 什么的

**Comment by billchenchina** [comment]
@hsfzLZH1 提议使用
[[luogu/p(roblem)/1000]]
[[luogu/c(ontest)/1234]]
然后统一 render）

**Comment by hsfzLZH1** [comment]
> 
> 
> 我的建议是，工作量比较大，不是很必要，如果有天挂了的话再说，是修链接还是换 oj 什么的

很好现在就已经锅了

**Comment by StudyingFather** [comment]
ssfd.webp

**Comment by Ir1d** [comment]
@hsfzLZH1 举个栗子评估一下影响？我翻了下 lct 那页 https://www.luogu.org/problemnew/show/P1501 貌似还能跳过去

**Comment by hsfzLZH1** [comment]
https://www.luogu.org/problem/show?pid=3372

mdzz 线段树那个页面质量太低了，原来的连接就是锅的。。。

**Comment by abc1763613206** [comment]
@hsfzLZH1 这链接原先是有效的吗

**Comment by Ir1d** [comment]
我猜上古时期可能有效吧。。线段树页面比较早了。

**Comment by abc1763613206** [comment]
@hsfzLZH1 向洛谷提意见了，之后会进行修复

**Comment by Prurite** [comment]
觉得直接让洛谷永久留一个301在那问题不会很大吧（
不过应该给洛谷反映一下

**Comment by abc1763613206** [comment]
![image](https://user-images.githubusercontent.com/30773956/63143318-458f0c80-c020-11e9-8bbb-40448f78dca2.png)

**Comment by StudyingFather** [comment]
fixed in #2195.
