### ISSUE TITLE
add Codeforces 的命令行工具 cf-tool

### ISSUE THREAD

**Issue by xalanq** [OI-wiki/OI-wiki#1473]
- 希望添加的是什么？

Codeforces 的一个 CLI 工具 cf-tool

- 英文叫什么？

cf-tool

- 有什么参考资料？

[xalanq/cf-tool](https://github.com/xalanq/cf-tool)

**Comment by Ir1d** [comment]
:+1: 可以直接 pr 到那个页面上哒

**Comment by xalanq** [comment]
我能在 `工具软件` 下加一个类别 `OJ 工具`，然后将这个工具在此类别下加一个页面吗？

**Comment by Ir1d** [comment]
哦哦，我觉得如果开一个 OJ 工具的页面是 ok 的，但是好像目前还没有特别多的内容把他变成一个类别..? 不如先开成一个 OJ 工具的页面然后写在那里面（？

**Comment by xalanq** [comment]
行

**Comment by xalanq** [comment]
See #1477
