### ISSUE TITLE
合并线性规划与单纯形

### ISSUE THREAD

**Issue by Xeonacid** [OI-wiki/OI-wiki#1478]
[线性规划](https://oi-wiki.org/math/linear-programming/)与[单纯形](https://oi-wiki.org/math/simplex/)内容重复

**Comment by Ir1d** [comment]
感觉可以把 线性规划 搞成问题介绍（手算姿势、与网络流关系？），然后单纯型的页面只讲单纯形法？

另外现在单纯形法那堆标题的序号在改的时候也得给去掉..
