### ISSUE TITLE
线段树页面表述不够严谨

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/OI-wiki#1486]
![image](https://user-images.githubusercontent.com/25521218/62342256-d0e4aa00-b518-11e9-8404-6c27da3db933.png)

![image](https://user-images.githubusercontent.com/25521218/62342330-04bfcf80-b519-11e9-913e-2eea85be4ec2.png)

![image](https://user-images.githubusercontent.com/25521218/62342364-1f924400-b519-11e9-80da-07e06be2aac4.png)

**Comment by partychicken** [comment]
我觉得OI-Wiki是时候统一一下笔风了。。。
有的写得却是有点儿出戏，不大符合wiki的定位

**Comment by Ir1d** [comment]
landed in #1489
