### ISSUE TITLE
手机版页面目录显示异常

### ISSUE THREAD

**Issue by Igronemyk** [OI-wiki/OI-wiki#1498]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

在手机班上打开OI Wiki并打开左侧的目录，跳转到根目录后进入一个二级目录，一级目录和二级目录可能会重叠显示。

![问题截图](http://bwh.igronemyk.xyz/photo_2019-08-04_19-31-44.jpg)

浏览器版本：Chrome 76.0.3809.89

- 你是否正在着手修复？

并不会修

- 如何复现？

重复问题操作，有概率复现

**Comment by Ir1d** [comment]
hi，能否看下 https://squidfunk.github.io/mkdocs-material/ 有没有相同的问题？

**Comment by Ir1d** [comment]
实在是难以复现。。先不管了吧 :new_moon_with_face:
