### ISSUE TITLE
add 自适应辛普森法

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#1508]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
自适应辛普森法

- 英文叫什么？
simpson

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by 97littleleaf11** [comment]
@trinkle23897 可以把你当年的blog加进来

**Comment by Trinkle23897** [comment]
@97littleleaf11 请您加

**Comment by Trinkle23897** [comment]
https://trinkle23897.github.io/2016/03/21/%E6%A0%BC%E6%9E%97%E5%85%AC%E5%BC%8F%E5%9C%A8%E9%9D%A2%E7%A7%AF%E5%B9%B6%E9%97%AE%E9%A2%98%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8.html

**Comment by Trinkle23897** [comment]
http://trinkle.blog.uoj.ac/blog/1519 这个好一点
