### ISSUE TITLE
add 置换群

### ISSUE THREAD

**Issue by Wajov** [OI-wiki/OI-wiki#1524]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
置换群

- 英文叫什么？
Permutation group

- 有什么参考资料？
[Burnside 引理](https://en.wikipedia.org/wiki/Burnside%27s_lemma)
[群作用](https://en.wikipedia.org/wiki/Group_action_(mathematics)#Orbit-stabilizer_theorem)
[Pólya 定理](https://en.wikipedia.org/wiki/Pólya_enumeration_theorem)

issue 标题请写为 'add ' + 要添加的内容

**Comment by StudyingFather** [comment]
pr #1526
