### ISSUE TITLE
将所有内链更改为相对路径+.md

### ISSUE THREAD

**Issue by Xeonacid** [OI-wiki/OI-wiki#1563]
现在内链使用的是渲染后绝对路径 `[title](xxx/yyy)` 的形式，我们需要全部转换为相对路径+.md（不支持绝对路径）
原因：
- 可以在GitHub内preview时点击内链正确跳转
- mkdocs会检查文件是否存在，不存在会报warning，过不去CI（彻底解决 #1523 ）

mkdocs会自动转换链接（去.md），这也是其文档的推荐做法

**Comment by sshwy** [comment]
@Xeonacid 我猜可以正则搜索一下
