### ISSUE TITLE
思想方法-递归&分治-二叉树遍历求和-示例代码有误

### ISSUE THREAD

**Issue by tptpp** [OI-wiki/OI-wiki#1578]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x ] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
https://oi-wiki.org/basic/divide-and-conquer/
原代码：
int count(TreeNode node, int sum) {
  if (node == null) return 0;
  return (node.val == sum) + count(node.left, sum - node.val) +
         count(node.right, sum - node.val);
}

问题用例：
root=[2,3,3], sum=8

预期返回1，实际会返回0

- 你是否正在着手修复？
否

- 如何复现？
参见上文，问题用例

**Comment by StudyingFather** [comment]
似乎是文中没有写清楚题意的原因...

其实只能从深度小的节点走向深度大的节点，我一会修一下这个锅吧。

**Comment by tptpp** [comment]
啊 确实是的，否则题目里的2 - 5 - 3 - -2也等于8了
