### ISSUE TITLE
申请把桶排序和计数排序分开

### ISSUE THREAD

**Issue by MrFoodinChina** [OI-wiki/OI-wiki#1600]
希望增加“桶排序”，并将其与计数排序分开

资料：
> 桶排序（Bucket sort）或所谓的箱排序，是一个排序算法，工作的原理是将数组分到有限数量的桶里。每个桶再个别排序（有可能再使用别的排序算法或是以递归方式继续使用桶排序进行排序）。桶排序是鸽巢排序的一种归纳结果。
> 计数排序（Counting sort）是一种稳定的线性时间排序算法。该算法于1954年由 Harold H. Seward 提出。计数排序使用一个额外的数组 {\displaystyle C}  C ，其中第i个元素是待排序数组 {\displaystyle A} A中值等于 {\displaystyle i} i的元素的个数。然后根据数组 {\displaystyle C}  C 来将 {\displaystyle A} A中的元素排到正确的位置。

来自wiki

**Comment by ouuan** [comment]
其实我今天才看到这个 issue（
