### ISSUE TITLE
伪代码推荐格式

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1601]
鉴于使用 TeX 转成图片不易于维护，大约使用这样的格式：

> **Input.** The nodes of the graph $V$; the function $g(u, v)$ which means the weight of the edge $(u, v)$; the function $adj(v)$ which means the nodes adjacent to $v$.
>
> **Output.** The sum of weights of the MST of the input graph.
>
> **Method.**
>
> $result \gets 0$
>
> choose an arbitrary node in $V$ to be the $root$
>
> $dis(root)\gets 0$
>
> **for** each node $v\in(V-\{root\})$
>
> &nbsp;&nbsp;&nbsp;&nbsp;$dis(v)\gets\infty$
>
> $rest\gets V$
>
> **while** $rest\ne\varnothing$
>
> &nbsp;&nbsp;&nbsp;&nbsp;$cur\gets$ the node with the minimum $dis$ in $rest$
>
> &nbsp;&nbsp;&nbsp;&nbsp;$result\gets result+dis(cur)$
>
> &nbsp;&nbsp;&nbsp;&nbsp;$rest\gets rest-\{cur\}$
>
> &nbsp;&nbsp;&nbsp;&nbsp;**for** each node $v\in adj(cur)$
>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$dis(v)\gets\min(dis(v), g(cur, v))$
>
> **return** $result$

```markdown
> **Input.** The nodes of the graph $V$; the function $g(u, v)$ which means the weight of the edge $(u, v)$; the function $adj(v)$ which means the nodes adjacent to $v$.
>
> **Output.** The sum of weights of the MST of the input graph.
>
> **Method.**
>
> $result \gets 0$
>
> choose an arbitrary node in $V$ to be the $root$
>
> $dis(root)\gets 0$
>
> **for** each node $v\in(V-\{root\})$
>
> &nbsp;&nbsp;&nbsp;&nbsp;$dis(v)\gets\infty$
>
> $rest\gets V$
>
> **while** $rest\ne\varnothing$
>
> &nbsp;&nbsp;&nbsp;&nbsp;$cur\gets$ the node with the minimum $dis$ in $rest$
>
> &nbsp;&nbsp;&nbsp;&nbsp;$result\gets result+dis(cur)$
>
> &nbsp;&nbsp;&nbsp;&nbsp;$rest\gets rest-\{cur\}$
```

主体是 Markdown 的引用（`>`），关键字加粗，缩进使用 `&nbsp;&nbsp;&nbsp;&nbsp;` 表示。

注意不要写成 Python 就好了，具体格式也说不清楚，可以参考算导或者各种论文吧。

我参考的是 [AC 自动机论文](http://students.mimuw.edu.pl/~ag181127/2004_2005/p333-aho-corasick.pdf)。

**Comment by sshwy** [comment]
@ouuan 要不开个pr加到htc里
