### ISSUE TITLE
add： 压位高精度  高精度取余

### ISSUE THREAD

**Issue by sshwy** [OI-wiki/OI-wiki#1608]
你站陈年老锅

翻新一下

---

首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

压位高精度  高精度取余

- 英文叫什么？

- 有什么参考资料？

#577 

issue 标题请写为 'add ' + 要添加的内容

**Comment by StudyingFather** [comment]
see #2392.
