### ISSUE TITLE
add kruskal重构树

### ISSUE THREAD

**Issue by zhouyuyang2002** [OI-wiki/OI-wiki#1616]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

kruskal 重构树

- 英文叫什么？

加在mst部分

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

我可能把kruskal重构树和最小瓶颈路一起写掉了QAQ

**Comment by ouuan** [comment]
写之前记得先 pull https://github.com/sshwy/OI-wiki.git mst

**Comment by Ir1d** [comment]
抱歉拖得比较久了，已经合并 #1592 ，只需要 rebase master
