### ISSUE TITLE
NOIP走了

### ISSUE THREAD

**Issue by CBW2007** [OI-wiki/OI-wiki#1626]
CSP来了，<https://oi-wiki.org/intro/oi/#noip>这一部分文章要换一下吗？

**Comment by Doveqise** [comment]
有道理欸 要8要您写一个然后pull requestQwQ

**Comment by ouuan** [comment]
明年再换吧..现在大家都不知道具体情况，怎么写，写给谁看啊..

**Comment by CBW2007** [comment]
abcdefghijklmnopqrstuvwxyz
