### ISSUE TITLE
作者信息统计有误

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1663]
以 ds/lct 为例，https://github.com/OI-wiki/OI-wiki/commits/master/docs/ds/lct.md 
比较久远的 82d2a8e090c414c9526108fc05c4627a89ec78e7 就被挤掉了，API 中没法获取。

参考解决方案：通过 lint bot 维护 author 字段
思考：lint bot 的话，每次都需要 pull 全部 history，压力有点大，不如放在哪里 crontab

**Comment by frank-xjh** [comment]
维护一份api，放作者名单，bot每次去增加人员

**Comment by Ir1d** [comment]
放 md 头部的 author 字段呗

**Comment by Enter-tainer** [comment]
现在已通过author字段部分缓解
