### ISSUE TITLE
遗留的roadmap？

### ISSUE THREAD

**Issue by cmpute** [OI-wiki/OI-wiki#1668]
[数据结构页面](https://oi-wiki.org/ds/)的roadmap是忘记删除了吗？

**Comment by ouuan** [comment]
目录吗？~~建议把 #1140 rollback~~。

要不把简介里的目录删了吧..

**Comment by ouuan** [comment]
其实很多板块的简介都是目录 / 基础知识 / 杂项。

**Comment by ouuan** [comment]
比如说，图论简介、图论基础、图论杂项，到底是怎么分的...

**Comment by cmpute** [comment]
嗯嗯把目录删了吧，和导航栏重复了

**Comment by cmpute** [comment]
以及我觉得数据结构板块的结构可以再理一下 🌚 例如线段树和BST同级了什么的
