### ISSUE TITLE
给排序开单独的标签

### ISSUE THREAD

**Issue by cmpute** [OI-wiki/OI-wiki#1669]
目前[排序的内容](https://oi-wiki.org/basic/sort-intro/)放在了思想方法底下，我觉得可以考虑新开一个标签来单独介绍，因为 1) 排序并不能算是一个通用的思想， 2) 排序方法本身会用到二分等思想。

PS：我觉得把“思想方法”改名成“方法论”更好听

**Comment by cmpute** [comment]
另外，二分的内容应该划分到分治里面？

**Comment by ouuan** [comment]
“思想方法”是历史遗留问题，一开始没有“语言基础”，现在的“思想方法”那时就是“基础”。

要不要改成“算法基础”？

**Comment by sshwy** [comment]
这个问题是不是可以close了 :thinking:

**Comment by StudyingFather** [comment]
> 这个问题是不是可以close了 🤔

应该可以了吧 😄
