### ISSUE TITLE
区分C和C++？

### ISSUE THREAD

**Issue by cmpute** [OI-wiki/OI-wiki#1670]
想问下C语言在文档里的定位是啥？是和C++合并到一块，还是可以专门写个页面？C和C++还是有一定区别的

**Comment by Ir1d** [comment]
我觉得可以开个页面讲讲区别🤔

**Comment by ouuan** [comment]
（我觉得不需要专门讲 C）

**Comment by Ir1d** [comment]
同时似乎也没什么理由不专门讲 C

**Comment by ouuan** [comment]
绝大部分 OIer 都用 C++，没必要讲 C。

**Comment by ouuan** [comment]
*绝大部分 OIer 都用 C with STL with iostream with （还有啥一下想不全了）

**Comment by Ir1d** [comment]
绝大部分 OIer 不用的东西多着去了（比如 wsl，testlib，latex 等等），为什么别的讲了，C 不能讲呢 :thinking: 
我觉得如果有人愿意写的话，没什么理由拒绝这部分内容

**Comment by ouuan** [comment]
我觉得 testlib 和 latex 只是部分 OIer 不用的东西吧（不知道有没有大部分）

如果刚入门的也算，那应该是大部分了。

**Comment by ouuan** [comment]
“如果有人愿意写的话，没什么理由拒绝这部分内容” 和我的论点不冲突，在当前不会对 Wiki 造成影响，我可以看做没有这句话吗（

**Comment by Ir1d** [comment]
fine，我理解楼主是想问要不要讲讲区别，我的观点是可以，你说不需要，如果这没什么冲突的话倒也挺好

**Comment by ouuan** [comment]
（那我重新表述一下我的观点吧）

可以但没必要专门写个页面讲 C 和 C++ 的区别。

在其它页面不要太过区分 C 和 C++。

**Comment by cmpute** [comment]
我其实是这么想的，可以做一页讲一下主要的区别和陷阱（如new和free混用）。类似于“Pascal 急救转 C++ ”的页面定位。
就是因为很多 OIer 写的都是C/C++的杂合体，导致很多人以后继续使用C++时写出来的代码奇丑无比= =，所以我觉得至少明确区分一下C和C++对代码的健壮性是由好处的。
另外我同意其他页面不要太区分C/C++，并且推荐以C++语法为基准。

**Comment by cmpute** [comment]
我在我的PR里一块加了吧

**Comment by Enter-tainer** [comment]
> 我其实是这么想的，可以做一页讲一下主要的区别和陷阱（如new和free混用）。类似于“Pascal 急救转 C++ ”的页面定位。
> 就是因为很多 OIer 写的都是C/C++的杂合体，导致很多人以后继续使用C++时写出来的代码奇丑无比= =，所以我觉得至少明确区分一下C和C++对代码的健壮性是由好处的。
> 另外我同意其他页面不要太区分C/C++，并且推荐以C++语法为基准。

说句题外话x，关于 new 和 free 的问题，我自己在写一些动态开点的数据结构的时候好像从来没 free 过内存（大雾）（把锅甩给操作系统）

另外，可以详细说一下 “new 和 free 混用的” 的问题吗？

**Comment by cmpute** [comment]
@Enter-tainer  new和free混用可能会导致内存泄漏，我记得好像是用`new int[10]`这样的语法弄出来的数组用`free`就清不干净。不过确实在OI的时候没人会free，毕竟只跑一次x
但是介绍一下还是有好处的

**Comment by Enter-tainer** [comment]
想了下好像应该配套使用的是 new 和 delete？（记不到了，毕竟用的少）

**Comment by cmpute** [comment]
是的，new用delete，malloc用free
