### ISSUE TITLE
add git 使用指南

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1674]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

git 使用指南

- 英文叫什么？

git-guidebook

- 有什么参考资料？

https://git-scm.com/docs
https://git-scm.com/book/zh/v2

issue 标题请写为 'add ' + 要添加的内容

然后可以在 htc 里 link 一下。（我刚开始写 Wiki 的时候就不知道怎么做到“一个 pr 只干一件事”）

**Comment by StudyingFather** [comment]
也许可以考虑把窝之前在洛谷日报上的投稿搬运过来QAQ（不过那个写的有点烂/kk）

**Comment by ouuan** [comment]
> 也许可以考虑把窝之前在洛谷日报上的投稿搬运过来QAQ（不过那个写的有点烂/kk）

感觉海星。

**Comment by Xeonacid** [comment]
https://learngitbranching.js.org/ 好（

**Comment by abc1763613206** [comment]
这里有些 IBM Developer 的 git 教程，我觉得也能参考一下（
https://www.ibm.com/developerworks/cn/opensource/os-cn-git-and-github-1/index.html
https://www.ibm.com/developerworks/cn/opensource/os-cn-git-and-github-2/index.html
https://www.ibm.com/developerworks/cn/opensource/os-cn-git-and-github-3/index.html
https://www.ibm.com/developerworks/cn/opensource/os-cn-git-and-github-4/index.html
https://www.ibm.com/developerworks/cn/opensource/os-cn-git-and-github-5/index.html

**Comment by ouuan** [comment]
（我把 Learn Git Branching 打通了）

**Comment by AngelKitty** [comment]
也许这些也可以作为参考：
https://github.com/521xueweihan/git-tips
https://progit.bootcss.com/

**Comment by partychicken** [comment]
等等，我们维护的是oi-wiki吧。。。
git使用指南是smg

**Comment by ouuan** [comment]
> 等等，我们维护的是oi-wiki吧。。。
> git使用指南是smg

htc 的补充内容

> 然后可以在 htc 里 link 一下。（我刚开始写 Wiki 的时候就不知道怎么做到“一个 pr 只干一件事”）

**Comment by ouuan** [comment]
mark 一下：

1. htc 加入 commit suggestion 指南（add to batch）。
2. htc 加入折叠框中代码空行保留四空格提醒。

**Comment by ouuan** [comment]
群内讨论备忘：

![图片](https://user-images.githubusercontent.com/30581822/87310614-c7e5c080-c550-11ea-983c-1d64afd0c8dc.png)

![图片](https://user-images.githubusercontent.com/30581822/87310630-ccaa7480-c550-11ea-98a0-8b9936eaf1bb.png)

![图片](https://user-images.githubusercontent.com/30581822/87310885-257a0d00-c551-11ea-8163-5394a02f93b8.png)

![图片](https://user-images.githubusercontent.com/30581822/87310774-ffed0380-c550-11ea-8692-6c17b1dc7384.png)

![图片](https://user-images.githubusercontent.com/30581822/87310770-fcf21300-c550-11ea-8d19-38d85e7bc065.png)

![图片](https://user-images.githubusercontent.com/30581822/87310801-0b402f00-c551-11ea-9e3c-b30dde41fa11.png)

![图片](https://user-images.githubusercontent.com/30581822/87311001-46daf900-c551-11ea-831d-9cf6b667b692.png)
