### ISSUE TITLE
OI Wiki 页面修改意见收集

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1684]
Hi！新学期就要到啦，我们也正在筹备新一轮更新计划，对 OI Wiki 哪些页面不满意，或者有什么意见建议，欢迎反馈到这个问卷来。（滋兹匿名提交，欢迎转发～

https://wj.qq.com/s2/4467592/b1e9/

**Comment by YanWQ-monad** [comment]
似乎这个提示框的宽度不对？

![oi-wiki screenshot](https://user-images.githubusercontent.com/20324409/64483928-b9968c00-d23d-11e9-9079-95ca56627e31.png)

浏览器版本：Chrome 76.0.3809.132  
此外，Firefox 没有此问题

**Comment by abc1763613206** [comment]
@YanWQ-monad 目前这bug实在是修不好了......您如果有什么好的idea可以提出来

**Comment by frank-xjh** [comment]
已经更换新的toast [#18](https://github.com/OI-wiki/mkdocs-material/pull/18)

**Comment by CBW2007** [comment]
填表太慢了，直接来吧 :smile:

这个提示框感觉还是不太友好 :thinking:

在顶部的话，有点挡翻页栏和搜索框，建议放在左/右下角

**Comment by hackermengzhi** [comment]
学习路线建议，首先，若是条件允许的话，最好在linux环境下编程，当你用了gedit,vim,emacs,atom等编辑器后你会发现dev c++真得垃圾，若不相信我，到以后你会发现dev的很多玄学错误的。同时，若是不会手打配置，以及不会在高级环境下编程的话，以后也是走不远的。还有我们这边不管什么比赛用的都是linux环境，建议你最好了解下，确认下你们那边的环境。
还有就是推荐几本书，最基础的当然推荐c++一本通，黄壳子的，可以学到很多基础知识。我看你在高精度这题上还用的int，就晓得你基础知识不牢，int最高2∧31-1,高精很明显是暴了int的。虽然这种错误入门时也犯过，但现在熟悉基础知识后就不会再错了。到后期可以买刘汝佳的那两本算法书，学更高级的算法，诸如线段树，splay,link cut tree,等等。
再者就是要走oi这条路，就一定要沉住气，前期可能是因为基础知识不牢可以看题解，但后期绝不能看，否则会影响自己的思维逻辑体系。
而且也可以去国外的网站练习,如codeforces。
我也算是前带后，真不希望看到一个个有天赋的人走上弯路。

**Comment by mwsht** [comment]
@hackermengzhi 。。。

**Comment by hackermengzhi** [comment]
> @hackermengzhi 。。。

其实我就是想吐槽为啥学习路线是空的

**Comment by Ir1d** [comment]
感谢大家的反馈，稍作整理后我们会将问卷内容更新到这（下）一轮迭代计划中！祝大家期中 / CSP 顺利，OI Wiki 越办越好！

另：我们开始采用 [FeatHub](https://feathub.com/OI-wiki/OI-wiki) 啦！欢迎大佬们来吐槽 / 投票
