### ISSUE TITLE
数学部分分类不易于查找

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1694]
感觉 #1577 的改动使得在数学部分查找内容更加困难，而且存在期望分在组合数学里这样有争议的分类。

我的建议是目录回滚到 #1577 之前。

我认为必须要改的：
- 去掉一级目录“基础知识”、“常用算法与应试技巧”；
- 将“概率 & 期望”移出组合数学；
- **合并** 线性规划与单纯形。

其它目录改不改再讨论吧。

**Comment by Enter-tainer** [comment]
概率期望是的确放错地方了

但是基础知识好像没啥毛病？

**Comment by Ir1d** [comment]
不好找是的确不好找.. 这个问题的解决办法是不是干掉目录，然后给页面加 tag..

**Comment by ouuan** [comment]
在我理解中，“基础知识”是整个板块所有其它内容的前置知识。

**Comment by ouuan** [comment]
而且我分不清“基础知识”和“常用算法与应试技巧”。

**Comment by sshwy** [comment]
> 而且我分不清“基础知识”和“常用算法与应试技巧”。

这个常用算法与应试技巧就很不严谨Q^Q

**Comment by ouuan** [comment]
（大家觉得怎么改比较好）

**Comment by ouuan** [comment]
fixed by #1824

**Comment by sshwy** [comment]
这个数学目录咋没有更新啊
看不透

**Comment by ouuan** [comment]
> 这个数学目录咋没有更新啊
> 看不透

@Ir1d 
coding.oi-wiki.org 和 demo.oi-wiki.org 都更新了，oi-wiki.org 还停留在 1667a90, 2019-11-20 /jk

**Comment by Ir1d** [comment]
抱歉是因为改了 dns，这台机器没有配 webhook，我这两天抽空处理一下
现在已经 reset 到 master 了
