### ISSUE TITLE
404not found

### ISSUE THREAD

**Issue by sherry255** [OI-wiki/OI-wiki#1714]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？
所有页面都404了

- 你是否正在着手修复？

- 如何复现？

issue 标题请写为 要汇报的主要内容

**Comment by ouuan** [comment]
- 请尝试访问 demo.oi-wiki.org

- 请尝试用其它设备访问

- 请尝试联系他人尝试访问

反正我能上。

**Comment by Ir1d** [comment]
@sherry255 检查一下 dns 设置？
oi-wiki.org coding.oi-wiki.org 现在都放在 coding，demo.oi-wiki.org 放在 netlify

**Comment by sherry255** [comment]
> * 请尝试访问 demo.oi-wiki.org
> * 请尝试用其它设备访问
> * 请尝试联系他人尝试访问
> 
> 反正我能上。

解决了, 谢谢!
