### ISSUE TITLE
bzoj 题目链接问题

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#1721]
最近 bzoj 官方宣称因为题库维护原因要暂时下线半个月。

考虑到国庆期间网站访问量较大，且站内 bzoj 题目较多，失效链接可能会对用户体验感造成较大影响。

目前一种较为可行的解决方案是将所有 bzoj 题目链接更换为 [OI Archive](https://oi-archive.wa-am.com/) 上的对应链接。

欢迎各位讨论这个问题~

**Comment by Ir1d** [comment]
去 #1722 吧 他比较长
