### ISSUE TITLE
大视野在线测评(BZOJ) 当前不可用

### ISSUE THREAD

**Issue by abc1763613206** [OI-wiki/OI-wiki#1722]
如题。
大视野在线测评(又名 BZOJ) <https://www.lydsy.com/JudgeOnline/> ，近日陷入了不可用的状态。         
谷歌上的快照时间截止在 `2019年9月22日 11:47:08 GMT` 。

大概波及到了 wiki 上的一些链接？ https://github.com/OI-wiki/gitment/issues/45#issuecomment-534530812    https://github.com/OI-wiki/gitment/issues/97#issuecomment-534537704    

目前个人想到的几个解决方案：   
- 临时迁移到 [OI Archive](https://oi-archive.wa-am.com/#/problem/bzoj/1000)       
- 对于非 BZOJ 特有版权题目，迁移至其他OJ （如 LOJ）      
- 迁移到 darkBZOJ （不推荐）
- 迁移到 vjudge

**Comment by ouuan** [comment]
如果只是题面的话，4894 及之前可以使用 https://ruanx.pw/bzojch/

**Comment by abc1763613206** [comment]
https://ruanx.pw/bzojch/result.json

**Comment by Ir1d** [comment]
我个人比较倾向于 迁移到 vjudge..
目前可以这么搞：之前放进来的没空管就先搁置，之后新开的 pr 链接挪到 vjudge 去 :thinking:

**Comment by Phemon** [comment]
关站前的公告写的是十五天恢复？是不是可以先撑到十一假期之后看看BZOJ的情况再作下一步讨论？

**Comment by StudyingFather** [comment]
@Phemon 不太好吧...主要是假期 OI-wiki 的访问量挺大的，挂太多失效链接体验不是太好吧（

**Comment by Phemon** [comment]
> @Phemon 不太好吧...主要是假期 OI-wiki 的访问量挺大的，挂太多失效链接体验不是太好吧（

那是不是可以考虑优先替换为其他OJ的同一道题，在其他OJ没有的时候再换一个离线题面链接。

**Comment by ouuan** [comment]
fix in progress

**Comment by ouuan** [comment]
https://github.com/OI-wiki/OI-wiki/commit/c074a8668c59a87b7e776fdcd3ff25a81800acc6#diff-64d41e955ee3e27bdb24a1e9a8783017（草）

**Comment by ouuan** [comment]
其实我觉得没有社区功能的洛谷不比 BZOJ 差..

**Comment by Prurite** [comment]
目前为止bzoj还没恢复 ~~15天？~~

**Comment by StudyingFather** [comment]
@Prurite 猜测可能是备案失效了？（去备案系统查了一下发现没记录了）...

**Comment by Phemon** [comment]
> 目前为止bzoj还没恢复 ~15天？~

bzoj的服务器没有关闭，一直有人在交题，只不过域名一直没有解析到服务器。

**Comment by Phemon** [comment]
> @Prurite 猜测可能是备案失效了？（去备案系统查了一下发现没记录了）...

我在 http://beian.miit.gov.cn 使用域名 lydsy.com 查询依然可以查到备案信息。

**Comment by billchenchina** [comment]
@Phemon 查询域名 lydsy.com
许可证号: 湘ICP备19021049号-1
网站名称: 大视野在线测评
主办单位: 谢光伟 (个人)
验证时间: 2019-10-21 16:22:46
显示是昨天刚备案完的
