### ISSUE TITLE
add 吉司机线段树

### ISSUE THREAD

**Issue by lushuyu** [OI-wiki/OI-wiki#1723]
- 希望添加的是什么？
吉司机线段树...估计没有什么人听过，我只见过题目，没有blog介绍这个东东

- 英文叫什么？
不知道qaq

- 有什么参考资料？
一些模糊的博客:
https://blog.csdn.net/qq_36284842/article/details/80058746
https://www.cnblogs.com/zwfymqz/p/9671730.html

**Comment by sshwy** [comment]
https://oi-wiki.org/ds/seg-beats/
如果您有什么需要补充的欢迎开PR QvQ

<blockquote><img src="../../favicon.ico" width="48" align="right"><div><strong><a href="https://oi-wiki.org/ds/seg-beats/">线段树 & 区间历史最值 - OI Wiki</a></strong></div><div>OI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛</div></blockquote>

**Comment by ouuan** [comment]
这个标题很迷惑..我感觉我很久之前就提过这个问题。

**Comment by abc1763613206** [comment]
@ouuan duplicate了？

**Comment by ouuan** [comment]
> @ouuan duplicate了？

不把，我都不记得我在哪提过了..

**Comment by ouuan** [comment]
这个 issue 证明了 “线段树 & 区间历史最值” 这个标题的确是迷惑的。

**Comment by ouuan** [comment]
https://github.com/OI-wiki/OI-wiki/pull/1331#issuecomment-510509885

**Comment by TrisolarisHD** [comment]
#1167 了解一下...？close 了吧

**Comment by lushuyu** [comment]
> #1167 了解一下...？close 了吧

感谢，我看到了

**Comment by lushuyu** [comment]
> 这个 issue 证明了 “线段树 & 区间历史最值” 这个标题的确是迷惑的。

OK 谢谢
