### ISSUE TITLE
Segment Tree Beats! 在目录中应该如何命名？

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1724]
[![](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/%E5%90%89%E8%80%81%E5%B8%88%E7%BA%BF%E6%AE%B5%E6%A0%91)](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/%E5%90%89%E8%80%81%E5%B8%88%E7%BA%BF%E6%AE%B5%E6%A0%91/vote)
[![](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/Segment%20Tree%20Beats!)](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/Segment%20Tree%20Beats!/vote)
[![](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/%E5%8C%BA%E9%97%B4%E6%9C%80%E5%80%BC%E6%93%8D%E4%BD%9C%20%26%20%E5%8C%BA%E9%97%B4%E5%8E%86%E5%8F%B2%E6%9C%80%E5%80%BC)](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/%E5%8C%BA%E9%97%B4%E6%9C%80%E5%80%BC%E6%93%8D%E4%BD%9C%20%26%20%E5%8C%BA%E9%97%B4%E5%8E%86%E5%8F%B2%E6%9C%80%E5%80%BC/vote)
[![](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/%E5%90%89%E8%80%81%E5%B8%88%E7%BA%BF%E6%AE%B5%E6%A0%91%EF%BC%88%E5%8C%BA%E9%97%B4%E6%9C%80%E5%80%BC%EF%BC%89)](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/%E5%90%89%E8%80%81%E5%B8%88%E7%BA%BF%E6%AE%B5%E6%A0%91%EF%BC%88%E5%8C%BA%E9%97%B4%E6%9C%80%E5%80%BC%EF%BC%89/vote)
[![](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/Segment%20Tree%20Beats!%EF%BC%88%E5%8C%BA%E9%97%B4%E6%9C%80%E5%80%BC%EF%BC%89)](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/Segment%20Tree%20Beats!%EF%BC%88%E5%8C%BA%E9%97%B4%E6%9C%80%E5%80%BC%EF%BC%89/vote)
[![](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/%E7%BA%BF%E6%AE%B5%E6%A0%91%20%26%20%E5%8C%BA%E9%97%B4%E6%9C%80%E5%80%BC%E6%93%8D%E4%BD%9C%20%26%20%E5%8C%BA%E9%97%B4%E5%8E%86%E5%8F%B2%E6%9C%80%E5%80%BC)](https://api.gh-polls.com/poll/01DNJVFZYRM3TRADGW9SDWYYCQ/%E7%BA%BF%E6%AE%B5%E6%A0%91%20%26%20%E5%8C%BA%E9%97%B4%E6%9C%80%E5%80%BC%E6%93%8D%E4%BD%9C%20%26%20%E5%8C%BA%E9%97%B4%E5%8E%86%E5%8F%B2%E6%9C%80%E5%80%BC/vote)

**Comment by Enter-tainer** [comment]
建议咨询本人？

**Comment by ouuan** [comment]
11111 大草（

**Comment by Ir1d** [comment]
图源 @sshwy 

![image](https://user-images.githubusercontent.com/10709657/65597412-a7ea0e00-dfcb-11e9-9a66-14aa27963a4a.png)

![image](https://user-images.githubusercontent.com/10709657/65597400-a4568700-dfcb-11e9-8151-5ff81d8c4bb7.png)

**Comment by ouuan** [comment]
（其实我觉得叫吉老师线段树是最方便检索的）

**Comment by Ir1d** [comment]
嗯.. 现在搜索貌似是废的，我抽空修一下

**Comment by ouuan** [comment]
![image](https://user-images.githubusercontent.com/30581822/65597697-50986d80-dfcc-11e9-9548-5f4e00f5d2e6.png)

emm..好像没有问题，那可能 #1723 真的是个人问题（

**Comment by ouuan** [comment]
![image](https://user-images.githubusercontent.com/30581822/65597860-ab31c980-dfcc-11e9-93e3-a0f041e0f9bf.png)
