### ISSUE TITLE
搜索失效了!

### ISSUE THREAD

**Issue by lushuyu** [OI-wiki/OI-wiki#1726]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x ] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
关于搜索
他死了。
![image](https://user-images.githubusercontent.com/27007632/65647248-adc60a80-e030-11e9-81e9-da1697799fb8.png)

**Comment by Ir1d** [comment]
感谢提醒，应该已经修复了。麻烦 Ctrl f5 刷新之后再看看
