### ISSUE TITLE
更新后缀数组

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1729]
感觉 [我写的后缀数组学习笔记](https://ouuan.github.io/后缀数组学习笔记/) 是我写的算法博客中写的最好的（

大家觉得要不要用 [它](https://ouuan.github.io/后缀数组学习笔记/#后缀数组怎么求？) 换掉 [现在后缀数组的“构造”部分](https://oi-wiki.org/string/sa/#_2)。

当然有些细节可能还是得修一修（毕竟是半年前写的）。

[![](https://api.gh-polls.com/poll/01DNTMS8HV9QQW711TNKN937G1/%E6%8D%A2)](https://api.gh-polls.com/poll/01DNTMS8HV9QQW711TNKN937G1/%E6%8D%A2/vote)
[![](https://api.gh-polls.com/poll/01DNTMS8HV9QQW711TNKN937G1/%E4%B8%8D%E6%8D%A2)](https://api.gh-polls.com/poll/01DNTMS8HV9QQW711TNKN937G1/%E4%B8%8D%E6%8D%A2/vote)

**Comment by ouuan** [comment]
我个人觉得我对 height 那个引理的证明也写的比较清楚（

**Comment by ouuan** [comment]
那个循环子串好神秘啊..

**Comment by Ir1d** [comment]
没太搞懂，你是说在构造那里讲一下计数排序吗？
那个神秘的循环子串可能是从 emaxx 翻译的时候导致的

**Comment by ouuan** [comment]
我是说换成我的..

**Comment by ouuan** [comment]
为什么会理解成“讲一下计数排序”呢？

**Comment by Ir1d** [comment]
把你那篇的哪部分换进来呢？

**Comment by ouuan** [comment]
“后缀数组怎么求？” & “O(n) 求 height 数组需要的一个引理” 吧

**Comment by ouuan** [comment]
很多（包括 Wiki）的后缀数组教程都是直接给的板子（除了 n^2logn），中间都没给，感觉会让初学者非常迷惑。

**Comment by Ir1d** [comment]
你感觉这两部分有办法合并起来吗，而不是直接替换掉

**Comment by ouuan** [comment]
那我试图 merge 一下吧（~~又多了一个咕 #1672 的理由~~）

**Comment by ouuan** [comment]
感觉“实用技巧及数据结构”那段有些看不懂，里面有几道我做过的题我换成例题的形式，剩下的只能保持原样了..
