### ISSUE TITLE
例题推荐链接

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1741]
UOJ > LOJ > 洛谷 > BZOJ（估计大家不会同意放 darkbzoj，这样的话我认为优先级低于洛谷吧..）

国外 OJ 便于访问、提交的优先原 OJ。

大家觉得怎么样？

**Comment by ouuan** [comment]
到时候放到 htc 里。

**Comment by Ir1d** [comment]
好呀，顺便说之前这部分一直没碰是因为想造一个题目的索引。大概是链接到那个索引工具去，在那里面再分流到不同 OJ :joy:
感觉没功夫整了，欢迎感兴趣的同学来实现，或者有机会可以把这个功能塞到 @oi-archive 里面

**Comment by ouuan** [comment]
> 好呀，顺便说之前这部分一直没碰是因为想造一个题目的索引。大概是链接到那个索引工具去，在那里面再分流到不同 OJ 
> 感觉没功夫整了，欢迎感兴趣的同学来实现，或者有机会可以把这个功能塞到 @oi-archive 里面
> 
> // emmm 可能有点像 vjudge 了

我觉得更像洛谷 remote judge 的跳转至原 OJ（

**Comment by ouuan** [comment]
感觉就算写了插件，添加 link 也工作量巨大（

**Comment by Ir1d** [comment]
所以我觉得可以先维持原状，等待科技发展到足够水平再来搞（

**Comment by ouuan** [comment]
可以接受把 link 链接丢前端吗（

**Comment by ouuan** [comment]
怎么写插件啊 :thinking:

**Comment by ouuan** [comment]
感觉 wiki 上链接也不是特别多，全丢前端好像可以接受（×

**Comment by Ir1d** [comment]
什么事丢前端？
mkdocs 插件参考 https://github.com/facelessuser/pymdown-extensions/
remarkjs 插件参考 https://github.com/remarkjs/remark/tree/master/packages/remark-stringify/lib/visitors

**Comment by ouuan** [comment]
我写了个 JavaScript 实现的，从 json 获取数据（

**Comment by ouuan** [comment]
题目重名好像不太好处理..

**Comment by ouuan** [comment]
其实 LOJ 和洛谷的优先度值得商榷，个人感觉 LOJ 的优势是题面 & 数据下载，洛谷的优势是题解。好像也不能说就无脑全 LOJ...

**Comment by ouuan** [comment]
只不过考虑到读者未来可能会出题，我觉得优秀的题面以及能下载 checker 更加重要（×

**Comment by ouuan** [comment]
还能锻炼读者的搜索题解能力（×
