### ISSUE TITLE
调整板块划分

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1751]
可以把 ~~杂项的杂项~~ 首页里的评测工具、SPJ、Testlib、Polygon、LaTeX 入门移过去，把出题专题拆分成多篇文章。

另外我今天刚刚看到 [GCJ 出题指南](https://code.google.com/codejam/resources/problem-preparation)，想翻译了放上来。

**Comment by abc1763613206** [comment]
感觉得讨论下权重，避免沦为出题wiki（

**Comment by Ir1d** [comment]
可能有的一个问题是，评测工具 和 LaTeX 入门 不局限于出题人吧。如果放在出题板块下，会不会变得不好找了。
我想到一种方案：各种出题指南放杂项里，在专题里搞一个汇总页面（

**Comment by ouuan** [comment]
所以要成为杂项 Wiki 吗..

而且我觉得成为出题 Wiki 也未必是坏事。算是能为国内出题环境做一点贡献吧..

**Comment by ouuan** [comment]
> 可能有的一个问题是，评测工具 和 LaTeX 入门 不局限于出题人吧。如果放在出题板块下，会不会变得不好找了。
> 我想到一种方案：各种出题指南放杂项里，在专题里搞一个汇总页面（

现在差不多就是这样..真的就杂项 Wiki 吗..

**Comment by Ir1d** [comment]
杂项 Wiki 是什么意思

**Comment by ouuan** [comment]
而且出题指出题相关，不是只有出题人才会用到。

**Comment by Ir1d** [comment]
我的意思是做题的时候也会想了解评测工具，latex 入门也可以作为 htc 的补充 :thinking:

**Comment by ouuan** [comment]
或者不叫出题， 就放题目相关的东西. LaTeX 可以放首页。

**Comment by StudyingFather** [comment]
> 或者不叫出题， 就放题目相关的东西. LaTeX 可以放首页。

看上去是一个不错的解决方案 👍

**Comment by Ir1d** [comment]
恩，这个名字有点不太好想

**Comment by ouuan** [comment]
简介：Wiki 相关与 OI（竞赛）相关。
题目：出题、评测……大致是 CP 去掉竞赛去掉语言、算法与数据结构。
杂项：无法分类的算法与数据结构。
语言基础：改名为“语言”，把 IDE 什么的也放进去。
其它板块：放算法与数据结构。

**Comment by Ir1d** [comment]
题目 会不会给人一种 OJ 的感觉

**Comment by ouuan** [comment]
> 题目 会不会给人一种 OJ 的感觉

> 恩，这个名字有点不太好想

（论如何区分 Quote Reply 与引用）

**Comment by ouuan** [comment]
反正大致思想就是 OI = （设计算法解决问题 = 语言 + 算法 + 数据结构） + （题目 = （做题 = 解题技巧、题目类型……） + （出题 = （如何出题 = 如何造数据、题目投到哪……） + （如何出好题 = 题面规范、数据规范、idea 要求……）） + 评测……）+（竞赛 = 国内 OI 赛制、训练指南……）

感觉这样分的话除了同时用到多种知识点的算法之类的都差不多 OK 了。

**Comment by orzAtalod** [comment]
> 反正大致思想就是 OI = （设计算法解决问题 = 语言 + 算法 + 数据结构，不可分类的放杂项） + （题目 = （做题 = 解题技巧、题目类型……） + （出题 = （如何出题 = 如何造数据、题目投到哪……） + （如何出好题 = 题面规范、数据规范、idea 要求……）） + 评测……）+（竞赛 = 国内 OI 赛制、训练指南……）
> 
> 感觉这样分的话除了同时用到多种知识点的算法之类的都差不多 OK 了。

建议在“设计算法解决问题”的不可分类一处再设置“不可分类的算法”和“算法设计有关的知识点”

~~（不过本来就没有多少不可分类的，分了也不会更容易找啥的）~~

**Comment by ouuan** [comment]
“算法设计有关的知识点”是啥 🤔

**Comment by ouuan** [comment]
> ~~如果“杂项”的意义是“无法分类的算法”的话，复杂度貌似并不算算法，按照五项划分的话，似乎应该放在设计算法解决问题的某一处~~
>
> 感觉五项划分和我刚刚提出的想法挺类似的 ~~意思是，抱歉让您看了那么多废话~~ 

我分类的杂项其实是“无法分类的知识点”，而不只是算法。

我感觉我的分类和您的分类差的挺大吧（

**Comment by NachtgeistW** [comment]
“算法基础”下的“交互题”应该挪走。这不是算法这是题型……
或许可以开一个“题型”栏？如果没地方可放的话可以先扔到简介下跟“非传统题”合一起

**Comment by ouuan** [comment]
![图片](https://user-images.githubusercontent.com/30581822/85854025-318e6c80-b7e6-11ea-8c60-28ed0f0c6a95.png)

**Comment by ouuan** [comment]
大概可以这样：

1. 新建“试题”（试题/比赛相关信息，解题技巧（相对于更加偏向理论的“知识点”）等）和“工具”两个大分类，去掉“专题”分类。
2. 主页只留（只）和 OI Wiki 相关的东西，比如 #2108 里提到的那些。
3. 现在主页的“工具软件”可以移到“工具”下面作为一级子目录，“语言基础”里的 IDE/编辑器 也可以移到“工具”。
4. 主页里那些和赛制、题型、做题技巧有关的，以及“专题/出题”，都移到“试题”分类。专题里的其它东西可以放在”试题/经典问题“子目录下。
5. 感觉”杂项/读入、输出优化“也可以放在”试题“分类下作为做题技巧。

**Comment by NachtgeistW** [comment]
> 大概可以这样：
> 
> 1. 新建“试题”（试题/比赛相关信息，解题技巧（相对于更加偏向理论的“知识点”）等）和“工具”两个大分类，去掉“专题”分类。
> 2. 主页只留（只）和 OI Wiki 相关的东西，比如 #2108 里提到的那些。
> 3. 现在主页的“工具软件”可以移到“工具”下面作为一级子目录，“语言基础”里的 IDE/编辑器 也可以移到“工具”。
> 4. 主页里那些和赛制、题型、做题技巧有关的，以及“专题/出题”，都移到“试题”分类。专题里的其它东西可以放在”试题/经典问题“子目录下。
> 5. 感觉”杂项/读入、输出优化“也可以放在”试题“分类下作为做题技巧。

我感觉“试题”改为“竞赛相关”会不会更好？“试题”只能反映题目相关的内容，用“竞赛相关”就能把所有与比赛相关的内容划过去了。
另外给一个我的子目录划分
- 竞赛相关
  - 赛制
    - OI（后略）
    - ACM/ICPC（后略）
  - 学习路线
  - 学习资源
  - 常见错误
  - 常见技巧
  - 题型
    - 非传统题
    - 交互题（算法基础/交互题）
  - 出题

**Comment by ouuan** [comment]
> 另外给一个我的子目录划分
> 
>     * 竞赛相关
>       
>       * 赛制
>         
>         * OI（后略）
>         * ACM/ICPC（后略）
>       * 学习路线
>       * 学习资源
>       * 常见错误
>       * 常见技巧
>       * 题型
>         
>         * 非传统题
>         * 交互题（算法基础/交互题）
>       * 出题

学习路线和学习资源需要放这一类吗 :thinking:

**Comment by NachtgeistW** [comment]
> > 另外给一个我的子目录划分
> > 
> >     * 竞赛相关
> >       
> >       * 赛制
> >         
> >         * OI（后略）
> >         * ACM/ICPC（后略）
> >       * 学习路线
> >       * 学习资源
> >       * 常见错误
> >       * 常见技巧
> >       * 题型
> >         
> >         * 非传统题
> >         * 交互题（算法基础/交互题）
> >       * 出题
> 
> 学习路线和学习资源需要放这一类吗 :thinking:

感觉可以的吧。如果说首页只留和OI Wiki相关的内容的话，那这两个也得挪走。

**Comment by StudyingFather** [comment]
resolved in #2437.
