### ISSUE TITLE
add mingw_w64/gcc 安装指南

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/OI-wiki#1766]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

mingw_w64 安装指南

- 有什么参考资料？

https://www.msys2.org/

众所周知，在 Windows 下安装 gcc 是一大难题

**Comment by TieWay59** [comment]
http://mingw-w64.org/doku.php/start
http://mingw-w64.org/doku.php/download/mingw-builds

给准备写这篇的朋友提供一个资源站···

**Comment by MXR128** [comment]
众所周知，装gcc不就是官网安装包一装然后搞一下命令路径就好了？

**Comment by Enter-tainer** [comment]
mingw 的最新版本实际上很旧（gcc4.x）
mingw w64 的最新版本停留在 gcc7.x
只有 msys2 上的 mingw w64 才是 9.x 的

**Comment by Xeonacid** [comment]
@Enter-tainer 无脑吹 https://nuwen.net/mingw.html
版本是8.2.0，解压就能用
大概是方便程度和版本新旧上比较好的折中选择

**Comment by kexplorning** [comment]
MinGW 这个东西其实一直活着，如果去看官网（由于与 SourceForge 有矛盾所以搬到 OSDN 上了）上的 Release 目录，会发现有 GCC-8.2.0（只有 32 位版本的），这个东西是上个月发布的。劣势很明显，没有 64 位版本。（不知道是不是我打开方式有问题，下载后跑起来没有反应……）

MinGW-w64 在 SourceForge 上官方目前（最新）只提供了 GCC-8.1.0 的 Windows 编译版本。

MSYS2 是 Arch 风格滚动更新，所以，当然更新最积极。

---

个人认为安装还是包管理器最简单，一行命令解决
```
scoop install gcc gdb
```

或者用 WSL。到了 Linux，这些麻烦事都没了。还有，由于 VSCode 是微软亲儿子，所以 VSCode 上面就有一个 WSL Remote 插件，无缝连接 Linux，用起来非常舒服。个人觉得这是 WSL 最 awesome 的一点，这与装虚拟机或是装双系统完全不同的体验，可以打败这种体验的大概只有 macOS（和黑苹果），可惜 OI Wiki 上没有介绍……

---

单安装 GCC 的确不麻烦，麻烦在于

1. 第三方库，手动安装是很麻烦的，为此，Visual Studio 还搞出了一个 C++ 的包管理器。不过 OI 也不怎么需要这东西……
2. 软件冲突，在 Windows 下这个东西难以解决。很多来自 Linux 世界的软件，安装起来都会附带一份 GCC，比如安装 Git、Emacs、Perl 等软件，各自有自己那个版本的 MinGW……安装个 Git 顺便就带了个 MSYS……这个时候得对 `PATH` 非常小心，防止软件冲突。

**Comment by bhuztez** [comment]
用`choco install`吧，不然CI不好搞。比如，Travis-CI，Azure Pipeline都支持choco

**Comment by Enter-tainer** [comment]
@bhuztez 好像没有用过这个..问一下，choco在国内速度怎么样？

**Comment by kexplorning** [comment]
@Enter-tainer 。。个人觉得有点慢。。（所以我换成了 scoop，多线程下载还可以补救一下。。）

**Comment by neko-para** [comment]
如果想在windows上用类linux环境，使用perl、vim等等的程序的话，用msys2应该是最轻松的了吧，pacman真的香
另外终端也可以很容易的集成到vscode里面

**Comment by kexplorning** [comment]
。。这里貌似变成圣战了

**Comment by kexplorning** [comment]
总结一下，一共有几种路子：

- 我要最 Linux 的体验：安装 Linux 系统吧，或者双系统
- 我不想抛弃 Windows（因为有 PhotoShop 之类的常用软件）
   - 有钱：苹果机（UNIX native）
   - 可以折腾且台式机：黑苹果
   - 没钱或笔记本：见下一条
- 你要？
   - 隔离环境的 Linux/MacOS（不怕玩坏）：虚拟机
   - 容易合作快速部署的环境：Docker 容器
   - 写代码调程序方便就可以了~~：见下一条
- 在这个时候有三种选择
   - ~~babun~~（死了）
   - MSYS2 / Cygwin
   - 要有尽可能完整的 Linux 系统：WSL
   - **轻量级**（拒绝上述两个庞大的选择）命令行：gow（然而这个选项不能使用 gcc 也不能使用 MSVC）
   - 另辟蹊径：在 git for windows 中搞事情（见最后）
- 要有滚动更新的快感
   - MSYS2（要用国内镜像）
   - WSL: Arch Linux (archwsl)（要用国内镜像）
- 你还要 Windows 的包管理器？
    - Scoop（可使用 Aria2 多线程下载，部分地区依然需要挂）（P.S. Scoop 其实是滚动更新的）
    - Choco（国内请挂梯子使用）（P.S. 其实 Choco 也是，不过有些软件的更新策略随维护者心情而变）
- 好的，作为一个正经的 OIer 兼 Linux 用户（雾），来来来，选择一个编辑器：
   - vi
   - emacs
   - others
       - vscode
       - Notepad++
- 啊！我只想编译 C/C++
   - MinGW-w64
   - MinGW Distro - nuwen.net
- 什么？你在说什么？
   - Code::Block
   - Dev-C++
   - Visual Studio
- 我的电脑是 XP
   - 。。。。。。

---

**在 Git for Windows 中搞事情（之一）**

首先，Git for Windows 其实自带了一个 Git Bash，其中就有很多常用的工具，比如 `curl`，它还附带了 `vim`。

这个 Git Bash 其实是 MSYS2 的一个修改版，然而它没有 pacman 之类的东西，所以，如果你想搞事情，你可以尝试把 MinGW-w64 的 gcc 和 gdb 与 Git Bash 融合在一起。嗯。。如果你成功了，Git Bash 中的一切就足够你使用（大雾）

**在 Git for Windows 中搞事情（之二）**

当然，上面的融合方式可能过于困难，没关系，你还可以选择把 MinGW-w64 与 Git for windows 都安装了，并加入 `PATH` 中，然后你就可以在 Git Bash 中使用 gcc 了，还可以使用 gdb 命令行手动调试，甚至还可以自定义 `vim` 呢。

这个方案甚至非常方便并且切实可行，如果你用了 Windows 包管理器，你需要的就是两行命令，然后就搞定了呢（大雾）

P.S. 上述两个方案不保证稳定性。

**Comment by Xeonacid** [comment]
@kexplorning 笔记本也不是不能黑苹果嘛（x

**Comment by Enter-tainer** [comment]
https://jmeubank.github.io/tdm-gcc/ 

TDM-GCC 复活了，更新了 9.2.0 版本

**Comment by Suyun514** [comment]
吹一下 https://gcc-mcf.lhmouse.com/。
有多国语言的报错信息（包括中文），还自带 Python。

**Comment by Suyun514** [comment]
其他的 POSIX 工具用 Git for Windows 补齐吧（

**Comment by Enter-tainer** [comment]
http://winlibs.com/ 似乎是很不错的选择

**Comment by Enter-tainer** [comment]
现在看起来 winlibs.com 是最好的选择，包含了最新的全套 gcc 和 llvm。从编译器到 clang-extra-tools 应有尽有。

**Comment by alphagocc** [comment]
```
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
irm get.scoop.sh | iex
scoop install mingw-winlibs
```

**Comment by alphagocc** [comment]
@alphagocc 感觉最大问题是 github 连接性
