### ISSUE TITLE
CodeVS 当前不可用

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#1774]
CodeVS 近日因为备案失效的原因，陷入了不可用的状态。

考虑到 CodeVS 长期几乎无人维护的现状，短期内恢复访问的概率不大。

通过搜索发现 OI-wiki 上有少量的 CodeVS 题目链接，因 vjudge,OI-archive 等网站均未存储 CodeVS 的题目，因此应考虑将这些题目进行更换。

另外，bzoj 近日不可用的原因大概率也与备案失效有关（备案系统里没有查到 bzoj 旧备案号对应的记录，但按域名查询查到了于 10/21 验证的新备案记录）。

**Comment by WAAutoMaton** [comment]
@StudyingFather 我谢罪....本来早该爬cv了一直被我鸽着就鸽没了..

**Comment by WAAutoMaton** [comment]
JoyOI 似乎完整的爬取了 CodeVS 的所有题面， OI-Archive 接下来将存档这些数据。

**Comment by diauweb** [comment]
目前有下列页面中引用了CodeVS中的题目

位置 |  题号 
------------ | -------------
basic/prefix-sum.md | [CodeVS 1373. 射命丸文](http://codevs.cn/problem/1373/) 
geometry/triangulation.md | [CodeVS 2819 无尽的毁灭](http://codevs.cn/problem/2819/)
graph/lca.md | [CODEVS2370 小机房的树](http://codevs.cn/problem/2370/)
math/bit.md |  [CODEVS 2743 黑白棋游戏](http://codevs.cn/problem/2743/) 

介于issue被发起后18天 CodeVS 仍然处于无备案状态无法访问，现在是否可以考虑将所有页面中的CodeVS链接换成archive版本了？

**Comment by Ir1d** [comment]
哇感谢整理
可以先换成 joyoi..?
不过这部分题目感觉早晚得换掉了
oj-archive 还在初期阶段吧，别太 push 了🌚

**Comment by ChungZH** [comment]
那，https://oi-wiki.org/intro/resources/ 这里是不是也应该删掉 CodeVS 了呢...

**Comment by ranwen** [comment]
@ChungZH @WAAutoMaton 来加OI-Archive

**Comment by Ir1d** [comment]
> 那，[oi-wiki.org/intro/resources](https://oi-wiki.org/intro/resources/) 这里是不是也应该删掉 CodeVS 了呢...

@ChungZH 好呀，删掉吧（PR welcome

**Comment by ChungZH** [comment]
@Ir1d 以什么样的方式呢？加删除线还是完全删掉？

**Comment by Ir1d** [comment]
:smile: 在 md 里注释掉吧

**Comment by ChungZH** [comment]
:ok:
