### ISSUE TITLE
补充作者

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1785]
@Ir1d [PR 348](https://github.com/OI-wiki/OI-wiki/pull/496)好像说要在贡献名单追加 @Xarfa 来着

_Originally posted by @CBW2007 in https://github.com/OI-wiki/gitment/issues/22#issuecomment-546656331

#480

**Comment by ouuan** [comment]
这个我会在 #1752 修的（

**Comment by Ir1d** [comment]
#1752 干的事情太多，感觉不是很清晰了，不如这个单独搞

**Comment by ouuan** [comment]
单独搞也会 conflict...

**Comment by ouuan** [comment]
本来就是个小 fix

**Comment by ouuan** [comment]
其实我已经改过了，但是改到一半机房换电脑了（

https://github.com/ouuan/OI-wiki/tree/section-temp

**Comment by Ir1d** [comment]
fine。不过 conflict 是必然的，因为 1752 涉及 的页面有点多了。。我只是感觉如果很多 issue 都等一个 pr 的话这个压力略大..

**Comment by CBW2007** [comment]
![QQ截图20191030211836](https://user-images.githubusercontent.com/42204218/67861285-d921a500-fb5a-11e9-85d5-9ad523bbab77.png)

<https://oi-wiki.org/basic/divide-and-conquer/>我和其他许多人的贡献好像也丢了......history里能翻到，结果显示里炸了

#1191

**Comment by sshwy** [comment]
这个issue现在是来干啥的 /fad

**Comment by Ir1d** [comment]
关了吧，有遗漏可以再开 issue
