### ISSUE TITLE
图论 BFS 标题 在树/图上 BFS 链接到 404 页面

### ISSUE THREAD

**Issue by yjl9903** [OI-wiki/OI-wiki#1801]
页面 [BFS (图论)](https://oi-wiki.org/graph/bfs/) 中 在树/图上 BFS 标题链接到了不存在的页面 `/graph/traverse`

首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

- 你是否正在着手修复？

- 如何复现？

issue 标题请写为 要汇报的主要内容

**Comment by abc1763613206** [comment]
问题所在页面？

**Comment by Ir1d** [comment]
docs/graph/bfs.md 和 docs/misc/expression.md

**Comment by abc1763613206** [comment]
出现问题的 commit : https://github.com/OI-wiki/OI-wiki/commit/4c3dcc0c683b7ea6c8fc8fc29d54dc3084b0bb13

**Comment by abc1763613206** [comment]
出现问题的 pr : #1463
