### ISSUE TITLE
将 FAQ 中应当放在 htc 的部分合并至 htc 并更新 htc

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1815]
FAQ 与 htc 的定位各是什么，是否应该将 FAQ 中关于“如何贡献”的部分合并至 htc？

**Comment by ouuan** [comment]
感觉自己开的坑越来越多，然而还是整天只会 review 不去填坑（

**Comment by ouuan** [comment]
https://github.com/OI-wiki/OI-wiki/issues/1674#issuecomment-551068637

**Comment by ouuan** [comment]
感觉可以在 htc 中加入“请在编辑完成后阅读一遍自己所写的内容，编译测试一下所写的代码”。

另外可以强调一下 Markdown 每种语法的用途，尤其是 ``` `` ``` 的用途（不仅有滥用 ``` `` ``` 的人，甚至有能用 ``` `` ``` 全用斜体的人...）。

**Comment by ouuan** [comment]
然后平时审核时遇到的问题都可以加进来。

**Comment by ouuan** [comment]
需要提一下 author 是增量更新，有 commit 不需手动添加。

**Comment by ouuan** [comment]
https://github.com/OI-wiki/OI-wiki/pull/1826#issuecomment-551432972

**Comment by sshwy** [comment]
这个FAQ就是一个大坑。
