### ISSUE TITLE
本页面贡献者：本页面是自动生成的

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1821]
我看到的所有页面都是自动生成的。

**Comment by Ir1d** [comment]
#1800 导致的，document.getElementsByClassName('page_edit_url') 抓不到对应 Github
文件的链接了。

**Comment by ouuan** [comment]
我更倾向于修改右上角按钮跳转到的链接.（虽然暂时还并没有看过源码）

**Comment by Ir1d** [comment]
“修改右上角按钮跳转到的链接”？意思是不跳到这个 edit-landing 么

**Comment by ouuan** [comment]
意思是不跳到 repo_url/edit_uri

**Comment by ouuan** [comment]
要不先 revert 再修。

**Comment by Ir1d** [comment]
没懂你在说啥，现在就不是跳到 repo_url/edit_url

**Comment by ouuan** [comment]
我是说 repo_url 和 edit_uri 的设置改成 #1800 之前的，但依然跳转到 edit-landing

**Comment by ouuan** [comment]
现在是跳到 `repo_url/edit_uri` 啊，现在的 `edit_uri` 是 `'https://oi-wiki.org/edit-landing/?ref='`

**Comment by Ir1d** [comment]
抱歉，我误解你的意思了 :| 搞了个 workaround 但是我本地 rate limit 了，放到 preview 上面看看效果吧
