### ISSUE TITLE
fix: 语言基础的许多问题和内容缺失

### ISSUE THREAD

**Issue by orzAtalod** [OI-wiki/OI-wiki#1831]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

语言措辞问题（未经定义直接使用概念），内容缺失，内容排布问题（例如输入输出在变量前讲）

- 你是否正在着手修复？

是的

- 如何复现？

在 OI-wiki 中，点开语言基础

issue 标题请写为 要汇报的主要内容

**Comment by ouuan** [comment]
这个太宽泛了，~~我建议 fix OI Wiki 上的许多问题~~。

**Comment by ouuan** [comment]
开 pr 的话其实可以不先开 issue 🤔

**Comment by orzAtalod** [comment]
> 这个太宽泛了，~我建议 fix OI Wiki 上的许多问题~。

~~已经在群内开始讨论了，issue 只是象征性开一下~~

**Comment by akakw1** [comment]
不是语言基础吗（

怎么变成基础部分了

**Comment by abc1763613206** [comment]
这玩意儿还是想法子拉个清单吧......      
不然之后弃坑了后来人都补不上

**Comment by akakw1** [comment]
```text
1. 环境配置
2. 基础定义
3. 变量
   3.1 什么是变量
   3.2 变量类型
   3.3 常量
4. 流程控制语句
   3.1 选择
   3.2 循环
5. 指针和数组
6. 结构体
7. 函数
8. 基础文操 
```
😄

**Comment by orzAtalod** [comment]
~~目前缺失：指针（函数指针） 变量类型 函数~~

~~TODO：重新编排目录，补上缺失的~~

清单大概是哪个方面的清单 ~~如果是错误清单的话拉清单的工作量可能会和修的工作量差不多，待补齐清单直接看没啥补啥应该就好了~~

**Comment by ouuan** [comment]
建议把没有关联的页面拆分成多个 pr 改，像 #1752 咕了一万年最后还是拆分了（

**Comment by ouuan** [comment]
（只不过您是不是还不太会一个 pr 改多个文件）

**Comment by abc1763613206** [comment]
> （只不过您是不是还不太会一个 pr 改多个文件）

@ouuan #1832 里似乎他会

**Comment by Tiphereth-A** [comment]
> ```
> 1. 环境配置
> 2. 基础定义
> 3. 变量
>    3.1 什么是变量
>    3.2 变量类型
>    3.3 常量
> 4. 流程控制语句
>    3.1 选择
>    3.2 循环
> 5. 指针和数组
> 6. 结构体
> 7. 函数
> 8. 基础文操 
> ```
> 
> 😄

这里列出来的都已经有了，那这个 issue 是不是可以关了 🤔
