### ISSUE TITLE
fix: 搜索框无法通过右侧的“x”标记关闭

### ISSUE THREAD

**Issue by orzAtalod** [OI-wiki/OI-wiki#1833]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）

搜索框无法通过“x”关闭，需要点击页面空白处才可关闭。“x”标记只会清空搜索框中内容。

- 你是否正在着手修复？

不会修。

- 如何复现？

issue 标题请写为 要汇报的主要内容

**Comment by ouuan** [comment]
那么为什么要有两种关闭的方式，而去掉清空这个功能呢？

**Comment by orzAtalod** [comment]
> 
> 
> 那么为什么要有两种关闭的方式，而去掉清空这个功能呢？

因为我觉得一般人肯定会以为点叉是关闭（x

所以可以再设置一个清空按钮，点叉改成关闭（或者直接将 x 图标改为清空图标

**Comment by orzAtalod** [comment]
当时退不出我还以为搜索框关不掉了（糊

**Comment by ouuan** [comment]
改图标倒是可以考虑..

而且看到你这个 issue 后是我第一次去点这个叉..感觉这个 UI 给人的感觉就是点空白关闭（因为不是弹窗）。

**Comment by Ir1d** [comment]
这是上游的 feature，你可以去搜搜，作者好像有解释过。事实上点框外面任何一个地方都能关.. 私以为是挺常见的交互逻辑
