### ISSUE TITLE
完善关联式容器页面

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1843]
1. 默认比较函数为 `<`，如何自定义比较函数。

2. `++` 的复杂度。

3. 合并一些 set 和 map 相同的部分。

**Comment by StudyingFather** [comment]
我也许 CSP 后可以来填一下这个坑（咕）

**Comment by yjl9903** [comment]
C++11 可以这样重载 `std::set` 的小于号
```
auto cmp = [](int a, int b) { return a > b; };
std::set<int, decltype(cmp)> st(cmp);
```

**Comment by orzAtalod** [comment]
感觉 functor 可以新开个运算符重载，然后在那里讲，重载小于号只需要 link 一下就好了（坑+1

**Comment by StudyingFather** [comment]
> 感觉 functor 可以新开个运算符重载，然后在那里讲，重载小于号只需要 link 一下就好了（坑+1

安排上了 √
