### ISSUE TITLE
完善二分图页面

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#1847]
https://oi-wiki.org/graph/bi-graph/

写“图论相关概念”页面的时候写到匹配，想 link 过去，然后懵了（

**Comment by ouuan** [comment]
解决 DFS 式开坑（link 过程中开坑）的最好方法果然是开 issue（

**Comment by sshwy** [comment]
咋完善啊

**Comment by ouuan** [comment]
> 咋完善啊

https://github.com/OI-wiki/OI-wiki/blob/c96f1f7/docs/graph/bi-graph.md

**Comment by ouuan** [comment]
又是 PR 不 fix 的 /kk
