### ISSUE TITLE
mkdocs 支持 dag 形式的目录

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1861]
之前一直以为它只支持树型，可能对我们调整分类会有一点帮助

如图，两种情况均是 ok 的

![image](https://user-images.githubusercontent.com/10709657/69412484-ed1b8980-0d49-11ea-9874-7ea0b65a7423.png)
![image](https://user-images.githubusercontent.com/10709657/69412486-eee54d00-0d49-11ea-9671-283d120a65a9.png)

**Comment by ouuan** [comment]
不树形分类的话感觉阅读起来很迷惑（

**Comment by ouuan** [comment]
关键是一个目录在那..

**Comment by Ir1d** [comment]
我是说每个分类不要求不能重复。。

**Comment by ouuan** [comment]
我是说一个目录放在左边给人的感觉就和 tag 不一样，所以完全按 tag 的感觉进行 DAG 分类会非常迷惑..仅仅只是少量的同一篇文章放在不同目录对分类没啥改善吧（

**Comment by ouuan** [comment]
其实 Wikipedia 那种更适合查阅而没有那么适合阅读学习，如果 OI Wiki 要保持现在这样查学皆宜的风格，其实没必要抛弃树形分类..

**Comment by Ir1d** [comment]
mediawiki 是 dag 形式的嘛，我们之前一直以为 mkdocs 只可以树形😂

**Comment by ouuan** [comment]
我明白您有了新发现，但我的观点是它没啥用（

**Comment by ouuan** [comment]
我觉得 mkdocs 无法很好地实现 Wikipedia 那种 tag 式分类.

**Comment by ouuan** [comment]
其实强行改好像也不是不行..

**Comment by ouuan** [comment]
我大概试一试（

**Comment by Ir1d** [comment]
哦我好像明白你意思了。。 dag 可能在一些多级 tag 的情况比较有用，不过我们目前应该还不涉及

或者是比如在目录中间加个分隔符啥的，就可以维护两套目录了（猜测
不过不是很有动力魔改 mkdocs，如果有现代前段工具应该会好弄很多。。

**Comment by ouuan** [comment]
我刚刚好像是用现在的分类的思路去思考了..如果我们抛弃现在对目录的认识，就把目录看成“tag 的层级关系”，而非“条目的归属”，好像就没有那么迷惑..

**Comment by ouuan** [comment]
只不过如果在左侧把所有 tag 列出来可能会很多..多分几级可能可以解决。

**Comment by Ir1d** [comment]
好像缺点就是原文件会折叠起来.. 
如果我们把所有 tag 折叠起来然后和原目录并列呢🤔比如这种（

- 数学
 - 数学的 tags
   - tag1
      - page1..
 - page1
 - page2

**Comment by ouuan** [comment]
一个 tag 它本身的页面必须重写一次非常难受..

比如说：

```yaml
- 树:
  - 树: tree.md
  - 最近公共祖先:
    - 最近公共祖先: lca.md
    - 最近公共祖先的倍增求法: xxxx.md
    - 最近公共祖先的树剖求法: xxxxx.md
  - 最小生成树:
    - 最小生成树: mst.md
    - Kruskal 算法: kruskal.md
……
```

**Comment by ouuan** [comment]
刚刚想找几个页面搞个 demo，然后意识到了 Wikipedia 的 “link 到未创建的页面”这个功能多么重要（不然根本没法在页面数非常少的时候前置知识完整地写作）。

感觉短期内先保持原状比较好吧..

真要改成 tag 式估计得搞几个月（

**Comment by Ir1d** [comment]
感觉有点给 mkdocs 强行续命了.. docusaurus 似乎差不多了，寒假应该可以 migrate 试试

`link 到未创建的页面` 其实可以本地 touch 一波空白 md 啊（

**Comment by ouuan** [comment]
问题在于到底要做一个“教程合集”还是“词条查询工具”。

**Comment by Ir1d** [comment]
这是个好问题，不过有点 beyond 这个 issue 了（
我们现在的状态可能是一种 mixed 的蜜汁中间态..

**Comment by bhuztez** [comment]
教程合集 和 词条查询工具 不冲突吧。不是还有 wikibooks

**Comment by ouuan** [comment]
> 教程合集 和 词条查询工具 不冲突吧。不是还有 wikibooks

这个东西的结构好像海星。
