### ISSUE TITLE
FFT 页面用哪篇

### ISSUE THREAD

**Issue by sshwy** [OI-wiki/OI-wiki#1862]
[![](https://api.gh-polls.com/poll/01DT9BPDWEYE2ZRSXTY9K55RAD/%E5%9C%A8%E5%8E%9F%E6%9D%A5%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%8A%E5%A4%A7%E6%94%B9%20%231743)](https://api.gh-polls.com/poll/01DT9BPDWEYE2ZRSXTY9K55RAD/%E5%9C%A8%E5%8E%9F%E6%9D%A5%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%8A%E5%A4%A7%E6%94%B9%20%231743/vote)
[![](https://api.gh-polls.com/poll/01DT9BPDWEYE2ZRSXTY9K55RAD/%E6%8D%A2%E7%94%A8%E8%83%A1%E5%B0%8F%E5%85%94%E7%9A%84%E5%8D%9A%E5%AE%A2)](https://api.gh-polls.com/poll/01DT9BPDWEYE2ZRSXTY9K55RAD/%E6%8D%A2%E7%94%A8%E8%83%A1%E5%B0%8F%E5%85%94%E7%9A%84%E5%8D%9A%E5%AE%A2/vote)
[![](https://api.gh-polls.com/poll/01DT9BPDWEYE2ZRSXTY9K55RAD/%E6%9C%89%E6%9B%B4%E5%A5%BD%E7%9A%84%E6%96%B9%E6%A1%88)](https://api.gh-polls.com/poll/01DT9BPDWEYE2ZRSXTY9K55RAD/%E6%9C%89%E6%9B%B4%E5%A5%BD%E7%9A%84%E6%96%B9%E6%A1%88/vote)

[胡小兔博客链接](https://www.cnblogs.com/RabbitHu/p/FFT.html)

**Comment by ouuan** [comment]
既然已经改了这么多了，胡小兔的倒也没有什么明显的优势了..

**Comment by ouuan** [comment]
> 既然已经改了这么多了，胡小兔的倒也没有什么明显的优势了..

我可能要收回这句话。

**Comment by ouuan** [comment]
只不过说起来胡小兔那篇说不定也有不少要改的地方 🤔

**Comment by Ir1d** [comment]
landed in recent PR
