### ISSUE TITLE
进度统计

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#187]
#9
【注】：这里打钩仅表示有内容添加了，不代表这部分内容已经定稿，所有内容仍然在持续更新中。
nav:
  - 简介:
    - [x] Getting Started  index.md
    - [x] OI 赛事与赛制  intro/oi.md
    - [x] ICPC/CCPC 赛事与赛制  intro/icpc.md
    - [ ] 学习路线  intro/roadmap.md
    - [x] 学习资源  intro/resources.md
    - [x] 常见错误  intro/common-mistakes.md
    - [x] 常见技巧  intro/common-tricks.md
    - [x] 非传统题  intro/non-trad.md
    - 工具软件:
      - [x] 评测工具  intro/judgers.md
      - 编辑工具:
        - [x] Vim  intro/editor/vim.md
        - [x] Emacs  intro/editor/emacs.md
        - [x] VS Code  intro/editor/vscode.md
        - [x] Atom  intro/editor/atom.md
        - [x] Eclipse  intro/editor/eclipse.md
        - [x] Notepad++  intro/editor/npp.md
        - [x] Dev-C++  intro/editor/devcpp.md
      - [x] WSL (Windows 10)  intro/wsl.md
      - [x] Special Judge  intro/spj.md
      - Testlib:
        - [x] Testlib 简介  intro/testlib/index.md
        - [x] 通用  intro/testlib/general.md
        - [x] Generator  intro/testlib/generator.md
        - [x] Validator  intro/testlib/validator.md
        - [x] Interactor  intro/testlib/interactor.md
        - [x] Checker  intro/testlib/checker.md
      - [x] OJ 工具  intro/oj-tool.md
    - [x] Docker 部署  intro/docker-deploy.md
    - [x] 关于本项目  intro/about.md
    - [x] 如何参与  intro/htc.md
    - [x] F.A.Q.  intro/faq.md
    - [x] 致谢  intro/thanks.md
  - 语言基础:
    - C++ 基础:
      - [x] Hello, World!  lang/helloworld.md
      - [x] C++ 语法基础  lang/basic.md
      - [x] 变量  lang/var.md
      - [x] 运算  lang/op.md
      - [x] 数组  lang/array.md
      - [ ] 结构体  lang/struct.md
      - [ ] 指针  lang/pointer.md
      - [x] 分支  lang/branch.md
      - [x] 循环  lang/loop.md
      - [x] 函数  lang/func.md
      - [x] 文件操作  lang/file-op.md
    - C++ 标准库:
      - [x] C++ 标准库简介  lang/csl/index.md
      - STL 容器:
        - [x] STL 容器简介  lang/csl/container.md
        - [x] 迭代器  lang/csl/iterator.md
        - [x] 序列式容器  lang/csl/sequence-container.md
        - [x] 关联式容器  lang/csl/associative-container.md
        - [x] 无序关联式容器  lang/csl/unordered-container.md
        - [x] 容器适配器  lang/csl/container-adapter.md
      - [x] STL 算法  lang/csl/algorithm.md
    - C++ 进阶:
      - [ ] 类  lang/class.md
      - [x] 新版 C++ 特性  lang/new.md
      - pb_ds:
        - [x] pb_ds 简介  lang/pb-ds/index.md
        - [x] 堆  lang/pb-ds/pq.md
        - [ ] 平衡树  lang/pb-ds/tree.md
    - [ ] Pascal 转 C++ 急救  lang/pas-cpp.md
    - [x] Python 速成  lang/python.md
    - [ ] Java 速成  lang/java.md
  - 思想方法:
    - [x] 思想方法简介  basic/index.md
    - [x] 枚举  basic/enumerate.md
    - [x] 模拟  basic/simulate.md
    - [x] 递归 & 分治  basic/divide-and-conquer.md
    - [x] 贪心  basic/greedy.md
    - 排序:
      - [x] 排序简介  basic/sort-intro.md
      - [x] 选择排序  basic/selection-sort.md
      - [x] 冒泡排序  basic/bubble-sort.md
      - [x] 插入排序  basic/insertion-sort.md
      - [x] 计数排序  basic/bucket-sort.md
      - [x] 快速排序  basic/quick-sort.md
      - [x] 归并排序  basic/merge-sort.md
      - [x] 堆排序  basic/heap-sort.md
      - [x] 基数排序  basic/radix-sort.md
      - [x] 希尔排序  basic/shell-sort.md
      - [x] 排序相关 STL  basic/stl-sort.md
      - [x] 排序应用  basic/use-of-sort.md
    - [x] 二分  basic/binary.md
    - [x] 倍增  basic/binary-acc.md
    - [x] 构造  basic/construction.md
    - [x] 前缀和 & 差分  basic/prefix-sum.md
  - 搜索:
    - [x] 搜索部分简介  search/index.md
    - [x] DFS（搜索）  search/dfs.md
    - [x] BFS（搜索）  search/bfs.md
    - [x] 双向搜索  search/bidirectional.md
    - [x] 启发式搜索  search/heuristic.md
    - [x] A*  search/astar.md
    - [x] 迭代加深搜索  search/iterative.md
    - [x] IDA*  search/idastar.md
    - [x] 回溯法  search/backtracking.md
    - [ ] Dancing Links  search/dlx.md
    - [x] 优化  search/opt.md
  - 动态规划:
    - [x] 动态规划部分简介  dp/index.md
    - [x] 记忆化搜索  dp/memo.md
    - [x] 背包 DP  dp/knapsack.md
    - [x] 区间 DP  dp/interval.md
    - [x] DAG 上的 DP  dp/dag.md
    - [x] 树形 DP  dp/tree.md
    - [x] 状压 DP  dp/state.md
    - [x] 数位 DP  dp/number.md
    - [ ] 插头 DP  dp/plug.md
    - [ ] 计数 DP  dp/count.md
    - DP 优化:
      - [x] 二进制分组解多重背包  dp/opt/binary-knapsack.md
      - [x] 单调队列/单调栈优化  dp/opt/monotonous-queue-stack.md
      - [x] 斜率优化  dp/opt/slope.md
      - [x] 四边形不等式优化  dp/opt/quadrangle.md
      - [x] 状态设计优化  dp/opt/state.md
    - [ ] 其它 DP 方法  dp/misc.md
  - 字符串:
    - [x] 字符串部分简介  string/index.md
    - [x] 标准库  string/lib-func.md
    - [x] 字符串匹配  string/match.md
    - [x] 哈希  string/hash.md
    - [x] 前缀函数与 KMP 算法  string/kmp.md
    - [x] Z 函数（扩展 KMP）  string/z-func.md
    - [x] 字典树 (Trie)  string/trie.md
    - [x] 回文自动机  string/pam.md
    - [x] 后缀数组 (SA)  string/sa.md
    - [x] AC 自动机  string/ac-automaton.md
    - [x] 后缀自动机 (SAM)  string/sam.md
    - [ ] 后缀树  string/suffix-tree.md
    - [x] Manacher  string/manacher.md
    - [x] 最小表示法  string/minimal-string.md
    - [x] Lyndon 分解  string/lyndon.md
  - 数学:
    - [x] 数学部分简介  math/index.md
    - [x] 进制  math/base.md
    - [x] 位运算  math/bit.md
    - [x] 高精度  math/bignum.md
    - [x] 快速幂  math/quick-pow.md
    - 整除及其性质:
      - [x] 素数  math/prime.md
      - [x] 最大公约数  math/gcd.md
      - [x] 欧拉函数  math/euler.md
      - [x] 筛法  math/sieve.md
      - [x] 欧拉定理 & 费马小定理  math/fermat.md
      - [x] 类欧几里德算法  math/euclidean.md
    - 同余方程相关:
      - [x] 裴蜀定理  math/bezouts.md
      - [x] 乘法逆元  math/inverse.md
      - [x] 线性同余方程  math/linear-equation.md
      - [x] 中国剩余定理  math/crt.md
      - [x] BSGS  math/bsgs.md
      - [x] 原根  math/primitive-root.md
    - 线性代数:
      - [x] 矩阵  math/matrix.md
      - [x] 高斯消元  math/gauss.md
      - [x] 线性基  math/basis.md
    - [x] 复数  math/complex.md
    - [x] 分段打表  math/dictionary.md
    - [x] 牛顿迭代法  math/newton.md
    - 数论函数相关:
      - [x] 莫比乌斯反演  math/mobius.md
      - [x] 杜教筛  math/du.md
      - [x] Min_25 筛  math/min-25.md
    - 多项式:
      - [x] 多项式部分简介  math/poly/intro.md
      - [x] 拉格朗日插值  math/poly/lagrange.md
      - [x] 快速傅里叶变换  math/poly/fft.md
      - [x] 快速数论变换  math/poly/ntt.md
      - [x] 快速沃尔什变换  math/poly/fwt.md
      - [x] 多项式求逆  math/poly/inv.md
      - [x] 多项式开方  math/poly/sqrt.md
      - [x] 多项式除法|取模  math/poly/div-mod.md
      - [x] 多项式对数函数|指数函数  math/poly/ln-exp.md
      - [x] 多项式牛顿迭代  math/poly/newton.md
      - [x] 多项式多点求值|快速插值  math/poly/multipoint-eval-interpolation.md
      - [x] 多项式三角函数  math/poly/tri-func.md
      - [x] 多项式反三角函数  math/poly/inv-tri-func.md
    - 组合数学:
      - [x] 排列组合  math/combination.md
      - [x] 卡特兰数  math/catalan.md
      - [x] 斯特林数  math/stirling.md
      - [x] 康托展开  math/cantor.md
      - [x] 容斥原理  math/inclusion-exclusion-principle.md
      - [x] 抽屉原理  math/drawer-principle.md
    - [x] 概率 & 期望  math/expectation.md
    - [x] 斐波那契数列  math/fibonacci.md
    - [x] 置换群  math/permutation-group.md
    - [ ] 数值积分  math/integral.md
    - [x] 线性规划  math/linear-programming.md
    - [x] 单纯形  math/simplex.md
    - [x] 博弈论  math/game-theory.md
    - [x] 卢卡斯定理  math/lucas.md
    - [x] 数学杂项  math/misc.md
  - 数据结构:
    - [x] 数据结构部分简介  ds/index.md
    - [x] 栈  ds/stack.md
    - [x] 队列  ds/queue.md
    - [x] 链表  ds/linked-list.md
    - [x] 哈希表  ds/hash.md
    - [x] 并查集  ds/dsu.md
    - 堆:
      - [x] 堆简介  ds/heap.md
      - [x] 二叉堆  ds/binary-heap.md
      - [x] 配对堆  ds/pairing-heap.md
      - [x] 左偏树  ds/leftist-tree.md
    - 块状数据结构:
      - [x] 分块思想  ds/decompose.md
      - [x] 树分块  ds/tree-decompose.md
      - [x] 块状链表  ds/block-list.md
      - [x] 块状数组  ds/block-array.md
    - [x] 单调栈  ds/monotonous-stack.md
    - [x] 单调队列  ds/monotonous-queue.md
    - [x] ST 表  ds/sparse-table.md
    - [x] 树状数组  ds/bit.md
    - [x] 线段树  ds/seg.md
    - [x] 线段树 & 区间历史最值  ds/seg-beats.md
    - [x] 划分树  ds/dividing.md
    - 二叉搜索树 & 平衡树:
      - [x] 二叉搜索树简介  ds/bst.md
      - [x] Treap  ds/treap.md
      - [x] Splay  ds/splay.md
      - [x] WBLT  ds/wblt.md
      - [ ] Size Balanced Tree  ds/sbt.md
      - [x] AVL 树  ds/avl.md
      - [x] 替罪羊树  ds/sgt.md
      - [x] 笛卡尔树  ds/cartesian-tree.md
    - 可持久化数据结构:
      - [x] 可持久化数据结构简介  ds/persistent.md
      - [x] 可持久化线段树  ds/persistent-seg.md
      - [ ] 可持久化块状数组  ds/persistent-block-array.md
      - [x] 可持久化平衡树  ds/persistent-balanced.md
      - [x] 可持久化字典树  ds/persistent-trie.md
      - [x] 可持久化可并堆  ds/persistent-heap.md
    - 树套树:
      - [x] 线段树套线段树  ds/seg-in-seg.md
      - [ ] 平衡树套线段树  ds/seg-in-balanced.md
      - [x] 线段树套平衡树  ds/balanced-in-seg.md
      - [x] 树状数组套主席树  ds/persistent-in-bit.md
    - [x] K-D Tree  ds/kdt.md
    - [x] 珂朵莉树  ds/odt.md
    - 动态树:
      - [x] Link Cut Tree  ds/lct.md
      - [ ] Euler Tour Tree  ds/ett.md
      - [ ] Top Tree  ds/top-tree.md
    - [x] 析合树  ds/divide-combine.md
  - 图论:
    - [x] 图论部分简介  graph/index.md
    - [x] 图论基础  graph/basic.md
    - [x] DFS（图论）  graph/dfs.md
    - [x] BFS（图论）  graph/bfs.md
    - 树上问题:
      - [x] 树基础  graph/tree-basic.md
      - [x] 最近公共祖先  graph/lca.md
      - [x] 树的其他问题  graph/tree-misc.md
      - [x] 树哈希  graph/tree-hash.md
      - [x] 树链剖分  graph/hld.md
      - [x] 树分治  graph/tree-divide.md
      - [x] 动态树分治  graph/dynamic-tree-divide.md
      - [x] 虚树  graph/virtual-tree.md
      - [x] 树上启发式合并  graph/dsu-on-tree.md
    - [x] 矩阵树定理  graph/matrix-tree.md
    - [x] 有向无环图  graph/dag.md
    - [x] 拓扑排序  graph/topo.md
    - [x] 最小生成树  graph/mst.md
    - [x] 最小树形图  graph/mdst.md
    - [x] 最短路  graph/shortest-path.md
    - [x] 差分约束  graph/diff-constraints.md
    - [x] k 短路  graph/kth-path.md
    - 连通性相关:
      - [x] 强连通分量  graph/scc.md
      - [x] 双连通分量  graph/bcc.md
      - [x] 割点和桥  graph/bridge.md
      - [x] 2-SAT  graph/2-sat.md
    - [x] 欧拉图  graph/euler.md
    - [x] 哈密顿图  graph/hamilton.md
    - [x] 二分图  graph/bi-graph.md
    - [x] 最小环  graph/min-circle.md
    - [x] 平面图  graph/planar.md
    - [x] 图的着色  graph/color.md
    - 网络流:
      - [x] 网络流简介  graph/flow.md
      - [x] 拆点  graph/flow/node.md
      - [x] 最大流  graph/flow/max-flow.md
      - [x] 最小割  graph/flow/min-cut.md
      - [x] 费用流  graph/flow/min-cost.md
      - [x] 上下界网络流  graph/flow/bound.md
    - [x] Prufer 序列  graph/prufer.md
    - [x] 图论杂项  graph/misc.md
  - 计算几何:
    - [x] 计算几何部分简介  geometry/index.md
    - [x] 二维计算几何基础  geometry/2d.md
    - [ ] 三维计算几何基础  geometry/3d.md
    - [x] 距离  geometry/distance.md
    - [x] Pick 定理  geometry/pick.md
    - [ ] 三角剖分  geometry/triangulation.md
    - [x] 凸包  geometry/convex-hull.md
    - [x] 扫描线  geometry/scanning.md
    - [ ] 旋转卡壳  geometry/rotating-calipers.md
    - [x] 半平面交  geometry/half-plane.md
    - [x] 平面最近点对  geometry/nearest-points.md
    - [x] 随机增量法  geometry/random-incremental.md
    - [x] 计算几何杂项  geometry/misc.md
  - 杂项:
    - [x] 杂项简介  misc/index.md
    - [x] 读入、输出优化  misc/io.md
    - [x] 复杂度  misc/complexity.md
    - [x] 离散化  misc/discrete.md
    - 离线算法:
      - [ ] 离线算法简介  misc/offline.md
      - [x] CDQ 分治  misc/cdq-divide.md
      - [x] 整体二分  misc/parallel-binsearch.md
      - [x] 莫队算法  misc/mo-algo.md
    - [x] 分数规划  misc/frac-programming.md
    - 随机化:
      - [x] 随机函数  misc/random.md
      - [x] 爬山算法  misc/hill-climbing.md
      - [x] 模拟退火  misc/simulated-annealing.md
    - [x] 悬线法  misc/largest-matrix.md
    - [x] 计算理论基础  misc/cc-basic.md
    - [x] 字节顺序  misc/endianness.md
    - [x] 约瑟夫问题  misc/josephus.md
    - [x] Stern-Brocot 树与 Farey 序列  misc/stern-brocot.md
    - [x] 格雷码  misc/gray-code.md
    - [x] 表达式求值  misc/expression.md
  - 专题:
    - [x] RMQ  topic/rmq.md

**Comment by CBW2007** [comment]
@Ir1d search/optimization.md 已经添加

**Comment by yizr-cnyali** [comment]
@Ir1d  math/linear-programming.md已提交pr

**Comment by Ir1d** [comment]
（我们好像已经移除了这种bug
