### ISSUE TITLE
建议在新标签页打开站外链接

### ISSUE THREAD

**Issue by EndlessCheng** [OI-wiki/OI-wiki#1895]

**Comment by Ir1d** [comment]
这是个好建议 orz，目前好像没特意处理，但我觉得很有必要加上

**Comment by diauweb** [comment]
will close in #1956 if no future plans on changing Mkdocs

**Comment by diauweb** [comment]
https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+privacy.external_links_attr_map

**Comment by NachtgeistW** [comment]
> https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+privacy.external_links_attr_map
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/504f9237e43144204f55e11cd399e5a299f49015aa249ccf2d4e5bbdca908fb1/68747470733a2f2f737175696466756e6b2e6769746875622e696f2f6d6b646f63732d6d6174657269616c2f6173736574732f696d616765732f736f6369616c2f73657475702f656e737572696e672d646174612d707269766163792e706e67">**[Ensuring data privacy - Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/)**Write your documentation in Markdown and create a professional static site in minutes – searchable, customizable, for all devices

查看了一下。built-in privacy plugin 插件目前仅对 Insider 用户开放。
该提案只能等 built-in privacy plugin 插件面向公众开放的时候再提上议程了。

**Comment by NachtgeistW** [comment]
fixed at #5140
