### ISSUE TITLE
图是怎么存的内容过于简单

### ISSUE THREAD

**Issue by szdytom** [OI-wiki/OI-wiki#1919]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [ x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
有关[图是怎么存的](https://oi-wiki.org/graph/basic/)部分过于简单，不方便理解。
建议专门新建一个节讲解图的存储。
- 你是否正在着手修复？
否
- 如何复现？
访问https://oi-wiki.org/graph/basic/
issue 标题请写为 要汇报的主要内容

**Comment by yizr-cnyali** [comment]
图的存储不是去年就有了么[图的存储](https://oi-wiki.org/graph/save/)
