### ISSUE TITLE
上下界网络流页面待修整

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1929]
_Originally posted by @EndSaH in https://github.com/OI-wiki/gitment/issues/219#issuecomment-576246866_

<details>
<summary>Details</summary>

xiepingfu on Dec 7, 2019
无源汇上下界可行流那里源汇点搞反了，应该是:
若 M>0，此时出流量过大，需要新建附加汇点 TT，其向 TT 连流量为 M 的附加边。
若 M<0，此时入流量过大，需要新建附加源点 SS，SS 向其连流量为 -M 的附加边。
 
xiepingfu on Dec 7, 2019 
更简单一点就是M的定义写反了，应该是流入减流出

</details>

**Comment by Great-designer** [comment]
很奇怪。浏览了一遍，这个老issue确实没有解决

**Comment by Tiphereth-A** [comment]
This may have been fixed in #2754?

**Comment by HeRaNO** [comment]
看起来是的，应该都能对应上，如果有问题再 reopen 吧
