### ISSUE TITLE
NOIP活了

### ISSUE THREAD

**Issue by CBW2007** [OI-wiki/OI-wiki#1930]
[CCF关于恢复NOIP竞赛的公告](http://www.noi.cn/newsview.html?id=1172&hash=AC7D99&type=1)

但我觉得还是观望一会好，因为公告中写的是“将可能”，另外CSP将何去何从:thinking:

**Comment by diauweb** [comment]
“将可能”的是获得有关部门的经费赞助
恢复NOIP是CCF“决定”的

另外 Duplicate of #1925 ？

**Comment by HandwerSTD** [comment]
> “将可能”的是获得有关部门的经费赞助
> 恢复NOIP是CCF“决定”的
> 另外 Duplicate of #1925 ？

不是 duplicate 吧（
我那个说的是被暂停，这个说的是恢复
