### ISSUE TITLE
update lambda 表达式

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1932]
> 说句实话 lambda 表达式的内容多到可以专门新开一个页面

_Originally posted by @H-J-Granger in https://github.com/OI-wiki/gitment/issues/371#issuecomment-576773398_

**Comment by H-J-Granger** [comment]
感觉“新版 C++ 特性”要拆
不然迟早这个页面的内容会像Vim的内容一样多

**Comment by shuzhouliu** [comment]
orz 看看能不能拆
