### ISSUE TITLE
镜像站列表挂了

### ISSUE THREAD

**Issue by keywet06** [OI-wiki/OI-wiki#1947]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
https://status.oi-wiki.org/ 挂了

- 你是否正在着手修复？
不会修啊

- 如何复现？
修服务器

issue 标题请写为 要汇报的主要内容

**Comment by ranwen** [comment]
@keywet06 草草草

**Comment by CBW2007** [comment]
早就挂了:-|

**Comment by StudyingFather** [comment]
现在需要一个 status.status.oi-wiki.org 了（

**Comment by CBW2007** [comment]
现在的<status.oi-wiki.org>需要挂梯·子才能上的去

**Comment by xingjiapeng** [comment]
我这里访问正常

**Comment by keywet06** [comment]
又好了。。。
