### ISSUE TITLE
关于更换框架的事宜

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1956]
Hi all,
一段时间以来，我们意识到 mkdocs 的很多局限性（尤其是不能给页面打 tag），希望能改用更灵活的框架。
目前来看比较让人满意的是 gatsby，我们也在这个框架上进行了一番尝试，详见 [OI-wiki/gatsby-oi-wiki](https://github.com/OI-wiki/gatsby-oi-wiki)。

新框架的 Demo 可在 https://next.oi-wiki.org/ 上查看。

我们的水平很有限，十分希望熟悉前端 / JS 的朋友们能够不吝赐教，帮助我们完善框架的迁移工作。
同时，也希望小伙伴们能将想要的功能评论在下方，如果力所能及，我们会尝试将新功能引入进来。

欢迎加入施工讨论群（Telegram）：https://t.me/joinchat/GaEGzhcWGl8-1CSjdhi9kA

注：更换框架任务繁重，我们将划分一部分活动经费用于酬谢出力的朋友们（鞠躬.webp

- - -
希望引入的功能
- [x] 右侧 TOC
- [x] server side render math (katex)
- [x] pdf export
- [x] PWA
- [ ] RSS(?
- [x] images @sshwy 
- [x] https://github.com/mui-org/material-ui
- [ ] netlify-cms @Ir1d

**Comment by Alafun** [comment]
下一页按钮没有了感觉并不是很方便

before: 
![image](https://user-images.githubusercontent.com/78416589/159006072-2d70fe7f-3c95-49d7-90ee-42982f025582.png)
after: 
![image](https://user-images.githubusercontent.com/78416589/159006092-e573f8e8-5190-4ccd-af43-308ef4b15a95.png)

**Comment by 0zu-cc** [comment]
> 下一页按钮没有了感觉并不是很方便
> 
> before: ![image](https://user-images.githubusercontent.com/78416589/159006072-2d70fe7f-3c95-49d7-90ee-42982f025582.png) after: ![image](https://user-images.githubusercontent.com/78416589/159006092-e573f8e8-5190-4ccd-af43-308ef4b15a95.png)

侧栏菜单不本身就是页面目录吗

**Comment by 2044-space-elevator** [comment]
同感，但是重构基本框架前前后后的工作量会不会很大？因为不仅要改服务器的配置。还要修改 Action 脚本。

**Comment by Great-designer** [comment]
趁换了金主的机会这里是不是需要加速了

**Comment by Great-designer** [comment]
可以从置顶issue上面下架了吗？
