### ISSUE TITLE
建议添加对 常见错误 中名词的解释

### ISSUE THREAD

**Issue by bash-c** [OI-wiki/OI-wiki#1988]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- [x] 请确认已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)（确认过后请将选项打钩 / 填为 `[x]`）

- 是出现了什么问题？（最好截图）
[常见错误](https://oi-wiki.org/intro/common-mistakes/#wa) 中列出了常见的 wa, re, tle, mle 等常见错误的可能原因。但对于初学者（比如我）在阅读完该部分后仍然不知道这些错误产生的具体原因。建议添加对这些名词的进一步解释，如全称，产生的根因等。
- 你是否正在着手修复？
否
- 如何复现？

issue 标题请写为 要汇报的主要内容

**Comment by sshwy** [comment]
@bash-c 这个我咋记得我bb过一句 /fad

**Comment by ouuan** [comment]
建议开个新页面讲时间限制、空间限制、评测结果等。
