### ISSUE TITLE
讨论：整除符号表示方法

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#2028]
公式中的整除符号有两种打法：

1. `|`；
1. `\mid`；

暂时没看出来这两种表示方法在渲染方式上的区别。

在公式中哪一种表示方法更合适呢？欢迎讨论。

**Comment by LeoJacob** [comment]
根据 https://tex.stackexchange.com/a/506/76326，可能 `\mid` 更合适？感觉语境中整除指一个二元关系？

**Comment by helloearly** [comment]
我觉得应该用 `\mid`，就像 α 要用 `\alpha` 而不是直接用输入法打出。

**Comment by ouuan** [comment]
> 我觉得应该用 `\mid`，就像 α 要用 `\alpha` 而不是直接用输入法打出。

这个最大的不同在于 `|` 是 ASCII 字符。

**Comment by LeoJacob** [comment]
另外二者在渲染上的不同之处在于 `\mid` 会产生一些空格，而 `|` 则不会。

**Comment by helloearly** [comment]
![批注 2020-03-09 102525](https://user-images.githubusercontent.com/44915258/76177812-4ff93980-61f0-11ea-8b99-031503f01501.png)
是的，个人认为 `\mid` 的效果更好

**Comment by H-J-Granger** [comment]
`\mid` 更好吧
某些写的不好的markdown渲染器会把公式里的|看做是分割符

**Comment by ouuan** [comment]
感觉意见已经统一了啊 /fad

**Comment by StudyingFather** [comment]
> 感觉意见已经统一了啊 /fad

这周末就干活 🕊
