### ISSUE TITLE
建议在 简介-常见错误 中添加 使用关键字作为变量名

### ISSUE THREAD

**Issue by wenjunrui** [OI-wiki/OI-wiki#2065]
如 next，y1，y0 等

**Comment by 2014CAIS01** [comment]
感觉描述欠妥。都不是不能使用。
使用 `next` 造成错误的原因是和 `std::next` 函数重名，不是关键字。只要不使用 `using namespace std` 导入命名空间就好。
使用 y1 造成错误是由于 `cmath` 库里存在了全局的 `y1`，因此在 include 相关头文件时不能在**全局**使用 `y1`

**Comment by H-J-Granger** [comment]
同意楼上。
补充一下，next,y1,y0从来就不是关键字
