### ISSUE TITLE
LCT部分出现乱码

### ISSUE THREAD

**Issue by henrytbtrue** [OI-wiki/OI-wiki#2073]
由于我不会 LCT （想学一下才来 OI-Wiki 看的），所以我无法着手修改这个界面。

## 我正在访问这个页面（最好带链接）

https://oi-wiki.org/ds/lct/

## 我发现页面有这样的问题

内容内有很多方块状的乱码，像我这样的不会 LCT 的人会看不懂。

**Comment by Enter-tainer** [comment]
@henrytbtrue 可以发一下乱码的截图吗

**Comment by henrytbtrue** [comment]
![](https://i.loli.net/2020/03/20/dryI5ELzePu7nAQ.png)

**Comment by henrytbtrue** [comment]
ok

**Comment by henrytbtrue** [comment]
![这个](https://i.loli.net/2020/03/20/dryI5ELzePu7nAQ.png)

**Comment by henrytbtrue** [comment]
https://i.loli.net/2020/03/20/dryI5ELzePu7nAQ.png

**Comment by henrytbtrue** [comment]
不知道是我浏览器的问题还是编辑的问题/dk

**Comment by Enter-tainer** [comment]
@henrytbtrue 请问您的浏览器与操作系统的类型和版本号是？

**Comment by henrytbtrue** [comment]
窝看看

**Comment by henrytbtrue** [comment]
版本号：Chrome 80.0.3987.132 操作系统：Windows 7

**Comment by henrytbtrue** [comment]
![image](https://user-images.githubusercontent.com/43104853/77139978-f4ae2d80-6ab2-11ea-9667-65fe18d646d3.png)

我这里看到的编辑页面也是这个样子的

**Comment by Enter-tainer** [comment]
@henrytbtrue 方块的地方应该是日文汉字，我们正在着手修复，感谢指出问题

**Comment by henrytbtrue** [comment]
@Enter-tainer 没事，谢谢您了哈
