### ISSUE TITLE
[BUG] 递归的代码未格式化

### ISSUE THREAD

**Issue by H-J-Granger** [OI-wiki/OI-wiki#2097]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）
https://oi-wiki.org/basic/divide-and-conquer/
## 我发现页面有这样的问题
代码未格式化，部分代码依然是用 4 个空格缩进的。

**Comment by ouuan** [comment]
这几份代码是 Java，谁来写份 C++ 代码（
