### ISSUE TITLE
[BUG]代码块行号不对齐

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#2114]
具体原因暂未定位。表现现象是代码块左侧的行号和代码内容未对齐，而本地 build 的时候不会出现这个现象。具体来说是本地 build 结果里面的 css 和目前线上使用的 css 不一致。
已经尝试清除 travis 的 cache

或者可以等待换到 gatsby.. （因为换过去之后目前暂时无行号。。问题迎刃而解（（

**Comment by Ir1d** [comment]
> xiaodai 表示本地在使用自定义主题时似乎可以复现

猜测 bump 一下自定义主题可以解决这个问题..
指路: https://github.com/OI-wiki/mkdocs-material/tree/master/src 需要合并一下上游的更改

最近一段时间将处于 wontfix 状态，视 gatsby 迁移进度再作调整吧

**Comment by H-J-Granger** [comment]
好像是因为代码部分有两层 padding……
删掉一层就完事了

**Comment by H-J-Granger** [comment]
所以……直接搞掉行号？

刺激
