### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Wulnut** [OI-wiki/OI-wiki#2121]
- [ ] 我正在着手修复这个问题

## 这个页面
[前缀和&差分](https://oi-wiki.org/basic/prefix-sum/)

###  前缀和 & 差分
前缀和&差分里面，二维/多维前缀和部分中CodeVS 1373. 射命丸文连接似乎有问题，CodeVS好像凉了....,换个链接？

**Comment by H-J-Granger** [comment]
这个是不是可以 close 了……

一条 issue 不用发两遍吧……
