### ISSUE TITLE
[BUG] 前缀和 & 差分CodeVS 1373. 射命丸文链接貌似失效

### ISSUE THREAD

**Issue by Wulnut** [OI-wiki/OI-wiki#2122]
- [ ] 我正在着手修复这个问题

## 这个页面
[前缀和&差分](https://oi-wiki.org/basic/prefix-sum/)

###  前缀和 & 差分
前缀和&差分里面，二维/多维前缀和部分中CodeVS 1373. 射命丸文连接似乎有问题，CodeVS好像凉了....,换个链接？

**Comment by H-J-Granger** [comment]
要不谁去洛谷上建一道个人题库？

**Comment by CBW2007** [comment]
@H-J-Granger 不建议使用个人题目

**Comment by ShaoChenHeng** [comment]
这个问题还没有解决掉嘛？刚好我在给这个页面完善一些内容，要不直接把这个链接删掉换一个新题上去？😂

**Comment by Wulnut** [comment]
> 这个问题还没有解决掉嘛？刚好我在给这个页面完善一些内容，要不直接把这个链接删掉换一个新题上去？😂

换一个吧，反正那个题目也失效了，放在那也没啥用
