### ISSUE TITLE
[BUG] 裴蜀定理不是代数几何中的定理

### ISSUE THREAD

**Issue by zhangns** [OI-wiki/OI-wiki#2123]
- [x] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）
https://oi-wiki.org/math/bezouts/

## 我发现页面有这样的问题
这个关于整数的裴蜀定理不是代数几何中的定理，见
https://en.wikipedia.org/wiki/B%C3%A9zout's_identity
https://en.wikipedia.org/wiki/B%C3%A9zout%27s_theorem

**Comment by Ir1d** [comment]
Hi @zhangns 感谢反馈，方便开个 Pull Request 帮忙订正一下吗？感觉可以直接删掉那句话
