### ISSUE TITLE
线段树中懒惰标记区间查询代码注释有问题[BUG]

### ISSUE THREAD

**Issue by Wulnut** [OI-wiki/OI-wiki#2144]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）
[https://oi-wiki.org/ds/seg/](线段树)
## 我发现页面有这样的问题
1. 懒惰标记的板块里，区间查询代码注释很明显是复制区间修改的，要修一下。
2. 有个边界情况似乎没有考虑，就是查询区间和结点所包含的区间没有交集的特殊情况，不清楚是否要特判一下

**Comment by StudyingFather** [comment]
> 有个边界情况似乎没有考虑，就是查询区间和结点所包含的区间没有交集的特殊情况，不清楚是否要特判一下

看原来的代码似乎判断了这种情况。

如果左儿子/右儿子对应的区间和查询区间没有交集的话，就不会进入这个节点查询。
