### ISSUE TITLE
[BUG] 代码框行号栏缺失

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#2160]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）

代码框的行号栏缺失。例如 [这个页面](https://oi-wiki.org/intro/testlib/checker/)

**Comment by ouuan** [comment]
Related: #2114

**Comment by ouuan** [comment]
主站到底用的哪的 CSS /fad

**Comment by Ir1d** [comment]
https://squidfunk.github.io/mkdocs-material/releases/5/ 可能与上游更改有关，待进一步确认
