### ISSUE TITLE
[BUG]不统一的例题标题格式

### ISSUE THREAD

**Issue by countercurrent-time** [OI-wiki/OI-wiki#2164]
- [ ] 我正在着手修复这个问题

## 我发现页面有这样的问题

OI wiki 中有很多不同的例题标题格式。

- 例一：直接以例x为文中标题：（另外这篇文章中有一个标题是"例题："，这个应该也比较不规范）https://oi-wiki.org/basic/construction/
- 例二：例x + 题目名称：https://oi-wiki.org/ds/block-array/
- 例三：题目名称：https://oi-wiki.org/ds/seg/
- 例四：题目代表的一类知识点或专题：https://oi-wiki.org/string/sa/

我感觉第 4 种应该是比较好的，用知识点或者专题作为文中标题方便索引，多个例题可以按 #1710 里的示范排版。现在 OI wiki 的例题标题格式过于不统一了，还是应该考虑批量修改。
一个需要讨论的问题：例题的折叠块排版上应该按照 pr #506 里的方法用 `!!!` ，还是按照 Issue #1710 里的方法用 `???`？（感觉上应该使用 `???`）

另外，洛谷的例题格式并不统一。有使用 `luoguxxx` 和 `Pxxxx` 的，还有把洛谷的题目链接批量修改为 LOJ 的题目链接时，链接文本仍然是 `luoguxxxx` 的历史遗留问题，以及仍然大量使用的 `www.luogu.org` 和 `problemnew/show/xxxx` 链接。
需要讨论的问题：上面的这些有问题的洛谷题目链接是否应该批量修改？~~或者等到 #1741 里的索引工具出来再改？~~
另一个需要讨论的问题：对于 UVA 的题目，应该使用洛谷的 RemoteJudge 还是 vjudge？（貌似 vjudge 速度比洛谷略慢，而且 vjudge 有的洛谷都有了，vjudge 没有的洛谷也有）

**Comment by H-J-Granger** [comment]
> 另外，洛谷的例题格式并不统一。有使用 `luoguxxx` 和 `Pxxxx` 的，还有把洛谷的题目链接批量修改为 LOJ 的题目链接时，链接文本仍然是 `luoguxxxx` 的历史遗留问题，以及仍然大量使用的 `www.luogu.org` 和 `problemnew/show/xxxx` 链接。
> 需要讨论的问题：上面的这些有问题的洛谷题目链接是否应该批量修改？~或者等到 #1741 里的索引工具出来再改？~

fixed in #2195.
