### ISSUE TITLE
要不要开个新 repo/OJ 来存不稳定的例题、练习数据？

### ISSUE THREAD

**Issue by H-J-Granger** [OI-wiki/OI-wiki#2173]
## 我遇到的问题是
有些 OJ 国内访问速度奇慢，甚至不可访问。
## 我希望能有这样的解决方案
是否可以新开一个 repo 存不稳定的例题和练习数据？
## 我觉得其他这些方案也可以接受
或者开个基于 SYZOJ2 的 OJ？

**Comment by Ir1d** [comment]
有一个 repo 倒是。。。 https://github.com/OI-wiki/problemset
造 OJ 现阶段应该没机会搞
奇慢的问题其实有 vjudge

**Comment by H-J-Granger** [comment]
唔，感谢提醒……

不过那个 repo 几个月没动过了？

**Comment by Ir1d** [comment]
因为没有特别强烈的需求..？

**Comment by H-J-Granger** [comment]
codvs……

https://oi-wiki.org/basic/prefix-sum/#_5

**Comment by H-J-Granger** [comment]
我甚至都 ping 不到 joyoi.cn……

**Comment by Ir1d** [comment]
感觉这几个题还是换掉省事 :joy:

**Comment by H-J-Granger** [comment]
😂
