### ISSUE TITLE
修复距离中的一些typo

### ISSUE THREAD

**Issue by countercurrent-time** [OI-wiki/OI-wiki#2175]
修复距离板块中的一些 typo、一些笔误和一些例题的格式。

**Comment by ouuan** [comment]
在 htc 中要求在开 PR 前开 issue 的原因主要有：

1. 别人知道你要动笔了，可能可以给你提供一些帮助与建议。
2. 别人知道你要动笔了，就可以避免两个人进行重复的工作。
3. 如果你提出的问题实际上并不是一个问题，而是你看错了之类的，别人可以提醒你，你就不会在上面浪费时间了。
4. 如果问题比较复杂，可以在 issue 中对问题进行详细的说明，而在 PR 中专注与解决问题。

所以，下次您可以在动笔前就先开 issue 并说明自己正在着手解决这个问题。如果是动笔 -> 开 issue -> 开 PR 这个流程的话，其实和直接开 PR 差不了多少。谢谢合作，也谢谢您的贡献！
