### ISSUE TITLE
docker镜像出现多个BUG[BUG]

### ISSUE THREAD

**Issue by kxccc** [OI-wiki/OI-wiki#2181]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [x] 我已找到原因和解决方法

## 我遇到了这样的问题
在容器外拒绝访问
![image](https://user-images.githubusercontent.com/53963217/80912448-81653000-8d6f-11ea-8f04-03854c24b224.png)
在容器内可连接
![image](https://user-images.githubusercontent.com/53963217/80912488-dacd5f00-8d6f-11ea-87c1-e123771391b6.png)

## 原因
```
alias wiki-svr='export LC_ALL=C.UTF-8 && cd /OI-wiki && mkdocs serve -v'
```
中 mkdocs serve -v 只监听容器内的请求

## 解决方法
把 wiki-svr 对应的指令改为
```
alias wiki-svr='export LC_ALL=C.UTF-8 && cd /OI-wiki && mkdocs serve -v -a 0.0.0.0:8000'
```

**Comment by Ir1d** [comment]
:smile: 老铁有兴趣开个 pr 顺手给改了吗

**Comment by kxccc** [comment]
使用原镜像的过程中还发现 **Docker部署** 文档中的其他命令也有问题

1. **wiki-o** 无法使用
![image](https://user-images.githubusercontent.com/53963217/80931789-a6e54e80-8dee-11ea-91ad-14350a548c94.png)

2. 未使用 **wiki-theme** 前数学公式显示正常，使用后数学公式显示异常

还好 **wiki-bld** 和 **wiki-bld-math** 能正常使用

我尝试使用仓库里的 **.bashrc** 和 **Dockerfile** 重新构建镜像，但构建出来的镜像所有功能无法正常使用，可能 **Dockerfile** 已经”过时“了。

对我来说重构 **Dockerfile** 以符合文档说明很难，而直接修改 **Docker部署** 文档比较容易。

**Comment by Ir1d** [comment]
@frank-xjh ping
