### ISSUE TITLE
[BUG] 404 页面链接错误

### ISSUE THREAD

**Issue by Henry-ZHR** [OI-wiki/OI-wiki#2183]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

404 页面中的链接看起来没有做处理，导致所有相对链接爆炸（包括顶部 tabs、js 和 css 资源等）。

例如访问 <https://oi-wiki.org/math/math/>，返回 404，顶部 tabs 中“简介”的链接实际指向 <https://oi-wiki.org/math/math/> 而不是 <https://oi-wiki.org/>。

**Comment by StudyingFather** [comment]
resolved now.
