### ISSUE TITLE
[RFC] 优先使用 SVG 图片

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/OI-wiki#2215]
## Update
Became Summer 2021 [project](https://github.com/OI-wiki/OI-wiki/wiki/Open-Source-Promotion-Plan-Summer-2021#13-%E4%BD%BF%E7%94%A8-svg-%E4%BC%98%E5%8C%96-oi-wiki-%E4%B8%AD%E7%9A%84%E5%9B%BE%E5%83%8F).
## 我希望能添加的内容是
希望能把图片转成 SVG 以及 [LaTeX 绘制](https://www.overleaf.com/learn/latex/LaTeX_Graphics_using_TikZ:_A_Tutorial_for_Beginners_(Part_1)%E2%80%94Basic_Drawing)
## 我了解到的相关参考资料有
[draw.io](draw.io)

**Comment by ChungZH** [comment]
@ksyx 为啥要转 SVG 呀（

**Comment by ksyx** [comment]
1. svg 体积比较小 在各个方面上有优势？
2. 有些图画质太低了，既然要高清重制就做完全去吧（
3. wikipedia 上的图论图很多都是 svg 的，更规范？
4. ~个人 svg 强迫症~

**Comment by ayalhw** [comment]
附议，
SVG 在多分辨率下清晰度有极大优势，
而且其本质为 XML 文本，便于 Git 追踪变化
（在这里 SVG 与其他图片格式相比我感觉更接近一种“原始数据”的感觉

**Comment by ayalhw** [comment]
我提议分步进行：
- [ ] 首先更新格式手册，推荐优先使用 SVG 图片或 LaTeX 原文
- [ ] 逐步替换（高清重制？）原有文章中的图片

（前者比较简单，后者估计是个长期工程

**Comment by ayalhw** [comment]
格式手册已更新于 #2656

**Comment by CoelacanthusHex** [comment]
内容更新已于 OSPP2021 中由 @mcendu 同学完成，close
