### ISSUE TITLE
[BUG] 快速傅里叶变换中的用词

### ISSUE THREAD

**Issue by hly1204** [OI-wiki/OI-wiki#2219]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）
https://oi-wiki.org/math/poly/fft/
## 我发现页面有这样的问题
其中对于蝴蝶变换的描述有误，所描述的操作应为位逆序置换，而标题的蝴蝶变换（蝶形运算）一般为乘以旋转因子的运算。

**Comment by H-J-Granger** [comment]
能给个 ref 吗……
好像搜不到位逆序置换……

**Comment by hly1204** [comment]
> 能给个 ref 吗……
> 好像搜不到位逆序置换……

https://en.wikipedia.org/wiki/Bit-reversal_permutation 可能这个。。

**Comment by H-J-Granger** [comment]
唔……

搜“位逆序排列”也搜不到……

直接留英文好了……

**Comment by hly1204** [comment]
> 唔……
> 
> 搜“位逆序排列”也搜不到……
> 
> 直接留英文好了……

Bit-reversal permutation
