### ISSUE TITLE
[BUG] 树链剖分伪代码错误

### ISSUE THREAD

**Issue by H-J-Granger** [OI-wiki/OI-wiki#2223]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）
<https://oi-wiki.org/graph/hld/#_3>

第二篇伪代码第7行的son的n被挡住了一点，变成了r

**Comment by sshwy** [comment]
请问如何复现？（我看了，没啥问题

**Comment by H-J-Granger** [comment]
啊，我换个浏览器试试

**Comment by H-J-Granger** [comment]
啊……没事了，大概是浏览器遮挡问题，close了
