### ISSUE TITLE
add 树套树

### ISSUE THREAD

**Issue by Xarfa** [OI-wiki/OI-wiki#223]
添加：
- [ ] 树状数组套树状数组
- [ ] 树状数组套线段树
- [x] 树状数组套主席树 

(套线段树和主席树并不一样)

**Comment by Xarfa** [comment]
树套树,写错了

**Comment by hsfzLZH1** [comment]
@Xarfa 不知您能否提供一些例题？

另，树状数组套线段树和树状数组套主席树其实差不多，主席树就是动态开点的权值线段树。
