### ISSUE TITLE
add 类型转换

### ISSUE THREAD

**Issue by Suyun514** [OI-wiki/OI-wiki#2231]
## 我希望能添加的内容是

在 C++ 中不同类型的互相转换。既包括 C 风格（如 `(int)x`），也包括 C++ 风格（四种 `cast`），甚至一些 tricks（如通过 `* 1.0` 将整型转换为浮点型）。

## 我了解到的相关参考资料有

- [cppreference](https://zh.cppreference.com/w/cpp/language/expressions)

**Comment by H-J-Granger** [comment]
写 C++ 基础里
