### ISSUE TITLE
[BUG] 是否要在 OI 中推荐 Visual Studio？

### ISSUE THREAD

**Issue by Suyun514** [OI-wiki/OI-wiki#2232]
- [x] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）

https://oi-wiki.org/lang/pas-cpp/#ide

## 我发现页面有这样的问题

个人认为不应该推荐 OI 选手使用 Visual Studio。

**Comment by Ahacad** [comment]
也感觉可以直接上vim
参见这个页面[awesome-competitive-programming#ides](https://github.com/lnishan/awesome-competitive-programming#ides)

**Comment by H-J-Granger** [comment]
感觉推荐 VSCode 更好些……
VS 也不是说不行……

**Comment by Suyun514** [comment]
新手还是直接 DevCpp 或者 CB 吧（

**Comment by ksyx** [comment]
所以为啥不 mention GUIDE 呢 
和部分 pas 选手原来的习惯一致 多好（（

**Comment by Suyun514** [comment]
> 所以为啥不 mention GUIDE 呢 
> 和部分 pas 选手原来的习惯一致 多好（（
> 

Pascal 选手还行。对 Cpp 就是屑……

**Comment by ksyx** [comment]
> > 所以为啥不 mention GUIDE 呢
> > 和部分 pas 选手原来的习惯一致 多好（（
> 
> Pascal 选手还行。对 Cpp 就是屑……

但是这是极速 pas 转 cpp 指南（

**Comment by Suyun514** [comment]
> > > 所以为啥不 mention GUIDE 呢
> > > 和部分 pas 选手原来的习惯一致 多好（（
> > 
> > Pascal 选手还行。对 Cpp 就是屑……
> 
> 但是这是极速 pas 转 cpp 指南（
> 而且 NOI Linux 下面也没几个能用的 IDE（（

建议 gedit（

**Comment by ksyx** [comment]
> > > > 所以为啥不 mention GUIDE 呢
> > > > 和部分 pas 选手原来的习惯一致 多好（（
> > > 
> > > 
> > > Pascal 选手还行。对 Cpp 就是屑……
> > 
> > 
> > 但是这是极速 pas 转 cpp 指南（
> > 而且 NOI Linux 下面也没几个能用的 IDE（（
> 
> 建议 gedit（

那不是 IDE 了吧，虽然也可

**Comment by ksyx** [comment]
另外貌似 off topic 了，这里不是讨论的要不要留下 VS 的吗（
咋开始推荐编译器/编辑器/IDE了

**Comment by Henry-ZHR** [comment]
个人认为应该保留。

不过可以加上“对新手不友好”之类的提示。

**Comment by H-J-Granger** [comment]
> 个人认为应该保留。
> 
> 不过可以加上“对新手不友好”之类的提示。

+1
