### ISSUE TITLE
The Future of OI Wiki

### ISSUE THREAD

**Issue by Rapiz1** [OI-wiki/OI-wiki#2237]
众所周知，OI 要凉了，经过几届之后可能面临着很少有 OIer 看或者新生代 OIer 加入这个项目。OI 式微之后，OI Wiki 的未来怎么办？

下面是一些可能的选项：
- 更名 OI/ICPC Wiki or Algorithm Wiki 主要面向高校算法竞赛或对算法有兴趣的人群
- 转型 Computer Science Wiki 提供计算机科学的多领域自学指导

**Comment by Ir1d** [comment]
感觉是不是有点对名字的刻板印象呢？
我觉得从来也没有排斥你提到的这两个方向的内容啊？

**Comment by Rapiz1** [comment]
> 感觉是不是有点对名字的刻板印象呢？
> 我觉得从来也没有排斥你提到的这两个方向的内容啊？

和第一个方向内容是重合的
明显和第二个方向有偏差啊，比如编译原理、操作系统、图形学等等cs的其他方面没有涉及。比如如果添加多线程和锁的内容，适合放进 OI Wiki 吗……

**Comment by ouuan** [comment]
这，至少有 ACM 吧 /fad 而且所谓的“凉了”，等真的“凉了”再说吧，这是什么需要预言然后提前准备方案的事吗

**Comment by Ir1d** [comment]
> 添加进现阶段的OI Wiki真的合适吗
现阶段是不合适的，这也是我们计划从 mkdocs 换走的原因之一。

> 未来的算法竞赛会出现编译原理吗
这.. 除非你说自己是穿越回来的.. 谁敢说会 / 不会呢？
在我的印象中已经有很多编译 / 操桶知识引入到竞赛题中啊，可能不是那么明显？

> 明显和第二个方向有偏差啊
那确实是有偏差啊，目前这些内容较少一些，但是确实没有排斥啊？比如我们引入了一些 tcs 的内容，我觉得就非常 nice 啊？
所以我觉得你提出的 point 貌似在于改名.. 这就比较难以理解了..

**Comment by ouuan** [comment]
> 众所周知

给出“凉了”的定义，以及能够证明“众所周知”的统计数据？别随便“众所周知”啊，你说的“众”，是你，你看到过的人，和你想象中的其他人？你说的“凉了”，是个啥玩意？
