### ISSUE TITLE
clang-format 配置需调整

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#2242]
- 注释会影响 indent 的问题，貌似还没有好办法解决 https://stackoverflow.com/questions/44731978/make-clang-format-ignore-comments-for-line-break/44731999

- SpacesBeforeTrailingComments 似乎可以启用一下 https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by ksyx** [comment]
SpacesBeforeTrailingComments 目前不支持中文开头的 comment。。

**Comment by ksyx** [comment]
> SpacesBeforeTrailingComments 目前不支持中文开头的 comment。。

现在有了 但是在 14.0 branch 出去以后。。
