### ISSUE TITLE
韩国OI比赛的官网失效

### ISSUE THREAD

**Issue by NachtgeistW** [OI-wiki/OI-wiki#2264]
- [x ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）
https://oi-wiki.org/intro/oi/
http://www.digitalculture.or.kr/koi/
## 我发现页面有这样的问题
页面报Error Page

不排除该页面其他的link也有失效的可能

**Comment by black-desk** [comment]
我没有在你指出的页面中找到该链接 可能已经被移除了

**Comment by NachtgeistW** [comment]
> 我没有在你指出的页面中找到该链接 可能已经被移除了

我想应该已经移除了
