### ISSUE TITLE
[讨论] 是否有必要生成pdf供打印?

### ISSUE THREAD

**Issue by leoleoasd** [OI-wiki/OI-wiki#2272]
如题, 是否有必要写一个Github Actions, 生成pdf, 上传至release ,方便打印?

初步想法是把所有页面按照顺序连在一起, 生成一个包括所有页面的pdf, 方便acm赛制的比赛时打印出来做参考使用.

**Comment by Enter-tainer** [comment]
@leoleoasd hello~这个 feat 已经在鹿上了，见 https://github.com/OI-wiki/OI-wiki/wiki/Open-Source-Promotion-Plan---Summer-2020#3-%E5%AE%8C%E5%96%84%E5%9F%BA%E4%BA%8E-unified-ast-%E7%9A%84-markdown-%E5%9F%BA%E7%A1%80%E8%AE%BE%E6%96%BD

**Comment by leoleoasd** [comment]
> @leoleoasd hello~这个 feat 已经在鹿上了，见 https://github.com/OI-wiki/OI-wiki/wiki/Open-Source-Promotion-Plan---Summer-2020#3-%E5%AE%8C%E5%96%84%E5%9F%BA%E4%BA%8E-unified-ast-%E7%9A%84-markdown-%E5%9F%BA%E7%A1%80%E8%AE%BE%E6%96%BD

打扰了
