### ISSUE TITLE
[BUG] Quine 应该不算很难实现

### ISSUE THREAD

**Issue by Suyun514** [OI-wiki/OI-wiki#2298]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）

https://oi-wiki.org/intro/non-trad/#_6

## 我发现页面有这样的问题

> 题目很经典，但是在绝大多数 OJ 上都很难实现。

Quine 并不算很难实现的题目。

**Comment by H-J-Granger** [comment]
可能作者的意思是“在大多数 OJ 上普通用户都很难实现”……
Quine 无论是选手编写还是评测都比较简单吧

**Comment by ouuan** [comment]
不管难不难，和 OJ 大约没啥关系。

**Comment by swift-zym** [comment]
感觉没什么问题（？

目前好像大多数 OJ 都没向 SPJ 提供选手代码
