### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/OI-wiki#2305]
![image](https://user-images.githubusercontent.com/25521218/84587927-e6737180-ae55-11ea-8cf8-366d2f8ad0ef.png)

现在前端似乎加载了 MathJax，这应该不是必要的

![image](https://user-images.githubusercontent.com/25521218/84587935-f1c69d00-ae55-11ea-89af-9e8a10fb2df7.png)

netlify logo 图片过大，需要 oicdn@npm 的群友帮忙改一下

**Comment by Enter-tainer** [comment]
mathjax 的问题应该是因为，更换到 jsdeliver 之后没有修改 build.sh 导致的，具体问题见

https://github.com/OI-wiki/OI-wiki/blob/master/scripts/build.sh#L20

**Comment by Xeonacid** [comment]
fixed in #2307
