### ISSUE TITLE
[BUG] bot 在处理 Markdown 时的问题

### ISSUE THREAD

**Issue by Suyun514** [OI-wiki/OI-wiki#2312]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）

bot 会将 md 文件中用于表示斜体的 `*` 符号替换为 `_`，然而 OI Wiki 的 Markdown 渲染引擎不支持用 `_` 表示斜体。

## 我确认这个问题可以这样复现

https://github.com/OI-wiki/OI-wiki/commit/3dea660728405081be02d71086605e9bd0b9512c

**Comment by Ir1d** [comment]
可能需要搜一下有没有现成 lint 规则，我考完试看一下

**Comment by Suyun514** [comment]
[pangu.js](https://github.com/vinta/pangu.js)
或许有用？

**Comment by Enter-tainer** [comment]
- 会删除掉 删除线 两边的空格，导致删除线被渲染成下标。
- 会添加过多的空格：
![image](https://user-images.githubusercontent.com/25521218/88028451-46eb8200-cb6b-11ea-9063-766b1ab13d0b.png)

**Comment by Ir1d** [comment]
似乎在近年的更新中，本问题已经得到了解决 🙏
