### ISSUE TITLE
[BUG] Google Font 的阻塞问题

### ISSUE THREAD

**Issue by Yixuan-Wang** [OI-wiki/OI-wiki#2320]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）
![image](https://user-images.githubusercontent.com/21151119/84637168-f8bde000-af27-11ea-9fc2-96a8f2475b7c.png)

## 我确认这个问题可以这样复现
在特定运营商及地区访问任意OI-Wiki界面（比如：北京地区的中国联通）

目前OI-Wiki使用了Google Font加载[Fira Sans和Fira Mono字体](https://github.com/OI-wiki/OI-wiki/blob/0bd5d145b62ef08e3a88cb71afe22e1e6911077d/mkdocs.yml#L417)，但这一API在中国国内工作不稳定，可能会严重阻塞页面加载，是否应当考虑换用镜像、内嵌字体或者放弃加载网络字体等方式针对中国国内的网络环境进行优化？

**Comment by Ir1d** [comment]
之前好像有一阵子国内是可以打开 Google Font 的，看来目前还是有一定问题。。
@Yixuan-Wang 方便帮看下 Google Analytics 能否访问吗？

**Comment by Yixuan-Wang** [comment]
> 方便帮看下 Google Analytics 能否访问吗？
我这里加载 analytics.js 耗时 52ms，应该算是能正常访问。从[ Ping 结果](http://ping.chinaz.com/www.google-analytics.com)来看，似乎 Google Analytics 的服务是正常的。

**Comment by Ir1d** [comment]
不过这么说好像 https://fonts.googleapis.com/ 也是可达的
http://ping.chinaz.com/fonts.googleapis.com :joy:

**Comment by Yixuan-Wang** [comment]
是的……但我这里就 ping 不通……加载一个页面被阻塞一分钟，浏览体验大打折扣了……

**Comment by SukkaW** [comment]
Fixed by https://github.com/OI-wiki/mkdocs-material/pull/26

Will be in effect in next build.
