### ISSUE TITLE
add 最大费用可行流

### ISSUE THREAD

**Issue by FengZhg** [OI-wiki/OI-wiki#2366]
## 我希望能添加的内容是
最大费用可行流
## 我了解到的相关参考资料有
https://blog.csdn.net/yo_bc/article/details/72877059?utm_source=blogxgwz0
实际上就跟费用流差了一行，并且最小费用可行流无意义。只有最大费用可行流

**Comment by Nanarikom** [comment]
反对。这不构成单独的知识点，最多只能作为一个例题。

**Comment by alphagocc** [comment]
根据
https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E6%9D%83%E5%A8%81%E6%9C%BA%E6%9E%84
OI Wiki 不是百科全书
