### ISSUE TITLE
[BUG] intro/common_mistakes.md

### ISSUE THREAD

**Issue by isdanni** [OI-wiki/OI-wiki#2372]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [x] 我正在着手修复这个问题

## 我遇到了这样的问题

最后那句中文应该是“不满足要求 2 中的严格弱序”

![Screenshot from 2020-07-05 12-52-43](https://user-images.githubusercontent.com/38550500/86525870-0f1fe180-bebf-11ea-857d-2ddc9766a962.png)

## Reference

[kysx's code review in i18n](https://github.com/OI-wiki/i18n/pull/2#discussion_r449771311)

**Comment by ksyx** [comment]
Fixed in #2368, #2369 
btw, issue 模板选错了 qwq

**Comment by isdanni** [comment]
> Duplicated with #2368, which was fixed in #2369
> btw, issue 模板选错了 qwq

:sweat: :eyes:  那我关了.jpg
