### ISSUE TITLE
add Dinic's Algorithm 代码

### ISSUE THREAD

**Issue by isdanni** [OI-wiki/OI-wiki#2383]
## 我希望能添加的内容是

Dinic算法的简单代码实现（现在文档里是待补充）

链接： [topic/graph-matching/bigraph-match](https://github.com/OI-wiki/OI-wiki/blob/master/docs/topic/graph-matching/bigraph-match.md#%E4%BB%A3%E7%A0%81-1)

## 我了解到的相关参考资料有

- [Dinic's Algorithm WIki](https://zh.wikipedia.org/wiki/Dinic%E7%AE%97%E6%B3%95)
- [diff ways on CF](https://codeforces.com/blog/entry/61003)

**Comment by StudyingFather** [comment]
考虑到最大流页面有 Dinic 的代码，可以直接给个参考链接？

**Comment by isdanni** [comment]
> 考虑到最大流页面有 Dinic 的代码，可以直接给个参考链接？

好的 :+1:  那我把链接加上去
