### ISSUE TITLE
规范 MathJax 公式

### ISSUE THREAD

**Issue by Chrogeek** [OI-wiki/OI-wiki#2399]
重构 TeX 导出工具期间发现了不少问题。这些问题导致导出 TeX PDF 时出现版面错误、符号错误等现象。包括但不限于以下：

页面 string/bm.md：
> 首先考虑 $delta_1$ 不起作用的情况，也就是发现失配字符在 $pat$ 上重现的位置在已经匹配完的 $m$ 个字符中，这种情况的概率 $\textit{probdelta_1_worthless}$ 为
* 存在滥用 MathJax 公式的现象，甚至单个变量名也要用 $ 套起来；
* ~~命名不规范（TeX 不允许同一字符后连续接两个下标）；~~ 这一点属于 MathJax 和 LaTeX 的差异，不需要处理

页面 geometry/distance.md
> $(y_1 - y_2 \lt 0)\rightarrow |x_1-x_2|+|y_1-y_2|=x_1 - y_1 - (x_2 - y_2)$ 
* \lt 命令与 TeX 不兼容（需要 \newcommand 之类的 dirty hack）；

页面 math/permutation_group.md
> 对于两个置换 $f=\pmatrix{a_1,a_2,\dots,a_n\\a_{p_1},a_{p_2},\dots,a_{p_n}}$ 和 $g=\pmatrix{a_{p_1},a_{p_2},\dots,a_{p_n}\\a_{q_1},a_{q_2},\dots,a_{q_n}}$ 
* \pmatrix 是过时写法 (old form)，应使用 \begin{pmatrix} ... \end{pmatrix} 代替。

math 套汉字的问题

$公式中出现中文的情况$

## 可能需要做的修复

检查目前 OI Wiki 的所有页面，规范公式书写格式，尽可能保证公式同时被 MathJax 和 TeX 接受。
（接受的标准为 TeX 编译器不报 error 和 warning）

**Comment by Xeonacid** [comment]
> 我们通常使用 LaTeX 公式字体表示变量名称。
（格式手册）

这个可能需要讨论一下🤔

**Comment by Enter-tainer** [comment]
> $\textit{probdelta_1_worthless}$ 

这种怎么改比较好呢，我正在修这个东西

**Comment by Enter-tainer** [comment]
中文的部分，应该是使用 $\text{中文}$ 就可以了？

**Comment by Chrogeek** [comment]
> 中文的部分，应该是使用 $\text{中文}$ 就可以了？

是的

不过，如果一个公式里中文比较多的话，也应该考虑拆分

**Comment by Enter-tainer** [comment]
#2400 里面修了一部分中文，不知道还有没有漏掉的

**Comment by ouuan** [comment]
>  甚至单个变量名也要用 $ 套起来

为什么不呢 :thinking:

**Comment by Chrogeek** [comment]
> > 甚至单个变量名也要用 $ 套起来
> 
> 为什么不呢 🤔

想了一下这个似乎不算什么大问题🤔

**Comment by Chrogeek** [comment]
由于 #2412 已 merge，这个 issue 就先关了
