### ISSUE TITLE
add 参考资料跳回引用位置

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [OI-wiki/OI-wiki#2418]
## 我遇到的问题是
点击参考资料链接后无法方便地跳转回原来的位置
## 我希望能有这样的解决方案
加一个小小的`^`，链接到原来的位置。
## 我觉得其他这些方案也可以接受
N/A

**Comment by NachtgeistW** [comment]
我们现在用 MarkDown 脚注功能撰写的页面里，页面最下方的参考资料后面都会跟着一个←┘（比如[格式手册](https://oi-wiki.org/intro/format/#_11))，点击这个符号就能跳回去了。其他页面会陆续格式化的。
