### ISSUE TITLE
LaTeX PDF 问题追踪

### ISSUE THREAD

**Issue by Chrogeek** [OI-wiki/OI-wiki#2429]
OI Wiki 已开发了新版 LaTeX 导出工具，PDF 见群文件。
本 issue 用于反馈、追踪问题。

UPD：PDF 已更新至 a166da5 版本

**Comment by sshwy** [comment]
提一些主观建议：
1. 目录太长了。而且层级不对。有的文章连里面的二级标题都算到目录里了。最好能针对性调整一下
2. 对details的处理还不太好。个人偏好是加一个box https://blog.csdn.net/lemaden520/article/details/77917171
3. 图片太大了，总是顶宽。每次遇到有图的页，就没啥文字，会产生对比，让人感觉字体太小，行距太小。
4. 段落间距最好大于行距。
5. latex伪代码最好靠左。
6. 建议板块的标题（比如计算几何）单独占一页。

**Comment by Chrogeek** [comment]
> 提一些主观建议：
> 
> 1. 目录太长了。而且层级不对。有的文章连里面的二级标题都算到目录里了。最好能针对性调整一下
> 2. 对details的处理还不太好。个人偏好是加一个box https://blog.csdn.net/lemaden520/article/details/77917171
> 3. 图片太大了，总是顶宽。每次遇到有图的页，就没啥文字，会产生对比，让人感觉字体太小，行距太小。
> 4. 段落间距最好大于行距。
> 5. latex伪代码最好靠左。
> 6. 建议板块的标题（比如计算几何）单独占一页。
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/425bcc3694106012fc6d36eb199739cc7d2eaac8/68747470733a2f2f6373646e696d672e636e2f7075626c69632f66617669636f6e2e69636f">**[LaTex技巧（三）：如何为自己定制好看的盒子呢？_lemaden520的博客-CSDN博客_latex box](https://blog.csdn.net/lemaden520/article/details/77917171)**\\fbox和\\itemize在一起该如何放置例如我用下面错误命令示范：\\fbox{The\\textit{two-step}modelofXMCD:\\begin{itemize}\\item[Inthe\\textit{firststep},circularlypolarizedX-raysgeneratephotoelectronswithaspinand/oror_latex box

1, 4. 收到；
2. details 这个有一点问题，现在 mdframed 和 tcolorbox 都不支持嵌套分页（即，如果嵌套，且内层 box 涉及分页，输出会炸），而且几乎不可能从 oi wiki 中去除所有嵌套 details，所以做成了现在这样。不过解决方案也在寻找；
3. 正在修，但是可能不好做；
5. 伪代码是以公式的形式输入的，这个基本没有办法改了；
6. 国内好像没有这种排版习惯？

**Comment by Enter-tainer** [comment]
代码块中宏使用的是斜体的等宽体，不知道是不是字体选择的原因，看起来效果好像有点神秘，不知道这个是不是 feat（

![image](https://user-images.githubusercontent.com/25521218/88028875-cf6a2280-cb6b-11ea-8211-cbcc35cbb571.png)

**Comment by Henry-ZHR** [comment]
![](https://user-images.githubusercontent.com/51886614/88071907-fe51ba00-cba6-11ea-9cc1-d040bd8d70c4.png)

205 页，文字重叠

~~还有 206 页，平衡树的坑还没填，是不是该删掉~~

**Comment by Henry-ZHR** [comment]
![](https://user-images.githubusercontent.com/51886614/88073546-e3804500-cba8-11ea-8285-5ae6405b53b6.png)

224 页，超过屏幕宽度了

**Comment by Ir1d** [comment]
平衡树应该不需要导出工具这一侧的特殊处理 :thinking:

**Comment by Chrogeek** [comment]
> 代码块中宏使用的是斜体的等宽体，不知道是不是字体选择的原因，看起来效果好像有点神秘，不知道这个是不是 feat（
> 
> ![image](https://user-images.githubusercontent.com/25521218/88028875-cf6a2280-cb6b-11ea-8211-cbcc35cbb571.png)

won't fix：这个是 LaTeX 默认等宽字体 Computer Modern (Unicode) Typewriter 的 Italic 体（注意不是 Oblique）

**Comment by Henry-ZHR** [comment]
> 
> 
> 平衡树应该不需要导出工具这一侧的特殊处理 🤔
> 
> 等它有内容了再导出一遍就行（

这个不是重点。。。

**Comment by Chrogeek** [comment]
> ![](https://user-images.githubusercontent.com/51886614/88071907-fe51ba00-cba6-11ea-9cc1-d040bd8d70c4.png)
> 
> 205 页，文字重叠
> 
> ~还有 206 页，平衡树的坑还没填，是不是该删掉~

Fixed.

**Comment by Chrogeek** [comment]
> 提一些主观建议：
> 
> 1. 目录太长了。而且层级不对。有的文章连里面的二级标题都算到目录里了。最好能针对性调整一下
> 2. 对details的处理还不太好。个人偏好是加一个box https://blog.csdn.net/lemaden520/article/details/77917171
> 3. 图片太大了，总是顶宽。每次遇到有图的页，就没啥文字，会产生对比，让人感觉字体太小，行距太小。
> 4. 段落间距最好大于行距。
> 5. latex伪代码最好靠左。
> 6. 建议板块的标题（比如计算几何）单独占一页。
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/425bcc3694106012fc6d36eb199739cc7d2eaac8/68747470733a2f2f6373646e696d672e636e2f7075626c69632f66617669636f6e2e69636f">**[LaTex技巧（三）：如何为自己定制好看的盒子呢？_lemaden520的博客-CSDN博客_latex box](https://blog.csdn.net/lemaden520/article/details/77917171)**\\fbox和\\itemize在一起该如何放置例如我用下面错误命令示范：\\fbox{The\\textit{two-step}modelofXMCD:\\begin{itemize}\\item[Inthe\\textit{firststep},circularlypolarizedX-raysgeneratephotoelectronswithaspinand/oror_latex box

补充一下图片的一些问题：导出 PDF 需要保持文字和图片的顺序（典型例如[这个页面](https://oi-wiki.org/basic/binary/)），因此很难随意调整图片位置或文字环绕方式。除非将文本中的图片统一替换为索引（如「图 X.Y」这样），但是这样做会降低阅读体验。
