### ISSUE TITLE
[BUG] gray code 历史

### ISSUE THREAD

**Issue by isdanni** [OI-wiki/OI-wiki#2500]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）

[格雷码](https://oi-wiki.org/misc/gray-code/)
> oi-wiki 页面内容：
<img width="409" alt="截屏2020-08-04 下午3 33 52" src="https://user-images.githubusercontent.com/38550500/89266000-edee1480-d667-11ea-9993-f16a006808f1.png">

## 我发现页面有这样的问题

怀疑当初写内容时候是不是参考了[中文版 wiki](https://zh.wikipedia.org/wiki/%E6%A0%BC%E9%9B%B7%E7%A0%81) ，其中显示是1940年创作的：
> 图片1：
<img width="530" alt="截屏2020-08-04 下午3 35 51" src="https://user-images.githubusercontent.com/38550500/89266206-33124680-d668-11ea-84ec-86ce9055a3cf.png">

***

但是[英文版wiki](https://en.wikipedia.org/wiki/Gray_code#History_and_practical_application)中只提到了 1947 年在文章中引入概念，1953年申请专利；在全局搜索“1940”也没有结果：

> 图片2: 
<img width="298" alt="截屏2020-08-04 下午3 48 31" src="https://user-images.githubusercontent.com/38550500/89268130-b03ebb00-d66a-11ea-9689-5654695cc49e.png">

> 图片3:

<img width="531" alt="截屏2020-08-04 下午3 48 42" src="https://user-images.githubusercontent.com/38550500/89268153-b9c82300-d66a-11ea-892a-1e0763503314.png">

***

然后直接搜索的话，结果也是1953。

> 图片4:
<img width="551" alt="截屏2020-08-04 下午3 48 57" src="https://user-images.githubusercontent.com/38550500/89268637-65717300-d66b-11ea-8458-c14b7d0287a2.png">

> 图片5：
<img width="676" alt="截屏2020-08-04 下午3 50 17" src="https://user-images.githubusercontent.com/38550500/89268675-728e6200-d66b-11ea-83d6-ff7b67f170c0.png">

## 修改建议

将这句话修改成： 格雷码由贝尔实验室的 Frank Gray 于 1940 年**代**提出，并于1953年获得专利。

## 参考

- [cp-algorithms](https://cp-algorithms.com/algebra/gray-code.html)
- [en wiki gray code](https://en.wikipedia.org/wiki/Gray_code#History_and_practical_application)
- [gray code](https://openhome.cc/Gossip/AlgorithmGossip/GrayCode.htm)
- [What are Gray Codes?](https://www.allaboutcircuits.com/technical-articles/gray-code-basics/)

**Comment by Enter-tainer** [comment]
可以开一个 pr 帮忙修复吗(*^_^*)

**Comment by ksyx** [comment]
是历史学家 :+1:

**Comment by isdanni** [comment]
> 可以开一个 pr 帮忙修复吗(_^_^_)

🐒

**Comment by isdanni** [comment]
> 是历史学家 👍

🌚 🌕
