### ISSUE TITLE
[BUG] Gray Code

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/OI-wiki#2519]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）
<https://oi-wiki.org/misc/gray-code/#_2>
## 我发现页面有这样的问题
二进制中可以描述“个位”吗 🤔

**Comment by ShmilyQi-CN** [comment]
一般二进制都用高位，低位来描述没见过有用个位来描述的
