### ISSUE TITLE
[BUG] Splay 页面的旋转操作图示有误

### ISSUE THREAD

**Issue by YunQian-QwQ** [OI-wiki/OI-wiki#2540]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面

[这里](https://oi-wiki.org/ds/splay/#_7)

## 我发现页面有这样的问题

整棵树应该是满足左子树节点权值 < 根节点权值 < 右子树节点权值的吧 QAQ。

然而这张图

![](https://oi-wiki.org/ds/images/splay2.png)

明显有点问题啊......

**Comment by 20060321** [comment]
个人觉得这里的数字可以理解为点的编号吧awa，可能只是为了方便说明？

**Comment by StudyingFather** [comment]
图上的数字应该是点的编号，而非权值。

这里主要是为了阐述“旋转过程中中序遍历不变”的事实。
