### ISSUE TITLE
[BUG] bot 对列表格式处理有问题

### ISSUE THREAD

**Issue by ayalhw** [OI-wiki/OI-wiki#2624]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）
![图片](https://user-images.githubusercontent.com/43064781/91911396-97fea200-ece3-11ea-8598-f8734006d58a.png)

代码位于 https://github.com/OI-wiki/OI-wiki/blob/master/docs/tools/wsl.md#L290-L300

[`3f81925` (#2623)](https://github.com/OI-wiki/OI-wiki/pull/2623/commits/3f81925b333860adf849596af9059865f0e8b068)

https://github.com/OI-wiki/OI-wiki/pull/2623

**Comment by ayalhw** [comment]
又有一位同志惨遭波特打击（
https://github.com/OI-wiki/OI-wiki/pull/2629

**Comment by ouuan** [comment]
https://babelmark.github.io/?text=-+++a%0A%0A++++b%0A++++%0A-+++c%0A%0A++++d%0A++++%0A-+++e%0A%0A++++f

https://babelmark.github.io/?text=-+++a%0A%0A++++b%0A-+++c%0A%0A++++d%0A-+++e%0A%0A++++f

可以看到，在绝大部分实现下，这两者是一样的，除了，除了...除了 python-markdown（（（

**Comment by ayalhw** [comment]
过于草生，
upstream issue
（上游有在修吗？

**Comment by ayalhw** [comment]
This is my fault...
close...
I'm so sorry...
