### ISSUE TITLE
[BUG]关于 WSL 中运行 NOI 比赛指定环境的问题

### ISSUE THREAD

**Issue by Just-Prog** [OI-wiki/OI-wiki#2664]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）

[WSL (Windows 10)](https://oi-wiki.org/tools/wsl/#7)

## 我发现页面有这样的问题

```
sudo apt install build-essential vim ddd gdb fpc emacs gedit anjuta lazarus -y
wget http://download.noi.cn/T/noi/GUIDE-1.0.2-ubuntu.tar
tar -xvf GUIDE-1.0.2-ubuntu.tar
cd GUIDE-1.0.2-ubuntu
chmod +x install.sh && ./install.sh
```

感觉除了第一行安装 `vim`, `gcc` 等必要环境之外的话没有必要……

`Ubuntu 18 / 20`基本不支持 `GUIDE` 一类的 32 位程序

用 `GUIDE` 官方的脚本安装完直接就会报错

**Comment by ayalhw** [comment]
感觉可能是依赖库没装好……
32位程序还是支持的，有单独的32位库包

**Comment by ayalhw** [comment]
我收回前言，这个可执行文件确实有些古怪……

**Comment by ayalhw** [comment]
初步侦查可能是需要这些动态库和包（表中包名为 Arch 包名）

|动态库|Arch 包名|
|-----|--------|
|libpng12.so.0|lib32-libpng12|
|libSM.so.6|lib32-libsm|
|libICE.so.6|lib32-libice|
|libXi.so.6|lib32-libxi|
|libXrender.so.1|lib32-libxrender|
|libXrandr.so.2|lib32-libxrandr|
|libfreetype.so.6|lib32-freetype2|
|libfontconfig.so.1|lib32-fontconfig|
|libXext.so.6|lib32-libxext|
|libX11.so.6|lib32-libx11|
|libz.so.1|lib32-zlib|
|libgthread-2.0.so.0|lib32-glib2|
|librt.so.1|lib32-glibc|
|libglib-2.0.so.0|lib32-glib2|
|libpthread.so.0|lib32-glibc|
|libdl.so.2|lib32-glibc|
|libstdc++.so.6|lib32-gcc-libs|
|libm.so.6|lib32-glibc|
|libgcc_s.so.1|lib32-gcc-libs|
|libc.so.6|lib32-glibc|

**Need Test**

**Comment by ayalhw** [comment]
![图片](https://user-images.githubusercontent.com/43064781/93671027-3a839700-fad2-11ea-9583-ca1432743e79.png)
看上去除了长宽比例比较奇怪以外这个依赖表没啥问题……

**Comment by Just-Prog** [comment]
> ![图片](https://user-images.githubusercontent.com/43064781/93671027-3a839700-fad2-11ea-9583-ca1432743e79.png)
> 看上去除了长宽比例比较奇怪以外这个依赖表没啥问题……

太怪了……

我感觉还是 `VirtualBox` + `NOI Linux` 好点……

~~毕竟几年前的东西不能强求~~

**Comment by ayalhw** [comment]
@Just-Prog 但是 NOI Linux 就真的除了跑 GUIDE 和 Arbiter 干不了别的了（

**Comment by ayalhw** [comment]
可能需要一位 Ubuntu 用户来对应下 https://github.com/OI-wiki/OI-wiki/issues/2664#issuecomment-695270620 中动态库对应的包名……

**Comment by CoelacanthusHex** [comment]
|动态库|Arch 包名|Debian 包名|Fedora 包名|openSUSE x86 包名| openSUSE x86_64 包名|
|-----|--------|-----------|----------|----------------|--------------------|
|libpng12.so.0|lib32-libpng12|libpng12|libpng12|libpng12-0|libpng12-0-32bit|
|libSM.so.6|lib32-libsm|libsm6|libSM|libSM6|libSM6-32bit|
|libICE.so.6|lib32-libice|libice6|libICE|libICE6|libICE6-32bit|
|libXi.so.6|lib32-libxi|libxi6|libXi|libXi6|libXi6-32bit|
|libXrender.so.1|lib32-libxrender|libxrender1|libXrender|libXrender1|libXrender1-32bit|
|libXrandr.so.2|lib32-libxrandr|libxrandr|libXrandr|libXrandr2|libXrandr2-32bit|
|libfreetype.so.6|lib32-freetype2|libfreetype6|freetype|libfreetype6|libfreetype6-32bit
|libfontconfig.so.1|lib32-fontconfig|libfontconfig1|fontconfig|libfontconfig1|libfontconfig1-32bit|
|libXext.so.6|lib32-libxext|libxext6|libXext|libXext6|libXext6-32bit|
|libX11.so.6|lib32-libx11|libx11-6|libX11|libX11-6|libX11-6-32bit|
|libz.so.1|lib32-zlib|zlib1g|zlib|libz1|libz1-32bit|
|libgthread-2.0.so.0|lib32-glib2|libglib2.0-0|glib2|libgthread-2_0-0|libgthread-2_0-0-32bit
|libglib-2.0.so.0|lib32-glib2|libglib2.0-0|glib2|libglib2_0-0|libglib2_0-0-32bit|
|libstdc++.so.6|lib32-gcc-libs|libstdc++6|libstdc++|libstdc++6|libstdc++6-32bit|
|libgcc_s.so.1|lib32-gcc-libs|libgcc1/lib32gcc1|libgcc|libgcc_s1|libgcc_s1|
|librt.so.1|lib32-glibc|libc6|glibc|glibc|glibc-32bit|
|libpthread.so.0|lib32-glibc|libc6|glibc|glibc|glibc-32bit|
|libdl.so.2|lib32-glibc|libc6|glibc|glibc|glibc-32bit|
|libm.so.6|lib32-glibc|libc6|glibc|glibc|glibc-32bit|
|libc.so.6|lib32-glibc|libc6|glibc|glibc|glibc-32bit|

其中 Debian 的 `libgcc_s.so.1` 不确定是 `libgcc1` 还是 `lib32gcc1`，需要一名 Debian 用户验证

**Comment by CoelacanthusHex** [comment]
蹲一只 Debian 用户🤣

**Comment by CoelacanthusHex** [comment]
得到 Telegram 群内一名热心群友（ @ranwen ）的帮助，确定为 `lib32gcc1`

**Comment by CoelacanthusHex** [comment]
> ```
> sudo apt install build-essential vim ddd gdb fpc emacs gedit anjuta lazarus -y
> wget http://download.noi.cn/T/noi/GUIDE-1.0.2-ubuntu.tar
> tar -xvf GUIDE-1.0.2-ubuntu.tar
> cd GUIDE-1.0.2-ubuntu
> chmod +x install.sh && ./install.sh
> ```
> 
> 感觉除了第一行安装 `vim`, `gcc` 等必要环境之外的话没有必要……

这个是根据的官方 NOI Linux 所提供的环境安装的（不过没使用对应版本的

> `Ubuntu 18 / 20`基本不支持 `GUIDE` 一类的 32 位程序
> 
> 用 `GUIDE` 官方的脚本安装完直接就会报错

should fix via #2913
