### ISSUE TITLE
[BUG] wiki的评论功能崩了

### ISSUE THREAD

**Issue by dage233** [OI-wiki/OI-wiki#2700]
![image](https://user-images.githubusercontent.com/46173896/94981451-13fb3c80-0565-11eb-901e-9d1705ae5122.png)

如上图所示,在登陆github账号后,评论区显示Network Error ;在未登录情况下可以正常显示评论,但是无法评论.

日期:2020年10月3日

**Comment by CBW2007** [comment]
我这里好像没有问题？因为gh本来就不太稳，建议加一个googlehosts或者来点魔法（

**Comment by CBW2007** [comment]
#794 当年的zz行为（

**Comment by StudyingFather** [comment]
这个很有可能是您自身的网络问题。

可以考虑使用代理等方式解决。
