### ISSUE TITLE
多重背包时间复杂度问题

### ISSUE THREAD

**Issue by kjgfcdb** [OI-wiki/OI-wiki#2710]
## 我正在访问这个页面（最好带链接）

[背包DP](https://oi-wiki.org/dp/knapsack/#_2)

## 我发现页面有这样的问题

在这一页上，多重背包的朴素算法时间复杂度为`O(nW\sum k_i)`。请问这里是不是应该去掉`sum`，使用`max`比较正确？

**Comment by sbofgayschool** [comment]
感觉应该是 O(W\sum_{i=1}^nk_i) ~已commit到一个pr中~
