### ISSUE TITLE
[BUG]贪心算法-第一个例题国王游戏的解题思路中描述出现混乱

### ISSUE THREAD

**Issue by songpp** [OI-wiki/OI-wiki#2820]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）
https://oi-wiki.org/basic/greedy/
## 我发现页面有这样的问题
国王游戏解题思路中有这样的描述：
> 如果我们交换第i个大臣与第i+1个大臣的位置，那么第`i+1`个大臣得到的奖赏就是

但是紧接着下面一句又是`i+1`：

> 第`i+1`个大臣得到的奖励就是

如果我没有理解错误，我想下面这句应该是：`第i个大臣`?

**Comment by MXR612** [comment]
@songpp 【OT】纠正：如果我没有理解错无如果我没有理解错误
