### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by nanmenyangde** [OI-wiki/OI-wiki#2830]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）

[前缀函数与 KMP 算法](https://oi-wiki.org/string/kmp/)

[Z 函数（扩展 KMP）](https://oi-wiki.org/string/z-func/)

## 我发现页面有这样的问题

前缀函数和Z函数明明就是一个东西啊?

**Comment by CoderOJ** [comment]
>     * [ ]  我正在着手修复这个问题
> 
> 
> ## 我正在访问这个页面（最好带链接）
> 
> [前缀函数与 KMP 算法](https://oi-wiki.org/string/kmp/)
> 
> [Z 函数（扩展 KMP）](https://oi-wiki.org/string/z-func/)
> ## 我发现页面有这样的问题
> 
> 前缀函数和Z函数明明就是一个东西啊?

不是一个东西，前缀函数是以 i 结尾的，Z 函数以 i 开始的
