### ISSUE TITLE
[BUG]部署在网站子目录下搜索功能返回的href不正确

### ISSUE THREAD

**Issue by luxin4null** [OI-wiki/OI-wiki#2834]
- [ ✅] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ✅] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）
我将OI-wiki部署后使用nginx代理，在使用搜索功能时，搜索结果列表的href指向了一个不正确的路径
![image](https://user-images.githubusercontent.com/33851446/101784582-a9ebae80-3b36-11eb-8bcd-c832c07d2057.png)
点击搜索结果将会访问http://localhost/ds/bit-in-block-array/并提示404错误
实际上应该访问的路径是http://localhost/oi-wiki/ds/bit-in-block-array/

我尝试替换了主题，使用了ctf-wiki的配置解决了这个问题，但是他的响应速度太慢了，每次需要好几秒中，并且搜索结果的准确性也有问题
![image](https://user-images.githubusercontent.com/33851446/101785302-90973200-3b37-11eb-8cc1-4d374f8518f5.png)

![image](https://user-images.githubusercontent.com/33851446/101785553-dfdd6280-3b37-11eb-934b-cba05075954e.png)

## 我确认这个问题可以这样复现
是否存在两全其美的方法，可以部署在网站子目录下时仍保留响应速度以及搜素结果准确性？

**Comment by lawvs** [comment]
这个问题虽然修复了，但是仍然需要注意 OI-wiki 主题的搜索功能由自建的 elasticsearch 提供（`https://search.oi-wiki.org:8443/?s=`）。因此无法在离线环境下运行，如果有离线需要还是需要替换主题。
