### ISSUE TITLE
[BUG]Latex '-'无法正常显示

### ISSUE THREAD

**Issue by yzxoi** [OI-wiki/OI-wiki#2855]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [x] 我正在着手修复这个问题

## 我遇到了这样的问题

![image.png](https://i.loli.net/2020/12/27/gvjWVNoe4IYihCn.png)

![image.png](https://i.loli.net/2020/12/27/Zh1je3k7NbxEDRI.png)

如图，在某些页面中，Latex `-` 无法正常显示。
当我调整浏览器窗口大小时，Latex `-` 又会正常显示。

![image.png](https://i.loli.net/2020/12/27/SXwEJHYI4gjqCz5.png)

但与此同时，其他地方的 Latex `-` 也可能会无法正常显示。

**Comment by sshwy** [comment]
是你浏览器的问题吧
你试试放大到125%

**Comment by yzxoi** [comment]
> 是你浏览器（或者显示屏）的问题吧
> 你试试放大到125%

放大到 150% 后就都正常了，应该是我显示屏的问题吧
