### ISSUE TITLE
add 后缀平衡树

### ISSUE THREAD

**Issue by nanmenyangde** [OI-wiki/OI-wiki#2858]
## 我希望能添加的内容是
后缀平衡树
## 我了解到的相关参考资料有
[洛谷模板题题解](https://www.luogu.com.cn/problem/solution/P6164)
[flying2018的字符串学习笔记](https://www.cnblogs.com/Flying2018/p/13741568.html)

**Comment by StudyingFather** [comment]
added in #3133.
