### ISSUE TITLE
[BUG]由于NOI官网网站更换而导致的关于NOI官网的链接全部失效

### ISSUE THREAD

**Issue by bit00011011** [OI-wiki/OI-wiki#2896]
- [x] 我正在着手修复这个问题

## 我发现页面有这样的问题
关于NOI官网的链接全部失效

**Comment by ranwen** [comment]
再次发送这个issue是因为有许多其他的页面也有含有ccf-noi官网的链接还未修复吗？

**Comment by ranwen** [comment]
如果是的话，麻烦您做完所有工作后再统一发送一个PR，以减小我们工作的复杂度（OI-wiki每个PR都需要有至少两个人review）。

以及在PR中写 fix #xxxx ，当这个PR被merge时，会关闭引用的issue

**Comment by ouuan** [comment]
> 麻烦您做完所有工作后再统一发送一个PR

或者在全部完成之前开一个 draft PR：
![图片](https://user-images.githubusercontent.com/30581822/105453206-ad885e80-5cba-11eb-844a-c11b90125ce8.png)

或者把已经开了的 PR 转换成 draft PR：![图片](https://user-images.githubusercontent.com/30581822/105453088-7619b200-5cba-11eb-9d22-516eb46e77b3.png)
