### ISSUE TITLE
[BUG] exLucas 公式有误

### ISSUE THREAD

**Issue by imalyd** [OI-wiki/OI-wiki#2929]
- [x] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）

[exLucas](https://oi-wiki.org/math/lucas/#_5)

## 我发现页面有这样的问题

![image](https://user-images.githubusercontent.com/45112200/106081889-a9de5700-6154-11eb-82bb-4d629375cb34.png)

此公式有误，应改为

![image](https://user-images.githubusercontent.com/45112200/106082111-10637500-6155-11eb-8357-6200a88557c2.png)

**Comment by Great-designer** [comment]
感谢您的指正！在[Pull Request 3135](https://github.com/OI-wiki/OI-wiki/pull/3135)，做了些公式的修正。

根据原文的例子，原公式并没有错误，新公式也是对的。您的新公式相当于是原公式的进一步推导，因此把新公式紧跟着补在了后面。
