### ISSUE TITLE
[BUG]搜索框底景无法遮盖目录链接

### ISSUE THREAD

**Issue by Early0v0** [OI-wiki/OI-wiki#2939]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

## 我遇到了这样的问题

选中搜索框，鼠标移动到左侧目录仍能点击链接。

![image](https://user-images.githubusercontent.com/44915258/106235087-f39e6e80-6234-11eb-9e91-fb97a1d3c8d1.png)

我确认这个问题可以复现（在电脑端显示），应该是 css `z-index` 的问题。

**Comment by diauweb** [comment]
似乎目前不再出现
