### ISSUE TITLE
[BUG]点开搜索栏后无法叉掉

### ISSUE THREAD

**Issue by g-mph** [OI-wiki/OI-wiki#2962]
搜索栏点开后无法叉掉
必须点别的空白处才能关闭

**Comment by Enter-tainer** [comment]
@wwmiaopuhuan 你好 那个叉是用来清空输入的

**Comment by wwmiaopuhuan** [comment]
啊！原来是这样啊

这设计……能否换一下？

**Comment by abc1763613206** [comment]
@wwmiaopuhuan 您好，OI Wiki 整体使用了 mkdocs-material 主题，这个问题我们也曾经向上游反馈过，如有疑问可以向上游提出 issue。
另外，搜索框中的 X 的清空功能在 MD 中是一种通用的设计规范，具体可查看 https://www.mdui.org/design/patterns/search.html#search-in-app-search
感谢您的建议，该问题我们还将继续关注。
