### ISSUE TITLE
[BUG] merge sort 伪代码有问题

### ISSUE THREAD

**Issue by minghu6** [OI-wiki/OI-wiki#2969]
- [x]  我会在下一个pr里修改

[merge sort 伪代码](https://oi-wiki.org/basic/merge-sort/#_5)  一看就是没检查就提交了，而且改都没法儿改，因为笔误的地方太多（姑且这么定性）让人摸不清原思路。

Git 显示是这一块儿是 @NachtgeistW 写的。

**Comment by NachtgeistW** [comment]
> [merge sort 伪代码](https://oi-wiki.org/basic/merge-sort/#_5) 一看就是没检查就提交了，而且改都没法儿改，因为笔误的地方太多（姑且这么定性）让人摸不清原思路。
> 
> Git 显示是这一块儿是 @NachtgeistW 写的。

呃那个，看脚注的话我这块是直接照抄算法导论英文版第31页的伪代码，我觉得应该没什么问题吧
![image](https://user-images.githubusercontent.com/35161925/107174506-5c3fd500-6a05-11eb-949c-742fc8d85032.png)

**Comment by abc1763613206** [comment]
您好，根据脚注，这段伪代码引用自[Introduction to Algorithms, third edition](https://books.google.com.hk/books?id=F3anBQAAQBAJ&lpg=PR13&dq=Introduction%20to%20Algorithms&hl=zh-CN&pg=PA31#v=onepage&q&f=false) 的 P31-P34 页，您可以在超链接中查看 Google 的引用。

如有疑问可以继续交流，谢谢~

**Comment by NachtgeistW** [comment]
> [merge sort 伪代码](https://oi-wiki.org/basic/merge-sort/#_5) 一看就是没检查就提交了，而且改都没法儿改，因为笔误的地方太多（姑且这么定性）让人摸不清原思路。
> 
> Git 显示是这一块儿是 @NachtgeistW 写的。

呃那个，看脚注的话我这块是直接照抄算法导论英文版第31页的伪代码，我觉得应该没什么问题吧

**Comment by NachtgeistW** [comment]
> > [merge sort 伪代码](https://oi-wiki.org/basic/merge-sort/#_5) 一看就是没检查就提交了，而且改都没法儿改，因为笔误的地方太多（姑且这么定性）让人摸不清原思路。
> > Git 显示是这一块儿是 @NachtgeistW 写的。
> 
> 呃那个，看脚注的话我这块是直接照抄算法导论英文版第31页的伪代码，我觉得应该没什么问题吧

![image](https://user-images.githubusercontent.com/35161925/107174751-f7d14580-6a05-11eb-961b-c90ffbf86cb8.png)

**Comment by minghu6** [comment]
那根据对照，显然是抄写的时候的笔误，请看一下。

**Comment by Enter-tainer** [comment]
欢迎开一个 pr 帮忙修正一下

**Comment by minghu6** [comment]
> 欢迎开一个 pr 帮忙修正一下

说起来我之前那个修改后缀数组章节的pr还没人看呢

**Comment by ouuan** [comment]
1. 算导的伪代码不符合 OIer 习惯，大家一般写代码都不是这样写的。最好是能下面的 C++ 代码相符。
2. 算导是每个函数一块，函数名没有行号，在 OI Wiki 中最好是写成 "Function XXX()" 这种形式。至于 merge sort，在 OI 中习惯上把 “MERGE” 和 "MERGE-SORT" 作为一个函数，这样写的话也不需要写成函数了。
3. 开头第一个变量赋值就出错，确实很迷惑。

**Comment by Xeonacid** [comment]
> 我倒不介意顺便修一下，比如放在我的下一个介绍Optimal In-Place Suffix Sorting的pr里面（只不过不知道什么时候能写完）

亲，这边建议一个pr只做一件事的呢，这样有助于更快merge的哦

**Comment by minghu6** [comment]
> > 我倒不介意顺便修一下，比如放在我的下一个介绍Optimal In-Place Suffix Sorting的pr里面（只不过不知道什么时候能写完）
> 
> 亲，这边建议一个pr只做一件事的呢，这样有助于更快merge的哦

没关系，因为本来就会涉及到merge sort的内容
