### ISSUE TITLE
[BUG] gitalk 停止工作

### ISSUE THREAD

**Issue by ShuYuMo2003** [OI-wiki/OI-wiki#2971]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）

gitalk 所依赖的一个项目（cors-anywhere） 已经停止支持。

详见：https://github.com/Rob--W/cors-anywhere/issues/301

不知道 OI-wiki 有没有准备替代方案。

我个人博客的评论系统也基于 gitalk ，我的也不能工作了。

gitalk 官方还没有解决方案……

建议更换评论系统或者等待官方解决。

## 我确认这个问题可以这样复现

尝试使用 github 账号登录 gitalk

**Comment by Enter-tainer** [comment]
对于个人用户，可以尝试使用 https://github.com/Zibri/cloudflare-cors-anywhere。我们正在解决这个问题，感谢提醒！

**Comment by ShuYuMo2003** [comment]
我的评论系统down了之后，想看看OI wiki怎么解决的…然后发现OI wiki也down了 /kel…

**Comment by Enter-tainer** [comment]
已修复, 感谢提醒！

**Comment by ShuYuMo2003** [comment]
https://github.com/OI-wiki/mkdocs-material/pull/31/files 这个是为什么啊 /kel 我也想修修我的博客…… 不是很懂。

**Comment by abc1763613206** [comment]
> @ShuYuMo2003 [OI-wiki/mkdocs-material#31 (files)](https://github.com/OI-wiki/mkdocs-material/pull/31/files) 这个是为什么啊 /kel 我也想修修我的博客…… 不是很懂。


方法比较脏，大约是自行 fork 一个 gitalk ，然后自己参照 https://github.com/Zibri/cloudflare-cors-anywhere 搭建一个实例，把 gitalk 中的地址换掉。

**Comment by Enter-tainer** [comment]
@ShuYuMo2003 具体来说 你需要自行部署 cors anywhere，然后更改 gittalk 代码中的 cors anywhere 服务地址，然后重新构建 gittalk。

**Comment by ouuan** [comment]
@ShuYuMo2003 可以用 https://utteranc.es/

**Comment by ShuYuMo2003** [comment]
我的 NexT 使用 utterances 好像登录跳转路径有点问题 @ouuan

**Comment by ShuYuMo2003** [comment]
可以部署在哪里啊，是有什么免费的跑服务的地方还是必须部署在一台服务器上呢？ /jk

**Comment by Enter-tainer** [comment]
> 对于个人用户，可以尝试使用 https://github.com/Zibri/cloudflare-cors-anywhere 。我们正在解决这个问题，感谢提醒！

你好 请阅读这个链接

**Comment by ShuYuMo2003** [comment]
sorry for it.

**Comment by ouuan** [comment]
> 我的 NexT 使用 utterances 好像登录跳转路径有点问题 @ouuan

https://github.com/utterance/utterances/issues/474#issuecomment-774887936

**Comment by ShuYuMo2003** [comment]
谢谢 ouuan 的教育… /dk
