### ISSUE TITLE
add PQ 树

### ISSUE THREAD

**Issue by GitPinkRabbit** [OI-wiki/OI-wiki#2981]
## 我希望能添加的内容是

PQ 树

## 我了解到的相关参考资料有

[PQ Tree - Wikipedia](https://en.wikipedia.org/wiki/PQ_tree)  
[PQ 树小结 - CSDN](https://blog.csdn.net/yeziqing10/article/details/51997188)

我正在考虑写一篇 PQ 树的，有意向提供更多资料或者提出一些建议的欢迎联系我，联系方式我个人主页有。

**Comment by hly1204** [comment]
我以为是那个测试是否是平面图的，那个玩意儿感觉好复杂。。
