### ISSUE TITLE
add 繁体支持（行/列）

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/OI-wiki#2985]
## 我遇到的问题是

> @ksyx
> > 抱歉，台灣的行、列用法跟大陸好像是相反的
> > 能否在每個行、列後面標記英文讓我們能夠比較好理解
> > 台灣：直行（column）、橫列（row）
> 
> 不知道有否一些繁中和简中的转换插件能够帮到您呢

我試過了，那些東西只會將簡體字轉成繁體字，但他們並不太知道兩岸用語的差別，所以在轉換時只會轉換字體但其他東西是不會的。而且有些插件還會造成原本排版整個跑掉。這也是為什麼我後來沒有使用的原因。因為版面整個跑掉，內容整個看不懂（特別是有英文、數字符號的部分）。所以我現在是在看簡體網頁。

https://github.com/OI-wiki/gitment/issues/90#issuecomment-777184333

**Comment by CoelacanthusHex** [comment]
理论上 OpenCC 使用 s2tw 的配置应该可以正确处理（绝大部分）这类问题

**Comment by Great-designer** [comment]
！发现了这个宝藏 Issue ，原来这个问题很久以前就有人提过了
