### ISSUE TITLE
add dark mode

### ISSUE THREAD

**Issue by alphagocc** [OI-wiki/OI-wiki#3022]
## 我遇到的问题是

晚上看比较瞎眼

## 我希望能有这样的解决方案

有暗色模式

## 我觉得其他这些方案也可以接受

无

**Comment by CoelacanthusHex** [comment]
NG 有（

**Comment by diauweb** [comment]
我们计划引入一个[全新的框架](https://github.com/OI-wiki/gatsby-oi-wiki/)来解决此问题
目前该项目已经进入 Public Beta 阶段，欢迎访问 https://next.oi-wiki.org 体验 并留下您的宝贵建议

**Comment by NachtgeistW** [comment]
https://github.com/OI-wiki/OI-wiki/pull/4695
