### ISSUE TITLE
[RFC] 关于 Commit Message 书写以及 PR 合并方式的问题

### ISSUE THREAD

**Issue by CoelacanthusHex** [OI-wiki/OI-wiki#3061]
首先，我们在 How To Contribute 中有关于 Commit Message 格式的[基本要求](https://oi-wiki.org/intro/htc/#commit-pull-request)
然后，对于 Pull Request 的合并方式，
- 如果 Commit Message 书写符合格式，质量较高，我们将采用 Rebase 的方式合并
- 否则，我们将采用 Squash 的方式合并

---

- [x] 修改 edit-landing
- [x] OI Wiki News Channel 公告
- [x] QQ 群公告

**Comment by ouuan** [comment]
为什么要 Rebase 呢？

**Comment by ouuan** [comment]
我支持全部 squash

**Comment by CoelacanthusHex** [comment]
Read the discussion in Telegram Group, please

https://t.me/c/1344172945/100187
________________________________

**Comment by CoelacanthusHex** [comment]
![图片](https://user-images.githubusercontent.com/43064781/111422397-98173a00-8729-11eb-8262-f02162d5b179.png)
![图片](https://user-images.githubusercontent.com/43064781/111422484-bbda8000-8729-11eb-8858-cbdd04695d12.png)
![图片](https://user-images.githubusercontent.com/43064781/111422546-d4e33100-8729-11eb-8479-290306112563.png)

**Comment by Early0v0** [comment]
@CoelacanthusHex 我觉得中文 commit 没啥问题啊

**Comment by ksyx** [comment]
> @ksyx 我觉得中文 commit 没啥问题啊

既然要标准化那就一起规范掉嘛）

**Comment by StudyingFather** [comment]
个人偏向于合并 PR 时全部 squash。

- squash 可以让 commit history 看上去更舒适些；
- 那个排行榜真的有人会在意嘛（划掉

**Comment by ouuan** [comment]
简单来说，如果你有两份 contribution，就应该开两个 PR，要是 rebase 多一些 contribution，那不就是在水吗。要是全部 merge 我还能理解“在意 contribution”这个观点，但既然劣质 commits 会被 squash，rebase 对于 contribution 就没多大用了。

**Comment by ouuan** [comment]
而且考虑到 format bot，commit log 几乎不可能干净。

另外就是 squash 可以更方便地 link 到 PR。

**Comment by ksyx** [comment]
rebase 保留 commit log，在 commit msg 写得好的情况下能展现整个编写过程，而将 squash 认为是一气呵成写完

**Comment by CoelacanthusHex** [comment]
> 简单来说，如果你有两份 contribution，就应该开两个 PR，要是 rebase 多一些 contribution，那不就是在水吗。要是全部 merge 我还能理解“在意 contribution”这个观点，但既然劣质 commits 会被 squash，rebase 对于 contribution 就没多大用了。

一些关于 contribution 的观点
![图片](https://user-images.githubusercontent.com/43064781/111870507-2278cb80-89c0-11eb-92cf-1dec641f4db9.png)
![图片](https://user-images.githubusercontent.com/43064781/111870513-2c9aca00-89c0-11eb-8954-a1bfc7cf3046.png)

**Comment by ouuan** [comment]
> rebase 保留 commit log，在 commit msg 写得好的情况下能展现整个编写过程，而将 squash 认为是一气呵成写完

1. “整个编写过程”在多数情况下是完全无用的，有用的信息是整体的 topic，也就是 PR 的标题。
2. squash 并没有使编写过程消失，可以点进 PR，（如果在 merge 时不编辑默认的 commit message）也可以在 commit body 中查看。
3. “将 squash 认为是一气呵成写完”：你完全可以不这么想。或者不如说我不知道为什么会这么想，squash 本来就应该是多个 commits 合并而成的。

squash 可以看作是将 commits 分为 topic（体现在主分支的 commit log 中）和 commit（体现在 PR 的 commit log 中）两个层次，在保留 merge 提供的层次的同时还有 rebase 的线性 commit log 的清爽。

**Comment by ouuan** [comment]
总结一下我的观点：

1. 对于一般的 PR：如果有很多人很在意 contribution，就全部或部分 create commit and merge；否则就全部 squash and merge。
2. 永远不采用 rebase and merge。
3. 特殊情况：例如需要 ahead of 某个 branch，必须 create commit and merge。

**Comment by ouuan** [comment]
关于主站显示的 author，可以在获取 author 时识别 Co-Author。
