### ISSUE TITLE
[BUG] docker 无法使用

### ISSUE THREAD

**Issue by mxr612** [OI-wiki/OI-wiki#3104]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [x] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）

无法搭建container，pip版本不够

## 我确认这个问题可以这样复现

在VSCode中搭建Container。

**Comment by mxr612** [comment]
应该将Dockerfile中的FROM改成ubuntu:latest

**Comment by Ir1d** [comment]
@frank-xjh 能否跟进一下
@mxr612 方便有空开个 pr 吗（

**Comment by mxr612** [comment]
@Ir1d 艹，不知不觉AFO一年了，我今天看看
