### ISSUE TITLE
关于许可证

### ISSUE THREAD

**Issue by Rratic** [OI-wiki/OI-wiki#3118]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案

## 我遇到了这样的问题
> 除特别注明外，项目中除了代码部分均采用 (Creative Commons BY-SA 4.0) 知识共享署名 - 相同方式共享 4.0 国际许可协议 及附加的 The Star And Thank Author License 进行许可。
>
> 换言之，使用过程中您可以自由地共享、演绎，但是必须署名、以相同方式共享、分享时没有附加限制，
>
> 而且需要为 GitHub 仓库点赞（Star）。

1. SATA License需要相同方式共享吗？
2. "除了代码部分" 所以代码部分采用啥？没写啊
3. 学会了去写有什么限制吗

~~请原谅我平时用惯了MIT，不了解这一块qwq~~

**Comment by Rratic** [comment]
add the help wanted / 需要帮助 label

**Comment by ksyx** [comment]
本项目代码使用 Apache 2.0 授权。感谢您的支持。

**Comment by Rratic** [comment]
ok

**Comment by Rratic** [comment]
哎，等等，请问我如果引用部分代码怎么用Apache 2.0啊

请问将代码格式化算“修改”吗

**Comment by ksyx** [comment]
之前的描述可能有歧义，fixed.

**Comment by Rratic** [comment]
增加了一个问题，fixed
