### ISSUE TITLE
[BUG] 搜索框搜索结果错误显示

### ISSUE THREAD

**Issue by imp2002** [OI-wiki/OI-wiki#3140]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [x] 我正在着手修复这个问题

## 我遇到了这样的问题（最好截图）

![bug1 (2)](https://user-images.githubusercontent.com/41513919/116205817-b46ab580-a770-11eb-996a-a08580191879.png)

- 1处显示错误
- 2处标题不见了

**Comment by Ir1d** [comment]
由于内容变了现在搜索不到这个地方了.. 我检查了下，可能是 parse title 的时候有锅，理论上现在应该不受影响了
