### ISSUE TITLE
add 编译入门相关

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#3151]
## 希望能添加编译入门相关

之前写过一些。这东西确实很有用，写parser也算是程序员必备技能。然而觉得这个坑实在是过于巨大，自己水平实在不高，还是放弃了。不知道有没有巨佬能简单地写写相关内容，内容简单，效果显著的那种。

## 我了解到的相关参考资料有

大学课本。比如狼书之类的。

**Comment by Konano** [comment]
感谢您的建议，我个人是觉得「编译入门」和 OI 并没有太大的关系，并不支持加入到 Wiki 中。

**Comment by GavinZhengOI** [comment]
> 感谢您的建议，我个人是觉得「编译入门」和 OI 并没有太大的关系，并不支持加入到 Wiki 中。

看法一致

**Comment by Great-designer** [comment]
这个也比较老了。

**Comment by yusancky** [comment]
现在，[编译器](https://oi-wiki.org/tools/compiler/) 与 [命令行#使用命令行编译/调试](https://oi-wiki.org/tools/cmd/#%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E7%BC%96%E8%AF%91%E8%B0%83%E8%AF%95) 的相关内容对 OI 来说已经很详尽。

要不大家看看是否还需补充内容。如果没有的话就关了这个议题。

**Comment by inclyc** [comment]
http://oi-wiki.org/lang/optimizations/ 感觉这些就够用了。没必要学编译原理

**Comment by inclyc** [comment]
@yusancky 这条评论为啥web上没有
