### ISSUE TITLE
[BUG] max flow 之 EK 算法 有 typo

### ISSUE THREAD

**Issue by LeeLin2602** [OI-wiki/OI-wiki#3170]
- [x] 我正在着手修复这个问题

## 我正在访问这个页面（最好带链接）

https://oi-wiki.org/graph/flow/max-flow/#edmond-karp-ek

## 我发现页面有这样的问题

應該是 Edmonds-Karp  而非 Edmond-Karp？

**Comment by ksyx** [comment]
您好，方便开个 pr 帮助修复一下吗 :heart:

**Comment by LeeLin2602** [comment]
> 您好，方便开个 pr 帮助修复一下吗 ❤️

已發 pr。
