### ISSUE TITLE
add Powerful Number Sieve

### ISSUE THREAD

**Issue by Backl1ght** [OI-wiki/OI-wiki#3178]
## 我希望能添加的内容是

Powerful Number Sieve

## 我了解到的相关参考资料有

[利用powerful number求积性函数前缀和](https://www.cnblogs.com/zzqsblog/p/9904271.html)

**Comment by ksyx** [comment]
可不可以提供一些更详细的信息，例如哪题用到了这个知识，以及现在可用的参考资料有哪些？
