### ISSUE TITLE
[BUG]原根的内容有误

### ISSUE THREAD

**Issue by Chtho11y** [OI-wiki/OI-wiki#3195]
- [ ] 我正在着手修复这个问题

## 我正在访问这个页面 

[原根](https://oi-wiki.org/math/primitive-root/)

## 我发现页面有这样的问题

1. 性质3的充分性证明的第二行，应该是 $a^{\delta_m(ab)\delta_m(b)}$.
2. 原根个数证明的第四行，应该是 $1\leq k < \varphi(m)$

**Comment by opsiff** [comment]
#3207
