### ISSUE TITLE
“杂项”里的“复杂度”一文，是否可以移动到“算法基础”的第一篇文章？

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#3212]
学习时间复杂度是学习所有算法的基础。抛开时间复杂度学习算法是无稽之谈。所以我认为，“复杂度”一文似乎可以放在“算法基础”这一部分。

**Comment by black-desk** [comment]
这个已经合并了是不是可以关了?

**Comment by Enter-tainer** [comment]
> 这个已经合并了是不是可以关了?

why not
