### ISSUE TITLE
add Hackenbush Game

### ISSUE THREAD

**Issue by Backl1ght** [OI-wiki/OI-wiki#3224]
## 我希望能添加的内容是

Hackenbush游戏，国内的叫法好像是图上删边游戏？

## 我了解到的相关参考资料有

- [Wikipedia - Hachenbush](https://en.wikipedia.org/wiki/Hackenbush)
- [Thomas S. Ferguson - Game Theory](https://www.cs.cmu.edu/afs/cs/academic/class/15859-f01/www/notes/comb.pdf)

**Comment by alphagocc** [comment]
根据
https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E6%9D%83%E5%A8%81%E6%9C%BA%E6%9E%84
OI Wiki 不是百科全书

另外 群友说可以开不平等博弈的页面
