### ISSUE TITLE
[内容补充] 二叉树上 DFS 图待补

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/OI-wiki#3282]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

<https://oi-wiki.org/graph/tree-basic/>

### 我发现页面有这样的问题

二叉树上 DFS
图待补

**Comment by yuhuoji** [comment]
这个是不是已经完成了呢 https://github.com/OI-wiki/OI-wiki/commit/601d996ec00a8b5513a1a37730ea65013bd92b46
