### ISSUE TITLE
oi-wiki.org挂了？

### ISSUE THREAD

**Issue by Rratic** [OI-wiki/OI-wiki#3284]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

昨天就这样了：
登不上，只能用其它镜像（[镜像列表](https://status.oi-wiki.org/)也上不去~~废话~~，镜像是别人告诉我的）

### 我确认这个问题可以这样复现

访问[org](https://oi-wiki.org)

**Comment by Rratic** [comment]
已经有过issue了，那没事了

**Comment by 94rain** [comment]
请问已经有的是哪个issue呢？
我之前以为是被墙了，现在似乎完全上不去了

**Comment by ksyx** [comment]
> 请问已经有的是哪个issue呢？
> <s>我之前以为是被墙了，现在似乎完全上不去了</s> (又可以了)

可以尝试 oiwiki.com

**Comment by Rratic** [comment]
[这个](https://github.com/OI-wiki/OI-wiki/issues/3200)
@94rain

**Comment by Ir1d** [comment]
Hi, 网站 oi-wiki.org 已经恢复访问，对于近期带来不便非常抱歉，将于近日采取措施避免此类事件再次发生，谢谢大家理解与支持
