### ISSUE TITLE
[内容有误] string/manacher.md中样例代码和原文不一致

### ISSUE THREAD

**Issue by CamberLoid** [OI-wiki/OI-wiki#3330]
### 请选择：

- [x] 我正在着手修复这个问题

### 我正在访问这个页面

https://github.com/OI-wiki/OI-wiki/tree/master/docs/string/manacher.md

### 我发现页面有这样的问题

原文(英文翻译)中对d1[]计算的代码如下
```cpp
vector<int> d1(n);
for (int i = 0, l = 0, r = -1; i < n; i++) {
    int k = (i > r) ? 1 : min(d1[l + r - i], r - i + 1);  // 这行
    while (0 <= i - k && i + k < n && s[i - k] == s[i + k]) {
        k++;
    }
    d1[i] = k--;
    if (i + k > r) {
        l = i - k;
        r = i + k;
    }
}
```
而 docs/string/manacher.md 的代码和原文有一些偏差
`int k = (i > r) ? 1 : min(d1[l + r - i], r - i);`

可能是这个偏差让自己写[某裸题](https://www.luogu.com.cn/problem/P3805)时WA了

请协助勘误, 谢谢.

~~以及OI-Wiki/i18n那边可以全文引用英文翻译?(狗头)~~

**Comment by CamberLoid** [comment]
@welcome[bot]

**Comment by CamberLoid** [comment]
@CamberLoid @Ir1dXD @ksyxmeow

**Comment by sshwy** [comment]
@CamberLoid 来个pr？
