### ISSUE TITLE
[功能请求] 优化本地阅读方案

### ISSUE THREAD

**Issue by Empathy117** [OI-wiki/OI-wiki#3332]
### 我遇到的问题是

感觉在本地阅读的时候部署式方案显然还是不太好用，是不是可以优化一下。

### 我希望能有这样的解决方案

可以尝试用Zeal/Dash之类的离线文档浏览器在本地阅读。
 生成并维护一个DocSet然后写一个feed，就可以往zeal里添加feed就可以把文档直接拉取到本地了。

### 我觉得这些备选方案也可以接受

当然上面提到的东西有需求的话显然都可以自己完成（

**Comment by ksyx** [comment]
现有的 pdf export 有什么需求不能被满足呢 🤔

**Comment by Empathy117** [comment]
> 现有的 pdf export 有什么需求不能被满足呢

两者根本就不是一个东西吧（

pdf export是在牺牲阅览以及查询体验的基础上做到的本地化阅读

而文档这个东西其实就是本地化OI-wiki, 更接近本地部署OI-wiki, 但比本地部署更方便

**Comment by ksyx** [comment]
例如把生成静态页面打包吗

**Comment by CoelacanthusHex** [comment]
> 两者根本就不是一个东西吧（
> 
> pdf export是在牺牲阅览以及查询体验的基础上做到的本地化阅读
> 
> 而文档这个东西其实就是本地化OI-wiki, 更接近本地部署OI-wiki, 但比本地部署更方便

PDF 除了动图被干掉了没什么缺陷吧（甚至搜索还比网页快了
（要说有什么缺陷就是灰度打印后有可能出现辨识不清以及需要手打链接的问题（但是这是打印出来的问题 PDF 本身是没有的
