### ISSUE TITLE
Add 分拆数

### ISSUE THREAD

**Issue by fsy-juruo** [OI-wiki/OI-wiki#3373]
### 页面英文名

partition

### 我希望能添加的内容是

分拆数定义，一些性质，Ferrers 图，求法（暴力，五边形数定理，durfee square）

### 我了解到的相关参考资料有

* Richard A. Brualdi 著，冯速 等译，《组合数学（第 5 版）》，8.3 分拆数

* [五边形数与整数拆分问题 by Studying Father](https://studyingfather.blog.luogu.org/pentagonal-number-and-number-partitions)

* 相关维基百科

**Comment by fsy-juruo** [comment]
az 忘记把 EI 的 durfee square 求法贴上来了 [分拆数的第三种计算方法](https://blog.csdn.net/EI_Captain/article/details/104729572?spm=1001.2014.3001.5501)

btw 为什么不支持一个 issue 里请求加多个 topic 啊...

**Comment by ouuan** [comment]
> btw 为什么不支持一个 issue 里请求加多个 topic 啊...

多个 topic 的话，一个 topic 加完之后关不了 issue，link 到这个 issue 不知道是说哪个 topic，没法只 subscribe 一个 topic，在 issue 底下讨论不知道是哪个 topic……

**Comment by ouuan** [comment]
不行我还是忍不住..因为上面已经给过理由了还是发一下标点符号（

> btw 为什么不支持一个 issue 里请求加多个 topic 啊...

？？？

为什么要一个 issue 多个 topic？？？

**Comment by fsy-juruo** [comment]
> > btw 为什么不支持一个 issue 里请求加多个 topic 啊...
> 
> 多个 topic 的话，一个 topic 加完之后关不了 issue，link 到这个 issue 不知道是说哪个 topic，没法只 subscribe 一个 topic，在 issue 底下讨论不知道是哪个 topic……

哦 sry 我的锅... 当我没说...

**Comment by Great-designer** [comment]
你好！我这里已经在写了。计划下周进行大更新

**Comment by Great-designer** [comment]
已经写好了。不过应该要等上一个PR审完（若需要改还要等改完，再等审完）。上一个PR已经叠加得足够多了，如果再叠加一个partition估计审核的同学就集体崩溃了。

针对这种事情，我在下一个PR研究一下如何从master分支之外的分支进行……这样或许可以并行。目前我这里暂时还没有研究出并行进行的办法。

**Comment by Ir1d** [comment]
hi @Great-designer 感谢！创建分支或许可以参考这个页面，希望有所帮助： https://docs.github.com/cn/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository
