### ISSUE TITLE
[内容有误] basic/prefix-sum.md 缺失对前缀和的定义

### ISSUE THREAD

**Issue by CamberLoid** [OI-wiki/OI-wiki#3405]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://github.com/OI-wiki/OI-wiki/blob/master/docs/basic/prefix-sum.md

### 我发现页面有这样的问题

如题。于~~缓慢的~~翻译过程中发现的问题。

与之相对的，差分部分就有完整定义。建议加上（或者可能自己开pr）。

**Comment by ksyx** [comment]
> 可以简单理解为“数列的前 $n$ 项的和”。

这个应该够了吧 🤔
感觉这块不用太形式化

**Comment by CamberLoid** [comment]
好伐pwp

> > 可以简单理解为“数列的前 $n$ 项的和”。
> 
> 这个应该够了吧 thinking
> 感觉这块不用太形式化
