### ISSUE TITLE
[RFC] 关于动图使用 APNG 的讨论

### ISSUE THREAD

**Issue by CoelacanthusHex** [OI-wiki/OI-wiki#3422]
关于 APNG 的可用性覆盖率：
![图片](https://user-images.githubusercontent.com/43064781/128837219-cf70f04c-d6fe-4b2d-8179-2c7588b0c921.png)
数据来源： https://caniuse.com/?search=APNG

优势：
- 更高的清晰度（APNG 使用无损压缩，支持 32bit 图像、8bit 色深，会明显好于 GIF）
- 同质量下更小的体积（相对于 GIF 和 WebP）[1]，利用 PNG 的 filter 压缩率可以有巨大的优势
- 支持 Alpha 通道（即支持半透明）（与 GIF 比较）
- 可以支持动画从第二帧开始，第一帧留作他用（比如不支持的设备的 fallback 显示）示例 ![例子](https://www.zhangxinxu.com/study/201409/apng-support.png)  Related: https://github.com/OI-wiki/OI-wiki/issues/3435#issuecomment-896638363
- ~向后兼容 PNG（用不到）~

缺点：
- IE 不支持
- 待补充

Ref:
[1]: http://littlesvr.ca/apng/gif_apng_webp.html
[2]: https://www.zhangxinxu.com/wordpress/2014/09/apng-history-character-maker-editor/
[3]: https://en.wikipedia.org/wiki/APNG
[4]: https://wiki.mozilla.org/APNG_Specification

**Comment by llh721113** [comment]
LGTM

**Comment by renbaoshuo** [comment]
@llh721113 LGTM

**Comment by tsagaanbar** [comment]
LGTM

**Comment by CoelacanthusHex** [comment]
> 借个楼：关于替换文本等无障碍设计是否需要加入规范？

@tsagaanbar 可开 RFC 另作讨论，我个人持支持意见

**Comment by CoelacanthusHex** [comment]
https://github.com/OI-wiki/OI-wiki/pull/3418 和 https://github.com/OI-wiki/OI-wiki/pull/3434 分别是使用工具转换和重新制作的例子，各位可以参考一下效果（重新制作的版本的清晰度受限于我的屏幕分辨率（X11 就是一堆 shit），如果是 Wayland 用户或者 Windows 来录屏应该相对好一点）

**Comment by tsagaanbar** [comment]
> #3418 和 #3434 分别是使用工具转换和重新制作的例子，各位可以参考一下效果（重新制作的版本的清晰度受限于我的屏幕分辨率（X11 就是一堆 shit），如果是 Wayland 用户或者 Windows 来录屏应该相对好一点）

#3418 这样的 GIF，本身画面变化不大，色彩不多，在我这里观看情况转换前后二者无明显差别；
#3434 这种录屏式的动态图像，使用 APNG 的效果确实更好。

不过 **OI Wiki** 的页面能嵌入视频吗，个人认为演示类的图像使用动图，不便于定位动作的开始和结束，也不便手动执行“重新播放”等操作。

**Comment by CoelacanthusHex** [comment]
> 不过 **OI Wiki** 的页面能嵌入视频吗，个人认为演示类的图像使用动图，不便于定位动作的开始和结束，也不便手动执行“重新播放”等操作。

理论上肯定是可行的，但是实际上没什么必要。主要有以下几点：
- 不便于定位动作的开始和结束：OI Wiki 使用的动画演示一般不会太长，<=10s 的较多
- 也不便手动执行“重新播放”等操作：APNG 动图一般是循环播放的
- 视频文件的话要考虑格式编码兼容性，还要考虑视频栏的控件设计
- **Markdown 不支持 Video**

**Comment by tsagaanbar** [comment]
@CoelacanthusHex 可能是我刚刚表述有一点问题，也许应该这样表述：自动播循环放的动图有些时候像一个粘接起来的纸环，但我们往往很难找到这个纸环的接缝。

**Comment by llh721113** [comment]
> @CoelacanthusHex 可能是我刚刚表述有一点问题，也许应该这样表述：自动播循环放的动图有些时候像一个粘接起来的纸环，但我们往往很难找到这个纸环的接缝。

明白，以后制作ASVG的时候我也会注意这个问题

**Comment by CoelacanthusHex** [comment]
> @CoelacanthusHex 可能是我刚刚表述有一点问题，也许应该这样表述：自动播循环放的动图有些时候像一个粘接起来的纸环，但我们往往很难找到这个纸环的接缝。

制作的时候注意应该能比较有效的避免问题（尤其是开始和结束时的画面不同的时候），很多时候演示图像也配有文字说明

**Comment by Konano** [comment]
我表示支持
