### ISSUE TITLE
Add 支配树

### ISSUE THREAD

**Issue by fsy-juruo** [OI-wiki/OI-wiki#3438]
### 页面英文名

dominator-tree

### 我希望能添加的内容是

支配树 & Lengauer-Tarjan 算法

### 我了解到的相关参考资料有

* 陈孙立《浅谈支配树及其应用》（2020）

* [洛谷模板题解](https://www.luogu.com.cn/problem/solution/P5180)

**Comment by AtomAlpaca** [comment]
[#4950](https://github.com/OI-wiki/OI-wiki/pull/4950)
