### ISSUE TITLE
[BUG] 搜索一些关键词搜索不到

### ISSUE THREAD

**Issue by g-mph** [OI-wiki/OI-wiki#3462]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

有一些关键词在搜索框中搜索不到，如“欧拉函数”、“中国剩余定理”。

**Comment by Ir1d** [comment]
感谢反馈，已经修复并将在 #3664 跟进
