### ISSUE TITLE
[提问] gitalk 为什么需要写我的repo

### ISSUE THREAD

**Issue by JeffersonQin** [OI-wiki/OI-wiki#3503]
### 我遇到的问题是

![image](https://user-images.githubusercontent.com/30655701/131706473-74182a74-ddcf-474e-b7b4-29d2a3fc423a.png)

gitalk 需要写我的 repo

### 我希望能有这样的解决方案

我觉得评论功能要求这么高的权限是不合理的，是否应该考虑别的方式

**Comment by Enter-tainer** [comment]
这个似乎是 github oauth app 默认的权限范围🤔。我正在研究怎么限定权限的 scope

**Comment by Enter-tainer** [comment]
https://github.com/gitalk/gitalk/issues/95

**Comment by Enter-tainer** [comment]
看了一下, 似乎除了切换到 utterances 之类的系统之外,没有别的方法..

**Comment by JeffersonQin** [comment]
好的，感谢回复。
