### ISSUE TITLE
[BUG] 404 页面使用搜索功能时链接有误

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#3541]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![image](https://user-images.githubusercontent.com/10709657/133870504-162806a6-de28-4c92-ac35-a311f31f1b8e.png)
有结果但是链接不对

### 我确认这个问题可以这样复现

https://oi-wiki.org/404.html

**Comment by StudyingFather** [comment]
非 404 页面似乎也存在这样的问题。

尝试搜索“最小树形图”，点击搜索结果跑到了“最小直径生成树”页面。

**Comment by CoderOJ** [comment]
你 wiki 搜索日常出锅

**Comment by isdanni** [comment]
**404页面的新锅**
[oi-wiki.org/404.html](oi-wiki.org/404.html) 搜索结果的链接不全，点击调转缺少oi-wiki.org的前缀。

比如说点击结果应该跳转到 [oi-wiki.org/misc/job-order](oi-wiki.org/misc/job-order), 但跳转到了不全的链接 [misc/job-order](misc/job-order)

![error](https://user-images.githubusercontent.com/38550500/147474697-fd8f2dd9-0bed-4fd0-a9d2-48975304b426.png)

**Comment by billchenchina** [comment]
404 页面中 `app.initialize()` 的 `base_url` 是 `/`，URL 拼接之后变成了 `//misc/job-order`。。

**Comment by Ir1d** [comment]
是不是得改主题呀
