### ISSUE TITLE
Add “数论分块”一节下的 gitalk 评论用 issue

### ISSUE THREAD

**Issue by qwqAutomaton** [OI-wiki/OI-wiki#3552]
### 页面英文名

https://oi-wiki.org/math/number-theory/sqrt-decomposition/

### 我希望能添加的内容是

用于gitalk评论的issue

### 我了解到的相关参考资料有

页面提示信息：

> 未找到相关的 Issues 进行评论
> 
> 请联系 @Ir1d @cjsoft @TrisolarisHD @Xeonacid @sshwy @Enter-tainer @StudyingFather 初始化创建

**Comment by Xeonacid** [comment]
fixed
