### ISSUE TITLE
[BUG] 数学公式显示异常

### ISSUE THREAD

**Issue by YOYO-UIAT** [OI-wiki/OI-wiki#3592]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![](https://cdn.luogu.com.cn/upload/image_hosting/mwjpkzgj.png)

如上图，在缩放比例为 100% 时，会出现某些字母旋转了 90° 的情况。

我用的是 Edge 94.0.992.31。

### 我确认这个问题可以这样复现

访问“普通生成函数”页面，其中许多公式都有这种问题。

**Comment by YOYO-UIAT** [comment]
补充：这个 bug 只在特定的缩放比例下出现。

**Comment by Enter-tainer** [comment]
在 Windows Edge 94.0.992.38 上无法复现

**Comment by Enter-tainer** [comment]
woc 我复现了。。 https://oi-wiki.org/math/gen-func/ogf/#_7

Chrome 也可以

**Comment by YOYO-UIAT** [comment]
好像 loj 也有这个问题……

**Comment by EtaoinWu** [comment]
wikipedia也有这个问题。应当不是单项目的锅，浏览器的问题。

**Comment by alphagocc** [comment]
在 Windows 10 64 位系统 Chrome 94.0.4606.81 问题已经消失

**Comment by Enter-tainer** [comment]
是 Chrome 的 bug, https://bugs.chromium.org/p/chromium/issues/detail?id=1253952
