### ISSUE TITLE
Add VSCode settings for Contributors

### ISSUE THREAD

**Issue by ArielHeleneto** [OI-wiki/OI-wiki#3617]
### 我希望能添加的内容是

建议添加 '.vscode'  文件夹以帮助使用 VSCode 的用户配置他们的编写环境，比如本地测试，自动格式化等。

### 我了解到的相关参考资料有

参见 VSCode 相关帮助。

**Comment by ArielHeleneto** [comment]
@ArielHeleneto 建议添加在不同环境下配置 oi-wiki 编辑配置的指南

**Comment by renbaoshuo** [comment]
在 https://oi-wiki.org/intro/htc/ 页面中所述的 GitHub Web Editor 对于插件功能的支持并不完全，许多插件均无法安装，而且还没有命令行，所以 **我个人认为不太需要** 添加 `.vscode` 文件夹。
