### ISSUE TITLE
Fix / refactor request: 动态规划基础

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/OI-wiki#3656]
<https://oi-wiki.org/dp/basic/#_20>
- 最长回文子串
  - "代码在：..."
- 双调欧几里得旅行商问题
  - "upd：..."
- 整齐打印
  - "不知道这样可不可做"
- 编辑距离
  - 只有增加删除替换的模型
  - "复制、替换、删除、插入、旋转、终止" 的具体实现 / 转移方程

**Comment by StudyingFather** [comment]
@ksyx 都积压在 #2912 了🌚
