### ISSUE TITLE
[BUG] 搜索的一些问题

### ISSUE THREAD

**Issue by OldFishBall** [OI-wiki/OI-wiki#3664]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

当我在搜索栏中搜索`中国剩余定理`时，并没有跳出相关索引（但是wiki中的确有中国剩余定理的界面）。

![1](https://user-images.githubusercontent.com/61718487/141980554-282dcdc0-4db2-4159-b31b-2492f9022401.png)

后来以 `CRT` 为关键词搜索，出现一个没有任何文字的索引。

![2](https://user-images.githubusercontent.com/61718487/141980951-5809a1f2-c7f4-4a17-990b-fbaedd7143be.png)

另外，在搜索一些界面时，如果搜索关键词与界面标题相同，则在下面的索引中的此界面没有标题（只有小字正文一部分）

**Comment by OldFishBall** [comment]
（关于最后一句的补充）有的时候不一定要关键词相同，比如图1中的第四项（实际界面为`随机化技巧`）没有显示标题

**Comment by Ir1d** [comment]
@OldFishBall 收到，这周末会看一下

**Comment by Ir1d** [comment]
感谢反馈，问题已经定位并暂时修复（由于 Gitee 同步关闭而搜索服务器上没有拉取最新的跟新），周末会尝试进一步优化流程

**Comment by Ir1d** [comment]
> 另外，在搜索一些界面时，如果搜索关键词与界面标题相同，则在下面的索引中的此界面没有标题（只有小字正文一部分）

@OldFishBall 是说如果搜索的关键词是小标题，就不会在小字显示？比如搜 “随机化技巧”，出现的 “模拟”，是因为 模拟页面下有个 `技巧` 的小标题

![image](https://user-images.githubusercontent.com/10709657/147897620-56e5ae6d-09cc-4ed6-b4ab-f52f7a184c88.png)

**Comment by OldFishBall** [comment]
@Ir1d 

![image](https://user-images.githubusercontent.com/61718487/152295277-7f5b2d7c-d086-4bcd-be55-f83d67540486.png)

搜索 `概率dp` 所得，应出现的标题变成了这页内容的第一段，小字也有问题。

**Comment by Ir1d** [comment]
本页面涉及到的标题问题终于得到了修复，赞美 https://github.com/OI-wiki/elasticsearch-config/pull/2
