### ISSUE TITLE
[RFC] 处理无响应时间过长的 Pull Request

### ISSUE THREAD

**Issue by CoelacanthusHex** [OI-wiki/OI-wiki#3671]
如题，遍览本 Wiki 的 PR 列表，可以发现数个已半年无响应的 PR（三个月的就更多了），我认为我们应该适当地处理这些 PR，譬如关闭过长时间无响应的 PR，给过长时间无响应的 PR 打 tag 标记，给作者发邮件联系等。
本提案主要讨论以下几点问题：
1. 对多长时间无响应的 PR 进行处理？
2. 我们应该如何处理？是否要自动化？如何自动化？
3. 我们是否应当对时间分段处理？比如一个月自动发邮件，三个月关闭这样。
4. 我们是否需要一个特殊的标记用于标识那些作者明确说明了自己某段时间暂忙，将于某个时间后继续完成的 PR？
5. 其他我没有提到但是应当讨论的问题

**Comment by hly1204** [comment]
workflow 是不是可以自动化处理

**Comment by Enter-tainer** [comment]
https://github.com/actions/stale 看起来这个 action 可以自动化处理一些操作

**Comment by tsagaanbar** [comment]
可以把这些 PR 收集起来集中显示在一个页面吗？这样或许能够方便参考前人已有的贡献。

**Comment by CoelacanthusHex** [comment]
@tsagaanbar GitHub Project？

**Comment by tsagaanbar** [comment]
> @tsagaanbar GitHub Project？

去看了一下，好像是这个东西（我竟然还不知道这个东西是啥样的……

**Comment by chinesedfan** [comment]
> actions/stale 看起来这个 action 可以自动化处理一些操作

打label、关闭前提醒、自动关闭，都支持的。建议参考：https://github.com/axios/axios/blob/master/.github/workflows/stale.yml

> 可以把这些 PR 收集起来集中显示在一个页面吗？这样或许能够方便参考前人已有的贡献

Github issue本身在右侧有linked prs这个功能，只要pr的时候引用对应issue就行。参考：https://github.com/axios/axios/issues/2239

**Comment by CoelacanthusHex** [comment]
Okay, I will try to create a Pull Request.
Hope there will be more human to review it.
