### ISSUE TITLE
[功能请求] 如何让这个地服务器在小型局域网内被访问

### ISSUE THREAD

**Issue by YRL694560616** [OI-wiki/OI-wiki#3691]
### 我遇到的问题是

你好，我对于网络配置方面不太懂。我希望这个小型的服务器可以让局域网内的用户访问到。请问要如何操作呢？

### 我希望能有这样的解决方案

希望可以在小型的局域网内部署，直接通过IP+端口号（和现在一样访问 http://127.0.0.1:8000 可以查看效果，只不过IP从127.0.0.1换成局域网内的IP地址）

**Comment by diauweb** [comment]
请说明一下目前你使用的运行站点的方式

如果你使用的是 `mkdocs serve`，请添加 `-a ip地址:端口` 参数，并检查你使用的操作系统/发行版的防火墙有关设置。设置无误后即可向局域网开放访问站点

**Comment by YRL694560616** [comment]
> 请说明一下目前你使用的运行站点的方式
> 
> 如果你使用的是 `mkdocs serve`，请添加 `-a ip地址:端口` 参数，并检查你使用的操作系统/发行版的防火墙有关设置。设置无误后即可向局域网开放访问站点

谢谢，我关闭防火墙后可以实现局域网的访问了
