### ISSUE TITLE
tools/judger/index 不在目录中

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#3709]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://github.com/OI-wiki/OI-wiki/blob/master/docs/tools/judger/index.md

### 我发现页面有这样的问题

https://github.com/OI-wiki/OI-wiki/blob/master/docs/tools/judger/index.md 未在目录中

**Comment by CoelacanthusHex** [comment]
close via #3714 manually
