### ISSUE TITLE
[BUG] css 和 js 文件疑似丢失

### ISSUE THREAD

**Issue by xyf007** [OI-wiki/OI-wiki#3710]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

material-icons.css gitalk.css gitalk.min.js 全部 404 了，导致渲染出现问题。

**Comment by Ir1d** [comment]
Thank you @xyf007. We're working on an upgrade. Will be fixed in a couple of minutes.

**Comment by Ir1d** [comment]
@xyf007 感谢反馈！现在应该已经恢复了？麻烦有空帮忙 confirm 一下 :pray:

**Comment by xyf007** [comment]
我这里正常了。
