### ISSUE TITLE
[BUG] 再次搜索不到关键词

### ISSUE THREAD

**Issue by OldFishBall** [OI-wiki/OI-wiki#3736]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![微信截图_20220102150718](https://user-images.githubusercontent.com/61718487/147868832-34279a83-4a28-4852-8e66-2cebcbb2db79.png)

如图，搜索 `树的直径` 时无法搜索到界面，不知是否与 <https://github.com/OI-wiki/OI-wiki/issues/3664> 有关。

### 我确认这个问题可以这样复现

搜索 `树的直径`。

**Comment by Ir1d** [comment]
感谢反馈，依然是同步问题，似乎这回修复了，后续会继续跟进
