### ISSUE TITLE
Add 上海森堡矩阵

### ISSUE THREAD

**Issue by jujimeizuo** [OI-wiki/OI-wiki#3747]
### 页面英文名

upper Hessenberg matrix

### 我希望能添加的内容是

上海森堡矩阵

### 我了解到的相关参考资料有

- [【学习笔记】求矩阵的特征多项式](https://www.cnblogs.com/suncongbo/p/11163798.html)
- [求矩阵的特征多项式](https://blog.csdn.net/weixin_30576827/article/details/98088448)

**Comment by GitPinkRabbit** [comment]
再加一个 [另一种特征多项式算法 - EntropyIncreaser](https://www.cnblogs.com/Elegia/p/alternative_charpoly.html)

**Comment by GitPinkRabbit** [comment]
OI Wiki 里已经有了：https://oi-wiki.org/math/char-poly/#hessenberg

**Comment by jujimeizuo** [comment]
😯老花眼了我
