### ISSUE TITLE
[内容有误] 语言基础 - C++ 标准库 - STL 算法中对随机函数描述有误

### ISSUE THREAD

**Issue by HeRaNO** [OI-wiki/OI-wiki#3753]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/lang/csl/algorithm/

### 我发现页面有这样的问题

在这页关于 `random_shuffle` 的 Warning 中，提到：

> 在 C++11 以及更新的标准中，您可以使用 shuffle 函数代替原来的 random_shuffle。使用方法为 shuffle(v.begin(),v.end(),rand)（最后一个参数传入的是使用的随机数生成器，一般情况下传入 rand 即可）。

但无法通过编译（C++14），代码在[这里](https://ideone.com/sTVuHp)。

并且在[杂项 - 随机函数](https://oi-wiki.org/misc/random/)中已经介绍过了，内容有重复。

**Comment by tsagaanbar** [comment]
试了一下，好像确实有问题，换成 [`std::mt19937`](https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine) 就没问题了。

```cpp
#include <vector>
#include <random>
#include <algorithm>

int main(int argc, char const *argv[])
{
        std::mt19937 rand_gen;
        std::vector<int> v{1, 2, 3, 4, 5};
        std::shuffle(v.begin(), v.end(), rand_gen);
        return 0;
}
```

参考链接：[std::shuffle - cppreference.com](https://en.cppreference.com/w/cpp/algorithm/random_shuffle)
