### ISSUE TITLE
Add 添加Java进阶技巧页面

### ISSUE THREAD

**Issue by IceOfSummer** [OI-wiki/OI-wiki#3771]
### 页面英文名

java-advance

### 我希望能添加的内容是

**内容主要围绕一些常用类进行讲解, 预计主要包含如下内容**

1. 输入与输出优化
2. 高精度运算类介绍
3. Arrays工具类介绍
4. Set接口的部分实现类介绍
5. 正则表达式的使用
6. ...

由于本人之前都用java干后台开发，最近才开始刷题的。但最近在洛谷刷题的时候，看到大部分人的java代码都有巨大的优化空间(~大部分人的代码格式看的我强迫症都要犯了~)。最近我还收到了一个人的私信，说看不懂我的代码为什么几行就结束了，问了一下他，他是直接上手java，没有学过c++，基础很差，不知道在哪学这些高级一点的内容(毕竟大部分都是c++)。

希望自己能尽一些微薄之力吧

### 我了解到的相关参考资料有

*全是个人之前开发经验 + 刷题的总结*

**Comment by HuPeng333** [comment]
第一次加页面，是要自己创建新文件还是要怎么搞 (

**Comment by Enter-tainer** [comment]
> 第一次加页面，是要自己创建新文件还是要怎么搞 (

需要处理两个地方：

- 在 docs 文件夹下的合适层级新建一个md文件，在里面写内容
- 在 mkdocs.yml 里面添加你的新文件

**Comment by HuPeng333** [comment]
> > 第一次加页面，是要自己创建新文件还是要怎么搞 (
> 
> 需要处理两个地方：
> 
> * 在 docs 文件夹下的合适层级新建一个md文件，在里面写内容
> * 在 mkdocs.yml 里面添加你的新文件

好的

**Comment by Great-designer** [comment]
已经由#3984解决
