### ISSUE TITLE
Add Powershell教程

### ISSUE THREAD

**Issue by YuzhenQin** [OI-wiki/OI-wiki#3788]
### 页面英文名

powershell

### 我希望能添加的内容是

一些 powershell 的语法。  

Powershell 是跨平台的 shell，可用于 OI。

### 我了解到的相关参考资料有

[Powershell 文档](https://aka.ms/powershell)

**Comment by ksyx** [comment]
如果没记错的话 noilinux 上面也没 pwsh 吧（
