### ISSUE TITLE
[内容补充] 线性基

### ISSUE THREAD

**Issue by rsdbkhusky** [OI-wiki/OI-wiki#3836]
### 请选择：

- [x] 我正在着手修复这个问题

### 我正在访问这个页面

[https://oiwiki.org/math/basis/](https://oiwiki.org/math/basis/)

### 我发现页面有这样的问题

线性基内容过少，待补充

**Comment by Saisyc** [comment]
目前 [OI-Wiki 的线性基词条](https://oi-wiki.org/math/basis/) 内容可能导致部分读者无法正确理解“基”这一线性代数的重要概念（虽然理解此概念对于程序设计竞赛可能不是特别必需的）；值得一提的是，线性基中“各数二进制最高位不同”的要求是不必的，但是任何线性基确实可以“规范化”成该形式，且该形式在应用上具有明显的简洁性与便利性。此外，线性基中元素的数量是唯一的但线性基不唯一，这一重要结论可能会导致读者的困惑，也许应予以提及并加以解释。

**Comment by Great-designer** [comment]
内容转移至#4287
