### ISSUE TITLE
[BUG] 一些函数名和名词之类的东西

### ISSUE THREAD

**Issue by hly1204** [OI-wiki/OI-wiki#3848]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

看到一些 `push_down` 和 `push_up` 之类的函数 <https://oi-wiki.org/ds/seg/> ，但是 `push` 的反义词不是大概是 `pull` 之类的嘛。。。似乎不太合理。

“lowbit”这个命名我也只在中文资料 <https://oi-wiki.org/ds/fenwick/> 中看到，一般英文似乎都称呼为“least significant bit”之类的，这个是自造词吗？

对于多项式和形式幂级数的定义没有做好区分 <https://oi-wiki.org/math/poly/intro/> 。。

**Comment by Saisyc** [comment]
关于push_down与push_up的问题，[*Algorithms for Competitive Programming*](https://cp-algorithms.com/data_structures/segment_tree.html) 使用的术语是 push 与 push_back；对于 push 与 pull 的问题，信息的传输总是 push，改变的是 push 的方向（down 或者 up）；另外，在语义中，向左推和向右拉并不是完全一致的。

而对于 lowbit 的问题，不得不说，中文资料中有若干具有“中文文献特色”的术语，其中一个典例是国内绝大多数文献对于KMP算法中next数组的定义与国际通用的定义（即KMP原始文献中next数组的定义）完全不同；我认为这种现象是应当尽量避免的。因此，支持取缔 lowbit 的说法；且对于此问题，我更倾向于使用 builtin_popcount 等函数的相关名称指代最低有效位的问题，或直接对 least significant bit进行缩写。

而多项式和形式幂级数的定义没有做好区分等问题，可能是作者比较重视应用层面且数学学习水平不太充分导致的；个人认为，目前绝大多数OIer的对于实数和复数的认知水平应该不高于《工科数学分析》的中低难度内容（尤其是广大中小学生OIer）。
