### ISSUE TITLE
10000 Stars Celebration

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#3858]
> To celebrate that our project's stars will soon reach 10000.
> This issue will be closed in one week.

~~不是传统意义上的整数，不过考虑到意义不小，就手动发一条好了~~

为庆祝我们的 **OI Wiki** 项目 Stars 即将到达 10000，特开此 Issue，大家也放松下。

诸位维护本项目也都辛苦了，我刚刚看了下 Commits 也到达了 10492，大家在本 Issue 里面想说什么就说什么吧（But please don't spam in this issue）。

祝大家愉快。

***

非常感谢这么长时间以来大家的支持，我们再接再厉～

最后，祝大家身体健康，我们 16384 stars 时再见。

cc #739 #882 #1202 #2015 #3558

**Comment by TechCiel** [comment]
10492 🌿

**Comment by undefined-moe** [comment]
大佬们带带 awa

**Comment by Doveqise** [comment]
好似，开香槟咯

**Comment by renbaoshuo** [comment]
![image](https://user-images.githubusercontent.com/47095648/159203351-f97810b3-597b-4ab3-a8a4-7268f5d2a68a.png)

![image](https://user-images.githubusercontent.com/47095648/159203356-02fb105a-f8a1-4741-8138-dfea4623b441.png)

👀

**Comment by Ancker-0** [comment]
身体健康

**Comment by Diwanul** [comment]
祝贺！（话说16384是有啥特殊意义么

**Comment by renbaoshuo** [comment]
> 祝贺！（话说16384是有啥特殊意义么

2 的 14 次方是 16384。

**Comment by 99-woods** [comment]
恭喜恭喜！

**Comment by EarthMessenger** [comment]
好耶！祝早日 16384！
