### ISSUE TITLE
[内容有误] 希望能够更加科学地介绍一下模多项式

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#3894]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/poly/inv/

### 我发现页面有这样的问题

https://github.com/OI-wiki/OI-wiki/pull/3489

之前试着写过，但是无下文了，本人能力有限，无力维护，故删库跑路。

多项式的逆元是相对于模多项式而言的。即使是FFT操作，也是模一个$x^{2^n}-1$的多项式，即直接求点值倒数，得到的是模$x^{2^n}-1$的逆元。

希望能够更加科学地介绍一下模多项式。

**Comment by wangr-x** [comment]
在生成函数加入多项式环、形式幂级数环、形式洛朗级数环相关内容应该就完了

**Comment by Great-designer** [comment]
……关于此方面，我的水平最高也只能写成
https://github.com/OI-wiki/OI-wiki/pull/3489/files
这样……而且原仓库也已经删了。

有愿意接手这个，愿意以较为严谨地方式行文的（哪怕是抄课本），上述pr里的行文逻辑可以作为一个参考。

**Comment by wangr-x** [comment]
已接手

**Comment by wangr-x** [comment]
乘法逆不需要指定模哪个多项式，它是个无穷级数

**Comment by Great-designer** [comment]
> 乘法逆不需要指定模哪个多项式，它是个无穷级数

这个故事由学弟群友Saisyc指出是这样的：

https://github.com/Saisyc

定义乘法逆的时候，需要先指明乘法定义在什么集合上。

“逆是一个无穷级数”，这个叙述没有错，有前提条件，在“形式幂级数环”上是这样的。

多项式环本身没有乘法逆。只有1乘1得1。

旧pr讨论的是，计算机存储都是有限位的，不可能存下无穷级数。

存下前若干位，截断的操作，等价于mod x^n。这是常规操作。

如果用FFT点值取倒数，等价于mod x^n - 1。它和上一个完全不一样。

两个操作都等价于将无穷长的“形式幂级数环上的乘法逆”，对“特定的多项式”取模。只是“特定的多项式”不同。

无论怎样都是模多项式。这是旧pr想讲的内容。也就是说，必须要讲到“模多项式环”，不只是形式幂级数环这么简单。

因此可能的结论是，你的pr较为浅显，而且内容不太够。此方面我可能不如我的群友学弟Saisyc专业。更多评论可以请更专业的人写写。

**Comment by Saisyc** [comment]
> 乘法逆不需要指定模哪个多项式，它是个无穷级数

模 $x^n$ 的截断对于形式幂级数而言是自然且良定义的，但是 FFT 模 $x^n-1$ 对于形式幂级数而言是不自然且非良定义的；只讨论形式幂级数环的问题是非常不充分的。

**Comment by wangr-x** [comment]
> 无论怎样都是模多项式。这是旧pr想讲的内容。也就是说，必须要讲到“模多项式环”，不只是形式幂级数环这么简单。
推出多项式欧几里得后，模多项式环应当是显然的。  
只需要讨论多项式欧几里得及其适用范围即可。

**Comment by Saisyc** [comment]
> > 无论怎样都是模多项式。这是旧pr想讲的内容。也就是说，必须要讲到“模多项式环”，不只是形式幂级数环这么简单。
> 
> 推出多项式欧几里得后，模多项式环应当是显然的。 只需要讨论多项式欧几里得及其适用范围即可。

模多项式环绝不是显然的，因为模多项式并不是简单的截断；你可以思考一下1/(x-2)的形式幂级数形式如何模x^2-1

多项式环的商环与形式幂级数环的商环在实质上具有很大区别

**Comment by wangr-x** [comment]
> > > 无论怎样都是模多项式。这是旧pr想讲的内容。也就是说，必须要讲到“模多项式环”，不只是形式幂级数环这么简单。
> > 
> > 
> > 推出多项式欧几里得后，模多项式环应当是显然的。 只需要讨论多项式欧几里得及其适用范围即可。
> 
> 模多项式环绝不是显然的，因为模多项式并不是简单的截断；你可以思考一下1/(x-2)的形式幂级数形式如何模x^2-1
> 
> 多项式环的商环与形式幂级数环的商环在实质上具有很大区别

只需要将问题限制在普通多项式环而非形式幂级数环上即可。

OI 范围内不会涉及形式幂级数的带余除法

**Comment by xyf007** [comment]
讲道理正常 OI 选手不会去研究环一类的玩意（

**Comment by wangr-x** [comment]
而且形式幂级数环和多项式环上的带余除法有巨大区别，确实脱离了直观性

**Comment by Saisyc** [comment]
> > > > 无论怎样都是模多项式。这是旧pr想讲的内容。也就是说，必须要讲到“模多项式环”，不只是形式幂级数环这么简单。
> > > 
> > > 
> > > 推出多项式欧几里得后，模多项式环应当是显然的。 只需要讨论多项式欧几里得及其适用范围即可。
> > 
> > 
> > 模多项式环绝不是显然的，因为模多项式并不是简单的截断；你可以思考一下1/(x-2)的形式幂级数形式如何模x^2-1
> > 多项式环的商环与形式幂级数环的商环在实质上具有很大区别
> 
> 只需要将问题限制在普通多项式环而非形式幂级数环上即可。
> 
> OI 范围内不会涉及形式幂级数的带余除法

FFT显然就是模x^n-1下搞多项式，直接当成形式幂级数的欧几里得除法直接原地暴毙

**Comment by wangr-x** [comment]
> > > > > 无论怎样都是模多项式。这是旧pr想讲的内容。也就是说，必须要讲到“模多项式环”，不只是形式幂级数环这么简单。
> > > > 
> > > > 
> > > > 推出多项式欧几里得后，模多项式环应当是显然的。 只需要讨论多项式欧几里得及其适用范围即可。
> > > 
> > > 
> > > 模多项式环绝不是显然的，因为模多项式并不是简单的截断；你可以思考一下1/(x-2)的形式幂级数形式如何模x^2-1
> > > 多项式环的商环与形式幂级数环的商环在实质上具有很大区别
> > 
> > 
> > 只需要将问题限制在普通多项式环而非形式幂级数环上即可。
> > OI 范围内不会涉及形式幂级数的带余除法
> 
> FFT显然就是模x^n-1下搞多项式，直接当成形式幂级数的欧几里得除法直接原地暴毙

当成多项式环下的带余除法可以轻松解决，就是求解关于 $P(x),Q(x)$ 的不定方程

$$f(x)P(x)+(x^n-1)Q(x)=1$$

这一情况下，得出的逆元在 mod (x^n-1) 意义下具有唯一性

**Comment by wangr-x** [comment]
只要是普通的多项式而非无穷级数就没问题

**Comment by Saisyc** [comment]
> 推出

我建议还是尽量在多项式环下讨论模多项式商环的问题，而不是形式幂级数

**Comment by yzhx233666** [comment]
> 

可是确实没有啥正经OI选手学习环之类的吧

**Comment by wangr-x** [comment]
因为本人已经退役，本人的 pr 需要换个人接手

**Comment by Great-designer** [comment]
本人已经重新接盘。见

https://github.com/OI-wiki/OI-wiki/pull/3928

**Comment by Great-designer** [comment]
已经可以close了
