### ISSUE TITLE
[内容疑似有误] 快速幂词条的翻译

### ISSUE THREAD

**Issue by Saisyc** [OI-wiki/OI-wiki#3911]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/quick-pow/

### 我发现页面有这样的问题

https://oi-wiki.org/math/quick-pow/ 采用了 quick-pow 但是外文文献似乎一般称为 fast power algorithm 而非 quick

参考 en.wikipedia 算法竞赛中的快速幂算法实质上对应 exponentiation by squaring，而 binary exponentiation 似乎不是普遍称呼

**Comment by Great-designer** [comment]
这个要确认一下：真的是这样的吗？
在对应页面代码段与正文中未找到“quick power”或“fast power”，只在地址栏出现了。
如果确实存在翻译问题，只需重命名页面，并进行重定向即可。
