### ISSUE TITLE
[内容有误] 三分页面缺配图

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#3921]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/basic/binary/#_10

### 我发现页面有这样的问题

![image](https://user-images.githubusercontent.com/10709657/164134458-9ac8d2bb-2d1c-44f4-9b51-3173cca82326.png)

**Comment by yusancky** [comment]
@Ir1d 我在本周周末可能有时间帮忙补图，请问我需要怎么做？我已经阅读过了相关的文档。

**Comment by Ir1d** [comment]
@yusancky 辛苦！创建配图后上传到相关目录然后在文档中引用就好啦
