### ISSUE TITLE
[内容有误] Tarjan算法求LCA

### ISSUE THREAD

**Issue by ghost** [OI-wiki/OI-wiki#3927]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/graph/lca/#tarjan

### 我发现页面有这样的问题

![image](https://user-images.githubusercontent.com/101644612/164382596-0a661441-3445-4ebd-9160-37034e67b1c3.png)
根据参考文献，需要修改并查集的实现，才能得到$O(1)$的复杂度。并不是只要写带路径压缩的并查集就可以自动得到$O(1)$的复杂度。

**Comment by Cat-shao** [comment]
本人找到一个这个 [https://ljt12138.blog.uoj.ac/blog/4874](https://ljt12138.blog.uoj.ac/blog/4874) ，不知道有没有帮助。

**Comment by Great-designer** [comment]
作为#1567 的延续

**Comment by Cat-shao** [comment]
@Great-designer 求 lca 算法不是 tarjan 最早提出的。

**Comment by psz2007** [comment]
现在才看到这个，在 #4431 大概已经解决了，应该可以 close 了
