### ISSUE TITLE
[内容有误] 

### ISSUE THREAD

**Issue by Abruptrainlover** [OI-wiki/OI-wiki#3932]
### 请选择：

- [x] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/contest/resources/

### 我发现页面有这样的问题

[Legend-K 的数据结构与算法的笔记](http://www.legend-k.com/Algorithm/Algorithm.pdf) 存在错误

**Comment by HeRaNO** [comment]
Here is a backup from [Web Archive](http://web.archive.org/web/20180826111306/http://www.legend-k.com/Algorithm/Algorithm.pdf)
