### ISSUE TITLE
[BUG] BM 页面目录内公式应当考虑修改

### ISSUE THREAD

**Issue by alphagocc** [OI-wiki/OI-wiki#3936]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

如下图
![image](https://user-images.githubusercontent.com/28982331/165026573-0a096189-1637-4032-8349-5ac99bc74002.png)

**Comment by CoelacanthusHex** [comment]
但是答案就在 FAQ 中

**Comment by alphagocc** [comment]
~~经群友提醒后看到了，所以换了表述~~

**Comment by Tiphereth-A** [comment]
![w](https://github.com/OI-wiki/OI-wiki/assets/62847935/3e8b24ce-3b03-453b-a0af-1775f9f75d9a)

现在似乎能正常显示了，也许可以 close 了？
