### ISSUE TITLE
[BUG] 目录显示不正常

### ISSUE THREAD

**Issue by Cat-shao** [OI-wiki/OI-wiki#3944]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![image](https://user-images.githubusercontent.com/55950034/166082488-4b9c5156-cc66-4ee8-a37c-4bb85bb1d896.png)

以 https://oi-wiki.org/tools/wsl/#fnref:ref3 为例，标题上右上角的脚注 3 不应该出现在目录中。红圈标红的都是脚注的编号被渲染进目录中的。

### 我确认这个问题可以这样复现

打开 https://oi-wiki.org/tools/wsl/#fnref:ref3

**Comment by Cat-shao** [comment]
又发现一个：在标题处用 LaTex 会渲染错误：

![image](https://user-images.githubusercontent.com/55950034/166141911-8e568a19-936c-4ff5-83f8-eeee7619ab01.png)
https://oi-wiki.org/string/bm/#on3on3-delta_2delta_2

**Comment by xyf007** [comment]
看一下 F.A.Q. 就会发现里面讲到了后一个问题。

**Comment by Cat-shao** [comment]
@xyf007 确实，但是其中只提到了公式，没提到有关标题中上标也会进入标题。

希望开发者修复公式在目录中的 bug 的时候顺手把这个也修复了。

**Comment by Cat-shao** [comment]
这个问题已经有人提过了（#2916）
