### ISSUE TITLE
[内容补充] Sqrt Tree 就是 vEB 树吧

### ISSUE THREAD

**Issue by NFLSCode** [OI-wiki/OI-wiki#3960]
建议提一句

**Comment by NFLSCode** [comment]
[vEB Link](https://www.luogu.com.cn/blog/RuntimeErrror/ni-suo-fou-zhi-dao-di-shuo-ju-jie-gou-van-emde-boas-shu)

**Comment by Cat-shao** [comment]
@NFLSCode ？？？这都干的不是一个活，结构也不同。

**Comment by Marcythm** [comment]
这里讲的 sqrt tree 和 vEB 树是有相当显著的区别的。您是否是因为看到您所发的链接中 2.2 节提到的分块解法与 sqrt tree 本质相同，所以发了这个 issue 呢
