### ISSUE TITLE
[内容有误] 为什么会有Hulu啊

### ISSUE THREAD

**Issue by Deng-Duck** [OI-wiki/OI-wiki#3961]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/intro/hulu/

### 我发现页面有这样的问题

不知道与OI有何关联

**Comment by Deng-Duck** [comment]
本鸭回邮箱较慢，谢谢！

**Comment by Menci** [comment]
@Deng-Duck Hulu 是 OI Wiki 的赞助商，所以我们放了一个页面来介绍 Hulu 公司

**Comment by Deng-Duck** [comment]
@Menci 哦哦哦，没事了，还以为是有人恶意篡改的呢，能不能再页面说清楚啊

**Comment by Menci** [comment]
@Deng-Duck 诶，其实页面下面原来有写着 Sponsored by Hulu 的，现在怎么没了
