### ISSUE TITLE
[内容有误] 珂朵莉树代码含义不明

### ISSUE THREAD

**Issue by Jebearssica** [OI-wiki/OI-wiki#3981]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

http://oi-wiki.com/ds/odt/

### 我发现页面有这样的问题

* 函数 `split` 中的变量 `n` 并未注明含义
* 珂朵莉树的初始化没讲清楚, 如果 `split` 的值目前并不在树上会产生错误

**Comment by Jebearssica** [comment]
要是给我改的话，我想把整个 `split` 前半部分改成下面这种情况:

```c++
auto split(int x)
{
    auto iter = odt.lower_bound(Node_t(x, 0, 0));
    if(iter != odt.end() && iter->left == x)
        return iter;
    --iter;
    ......
}
```

**Comment by NFLSCode** [comment]
是`upper_bound`吧

**Comment by Jebearssica** [comment]
> 是`upper_bound`吧

`--upper_bound` 是最后一个 `lower_bound`, 是不是这样就能把所有重复的右边界都包括进去

**Comment by Jebearssica** [comment]
感觉主要思想并没有阐述很清楚，是因为竞赛里都会卡这个，所以没有学习的必要了吗。。。作为一个面向面试的学习者，遇到区间修改的时候写这个很明显比写树状数组或线段树要快很多的样子。。。

**Comment by Great-designer** [comment]
#4368
