### ISSUE TITLE
Add java进阶

### ISSUE THREAD

**Issue by 1804040636** [OI-wiki/OI-wiki#3982]
### 页面英文名

java advance

### 我希望能添加的内容是

想添加一些我认为可以在acm中使用到的一些自带的轮子和一些自己踩的坑
因为原本的java速成里面已经有关于快读的介绍了，那个快读已经封装的很好了，我打算介绍如下内容
1.常用数据结构 例如可变数组，双链表，双端队列，栈，优先队列等
2.Arrays与Collections
3.BigInteger 的使用与数论有关的知识
4.踩坑随笔

### 我了解到的相关参考资料有

https://zhuanlan.zhihu.com/p/476468424
我自己知乎正在更新的文章

**Comment by 1804040636** [comment]
是一个才开始学习的新人，很多内容都是看之前的回复在学习orz

**Comment by aofall** [comment]
#3984
