### ISSUE TITLE
[内容有误] Wilson 頁面

### ISSUE THREAD

**Issue by mudream4869** [OI-wiki/OI-wiki#3991]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/number-theory/wilson/

### 我发现页面有这样的问题

若 $3k + 7$ 是质数，则有 $(3k+7) \mid (3k+6)!$  => 若 $3k + 7$ 不是质数，则有 $(3k+7) \mid (3k+6)!$

**Comment by Saisyc** [comment]
个人认为应选择更有意义的例题，该例题明显是强行构造 Wilson 定理的使用形式
