### ISSUE TITLE
在 OJ 工具页面中添加 Codeforces Contest Helper v2 

### ISSUE THREAD

**Issue by ttzytt** [OI-wiki/OI-wiki#4005]
### 页面英文名

Codeforces Contest Helper v2

### 我希望能添加的内容是

OJ 工具这个[页面](https://oi-wiki.org/tools/oj-tool/)，建议添加一个 CCHv2（Codeforces Contest Helper v2），个人认为这个软件对于使用 CF 还是很有帮助的，主要的内容感觉可以直接把 tiger2005 写的博客搬运过来（不过肯定要简化一些，原文很长）。

### 我了解到的相关参考资料有

tiger2005 的博客：[https://www.luogu.com.cn/blog/tiger2005/codeforces-contest-helper-v2-qing-song-xie-jue-cf-bi-sai-xu-qiu](https://www.luogu.com.cn/blog/tiger2005/codeforces-contest-helper-v2-qing-song-xie-jue-cf-bi-sai-xu-qiu)

**Comment by CoelacanthusHex** [comment]
The author has archived this tool.

**Comment by Tiphereth-A** [comment]
因不满足 <https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E5%AE%A3%E4%BC%A0%E5%B7%A5%E5%85%B7> 中「在编程竞赛领域已经广为人知的网站或软件」而关闭
