### ISSUE TITLE
[内容有误] Eulerian number词条名与词条内容缺乏一致性

### ISSUE THREAD

**Issue by Saisyc** [OI-wiki/OI-wiki#4012]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/combinatorics/eulerian/

### 我发现页面有这样的问题

若“欧拉数”可作为Eulerian number的中文名，则应直接作为词条名；

否则，词条内容不应将其作为中文名。

**Comment by shuzhouliu** [comment]
> ### 请选择：
> * [ ]  我正在着手修复这个问题
> 
> ### 我正在访问这个页面
> https://oi-wiki.org/math/combinatorics/eulerian/
> 
> ### 我发现页面有这样的问题
> 一方面，词条中给出的中文名“欧拉数”可直接作为词条名而不必使用“Eulerian Number”；另一方面，“Eulerian Number”的"N"应小写。
> 
> 似乎词条编辑界面无法编辑词条名

在`mkdocs.yml`大概是可以改的（

**Comment by Great-designer** [comment]
题主可以去http://mathworld.wolfram.com/

查一下文章开头列出的“Euler numbers”和“Euler's number”都是些什么东西。（除本文外，至少还有“E_n”，自然对数底“e”，欧拉-马歇罗尼常熟“\gamma”等等）

北航的旧OJ4th（accoding.cn）（今年停用）的题目编号4271“不可思议的展开”（E5-2020级-航类第5次练习，2020级-航空航天大类-C语言程序设计，本题不公开）用到了“Euler number”（E_n，正切函数展开式的系数），与本文不同。因此组合数学里面至少还有“E_n”称为“Euler number”。组合数学里面有俩“欧拉数”，数学常数里面还有俩“欧拉数”，只看标题、缺乏上下文语境，完全不知道说的是啥。

我只能说，Euler是个筐，什么都能往里装。诸如“欧拉定理”有一堆，有复数的，有数论的，有平面几何的（三角形欧拉线相关），有拓扑的（多边形或多面体顶点、面、棱关系），有图论的（拓扑衍生，甚至图论还有另外的“欧拉回路”）。

所以，公认直接翻译成“欧拉数”是极为草率的，完全不知道在说什么（不知道说的是哪个“欧拉数”）。如果文章的标题是“欧拉数”，那么所有的“欧拉数”都要讲一遍。要是非把这俩只有名字相似而内容风马牛不相及的东西扔一块儿，又要和审核员们一起讨论半天，讨论两年过去估计也merge不了。（然后这时候题主都快大学毕业了：谁还老盯着OI-Wiki看呢？）

包括我在内，这里应该没有人有精力或者时间成本做这件事情。目前的解决办法是“Eulerian number”不翻译，这样没有歧义。

（另注：Leonhard Euler是瑞士人，在德国和法国工作过，会说德语和法语。由于后来他在俄国工作，失明后也最终死在俄国，所以也会俄语。由于没去过英语地区，他本人唯独不会英语。因此后来这堆英文名词也全都是后人推到他脑袋上的。）

**Comment by Great-designer** [comment]
本issue讨论转移至 #4062
