### ISSUE TITLE
[内容有误] 人名间的"连字符"应该使用 –

### ISSUE THREAD

**Issue by hly1204** [OI-wiki/OI-wiki#4013]
标题可能也不太对, 所以我用双引号括了, 这个大概是 en dash, 我们应该区分于 hyphen 等.

### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

对应页面

### 我发现页面有这样的问题

很抱歉我曾经也乱写了一些, 希望有机会可以修正这些错误.

**Comment by Tiphereth-A** [comment]
感觉这个应该加到格式手册里, 可以参照 <https://www.grammarly.com/blog/hyphens-and-dashes/>

**Comment by CoelacanthusHex** [comment]
cc @llh721113
