### ISSUE TITLE
Add 更详细的 GitHub 与 git 使用指南

### ISSUE THREAD

**Issue by Cubik65536** [OI-wiki/OI-wiki#4017]
### 我希望能添加的内容是

近期我发现有多个 Pull Request 没有在收到更改建议后，通过向请求拉取的分支 commit 来改正问题，而是直接开启了新分支进行更改。这样会导致一个 Pull Request 应该更改的内容被分布在了多个 Pull Request 中。所以我希望可以增加更详细的  GitHub/git 使用指南，这或许会让第一次参加开源项目的贡献者们更难上手，但这无疑可以优化整个社区的工作流程。

PS. 目前大部分类似的情况似乎都是因为贡献者参考了 [如何参与 - 在 GitHub 上编辑](https://oi-wiki.org/intro/htc/#github) 章节。这个章节的操作在仅进行一次更改的情况下并不会有任何问题，但是在需要多次 commit（例如根据 review 进行改进）的时候，由于 GitHub 并不会向 fork 已有的分支 commit，而是开一个新的分支，但实际上贡献者们需要直接更改自己的 fork 的相关分支，因此造成了问题。

**Comment by CoelacanthusHex** [comment]
事实上这些问题在 GitHub 的文档是有提到的，比如更新 PR 的问题：
> 在创建拉取请求后，您可以从主题分支推送提交，以将它们添加到现有的拉取请求。 这些提交将以时间顺序显示在您的拉取请求中，在 "Files changed"（更改的文件）选项卡中可以看到更改。
https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

所以可能只添加一个链接就够了

**Comment by Cubik65536** [comment]
> 事实上这些问题在 GitHub 的文档是有提到的，比如更新 PR 的问题：
> 
> > 在创建拉取请求后，您可以从主题分支推送提交，以将它们添加到现有的拉取请求。 这些提交将以时间顺序显示在您的拉取请求中，在 "Files changed"（更改的文件）选项卡中可以看到更改。
> > https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
> 
> 所以可能只添加一个链接就够了
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e3498776c2fc6e103c368b2e0a90aac9dbb53e742fc03c294b4c4073cc7e7bd0/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f6f70656e5f67726170682f6769746875622d6c6f676f2e706e67"><img alt="" height="14" src="/assets/cb-803/images/site/favicon.svg"> GitHub Docs**[关于拉取请求 - GitHub Docs](https://ghdocs-prod.azurewebsites.net/cn/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)**拉取请求可让您在 GitHub 上向他人告知您已经推送到仓库中分支的更改。 在拉取请求打开后，您可以与协作者讨论并审查潜在更改，在更改合并到基本分支之前添加跟进提交。

感觉可以，不过应该还是得稍微多加一些解释，因为新手应该很难马上理解什么是 `主题分支`，我目前正在准备写相关内容。

**Comment by Cubik65536** [comment]
提醒一下，我正在编写相关内容

**Comment by Cubik65536** [comment]
该内容已于 PR #4067 增加，且已被合并
