### ISSUE TITLE
[内容有误] 三分法的图示和示例错误

### ISSUE THREAD

**Issue by zclllyybb** [OI-wiki/OI-wiki#4039]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/basic/binary/#_10

### 我发现页面有这样的问题

在三分法的图示中，介绍了lmid和rmid分别位于最值同侧和异侧的情况，然而对于该算法而言，这属于实质上的同一种情形“lmid>rmid”。在三分法的试探中，这两种情况是**完全不可分的**，而非页面所述的

> 但为和上一分类保持一致性，舍去较远的点对应的区间（图中红色的区间）。

正确的三分每一步的调整应当区别于f(lmid)和f(rmid)的大小，而非如当前所属的错误方式。

另外，以下的代码也是不完整的。有待补充例题与完整代码。

**Comment by yusancky** [comment]
@zclllyybb 我将会修复这些问题。
