### ISSUE TITLE
建议合并“杂项”和“专题”目录

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4069]
### 请选择：

- [x] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/misc/

### 我发现页面有这样的问题

在“杂项简介”页面中指出，“这个板块主要介绍的是一些难以分类的算法及 OI 相关知识”，按照常理逻辑来讲，无法分入前面任何一个分类的内容，应当放入“杂项”分类。
然后后面出现了一个“专题”分类，该分类未加解释。这类似于在分类“其他”之后，又出现一些未分类内容一样。
是否考虑将“专题”分类的内容，全部并入“杂项”分类，从而减少一个目录项？这样操作之后，或者可以在“杂项简介”页面补充为：
“这个板块主要介绍的是一些难以分类的算法及 OI 相关知识，以及一些专题内容。”
或者不补充，因为我也没看明白“专题”分类的“专题”一词说的是什么含义。

**Comment by codewasp942** [comment]
一种分类方式： RMQ 专题和并查集专题放数据结构里，括号序放杂项或者字符串

**Comment by ouuan** [comment]
可以阅读一下 #420 和 #1751 中的讨论，杂项和专题也是 OI Wiki ![亘古以来的灵魂之问](https://user-images.githubusercontent.com/30581822/182102760-eb8d06b4-9421-4c97-8669-0c1406fbef6e.png) 了（

**Comment by ouuan** [comment]
哦，还有好多在 #1752 ，刚刚没搜出来

**Comment by Great-designer** [comment]
这个看来是挖到了祖坟的历史遗留问题……再吵下去没完了。建议搁置。
