### ISSUE TITLE
[内容待改善] 快速复数论变换词条 

### ISSUE THREAD

**Issue by Saisyc** [OI-wiki/OI-wiki#4074]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/poly/cntt/

### 我发现页面有这样的问题

[快速复数论变换词条](https://oi-wiki.org/math/poly/cntt/) 目前只给出了简介概述及常用参数，且表述有待改善。

**Comment by Great-designer** [comment]
正好把“快速数论变换”
https://oi-wiki.org/math/poly/ntt/
也一并改改吧。我看里面好多内容应该放到对应页面：
“离散傅里叶变换”这一段应该转移到“快速傅里叶变换”一文中，不应该出现在本文。在“快速傅里叶变换”一文中已经写了，可以考虑合并。可以考虑照猫画虎，写一段带公式的“数论变换”，把公式对照写正确。
“生成子群”这一段应该转移到“群论简介”子群这一段下面。
“原根”这一段应该转移到“原根”一文中。在“原根”一文中也已经指出原根是循环群的生成元，考虑到前文以群论方式引入而非数论方式引入，下文的“原根”疑用“生成元”一词较为合适。
（“转移”是指在本文中直接删掉这些段落，并在目标地址进行文本修改。）
删完这些部分之后，“快速数论变换”几乎啥都没写，云里雾里，甚至还不如“快速复数论变换”相对清楚一点儿。虽然我知道是怎么回事儿，但是我讲不出来。
我觉得前面这部分不该要，至多“需要前置知识xx、xx、xx”即可，后面这部分应当是重点，需要扩写并写清楚。行文方式可以仿照“快速复数论变换”一文。

**Comment by Great-designer** [comment]
> 正好把“快速数论变换” https://oi-wiki.org/math/poly/ntt/ 也一并改改吧。我看里面好多内容应该放到对应页面： “离散傅里叶变换”这一段应该转移到“快速傅里叶变换”一文中，不应该出现在本文。在“快速傅里叶变换”一文中已经写了，可以考虑合并。可以考虑照猫画虎，写一段带公式的“数论变换”，把公式对照写正确。 “生成子群”这一段应该转移到“群论简介”子群这一段下面。 “原根”这一段应该转移到“原根”一文中。在“原根”一文中也已经指出原根是循环群的生成元，考虑到前文以群论方式引入而非数论方式引入，下文的“原根”疑用“生成元”一词较为合适。 （“转移”是指在本文中直接删掉这些段落，并在目标地址进行文本修改。） 删完这些部分之后，“快速数论变换”几乎啥都没写，云里雾里，甚至还不如“快速复数论变换”相对清楚一点儿。虽然我知道是怎么回事儿，但是我讲不出来。 我觉得前面这部分不该要，至多“需要前置知识xx、xx、xx”即可，后面这部分应当是重点，需要扩写并写清楚。行文方式可以仿照“快速复数论变换”一文。
> 
> > <img alt="" width="48" src="../../../favicon.ico">**[快速数论变换 - OI Wiki](https://oi-wiki.org/math/poly/ntt/)**OI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛

尤其是应该区分一下“数论变换”（NTT）和“快速数论变换”（FNTT）两个概念。现在OI选手通行的“NTT”叙述，事实上一律指的是“FNTT”而不是“NTT”本身，所以，这里应该为两节详细介绍，做好区分概念。

**Comment by Great-designer** [comment]
施工也是一步一个脚印地来。如果觉得较难的后文部分不知道写的是什么，很可能在前文就没有写好。把前文写好了，后文的内容可能会变得显而易见。

**Comment by Saisyc** [comment]
@Great-designer 其实我认为 NTT, CNTT 就应该都放在 FFT 词条中，一般环上的 DFT, FFT 与复数域上的实在没什么区别，可考虑将 $\mathbb{C}, \mathbb{Z}_p, \mathbb{Z}_p[\operatorname{i}]$ 视为特例的具体实现。

**Comment by Great-designer** [comment]
> @Great-designer 其实我认为 NTT, CNTT 就应该都放在 FFT 词条中，一般环上的 DFT, FFT 与复数域上的实在没什么区别，可考虑将 C,Zp,Zp[i] 视为特例的具体实现。

我感觉FT、DFT和FFT应该是一个页面，NTT、FNTT应该是一个页面，CNTT、FCNTT应该是一个页面。如果说，把后两者NTT、FNTT、CNTT、FCNTT放到一个页面，也完全可以，因为都与离散的数论相关，一脉相承。而后两者和“FT、DFT和FFT”差距还真是比较大。

**Comment by Great-designer** [comment]
> > > @Great-designer 其实我认为 NTT, CNTT 就应该都放在 FFT 词条中，一般环上的 DFT, FFT 与复数域上的实在没什么区别，可考虑将 C,Zp,Zp[i] 视为特例的具体实现。
> > 
> > 
> > 我感觉FT、DFT和FFT应该是一个页面，NTT、FNTT应该是一个页面，CNTT、FCNTT应该是一个页面。如果说，把后两者NTT、FNTT、CNTT、FCNTT放到一个页面，也完全可以，因为都与离散的数论相关，一脉相承。而后两者和“FT、DFT和FFT”差距还真是比较大。
> 
> 支持将 FT 与其分离，但 NTT 与 CNTT 就是 DFT, FFT 在不同整环上的表现；而算法竞赛似乎不常见运用(连续)傅里叶变换与傅里叶级数的内容

……是这样的。OI的很多知识，建立在“空中楼阁”之上，下面本来应该是很厚的坚实的地基，在这里却相当松垮，导致简单的内容特别水，复杂的内容看不懂。

我毕竟已经本科毕业。就本科的知识与视角而言，“微积分”或者“数学分析”部分OI基本上不涉及，高中数学物理导数、展开、级数等等，基本上是够用，考虑到“微积分”没什么门槛，中学生自学的也特别多，OI Wiki不写也罢。“概率论与数理统计”部分在大学用的特别多，OI涉及的不多，OI Wiki上写的特别入门与简单，不够深入，看看就行了。

“高等代数”分为“线性代数”和“多项式代数”，从分类上讲，真正的代数学从“抽象代数”或者“近世代数”开始，而“高等代数”其实仍旧属于“初等代数”的范畴，只是这部分扔到大学讲，而“多项式代数”由于偏简单，像“微积分”一样看不到门槛，中学生可以较为轻松地自学，所以OI Wiki上写“多项式代数”相对来讲，目前比较完备。

顶尖的OI人可能来到清华大学这样较为综合的院校，但要考虑到至少有半数OI人会来到工程类院校。对于“傅里叶变换”问题，在工程类院校，其实正统的“傅里叶变换”会和“拉普拉斯变换”一起，出现在“复变函数与积分变换”这门课当中，作为“信号处理”或者“电磁场”的基础；即使算法中的“离散傅里叶变换”，也会作为图像处理领域的“频谱分析”的基础。我们讲述“傅里叶变换”，一定要讲述正统的“傅里叶变换”是从哪里来的，历史上为什么会有“傅里叶变换”这个东西，而不是光讲讲“离散傅里叶变换”在“多项式代数”领域起到的重要作用。讲它在代数领域的作用很重要、很必要，不可或缺，但是不够。

Wiki这个词来源于夏威夷语的公交车，体现了知识的共享性。一个Wiki设立的初衷就是打破知识壁垒，让知识作为自由的存在而呈现给读者，所以讲一讲历史由来，让逻辑推理顺畅，让知识建构成体系，可以体现这样的自由度。

最烂的地方应该属于“线性代数”领域。对于中学生而言变量与符号偏多，体系偏向抽象，“线性代数”本身学起来就比较困难。这个不止OI Wiki写得不怎么样，全国的学生都在痛斥各版“线性代数”课本，同济版“线性代数”弊病颇多、害人匪浅。仅仅一个“先讲矩阵还是先讲行列式还是先讲线性空间”的问题，能够在各大高校讨论区天天吵、年年吵、随时随地都能吵。我看不管先讲哪儿，最后的结局都是：问题讲不明白、讲不透彻，只能靠学生自己“顿悟”。OI Wiki上也这样，不成体系，于是读一遍，会的还是会，不会的还是不会，一点儿用没有。

也难怪。Wiki往往是知识呈现，而不是教程。“线性代数”领域属于完全不成体系，东一榔头西一棒槌。题主强调“不想追溯知识的根源与联系”，指出“不该写傅里叶变换与傅里叶级数”，估计看“线性代数”部分也会这样，读一遍，会的还是会，不会的还是不会。

总之，无论是否支持，作为知识的呈现，里面已经写好了。如果愿意，也可以去试着改革上文列出的问题，试着通过建构文本的力量，实现通俗化、严谨化，而不是幼儿园化或者装逼化。

**Comment by Saisyc** [comment]
还是说直接把没啥用的 CNTT 直接给挫骨扬灰比较好？

**Comment by Great-designer** [comment]
> 还是说直接把没啥用的 CNTT 直接给挫骨扬灰比较好？
> 
> （但是Stern-Brocot tree似乎也没有太多的应用，不合适的类比）

你别这么没自信嘛。实在不行的话，等过一阵儿我试着写写？把FNTT和FCNTT看能不能合一块儿
这都拓展思维的好东西。数学家狂喜。研究计算机科学肯定也需要这类拓展思维的玩意儿
（虽然我还是更想写线性代数来着）

**Comment by Great-designer** [comment]
已经看过了“快速复数论变换”的相关提交记录，主要集中在11月10日的各种提交记录中：
https://www.luogu.com.cn/record/list?pid=P3803&user=saisyc&status=12&page=4&orderBy=0
事实证明，它只能说明可行性，可以AC，但是确实比NTT要慢。
因此这个页面我也不知道该怎么改。很可能还是NTT更加实用一些。
