### ISSUE TITLE
建议将“杂项-计算理论基础”移动至“算法”分类的最后一篇

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4075]
### 请选择：

- [x] #4160

### 我正在访问这个页面

https://oi-wiki.org/misc/cc-basic/

### 我发现页面有这样的问题

我在该文下方也给予了评论：
同样是“基础”，感觉这个适合放在“算法基础”栏目下的最后一节或者该栏目下很靠后的分节，这样就和“复杂度”呼应了。并且，本文末尾的P和NP问题，也恰好是算法理论领域的皇冠明珠问题。
之前也是我的提议，将“复杂度”移动至了分类的第一篇。

**Comment by ouuan** [comment]
这个页面的内容本来就很多和 OI 没啥关系，“算法基础”更应该理解为“基础算法”而不是“算法的基础”

**Comment by ouuan** [comment]
> 本章主要介绍一些基础算法，为之后的进阶内容做铺垫。
>
> 一方面，这些内容可以让初学者对 OI 的一些思想有初步的认识；另一方面，本章介绍的大部分算法还会在以后的进阶内容中得到运用。

**Comment by Great-designer** [comment]
> 计算理论基础这个页面的内容本来就很多和 OI 没啥关系，“算法基础”更应该理解为“基础算法”而不是“算法的基础”

……文本一旦写出来，去理解它的就变成了读者，而不是作者了。1000个人心中会有1000个Hamlet。
至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。

**Comment by ouuan** [comment]
> 至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。

可这是 OI，事实就是知道的人是少数，我相信几乎没有人刚学 OI 就学了这些内容。复杂度页面都被吐槽对初学者不友好了..我觉得支持把这个页面删掉的人都会比支持把这个页面放到算法基础的人多。

**Comment by Great-designer** [comment]
> > 至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。
> 
> 可这是 OI，事实就是知道的人是少数，我相信几乎没有人刚学 OI 就学了这些内容。复杂度页面都被吐槽对初学者不友好了..我觉得支持把这个页面删掉的人都会比支持把这个页面放到算法基础的人多。

这句就完全是在胡说八道了！学算法不学复杂度？（捂脸表情）……
考虑一下这样的场景：一位OIer终于突破了重·重·考·验，走进了清华大学的面试现场。清华的面试官随口一问：
“你知道主定理的内容吗？”
或者一问：
“你说这个排序算法复杂度是O(n^2)，大O是什么意思？你看我输入一个1、2、3，进入程序自动就出来了，怎么就O(n^2)了？”
这位OIer由于没有看过OI Wiki的“算法”目录下的《复杂度》页面，对基础不重视，导致挥泪悔恨终生，这怎么办？

**Comment by Great-designer** [comment]
> > 至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。
> 
> 可这是 OI，事实就是知道的人是少数，我相信几乎没有人刚学 OI 就学了这些内容。复杂度页面都被吐槽对初学者不友好了..我觉得支持把这个页面删掉的人都会比支持把这个页面放到算法基础的人多。
> 
> > ……文本一旦写出来，去理解它的就变成了读者，而不是作者了。1000个人心中会有1000个Hamlet。
> 
> 这句我是完全没看懂你想论证什么，愿意的话你可以解释一下

你理解为“基础算法”，我读的就是理解为“算法的基础”，在这种理解上，人是没有资格随意指导其他人的。

**Comment by codewasp942** [comment]
> > > 至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。
> > 
> > 
> > 可这是 OI，事实就是知道的人是少数，我相信几乎没有人刚学 OI 就学了这些内容。复杂度页面都被吐槽对初学者不友好了..我觉得支持把这个页面删掉的人都会比支持把这个页面放到算法基础的人多。
> 
> 这句就完全是在胡说八道了！学算法不学复杂度？（捂脸表情）…… 考虑一下这样的场景：一位OIer终于突破了重·重·考·验，走进了清华大学的面试现场。清华的面试官随口一问： “你知道主定理的内容吗？” 或者一问： “你说这个排序算法复杂度是O(n^2)，大O是什么意思？你看我输入一个1、2、3，进入程序自动就出来了，怎么就O(n^2)了？” 这位OIer由于没有看过OI Wiki的“算法”目录下的《复杂度》页面，对基础不重视，导致挥泪悔恨终生，这怎么办？

emmm都去thu了为什么这玩意没学过？

**Comment by Great-designer** [comment]
> > > > 至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。
> > > 
> > > 
> > > 可这是 OI，事实就是知道的人是少数，我相信几乎没有人刚学 OI 就学了这些内容。复杂度页面都被吐槽对初学者不友好了..我觉得支持把这个页面删掉的人都会比支持把这个页面放到算法基础的人多。
> > 
> > 
> > 这句就完全是在胡说八道了！学算法不学复杂度？（捂脸表情）…… 考虑一下这样的场景：一位OIer终于突破了重·重·考·验，走进了清华大学的面试现场。清华的面试官随口一问： “你知道主定理的内容吗？” 或者一问： “你说这个排序算法复杂度是O(n^2)，大O是什么意思？你看我输入一个1、2、3，进入程序自动就出来了，怎么就O(n^2)了？” 这位OIer由于没有看过OI Wiki的“算法”目录下的《复杂度》页面，对基础不重视，导致挥泪悔恨终生，这怎么办？
> 
> emmm都去thu了为什么这玩意没学过？

真的有，这不要不信。thu问得很细，而且很擅长提问或者环境氛围上给面试者心理施加压力，存在不少即使原本会也变得说不上来的情形。

**Comment by ouuan** [comment]
> 你理解为“基础算法”，我读的就是理解为“算法的基础”，在这种理解上，人是没有资格随意指导其他人的。

这个是板块划分规范，什么指导啊.. https://oi-wiki.org/basic/ 就是在说明这个板块收录的是什么，如果你觉得这个名字很容易理解错误可以再开 issue 讨论是否要改名，如果你觉得板块划分有问题需要改成算法的基础也可以讨论，但事实就是现在这个板块的收录范围是“基础算法”。

**Comment by ouuan** [comment]
> 真的有，这不要不信。thu问得很细，而且很擅长提问或者环境氛围上给面试者心理施加压力，存在不少即使原本会也变得说不上来的情形。

计算理论基础这个页面是我写的，我在 THU 营的自我介绍提到了我了解过计算理论基础，所以也被现场问了，可这和这个 issue 半点关系没有啊..

**Comment by Great-designer** [comment]
> > 真的有，这不要不信。thu问得很细，而且很擅长提问或者环境氛围上给面试者心理施加压力，存在不少即使原本会也变得说不上来的情形。
> 
> 计算理论基础这个页面是我写的，我在 THU 营的自我介绍提到了我了解过计算理论基础，所以也被现场问了，可这和这个 issue 半点关系没有啊..

那要膜拜一下

**Comment by ouuan** [comment]
> 我建议是不要吵了。不管怎样，晚上我开个pr。这就是举手之劳的事情

这不是太麻烦懒得搞的问题，是我觉得不应该改

**Comment by ouuan** [comment]
BTW，quote reply 请 quote 你 reply 的部分，而不是整个 comment

**Comment by Great-designer** [comment]
> > 我建议是不要吵了。不管怎样，晚上我开个pr。这就是举手之劳的事情
> 
> 这不是太麻烦懒得搞的问题，是我觉得不应该改

到pull request里面讨论好了

**Comment by Great-designer** [comment]
> BTW，quote reply 请 quote 你 reply 的部分，而不是整个 comment

这也没有资格指导别人怎么 quote ……不吵了，大家冷静一下

**Comment by ouuan** [comment]
> 这也没有资格指导别人怎么 quote

我说很多句，你 quote 整个评论，回复一个“这句”，然后我就会不知道你说的是哪句。你可以这样做只是我会不理解你。我收回我的“指导”，并为我的祈使语气致歉...

**Comment by Menci** [comment]
鉴于 OI 中几乎不会用到计算理论（最接近计算理论的知识点是各种自动机，而且学习计算理论对学习自动机在 OI 中的用法并不是必须的），所以我建议把计算理论基础放在杂项内，不要移动。

**Comment by ouuan** [comment]
> 到pull request里面讨论好了

这个修改又没有需要讨论怎样修改的细节，在 PR 里讨论并没有什么好处，只不过是换一个地方讨论，并且你需要多“举手之劳”一次而已

**Comment by Menci** [comment]
> > 计算理论基础这个页面的内容本来就很多和 OI 没啥关系，“算法基础”更应该理解为“基础算法”而不是“算法的基础”
> 
> ……文本一旦写出来，去理解它的就变成了读者，而不是作者了。1000个人心中会有1000个Hamlet。 至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。

我认为计算理论并不是【OI 中所用到的算法】的基础，即使将其理解为【学习算法的基础】，计算理论也不需要包含在内。

**Comment by Great-designer** [comment]
行罢。我总结一下：
即使在《算法基础简介》页面，也是在说：
“本章主要介绍一些基础算法，为之后的进阶内容做铺垫。”
还是把“算法”和“基础”俩词颠来倒去，变成一个语言学辩经问题，没有改变读者理解方法问题的实质。

现在正方和反方都有了。
正方的立论是，这本来就是属于算法的内容。
反方的立论是，新手不友好。

**Comment by Great-designer** [comment]
> > > 计算理论基础这个页面的内容本来就很多和 OI 没啥关系，“算法基础”更应该理解为“基础算法”而不是“算法的基础”
> > 
> > 
> > ……文本一旦写出来，去理解它的就变成了读者，而不是作者了。1000个人心中会有1000个Hamlet。 至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。
> 
> 我认为计算理论并不是【OI 中所用到的算法】的基础，即使将其理解为【学习算法的基础】，计算理论也不需要包含在内。

这“你认为”也不能说明什么。在北航的算法课上，无论是计算机学院还是软件学院，都会讲《计算理论基础》页面的内容，甚至位置不靠后，涉及内容还挺充实的。至少说明，这部分确实属于《算法》。

**Comment by ouuan** [comment]
> 事实已经证明了，在北航的算法课上，无论是计算机学院还是软件学院，都会讲《计算理论基础》页面的内容，甚至位置不靠后，涉及内容还挺充实的。至少说明，这部分确实属于《算法》。

这是 OI Wiki，如果你觉得课怎么上可以作为论据，那就更应该以 OI 课程而非大学课程为例。

**Comment by Menci** [comment]
> > > > 计算理论基础这个页面的内容本来就很多和 OI 没啥关系，“算法基础”更应该理解为“基础算法”而不是“算法的基础”
> > > 
> > > 
> > > ……文本一旦写出来，去理解它的就变成了读者，而不是作者了。1000个人心中会有1000个Hamlet。 至少在大学的《算法》课程上确实会讲“计算理论基础”页面的内容。
> > 
> > 
> > 我认为计算理论并不是【OI 中所用到的算法】的基础，即使将其理解为【学习算法的基础】，计算理论也不需要包含在内。
> 
> 这“你认为”也不能说明什么。在北航的算法课上，无论是计算机学院还是软件学院，都会讲《计算理论基础》页面的内容，甚至位置不靠后，涉及内容还挺充实的。至少说明，这部分确实属于《算法》。

这里是 **OI Wiki**，我认为你举**大学算法课**的例子并不能证明这些知识**在 OI 中**的地位。

**Comment by ouuan** [comment]
另外，复杂度页面的结尾 link 到了计算理论基础，想要深入了解的读者完全可以顺着 link 去阅读。

**Comment by Great-designer** [comment]
知识终究还是按照体系的建构逐步往前走的，OIer也不可能永远停留在当前的位置，在OIer的前方也是各种各样的出路。
也像此处的论题，后面也连接着信息论，连接着AI，最终连接着很多璀璨的终极问题。
人终究还是要有一些遨游广袤星辰的远大理想。即使按照“以人为本”的理念，移动了也不是错误。

**Comment by Great-designer** [comment]
越拖在这里吵，越没有时间去写pull request，这是无意义的。（捂脸）……
我去试着先写再说。

**Comment by Menci** [comment]
这里是 OI Wiki，为了便于**以参加算法竞赛为目**的读者进行学习，我们把范围局限在竞赛的需求上。

如果您希望能有一个不受限于竞赛知识体系的知识站，您可以自行建立一个《Algorithm Wiki》。

**Comment by Great-designer** [comment]
显见这里还是反方暂时占了上风……

**Comment by ouuan** [comment]
> 知识终究还是按照体系的建构逐步往前走的，OIer也不可能永远停留在当前的位置，在OIer的前方也是各种各样的出路。
> 也像此处的论题，后面也连接着信息论，连接着AI，最终连接着很多璀璨的终极问题。
> 人终究还是要有一些遨游广袤星辰的远大理想。即使按照“以人为本”的理念，移动了也不是错误。

先不说收录范围的事，就算是“以人为本”，先学其它内容再学计算理论基础对未来发展有什么危害吗？这段话如果是反驳把这一页面删除还算是有点道理。

**Comment by Great-designer** [comment]
以后的经验是，不要在issue下面吵架，会完全得不到支持

**Comment by Marcythm** [comment]
> 你理解为“基础算法”，我读的就是理解为“算法的基础”，在这种理解上，人是没有资格随意指导其他人的。

那么修改一下原标题使其表意明确会比吵这些有用多了，您觉得呢？

**Comment by Great-designer** [comment]
还有，因为已经是member，以后这种很小的、我能随手就改了的，也不用再发这么多issue。现在已经证明了，发issue基本没有用。
至于pull request能不能通过，也都是至少两个人的意见，不可能由一个人说了算。

**Comment by Great-designer** [comment]
我看了看，我大概错在指出“在这种理解上，人是没有资格随意指导其他人的”，
还有“没有资格指导别人怎么quote”，
还有“‘你认为’不能说明什么”，
可能这些表述确实或多或少涉及了对于对方的人身评价，导致对方可能感到不适，于是就不容易得到支持。这样不好。
还是列事实比较好。我以后也尽可能避免发表这样的评论。
