### ISSUE TITLE
建议整合“坐标系”页面

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4094]
故事是这样的：
我正在看“线性代数”这部分的混乱结构。“向量”属于“线性代数”，这当然没有错。然后尴尬地发现：作为最为基础的“坐标系”知识点，目前的介绍很是分散与混乱。
“坐标与坐标系”正式定义最早出现于初中二年级，甚至小学五年级课本中也会提到模糊的概念，然后它贯穿了初高中乃至本科的知识点，在高中又定义一遍，在本科又定义两遍：在线性代数和多元微积分与场论的部分全都用到了。因此，应当把“坐标与坐标系”单独出来。

- 目前它的情形是：
它分散在各个页面中。它出现在：
“线性代数”分类下“向量”一文的末尾：“极坐标与极坐标系”一节。
“计算几何”分类下“三维计算几何基础”一文，“极坐标”一节：混杂了“空间柱坐标系”和“空间球坐标系”两个不同的概念。
“计算几何”分类下“极坐标系”一文：和“向量”一文的末尾形成重复。
作为数学的共识性知识，其他地方也普遍用到，不应当单独列在“计算几何”分类下。
这个时候不该看着所谓的数学课纲如何，因为知识体系的构建是客观的。现在所谓的“极坐标”属于选修部分，属于历史原因，不能带着“选修”的偏见看问题。
- 它应当位于的位置是：
在“数学”分类下，从上往下数，“符号”的下面，“复数”的上面。这是因为，“复数”也用到了坐标系。
在这里澄清一个误区：“复数”和“向量”是两套完全不同的概念，“复数”本身是一个整体，“复数”和“向量”事实上没有任何关联，至多说形成某种同构。从数学的角度讲，局限于向量的思维理解复数其实较为有害。如果说同构的话，“复数”与主对角线元素相同的实数二阶反对称阵同构。历史上Gauss的博士毕业论文总结整理了前人所有关于复数的研究，他在文中表示复数的办法，用的就是这种特殊的实数二阶反对称阵。所以，“复数”和“向量”没有任何关联。
然后，“复数”的表示当然离不开坐标系，这是毋庸置疑的。
即使是一维的数轴，也可以看作某种坐标系。
- 它应当包含的内容是：
初中至本科，五种常用坐标系的介绍：平面直角坐标系、平面极坐标系、空间直角坐标系、空间柱坐标系、空间球坐标系，以及点的相应坐标表示，这几个坐标系之间的坐标转换。
由于“向量”一文的末尾讲到了“角度制与弧度制”，为了介绍其他坐标系，这两种度量也应当位于本文的开头，作为独立的分节出现。即，本文应当包含“角的度量”、“五种坐标系”、“坐标转换”几节内容。
- 它不应当包含的内容是：
向量与向量的运算。因此，直线、平面乃至曲线、曲面的坐标表示、坐标转换，可以出现在计算几何的“二三维计算几何基础”部分。
对于线性坐标系之间的坐标变换，属于“线性代数”的内容，不应该在本文。

**Comment by Great-designer** [comment]
顺便，“数学”分类的前几个页面，按照逻辑顺序，也应该重新排排序。
如果本提议能通过，前几个页面的顺序应当是：

- 进位制。“数的表示”是整个计算机领域与数学联系的基础，在数学也是基础中的基础。计算机中，数是用二进制表示的。位运算等必然放在进位制后面。
- 平衡三进制、高精度计算、位运算、快速幂。这几个页面与进位制直接相关。平衡三进制是一种特殊的进制体系，高精度计算是加减乘除，快速幂计算幂，用到二进制的特殊性质（其实其他进制也可以，只是可能不够快）。由于快速幂用到位运算，位运算应当排在快速幂前面。位运算放在最前面也可以，平衡三进制放在最后也可以。
这部分可行的顺序有：
平衡三进制-高精度计算-位运算-快速幂
平衡三进制-位运算-高精度计算-快速幂
位运算-平衡三进制-高精度计算-快速幂
位运算-高精度计算-快速幂-平衡三进制
高精度计算-位运算-快速幂-平衡三进制
- 坐标系。如上讨论。
- 复数。如上讨论。
- 其他。

**Comment by Saisyc** [comment]
> 顺便，“数学”分类的前几个页面，按照逻辑顺序，也应该重新排排序。 如果本提议能通过，前几个页面的顺序应当是：
> 
> * 进位制。“数的表示”是整个计算机领域与数学联系的基础，在数学也是基础中的基础。计算机中，数是用二进制表示的。位运算等必然放在进位制后面。
> * 平衡三进制、高精度计算、位运算、快速幂。这几个页面与进位制直接相关。平衡三进制是一种特殊的进制体系，高精度计算是加减乘除，快速幂计算幂，用到二进制的特殊性质（其实其他进制也可以，只是可能不够快）。由于快速幂用到位运算，位运算应当排在快速幂前面。位运算放在最前面也可以，平衡三进制放在最后也可以。
>   这部分可行的顺序有：
>   平衡三进制-高精度计算-位运算-快速幂
>   平衡三进制-位运算-高精度计算-快速幂
>   位运算-平衡三进制-高精度计算-快速幂
>   位运算-高精度计算-快速幂-平衡三进制
>   高精度计算-位运算-快速幂-平衡三进制
> * 坐标系。如上讨论。
> * 复数。如上讨论。
> * 其他。

快速幂算法的英文为 exponentiating by squaring，本身并不依赖于进制表示

**Comment by Great-designer** [comment]
> > 顺便，“数学”分类的前几个页面，按照逻辑顺序，也应该重新排排序。 如果本提议能通过，前几个页面的顺序应当是：
> > 
> > * 进位制。“数的表示”是整个计算机领域与数学联系的基础，在数学也是基础中的基础。计算机中，数是用二进制表示的。位运算等必然放在进位制后面。
> > * 平衡三进制、高精度计算、位运算、快速幂。这几个页面与进位制直接相关。平衡三进制是一种特殊的进制体系，高精度计算是加减乘除，快速幂计算幂，用到二进制的特殊性质（其实其他进制也可以，只是可能不够快）。由于快速幂用到位运算，位运算应当排在快速幂前面。位运算放在最前面也可以，平衡三进制放在最后也可以。
> >   这部分可行的顺序有：
> >   平衡三进制-高精度计算-位运算-快速幂
> >   平衡三进制-位运算-高精度计算-快速幂
> >   位运算-平衡三进制-高精度计算-快速幂
> >   位运算-高精度计算-快速幂-平衡三进制
> >   高精度计算-位运算-快速幂-平衡三进制
> > * 坐标系。如上讨论。
> > * 复数。如上讨论。
> > * 其他。
> 
> 快速幂算法的英文为 exponentiating by squaring，本身并不依赖于进制表示

是的。它是计算“幂”的算法，事实上也有“快速乘”，并且，它可以不依赖于二进制，比如三进制也可以。计算机借助二进制进行数据表示，二进制相对简单，借助位运算的快速幂算法可以方便程序书写。

**Comment by Great-designer** [comment]
看了半天感觉Issues注定不可能达到“114”这个数字了吧（无端联想）

**Comment by Great-designer** [comment]
已经开工，搬运一下施工计划：（可能会edit）
——线性代数外——
- 坐标系（coordinate，包含弧度制）
摘自三篇文章，“线性代数”分类下“向量”一文（移动内容），“计算几何”分类下“三维计算几何基础”一文（移动内容），“极坐标系”一文（全文删简）。
数学部分开头调序，进位制-位运算-平衡三进制-高精度计算-快速幂-坐标系-复数。
——线性代数里，新建一个文件夹——
- 简介
- 向量
- 内积与外积（product，外积只需要二阶和三阶行列式，可以作为特例单独定义）
- 矩阵（介绍矩阵之前必须介绍向量内积，不然很难理解矩阵乘法。应用部分似乎应该是“矩阵乘法的应用”）
- 行列式（determinant，用到初等行变换）
- 高斯消元（作为纯粹算法的呈现，用到初等行变换）
……其他
欢迎内容上的公理化重构。我这可能只会改改架构，顺便补点我了解到的由于地区不同（西方或者其他中文地区，例如部分西方地区用字母“\tau”表示二倍圆周率（弧度制部分），中国台湾地区对于“行”和“列”的翻译恰好与中国大陆地区相反），以及数学物理学科不同的翻译不同（例如向量/矢量、内积/标积/点乘（俗称）、外积/矢积/叉乘（俗称）、特征/本征、酉/幺正），计算机距离数学更近一些，OI Wiki正文当然遵从数学学科的翻译。

注：行列式这篇估计暂时写不了，我会先空出来，可能要让其他人写了

**Comment by Great-designer** [comment]
这个issue最初的计划已经搞定了。
