### ISSUE TITLE
Add 行列式

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4126]
### 页面英文名

determinant

### 我希望能添加的内容是

行列式的三种等价定义：
全排列法定义：需要用到群论中“置换”、“逆序数”、“奇偶排列”的概念。
按行/列展开法递归/归纳定义：需要介绍余子式和代数余子式。
代数性质法定义：满足某些代数性质的唯一运算是行列式——我记不真切了，好像是恰好对应三种初等行/列变换来着。
把上面这堆讲清楚就已经不容易了，至于等价性证明啥的不是重点，写不写都无所谓。

### 我了解到的相关参考资料有

这还需要什么资料吗？
在所有的线性代数书上，行列式都是用一章来讲的。目前这里好像只在高斯消元一文讲了三次方量级的算法，实际上还是在运用三种初等行变换。

**Comment by Great-designer** [comment]
ps：要在文章开头写清楚：
“行列式是方阵的一种运算。”
因此要先介绍方阵，再介绍行列式。如果像同济版线代那样第一章就行列式，第二章矩阵的话，那就直接寄罢。

**Comment by Great-designer** [comment]
> ps：要在文章开头写清楚： “行列式是方阵的一种运算。” 因此要先介绍方阵，再介绍行列式。如果像同济版线代那样第一章就行列式，第二章矩阵的话，那就直接寄罢。

啊，不好意思，我的意思是可以像同济版线代那样写，但是位置应该放在矩阵之后。这里只是玩笑式举个例子。

**Comment by Saisyc** [comment]
代数性质法定义：满足某些代数性质的唯一运算是行列式——我记不真切了，好像是恰好对应三种初等行/列变换来着。

你大概说的是 **$n$ 元反对称线性型**；此外，`三种初等变换` 在实质上只有两种， switching 可通过 multiplication 与 addition 实现，我觉得这也是值得一提的。

**Comment by Great-designer** [comment]
> ```
> 代数性质法定义：满足某些代数性质的唯一运算是行列式——我记不真切了，好像是恰好对应三种初等行/列变换来着。
> ```
> 
> 你大概说的是 **n 元反对称线性型**；此外，`三种初等变换` 在实质上只有两种， switching 可通过 multiplication 与 addition 实现，我觉得这也是值得一提的。

这也可以考虑写写。

**Comment by Great-designer** [comment]
如pull request #4150
确实没写行列式。如果是我要想写这个，可能需要等开学后翻课本……
先挂一个help wanted作为暂时的现状。

**Comment by Great-designer** [comment]
行列式在写，预计下周前上线
