### ISSUE TITLE
[功能请求] 规范化英文翻译的大小写

### ISSUE THREAD

**Issue by Saisyc** [OI-wiki/OI-wiki#4133]
较多页面中的英文翻译存在滥用大写的问题，希望能较为自动的将滥用大写的英文翻译进行规范化。

**Comment by Saisyc** [comment]
希望能实现较为自动的规范化英文翻译，而不是需要 #4134 一样进行手动的大量修改

**Comment by Saisyc** [comment]
但是滥用大小写似乎不会造成什么危害？

**Comment by Saisyc** [comment]
> 希望能实现较为自动规范化英文翻译的大小写，而不是需要 #4134 一样进行手动的大量修改

如果不方便自动化的化，那就靠大家一起 PR 慢慢修改吧~

**Comment by Saisyc** [comment]
好消息~
#4134 已合并~

**Comment by Great-designer** [comment]
这个叙述过于宽泛，工程量太大，题主也说意义不太大的样子。
我看原本做了点工作，开着的两个pull request也关掉了……略显可惜吧。

**Comment by Konano** [comment]
如何定义「滥用」和「标准」？
