### ISSUE TITLE
[功能请求] 规范化渐进分析

### ISSUE THREAD

**Issue by Saisyc** [OI-wiki/OI-wiki#4135]
### 我遇到的问题是

部分词条中，$\Theta$ 与 $\mathrm{O}$ 的混用较为严重，不会造成错误但是使得结论显得不够准确；对于 OIer 而言，区分 $\Theta$ 与 $\mathrm{O}$ 有一定的意义。

如：

1. 冒泡排序的时间复杂度为 $\mathrm{O} \left( n^2 \right)$，最优时间复杂度为 $\Theta \left( n \right)$，平均复杂度为 $\Theta \left( n^2 \right)$，最坏时间复杂度为 $\Theta \left( n^2 \right)$；
2. 快速排序的时间复杂度为 $\mathrm{O} \left( n^2 \right)$，平均时间复杂度为 $\Theta \left( n \log n \right)$，归并排序的时间复杂度为 $\Theta \left( n \log n \right)$。

**Comment by Marcythm** [comment]
嗯...可否展开讲述一下这对 OIer 的意义是什么

**Comment by Saisyc** [comment]
> 嗯...可否展开讲述一下这对 OIer 的意义是什么

主要是在某些教程中，$\mathrm{O}$ 提及的界是不紧的，甚至是很松的；这可能会导致 OIer 在“暴力乱搞”时错误的估计自身的复杂度，甚至以为本应能通过的算法是不能通过的。

举个不恰当的例子，`std::vector` 的 `push_back` 是 $\mathrm{O} \left( n \right)$ 的，但执行 $n$ 次一共是 $\Theta \left( n \right)$ 的；尽管很少遇到知道 `push_back` 是 $\mathrm{O} \left( n \right)$ 而不知道是均摊 $\Theta \left( 1 \right)$ 的 OIer，但只使用 $\mathrm{O}$ 分析确实存在一定风险。

**Comment by Saisyc** [comment]
> 嗯...可否展开讲述一下这对 OIer 的意义是什么

总的来说我觉得意义不大，但是对于简单算法，在作者有条件的情况下，区分 $\Theta$ 与 $\mathrm{O}$ 是对读者更好的。

**Comment by Saisyc** [comment]
> 

@Marcythm #4113 的给出的复杂度 $\mathrm{O} \left( \sqrt{n} \right)$ 可能存在这样的问题；根据我目前检索的资料，这个界可能是非常松的（严格的界可能是 $\mathrm{O} \left( \log n \right)$），但是我不太熟悉 STL 相关的复杂度的准确分析。

**Comment by CoelacanthusHex** [comment]
分析 STL 复杂度还会有一个问题，就是很多 STL 里的东西复杂度是实现相关的

**Comment by Menci** [comment]
@CoelacanthusHex OI 统一按 libstdc++ 吧，如果 libc++ 有差异就列出来（我印象里没有）其他的不用考虑

**Comment by Saisyc** [comment]
> 分析 STL 复杂度还会有一个问题，就是很多 STL 里的东西复杂度是实现相关的

但是感觉 `verctor` 的 `push_back` 这种单次 $\mathrm{O} \left( n \right)$ 均摊 $\Theta \left( 1 \right)$ 貌似是确定的？

**Comment by Saisyc** [comment]
> @CoelacanthusHex OI 统一按 libstdc++ 吧，如果 libc++ 有差异就列出来（我印象里没有）其他的不用考虑

因为 STL 对于许多 OIer 而言是只使用而不研究与证明的，所以我觉得 STL 有关复杂度的分析应当比较精准才好，这样方便大家拿着 STL 乱搞 AC 题目（逃

**Comment by littlefrogfromthenorth** [comment]
> > 分析 STL 复杂度还会有一个问题，就是很多 STL 里的东西复杂度是实现相关的
> 
> 但是感觉 `verctor` 的 `push_back` 这种单次 O(n) 均摊 Θ(1) 貌似是确定的？
> 
> 我主要是觉得 #4113 的 O(n) 有些奇奇怪怪的，并且作者没有给出任何参考文献或证明~

emm....... 现在经过查证, rope 的时间复杂度主要是由内部的可持久化平衡树提供的, 那就应该按照可持久化平衡树的 $O(log n)$ 来界定

**Comment by Saisyc** [comment]
> > > 分析 STL 复杂度还会有一个问题，就是很多 STL 里的东西复杂度是实现相关的
> > 
> > 
> > 但是感觉 `verctor` 的 `push_back` 这种单次 O(n) 均摊 Θ(1) 貌似是确定的？
> > 我主要是觉得 #4113 的 O(n) 有些奇奇怪怪的，并且作者没有给出任何参考文献或证明~
> 
> emm....... 现在经过查证, rope 的时间复杂度主要是由内部的可持久化平衡树提供的, 那就应该按照可持久化平衡树的 O(logn) 来界定

好耶 ヽ(✿ﾟ▽ﾟ)ノ

**Comment by Great-designer** [comment]
看了看，这个Issue没有什么必要……
大O记号用于讨论“小于等于”，等价于在数学证明中，只需证明“可行性”就行了。而大\Theta记号是严格等于，用于数学证明其实意义不大……
（一点小小的偏见，总是把界限卡得非常之严，却又无其必要性，有时候属于证明题做得半吊子水平）

**Comment by Marcythm** [comment]
> 看了看，这个Issue没有什么必要……
> 大O记号用于讨论“小于等于”，等价于在数学证明中，只需证明“可行性”就行了。而大\Theta记号是严格等于，用于数学证明其实意义不大……
我不认同用所谓“没有必要”来作为拒绝一个 proposal 的理由：任何一件事情都有其“必要”的角度，也有其“没有必要”的角度。况且您自己也承认了它有意义，只是“意义不大”。如果能在些微细节上能够做到严谨，我认为这是一个正向的改动；况且我以为这所增加的阅读负担也并不大（或许您不这么认为？期待您的看法）。

（抱歉我刚刚点 quote 的时候错选了 edit...在手机上操作完了才发现这一点。我会尝试在网页端复原这个评论。）

**Comment by Marcythm** [comment]
> 而且，一些算法难以计算精确的时间复杂度。（不是不能计算，而是精确计算很困难。）
> 精益求精固然好，能做到当然可以做到，只是会很大地提升成本，最终还是要尽可能在成本与效果之间达成平衡。

你说得对，这两点都很对；但是把能做好（并且需要付出的代价不大）的部分做好，有何不可呢？大家讨论的时候好像经常陷入一个误区：似乎对于某件事情只有“做到尽善尽美”和“完全不做”两个选项；这是不对的。

**Comment by Marcythm** [comment]
噢抱歉，我没有结合原本的 issue 内容理解你的讨论；确实这是一个如你所说的 trade-off，这没有问题。请仅将以上的评论当做我的个人观点来看待。

**Comment by ouuan** [comment]
感觉，要具体问题具体分析，但总的来说还是以 $O$ 为主比较好，要加 $\Theta$ 的时候可以每处分别讨论，能加的时候不排斥。关于这个在复杂度页面也有提到（也是我写的）：

![image](https://user-images.githubusercontent.com/30581822/182353424-efb6e0db-005c-4c25-8b80-1ee026adec77.png)

**Comment by Great-designer** [comment]
并且 $O$ 实际上也是来源于 $\Omicron$ ，甚至由于拉丁字母与希腊字母的字形一致，LaTeX不支持采用相关的语法书写这个希腊字母。从这个角度看，“电脑输入方便”似乎很难作为理由。
