### ISSUE TITLE
[内容有误] 冒泡排序词条上下文可能矛盾

### ISSUE THREAD

**Issue by Saisyc** [OI-wiki/OI-wiki#4138]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/basic/bubble-sort/

### 我发现页面有这样的问题

```
经过 i 次扫描后，数列的末尾  项必然是最大的 i 项，因此冒泡排序最多需要扫描 n-1 遍数组就能完成排序。
```

认为只需冒泡不超过 $n - 1$ 轮就能 **完成** 排序。

```cpp
// C++ Version
// 假设数组的大小是n+1，冒泡排序从数组下标1开始
void bubble_sort(int *a, int n) {
  bool flag = true;
  while (flag) {
    flag = false;
    for (int i = 1; i < n; ++i) {
      if (a[i] > a[i + 1]) {
        flag = true;
        int t = a[i];
        a[i] = a[i + 1];
        a[i + 1] = t;
      }
    }
  }
}
```

对于某些数据 `while` 循环需要执行 $n$ 轮才能 **结束** 排序，但在执行第 $n - 1$ 轮后就数组已经有序。

**Comment by Saisyc** [comment]
初学者可能误认为所给代码中的 `while` 循环至多执行 $n - 1$ 轮。

**Comment by Saisyc** [comment]
执行 $n$ 轮的例子：

0. 原数组 `2,3,1`；
1. 第 $1$ 轮冒泡后 `2,1,3`，冒泡次数为 $1$，继续执行；
2. 第 $2$ 轮冒泡后 `1,2,3`，冒泡次数为 $1$，继续执行；
3. 第 $3$ 轮冒泡后 `1,2,3`，冒泡次数为 $0$，结束排序。

**Comment by Great-designer** [comment]
首先，这个过于基础，不是重点，没有人打比赛会使用冒泡排序；
其次，也没看懂Issue发起者在说什么。
综上，这不是一个需要改动的问题。
