### ISSUE TITLE
显示bug:链接点不进去

### ISSUE THREAD

**Issue by shleodai** [OI-wiki/OI-wiki#414]
在窗口大小为80%时, 界面是这样的
![image](https://user-images.githubusercontent.com/42714804/45303652-de7ff280-b548-11e8-9c76-d22ebafe2898.png)
一切正常.
但是当窗口大小为100%时, 会发生问题

![image](https://user-images.githubusercontent.com/42714804/45303743-171fcc00-b549-11e8-8d6a-145139093072.png)
像这种链接无法点进去

![image](https://user-images.githubusercontent.com/42714804/45303822-43d3e380-b549-11e8-9a09-2cac1d4efcd4.png)

**浏览器版本:Google Chrome 版本 69.0.3497.81（正式版本） （32 位）**

**Comment by Ir1d** [comment]
@shleodai 谢谢反馈，麻烦你去看看 https://ctf-wiki.github.io/ctf-wiki/ 里面有没有这样的显示问题？

如果那边也有这个问题，建议你去 [mkdocs-material](https://github.com/squidfunk/mkdocs-material) 开一个 issue 反馈。

如果没有，按 f12 开 console 看看有没有报错啥的，然后 ctrl+f5 刷新试试问题是不是还在

**Comment by shleodai** [comment]
@Ir1d ctf-wiki那边也有这个问题... 
但是mkdocs官方没有 https://squidfunk.github.io/mkdocs-material/

**Comment by shleodai** [comment]
有2个报错: 

```
Uncaught ReferenceError: base_url is not defined
    at main.js:93
api.github.com/user:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
```
但是我看不懂是什么意思
顺便说一下, 我开了F12链接就能打开了....真是匪夷所思

**Comment by Ir1d** [comment]
@shleodai ctrl+f5 刷新试试？

第一个报错好像什么时候修过了，第二个是因为你没有登录 Github，GItment 访问 API 的时候会返回 401

开 f12 之后可以打开应该是因为改变了页面布局
