### ISSUE TITLE
[内容有误] 群论简介词条疑似存在主观内容

### ISSUE THREAD

**Issue by Saisyc** [OI-wiki/OI-wiki#4146]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/group-theory/

### 我发现页面有这样的问题

`置换群是第一类被系统性研究的群` 中的 **“第一类”** 疑似缺乏可靠信息来源（该内容是由 #3493 @isdanni 添加的）。

**Comment by MegaOwIer** [comment]
这个论断可能来自 [Wikipedia](https://en.wikipedia.org/wiki/Group_theory#Permutation_groups)

> The first class of groups to undergo a systematic study was permutation groups.

**Comment by Saisyc** [comment]
> 这个论断可能来自 [Wikipedia](https://en.wikipedia.org/wiki/Group_theory#Permutation_groups)
> 
> > The first class of groups to undergo a systematic study was permutation groups.

确实如此，不过涉及“第一类被研究”之类的历史性的东西，可能还是粘上参考来源比较好；

毕竟中文文献捏造历史的先例并不少见。

**Comment by Great-designer** [comment]
究竟是不是第一类，过于细节，科学史与学习的知识点关系不大。
况且，有人给出了可能的来源。
这不是需要改动的问题。
