### ISSUE TITLE
[REFORM or REVERT] 关于改革或回退的讨论

### ISSUE THREAD

**Issue by Saisyc** [OI-wiki/OI-wiki#4148]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

# 部分[**管理员**](https://github.com/Marcythm)在PR中评论**已贡献的创作者**`不亲自上手做任何建设性的工作`（[#4092](https://github.com/OI-wiki/OI-wiki/pull/4092)）

部分通过审核的词条存在**明显**且**严重**的错误（包括但不限于[#3811](https://github.com/OI-wiki/OI-wiki/pull/3811)与[#4015](https://github.com/OI-wiki/OI-wiki/pull/4015)已修复的内容）

部分通过审核的词条**明显**违反[格式手册](https://oi-wiki.org/intro/format/)（包括但不限于[群论简介](https://oi-wiki.org/math/group-theory/)中的$Z_m$）

部分**修改笔误**的简单PR**数周**未被通过（包括但不限于[#4063](https://github.com/OI-wiki/OI-wiki/pull/4063)）

对于修改**抖机灵**无关内容的PR在通过审核后被关闭（包括但不限于[#3875](https://github.com/OI-wiki/OI-wiki/pull/3875)）

### REFORM

**错误词条**对初学者**极度有害**，也使其他词条失去可信度

**捏造事实**攻击创作者的部分管理员对社区风气**极度有害**

### REVERT

**整顿管理团队，规范词条审核**

整顿完成前请将**愿意退出者**（**包括但不限于**[@Saisyc](https://github.com/Saisyc)）已更改的词条**回退**

# 整顿完成前请将[Saisyc](https://github.com/Saisyc)已更改的词条**回退**

**Comment by alphagocc** [comment]
Not Saisyc-Wiki

**Comment by ChungZH** [comment]
建议 @Saisyc 将 @Saisyc 改过的内容变回原样。

**Comment by undefined-moe** [comment]
觉得现在的管理员比较烂可以自己 fork 自己部署。
觉得内容烂可以不看。
没有心情管可以不管。

但无论如何，请不要干涉其他 contributor 正常产出内容。

**Comment by Marcythm** [comment]
我承认，我当时跟您道歉的时候说您“确实做出过建设性贡献”是为了安抚您的情绪，我不该这么做。
现在我实话实说：您提交过的几个 pr 不但 non-constructive，甚至是 destructive 的。通过审核才是管理团队更大的失职。

**Comment by llh721113** [comment]
快请您坐到写checker的位置上来

**Comment by Marcythm** [comment]
关于其它的内容：
1. 好教您知道，格式手册是在 wiki 发展了相当长一段时间后才出现的东西，对在这之前添加的不符合格式手册的词条开炮没有任何实际意义，不如自己开 pr 修。打嘴炮谁不会呢？
2. #4063 的例子原因为何我不知道，看起来似乎确实应当被合并。或许你可以尝试再次向管理员请求合并。有其他的例子吗？
3. 关于 #3875 的事情，我不知道别人的看法如何，但我的看法是有一些东西应当保留。或许被 approve 以后相当长的时间里都没有人来真的动手合并这个 pr 也说明了这点？
4. 已经通过审核的词条存在错误，很好，没问题。那你倒是开 pr 修啊？😓

**Comment by Konano** [comment]
#3875 已经 reopen 并 merge。
