### ISSUE TITLE
[完善] 高维前缀和 SOSDP

### ISSUE THREAD

**Issue by ChungZH** [OI-wiki/OI-wiki#4151]
### 我希望能添加的内容是

目前 wiki 介绍[高维前缀和](https://oi-wiki.org/basic/prefix-sum/#dp)部分过于简略，很难用于入门学习。

### 我了解到的相关参考资料有

https://codeforces.com/blog/entry/45223

**Comment by hhc0001** [comment]
还有一个问题，它似乎忘记了逐维前缀和

**Comment by hhc0001** [comment]
但由于不可抗力，我没法 pr 了（
