### ISSUE TITLE
建议合并概率论目录下“快速上手”和“基本概念”页面

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4153]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/expectation/

### 我发现页面有这样的问题

“快速上手”页面不在文件夹内，其命名“expectation”也是有些问题的。
其他的分类下用于介绍与入门的页面基本上都只是一个，到概率论这里变成两个，有些不太合适。

**Comment by MegaOwIer** [comment]
本来是打算这样的，当初是考虑到可能导致的外链失效问题就采取了现在这样的中间方案，然后 #3903 在 review 的时候好像也没有对此深入讨论，就成了现在这样（）

**Comment by Enter-tainer** [comment]
外链失效的问题可以通过添加重定向来解决（见根目录下面的 _redirect 文件）。

如果需要这两个页面的话，可以考虑再开pr（（

**Comment by MegaOwIer** [comment]
啊原来这样......

那我过两天再开个pr搞一下，顺便再加点新内容（？

**Comment by Great-designer** [comment]
目前不知道这个issue进度如何了……按理来说只是合并+重定向的话难度应该不太高

**Comment by MegaOwIer** [comment]
页面合并+重定向是早就搞完了。
本来想再加点概率不等式估计相关的新东西（就 Chernoff Bound 之类的），然后写完草稿发现我用的那个参考书在学校没拿回家，然后校对工作就暂时搁置了（）
