### ISSUE TITLE
[BUG] 评论区 LaTeX 公式无法正常渲染

### ISSUE THREAD

**Issue by littlefrogfromthenorth** [OI-wiki/OI-wiki#4163]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [x] 我正在着手修复这个问题

### 我遇到了这样的问题

![image](https://user-images.githubusercontent.com/49180735/182288553-53b6f4b8-c076-4cec-9620-d01408741200.png)

评论区 LaTeX 公式无法正常渲染

### 我确认这个问题可以这样复现

在 OI Wiki 评论区, 很多页面都有:

例如: https://oiwiki.org/math/number-theory/gcd/

**Comment by littlefrogfromthenorth** [comment]
貌似是由于 gitment 只有 Markdown, 没有 LaTeX 支持

**Comment by Great-designer** [comment]
挂有“内容无关的bug”看起来都不是能够轻松解决的问题，很多是某些无法左右的外界属性的锅，例如这个的锅很明显属于GitHub

**Comment by littlefrogfromthenorth** [comment]
还真不是，是gitment的锅


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月2日(周二) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OI-wiki/OI-wiki] [BUG] 评论区 LaTeX 公式无法正常渲染 (Issue #4163)




 
挂有“内容无关的bug”看起来都不是能够轻松解决的问题，很多是某些无法左右的外界属性的锅，例如这个的锅很明显属于GitHub
 
&mdash;

**Comment by littlefrogfromthenorth** [comment]
文章中的公式是服务端渲染，前端只负责换个字体加个css效果啥的，把文章里tex代码转换成html的是脚本

gitment的评论是动态的，想要服务端渲染也不太好做到（也不可能每次新建评论都更新一下静态html页面吧），我正在想办法搞个katex上去，然后在页面上动态渲染


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月2日(周二) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OI-wiki/OI-wiki] [BUG] 评论区 LaTeX 公式无法正常渲染 (Issue #4163)




 
挂有“内容无关的bug”看起来都不是能够轻松解决的问题，很多是某些无法左右的外界属性的锅，例如这个的锅很明显属于GitHub
 
&mdash;

**Comment by littlefrogfromthenorth** [comment]
稍等，我发个pr


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月2日(周二) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OI-wiki/OI-wiki] [BUG] 评论区 LaTeX 公式无法正常渲染 (Issue #4163)




 
挂有“内容无关的bug”看起来都不是能够轻松解决的问题，很多是某些无法左右的外界属性的锅，例如这个的锅很明显属于GitHub
 
&mdash;

**Comment by ouuan** [comment]
感觉换成 Giscus 比较好，Gitalk 的问题也不止 LaTeX

**Comment by littlefrogfromthenorth** [comment]
新版oi-wiki就不完全是gitment了（虽然也有这个问题）


---原始邮件---
发件人: &quot;Yufan ***@***.***&gt;
发送时间: 2022年8月2日(周二) 晚上7:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OI-wiki/OI-wiki] [BUG] 评论区 LaTeX 公式无法正常渲染 (Issue #4163)




 
感觉换成 Giscus 比较好，Gitalk 的问题也不止 LaTeX
 
&mdash;

**Comment by ouuan** [comment]
> 新版oi-wiki就不完全是gitment了（虽然也有这个问题）

用 ng 作理由咕两年我先不评论，只不过要么继续咕着要么干脆换了嘛，感觉手动给 Gitalk 加个 katex 有点脏..而且换掉 Gitalk 又不只是 LaTeX 一个原因。

**Comment by ouuan** [comment]
哦，ng 也是评论不是 Discussions 的话，还真不好换成 Giscus

**Comment by littlefrogfromthenorth** [comment]
不过的确该改改了


---原始邮件---
发件人: &quot;Yufan ***@***.***&gt;
发送时间: 2022年8月2日(周二) 晚上7:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OI-wiki/OI-wiki] [BUG] 评论区 LaTeX 公式无法正常渲染 (Issue #4163)




 
哦，ng 也是评论不是 Discussions 的话，还真不好换成 Giscus
 
&mdash;

**Comment by Enter-tainer** [comment]
see RFC #4169

**Comment by ouuan** [comment]
已切换至 giscus
