### ISSUE TITLE
[RFC] 更换评论框架为 giscus

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/OI-wiki#4169]
目前，我们使用的评论框架是 gitment。该框架目前已经停止维护，且存在各种问题。例如权限要求不合理，不支持数学公式等等。

因此考虑将框架切换为目前流行的 giscus。唯一可能需要注意的地方是，切换为giscus后将无法继续使用基于issue的评论系统。

群内聊天记录如下：

mgt:
giscus接入主站好搞吗🤔

要不换换

ouuan:
好搞啊

就是会 break 几分钟

要 convert to discussions

而且没法换回来

虽然看起来只有好处，但考虑到没法换回来，可以再征求一下大家同意（

**Comment by ouuan** [comment]
Gitalk 索取了过多的权限（每个评论者的所有 public repo 的读写权限），且必须由管理员手动给新页面开评论区。

[Giscus](https://giscus.app) 基于 GitHub Discussions，有包括但不限于下列优点：

1.	需要用户授权少
2.  每个用户都可以开新评论区
3.  可以给页面点 reactions，也可以给评论点 reactions
4.  可以有楼中楼
5.  可以折叠评论
6.  用户可以设定正序/倒序显示
7.  支持暗色模式
8.  支持 LaTeX 显示

**Comment by ouuan** [comment]
好像有一个问题，不知道怎么显示“我们鼓励在讨论区讨论有意义的内容及关于文章的勘误，无意义的讨论将会被管理员删除”

**Comment by ouuan** [comment]
还 fork 吗（真的要这句话吗，一定要显示在 placeholder 吗（

**Comment by Enter-tainer** [comment]
感觉不显示也行（）

**Comment by littlefrogfromthenorth** [comment]
可以参考下：
https://blog.csdn.net/duninet/article/details/125280107

**Comment by littlefrogfromthenorth** [comment]
关于部署gisgus

**Comment by kLiHz** [comment]
看起来不错, looks good to me 😆

**Comment by NachtgeistW** [comment]
Gitalk 索取了过多的权限（每个评论者的所有 public repo 的读写权限），且必须由管理员手动给新页面开评论区。
> 
> [Giscus](https://giscus.app) 基于 GitHub Discussions，有包括但不限于下列优点：
> 
> 1. 需要用户授权少
> 2. 每个用户都可以开新评论区
> 3. 可以给页面点 reactions，也可以给评论点 reactions
> 4. 可以有楼中楼
> 5. 可以折叠评论
> 6. 用户可以设定正序/倒序显示
> 7. 支持暗色模式
> 8. 支持 LaTeX 显示
> 9. 授权是统一的，用户只需在某个使用 Giscus 的站点授权一次，而 Gitalk 是每个站点有自己的 OAuth App

这么看的话切过去只有好处没有坏处。
主站 Break 几分钟不是什么问题，在 OI Wiki 首页挂一个“维护公告”说明一下“我们要迁移评论系统，在什么什么时间内主站无法访问”就可以了。
我只有一个问题：以前的评论要如何迁移。

**Comment by littlefrogfromthenorth** [comment]
> > Gitalk 索取了过多的权限（每个评论者的所有 public repo 的读写权限），且必须由管理员手动给新页面开评论区。
> > [Giscus](https://giscus.app) 基于 GitHub Discussions，有包括但不限于下列优点：
> > 
> > 1. 需要用户授权少
> > 2. 每个用户都可以开新评论区
> > 3. 可以给页面点 reactions，也可以给评论点 reactions
> > 4. 可以有楼中楼
> > 5. 可以折叠评论
> > 6. 用户可以设定正序/倒序显示
> > 7. 支持暗色模式
> > 8. 支持 LaTeX 显示
> > 9. 授权是统一的，用户只需在某个使用 Giscus 的站点授权一次，而 Gitalk 是每个站点有自己的 OAuth App
> 
> 这么看的话切过去只有好处没有坏处。 主站 Break 几分钟不是什么问题，在 OI Wiki 首页挂一个“维护公告”说明一下“我们要迁移评论系统，在什么什么时间内主站无法访问”就可以了。 我只有一个问题：以前的评论要如何迁移。

请参考:https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion

**Comment by NachtgeistW** [comment]
> > > Gitalk 索取了过多的权限（每个评论者的所有 public repo 的读写权限），且必须由管理员手动给新页面开评论区。
> > > [Giscus](https://giscus.app) 基于 GitHub Discussions，有包括但不限于下列优点：
> > > 
> > > 1. 需要用户授权少
> > > 2. 每个用户都可以开新评论区
> > > 3. 可以给页面点 reactions，也可以给评论点 reactions
> > > 4. 可以有楼中楼
> > > 5. 可以折叠评论
> > > 6. 用户可以设定正序/倒序显示
> > > 7. 支持暗色模式
> > > 8. 支持 LaTeX 显示
> > > 9. 授权是统一的，用户只需在某个使用 Giscus 的站点授权一次，而 Gitalk 是每个站点有自己的 OAuth App
> > 
> > 
> > 这么看的话切过去只有好处没有坏处。 主站 Break 几分钟不是什么问题，在 OI Wiki 首页挂一个“维护公告”说明一下“我们要迁移评论系统，在什么什么时间内主站无法访问”就可以了。 我只有一个问题：以前的评论要如何迁移。
> 
> 请参考:https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e3498776c2fc6e103c368b2e0a90aac9dbb53e742fc03c294b4c4073cc7e7bd0/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f6f70656e5f67726170682f6769746875622d6c6f676f2e706e67"><img alt="" height="14" src="/assets/cb-803/images/site/favicon.svg"> GitHub Docs**[Moderating discussions - GitHub Docs](https://ghdocs-prod.azurewebsites.net/en/discussions/managing-discussions-for-your-community/moderating-discussions)**You can promote healthy collaboration by marking comments as answers, locking or unlocking discussions, converting issues to discussions, and editing or deleting comments, discussions, and categories that don't align with your community's code of conduct.

阅读完毕，比我想得还容易。
那我没有任何意见了，LGTM。

**Comment by littlefrogfromthenorth** [comment]
现在改完的版本在这里：https://github.com/littlefrogfromthenorth/mkdocs-material

**Comment by ouuan** [comment]
convert 可以在 https://github.com/OI-wiki/gitment/labels 对 gitalk 标签选择 “Convert issues” 来批量完成。

有一个问题是，现在使用的是页面标题而没有目录结构，就会有 [基本概念](https://oi-wiki.org/math/probability/basic-conception/) 这种不知道是啥、很可能重复的页面标题，可以保持现状假装没有问题，也可以考虑写脚本自动把标题改了，或者是单独把这种有歧义的标题手动换掉。

**Comment by ouuan** [comment]
另外就是，gitment 这个 repo 标题要不还是改了，改成 comments 之类的 🌚

> 目前，我们使用的评论框架是 gitment

**Comment by kLiHz** [comment]
> 有一个问题是，现在使用的是页面标题而没有目录结构 ...

@ouuan 我记得 giscus 好像有几种不同的配置方式? 应该选择一个合适的就可以解决了 (比如有一种好像就是用目录结构作为 GitHub Discussion 的标题的).

**Comment by ouuan** [comment]
> 我记得 giscus 好像有几种不同的配置方式? 应该选择一个合适的就可以解决了 (比如有一种好像就是用目录结构作为 GitHub Discussion 的标题的).

问题在于现在的标题，而不是新的标题。如果要修就要批量修改现在的标题。

> 可以保持现状假装没有问题，也可以考虑写脚本自动把标题改了，或者是单独把这种有歧义的标题手动换掉。

我这段说的就是怎么处理旧标题。

**Comment by kLiHz** [comment]
明白，可能因为上一个评论主语不明显，所以本人没看出来，抱歉打扰了 😥

**Comment by Ir1d** [comment]
看了下似乎迁移难度不大，and 目前 gitalk 好像又出问题了（原因不明） #4252

**Comment by littlefrogfromthenorth** [comment]
现在旧版mkdocs里已经有了pullrequest说这个事了

新版也快了


---原始邮件---
发件人: &quot;Dejia ***@***.***&gt;
发送时间: 2022年8月27日(周六) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OI-wiki/OI-wiki] [RFC] 更换评论框架为 giscus (Issue #4169)




 
看了下似乎迁移难度不大，and 目前 gitment 好像又出问题了（原因不明） #4252
 
&mdash;
