### ISSUE TITLE
[功能请求] 统一中文引号使用

### ISSUE THREAD

**Issue by CCXXXI** [OI-wiki/OI-wiki#4186]
### 我遇到的问题是

当前格式手册中有如下内容：

> 请特别注意，我们通常习惯使用 `「` 与 `」` 来提高 **中文引号** 的辨识度。

但站内仍存在大量 `「」` `“”` 混用。

### 我希望能有这样的解决方案

由 bot 自动将 `“”` 替换为 `「」`。

### 我觉得这些备选方案也可以接受

- build 时替换
- 渲染时替换

**Comment by ouuan** [comment]
引号里是英文 / 引号所在段落是英文的情况应该用哪种引号呢 🤔 另外，使用 `"` 似乎是比使用 `“”` 更加严重的错误？

**Comment by Great-designer** [comment]
对于全角引号的替换，应该放进bot中进行替换，因为代码中没有全角引号。

对于半角引号，建议不操作。

**Comment by CCXXXI** [comment]
> 引号里是英文 / 引号所在段落是英文的情况应该用哪种引号呢 🤔 

根据知乎上的这些讨论，主流做法是与引号外内容保持一致：

 - [中文的一句话中需要引用英文，此时英文部分应该用哪种引号？ - 知乎 (zhihu.com)](https://www.zhihu.com/question/21615769)
- [中英文文本混排时，圆括号该用中文括号还是西文括号？ - 知乎 (zhihu.com)](https://www.zhihu.com/question/20488833)
- [中英文混排的时候如何使用标点符号？ - 知乎 (zhihu.com)](https://www.zhihu.com/question/19695720)

**Comment by CoelacanthusHex** [comment]
我认为应当避免 `“”‘’`，因其在 Unicode 中全半角共享码点，渲染为全半角完全取决于字体、渲染库和上下文。我个人认为应当全部使用`「」`和`""''`以取得较好的显示效果。

**Comment by Great-designer** [comment]
> 我认为应当避免 `“”‘’`，因其在 Unicode 中全半角共享码点，渲染为全半角完全取决于字体、渲染库和上下文。我个人认为应当全部使用`「」`和`""''`以取得较好的显示效果。

需要交给bot

**Comment by r-value** [comment]
> 需要交给bot

bot 如何区分何时替换, 何时不替换? 如上所述, `“”‘’` 在 Unicode 中全半角的编码是完全一致的, bot 不能在编码上区分. 如果全部替换会将半角语境下的英文引号一同替换.

**Comment by CCXXXI** [comment]
> > 需要交给bot
> 
> bot 如何区分何时替换, 何时不替换? 如上所述, `“”‘’` 在 Unicode 中全半角的编码是完全一致的, bot 不能在编码上区分. 如果全部替换会将半角语境下的英文引号一同替换.

OI-wiki 极少（如果不是从不）出现半角语境下的英文引号，人工转义一下应该足够了；或者也许可以根据引文前后的空格判断？

**Comment by Great-designer** [comment]
> bot 如何区分何时替换, 何时不替换? 如上所述, `“”‘’` 在 Unicode 中全半角的编码是完全一致的, bot 不能在编码上区分. 如果全部替换会将半角语境下的英文引号一同替换.

欸，刚刚理解这是在说啥，这确实是个问题。有两个基本事实：

- 全半角的码位相同，bot无法区分
- 方引号 `「」` 难以输入

接下来考虑渲染。浏览器是如何渲染全半角引号的？

`“”` `""` `''` `‘’`

或者可以根据出现的位置判断：凡是出现在正文中的，一律替换。对于 `这个位置`、LaTeX、代码段等，所有带有特殊格式的，一律不替换……

**Comment by r-value** [comment]
> 这四个测试了一下，虽然同一个码位，但是在GitHub Talk上竟然可以区分。第1个和第4个是全角，第2个和第3个是半角。

您举例中的这四个并非同一码位. 您在第2与第3个示例中使用的是所谓的 "傻瓜引号", 正如前文中 @ouuan 所提出的, 使用该引号也是很值得质疑的行为. 语法上讲英语不应当使用 "傻瓜引号".

**Comment by Great-designer** [comment]
> 您举例中的这四个并非同一码位. 您在第2与第3个示例中使用的是所谓的 "傻瓜引号", 正如前文中 @ouuan 所提出的, 使用该引号也是很值得质疑的行为. 语法上讲英语不应当使用 "傻瓜引号". 详细的内容可以参见 [Wikipedia: Quotation mark](https://en.wikipedia.org/wiki/Quotation_mark)

那么问题已经解决了。对于傻瓜引号，一律不处理，其余一律处理。因为程序代码中的引号一定是傻瓜引号，只要保证bot不会干扰程序代码就行了。

LaTeX中的撇号自然也是傻瓜引号（或者其他什么东西），也可以不处理。

**Comment by r-value** [comment]
> 那么问题已经解决了。对于傻瓜引号，一律不处理，其余一律处理。因为程序代码中的引号一定是傻瓜引号，只要保证bot不会干扰程序代码就行了。

但是英文语境中本就应当使用 `“”`, 所以我质疑一律处理会将英文预警中的引号替换为中文直角引号.

**Comment by Great-designer** [comment]
另注，直角引号甚至不在128\~255的扩展ASCII范围内，从而确实不便输入。见 #4694

**Comment by CoelacanthusHex** [comment]
> > 但是英文语境中本就应当使用 `“”`, 所以我质疑一律处理会将英文语境中的引号替换为中文直角引号.
> 
> 本站为中文网站。现需要举一个现存在本站的“英文语境且使用引号”的具体位置。（感觉这种情形本身较为罕见）
> 
> 另注，直角引号甚至不在128~255的扩展ASCII范围内，从而确实不便输入。见 #4694

直角引号位于中国国家强制标准 GB2312 中，无法输入该符号的输入系统皆不符合中华人民共和国通行标准。

**Comment by Great-designer** [comment]
> > 另注，直角引号甚至不在128~255的扩展ASCII范围内，从而确实不便输入。见 #4694
> 
> 直角引号位于中国国家强制标准 GB2312 中，无法输入该符号的输入系统皆不符合中华人民共和国通行标准。

另强调：“不便输入”不是“无法输入”。

宪法规定每个正常的公民均有被选举权，从而理论上你可以被选举为国家主席，这里不是“无法”。

**Comment by r-value** [comment]
> 本站为中文网站。

但是外部链接不一定是中文. 英文外部引用中的标题中出现引号是合理的潜在需求, 如果用 bot 强制替换那么会留下祸根, 到时候只能选择回滚 bot.

**Comment by Great-designer** [comment]
> 但是外部链接不一定是中文. 英文外部引用中的标题中出现引号是合理的潜在需求, 如果用 bot 强制替换那么会留下祸根, 到时候只能选择回滚 bot.

已列举第一种情况：对引用不处理

**Comment by r-value** [comment]
> 已列举第一种情况：对引用不处理

您需要提供一个合理的实现来判断此条件. 替换的想法是好的, 但是我这里想说的是实现是困难的.

**Comment by Great-designer** [comment]
> 您需要提供一个合理的实现来判断此条件. 替换的想法是好的, 但是我这里想说的是实现是困难的.

引用位于ref中。如果是一个网址，或者如果位于

- 这个位置

不处理。

**Comment by Great-designer** [comment]
> 但是我这里想说的是实现是困难的.

另注：其实这个跟“OI wiki里要不要放代码”的议题很像。通篇纸上谈兵的效果就是这样，一个代码没有，读者也很费解。见#4685

**Comment by r-value** [comment]
> > 您需要提供一个合理的实现来判断此条件. 替换的想法是好的, 但是我这里想说的是实现是困难的.
> 
> 引用位于ref中。如果是一个[网址](%E9%9A%8F%E4%BE%BF%E4%BB%80%E4%B9%88%E5%9C%B0%E5%9D%80)，或者如果位于
> 
> * 这个位置
> 
> 不处理。
> 
> 这样做确实会漏过一些
> 
> * 这个位置
> 
> 的情形。但是一篇正常的文章不可能通篇都是
> 
> * 这个位置
> 
> 的中文引号，从而特例不多。

看上去您已经对新功能的实现有了明确的思路, 那么不妨请您来实现.

**Comment by Great-designer** [comment]
> 看上去您已经对新功能的实现有了明确的思路, 那么不妨请您来实现.

瑟瑟发抖，不会写bot。如果负责写bot的同学确实不会，那就算了。

**Comment by Enter-tainer** [comment]
@Great-designer 感觉corner case有点多，最近不考虑

**Comment by Great-designer** [comment]
> 感觉corner case有点多，最近不考虑

- 交由编写者或者管理员输入直角，鉴于不便捷，无法实现。
- 交由bot处理，实现麻烦。

总结：暂时搁置，作为长期问题

**Comment by CoelacanthusHex** [comment]
@Great-designer https://github.com/OI-wiki/OI-wiki/issues/4186#issuecomment-1415776199
纸上谈兵的明显是您吧，群里bot开发者一直在积极和其他贡献者讨论技术上的可行性

**Comment by Great-designer** [comment]
> 纸上谈兵的明显是您吧，群里bot开发者一直在积极和其他贡献者讨论技术上的可行性

我没说“不是我”，也没说“不积极”，仅在作冷静陈述，其上的感情为读者的臆想。以后对于这种一概不回复

**Comment by CCXXXI** [comment]
> 另外，使用 `"` 似乎是比使用 `“”` 更加严重的错误？

这可能并不是什么严重错误，实际上，英文维基百科甚至要求使用直引号代替弯引号

https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Quotation_characters

**Comment by CCXXXI** [comment]
> 对于全角引号的替换，应该放进格式化bot中作为一条替换规则

在不了解技术细节的情况下，最好不要尝试提出具体实现方案，这通常难以落实

> 因为代码中没有全角引号。

全角引号可能出现于代码中的字符串等位置

> 对于半角引号，建议不操作。

无论如何，半角引号的处理不属于本 issue 内容

**Comment by CCXXXI** [comment]
> 语法上讲英语不应当使用 "傻瓜引号". 详细的内容可以参见 [Wikipedia: Quotation mark](https://en.wikipedia.org/wiki/Quotation_mark)

在该条目本身中就出现了数次傻瓜引号，这一用法也是英文维基百科的共识

**Comment by CCXXXI** [comment]
> 本站为中文网站。现需要举一个现存在本站的“英文语境且使用引号”的具体位置。（感觉这种情形本身较为罕见）

使用 VS Code 等工具进行搜索即可找到，比如 https://oi-wiki.org/lang/csl/bitset/

> 另注，直角引号甚至不在128~255的扩展ASCII范围内，从而确实不便输入。见 #4694

是否便于输入和本 issue 试图解决的问题无关
