### ISSUE TITLE
[BUG] overline 在某些缩放下消失

### ISSUE THREAD

**Issue by CCXXXI** [OI-wiki/OI-wiki#4193]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [x] 我正在着手修复这个问题

### 我遇到了这样的问题

![IMG_20220808_183339_072](https://user-images.githubusercontent.com/25550534/183399377-dbd26f31-2c88-4423-a802-ba97e0461020.jpg)
![IMG_20220808_183342_206](https://user-images.githubusercontent.com/25550534/183399392-8523268a-2d9f-48ae-be19-2aeace85d095.jpg)

https://oi-wiki.org/graph/concept

**Comment by littlefrogfromthenorth** [comment]
没能成功复现问题
![image](https://user-images.githubusercontent.com/49180735/183603036-0ef6681e-63a2-42c1-8483-7fc6b9a5587a.png)

**Comment by CCXXXI** [comment]
补充信息：

- https://oi-wiki.org/graph/concept/#特殊的图
- Microsoft Edge 版本 104.0.1293.47 (正式版本) (64 位)
- 宽度：1707.33 px

**Comment by CCXXXI** [comment]
临界点是 1600 px

**Comment by CCXXXI** [comment]
```css
@media only screen and (min-width: 100em)
html {
    /* font-size: 137.5%; */
}
```
似乎和这条 CSS 有关

**Comment by CCXXXI** [comment]
https://user-images.githubusercontent.com/25550534/183607188-f2b5fbdd-e290-4aa9-b201-557441135296.mp4

**Comment by Enter-tainer** [comment]
> 似乎和这条 CSS 有关

我们是否可以把这条css干掉？

**Comment by llh721113** [comment]
> > 似乎和这条 CSS 有关
> 
> 我们是否可以把这条css干掉？

为什么不试试看呢（x

**Comment by CCXXXI** [comment]
@Enter-tainer 对于这个特例可以，但其他字号也有问题（见录屏）

**Comment by CCXXXI** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/25550534/183633973-136bc133-d3d7-4d90-b816-b9ded6265b68.png">
Chrome 可复现

**Comment by CCXXXI** [comment]
另一台电脑无法复现

Microsoft Edge 版本 104.0.1293.47 (正式版本) (64 位)
宽度 1920 px

**Comment by CCXXXI** [comment]
- 屏幕宽度为 2560 px 的一台电脑在 100%、125% 系统缩放时正常，150% 以上可复现
- 屏幕宽度为 1980 px 的另一台电脑在 100%、125%、150% 系统缩放时正常，175% 以上可复现
- 在 Edge 和 Chrome 上表现一致

**Comment by CoelacanthusHex** [comment]
Firefox 105.0a1.20220809.00, 3840x2160, Arch Linux，未复现

**Comment by CCXXXI** [comment]
怀疑为 Windows 独占 bug

**Comment by CCXXXI** [comment]
- https://github.com/mathjax/MathJax/issues/2701

似乎是属于浏览器的 bug

**Comment by CCXXXI** [comment]
可能的临时解决方案：

```css
mjx-ext {
    border-top: 1px solid;
}
```

![image](https://user-images.githubusercontent.com/25550534/183640447-67ea9d55-74b9-4f8c-97f7-d01a696e85d5.png)

**Comment by littlefrogfromthenorth** [comment]
可能的临时解决方案：换svg, 不用 html + css

**Comment by CCXXXI** [comment]
搬运一些反馈：

### 整体统计

>  <img width="256" alt="image" src="https://user-images.githubusercontent.com/25550534/184047157-506bc70e-3e80-458f-95a2-81c6ada978ff.png">

### 页面加载后的变动

> 但是那条线比 A 晚出来

> 晚了好几秒

> 曾经有条线
> 然后自己消失了

### 浏览器相关

> Firefox Chromium 皆无法复现

> Firefox 不可
> Chrome 可
> Chrome我有装改字体插件（

> Firefox有 Edge无

### 缩放相关

> 我稍微放大点就没了

> 放大到500%的时候，bar消失了

> 放大了也没事

> 我放大到110%就消失
> 缩小到90%也消失了
> 就100%没事
> chrome 104.0.5112.79

**Comment by littlefrogfromthenorth** [comment]
要不就直接换回曾经的svg吧


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 下午4:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OI-wiki/OI-wiki] [BUG] 数学公式在窗口过宽时显示异常 (Issue #4193)




 
补充信息：
  
https://oi-wiki.org/graph/concept/#特殊的图 
Microsoft Edge 版本 104.0.1293.47 (正式版本) (64 位) 
宽度：1707.33 px  
&mdash;

**Comment by CCXXXI** [comment]
看起来已经被 MathJax 修好了
