### ISSUE TITLE
建议添加 ‘专题’ 栏目

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#420]
目前我们大多是按照算法和数据结构来拆一个页面，然而关于某种类型的问题（比如 RMQ 问题），不知道放到什么地方比较合适。所以我觉得最好开个 ‘专题’ 栏目来放这种经典的问题？

举几个栗子：

- RMQ
- 约瑟夫问题
- n 个球放 m 个盒子的方案数

**Comment by greyqz** [comment]
建议稍微区分「专题」之间的区别（作为二级菜单）：

- 区间最值查询 可以放在「图论」下面的「专题」里。
- 约瑟夫问题 建议放在「基础部分」下面的「专题」里。

**Comment by P6174** [comment]
个人意见：既然主要是根据算法和数据结构拆页面，那么经典问题就塞到各个算法 / 数据结构的页面里当例题。

**Comment by Ir1d** [comment]
然而经典问题可能对应多个算法/数据结构的页面，最好还是整理出来吧

**Comment by P6174** [comment]
经典问题多次出现没有问题吧……  
比如算导里面，一个「斐波那契数列」就被同时塞进了好几处

**Comment by Ir1d** [comment]
是没有问题，整理出来会不会更好一些？

**Comment by greyqz** [comment]
@Ir1d 还是放在各个页面吧，不过对于多种解法的问题，不同解法之间**交叉引用**一下，例如：

```markdown
# ST 表
### 区间最值查询问题（RMQ）
balabala...

关于 RMQ 问题 的 $O(n!)$ 做法，参见 [倍增](address#RMQ)。

关于 RMQ 问题 的 $O(n!!)$ 做法，参见 [Tarjan](address#RMQ)。

关于 RMQ 问题 的 $O(n!!!)$ 做法，参见 [树链剖分](address#RMQ)。
```

诸如此类。

这样查找 RMQ 的所有解法就可以 2 步完成：搜索 🔍 + **交叉引用**跳转。

**Comment by Ir1d** [comment]
但是为什么 RMQ 放在 ST 表下面呢……会不会给人一种钦定的感觉……

**Comment by ChungZH** [comment]
我个人喜欢把经典问题拆出来单独讲~

**Comment by Voileexperiments** [comment]
經典問題要講的話會有一個問題,就是經典問題太多了(因為經典問題跟智力題有重合),然後就會有project scope的問題,是要講狹義上的OI題呢?還是OJ題?還是各種奇怪又涉及偏門題材的~~毒瘤~~題呢?~~(例如Codewars上就有一堆如此的毒瘤題)~~

**Comment by sshwy** [comment]
要谈到学习效率的问题话，把一个经典问题的不同解法整理在一篇文章的效率肯定是最高的。毕竟我认为OI-WIKI不是追求极端的不复用性，而是一个高效的学习平台。同一个内容在多个页面出现，侧重点不同，编者撰文的内容也有不同。如果采用引用链接的方式，由于上下文的不一致，使得学习的效率反而变低。而且面对一篇满是链接的文章，吸引力无疑下降很多，不容易激发学习的兴趣。怎么阅读是读者的选择，但安排内容来吸引读者就是创作者的工作。

对于经典问题与算法的分类的问题，我认为经典问题应该单独分一类。首先经典问题是可能有多种解法的（毕竟是经典问题），不属于单个算法的范畴；其次把经典问题分一类可以让创作者将更多奇妙的~~乱搞~~算法直接补上去，不会受到算法分类的限制。

对于经典问题数量多的问题，首先经典问题是可以归类的，比如一些所谓的智力题可以归结为“小学奥赛题”的分类。另外我认为一道经典题之所以可以放在“专题”中，需要至少3种趋向各不相同的算法，或者三种侧重点不同的算法（比如一个算法是在较小的数据量，较大的值域范围求解，另一个算法是在较大的数据量但值域较小的范围内求解）。这样的题目其实是不多的。另外，就算问题数量太多也没关系。毕竟我认为开放issue和大众编辑的宗旨无疑是提高OI-WIKI的影响力，内容多了可以建立分站。但想要建立分站前提是你得有内容。

另外，我认为专题的不局限于经典题，也可以指一些更灵活的议论性质的文章。比如算法之间的对比，数据结构之间的对比。专题的含义应该比分类更广义，专题文章不只是让OIer去学习，而是可以引发OIer的思考，思考新的解法；我们有算法WIKI作为当前的主体内容，也是一直以来的主题内容，那么设置专题的目的就应该是展现不同算法，不同结构之间的区别与联系，完善学习者的思维网络，激发OIer的创造力，参与到这个分享与学习的过程中。

总结：我非常支持开发专题栏目。并且不建议做链接的引用，建议每个专题呈现完整的文章（可以对算法本身引用连接，比如“某某算法/结构请参见某某链接”，而用于汇总或者对比的内容应该呈现出来。

另外我也不是植入广告，我只是想解释一下我眼中的专题文章长什么样子。这是我没事口糊的一个咸鱼文章[从树套树浅析常用结构的特性](https://www.sshwy.tk/2019/06/17/29683/) （投过某日报）

以上仅个人观点～

**Comment by sshwy** [comment]
这个Issue四不四可以close了

**Comment by greyqz** [comment]
这是有生之年 issue～
