### ISSUE TITLE
Add cryptography topic

### ISSUE THREAD

**Issue by RIvance** [OI-wiki/OI-wiki#4238]
### 页面英文名

cryptography

### 我希望能添加的内容是

密码学是很多算法最直接的应用场景, 很多 OI 题目也会涉及部分密码学 (甚至区块链) 相关的内容或直接基于某一个加密算法为背景进行命题, 同时众多 OI 培训课程也会或多或少涉及部分内容 (比如讲解群论时可能会提到 reed-solomon 编码使用伽罗瓦域进行纠错), 但 OI wiki 目前还没有关于密码学的专题. 添加密码学专题一方面可以加深选手对一些算法在应用层面的理解, 另一方面也可以使得选手在遇到相关题目时更加得心应手. 除此之外, 我个人学习密码学时所使用的资料基本都为英文资料, 互联网上能搜索到的关于密码学有价值的中文资料较少 (甚至连ed25519这种ssh中每天都能用到的算法都搜不到什么较为详细的中文资料, 更别说复杂一些的算法), 希望 OI wiki 可以填补这部分的空缺.

### 我了解到的相关参考资料有

# [Symmetric Cryptography Algorithms](https://en.wikipedia.org/wiki/Symmetric-key_algorithm)

## DES
- https://en.wikipedia.org/wiki/Data_Encryption_Standard
- https://sci-hub.wf/10.1109/c-m.1977.217750
- https://www.cs.mcgill.ca/~rwest/wikispeedia/wpcd/wp/d/Data_Encryption_Standard.htm

## AES
- https://en.wikipedia.org/wiki/Advanced_Encryption_Standard
- https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197.pdf

## TEA/XTEA
- https://en.wikipedia.org/wiki/Tiny_Encryption_Algorithm
- https://citeseer.ist.psu.edu/viewdoc/download?doi=10.1.1.45.281&rep=rep1&type=pdf
- https://en.wikipedia.org/wiki/XTEA
- http://www.cix.co.uk/~klockstone/xtea.pdf

## RC2
- https://en.wikipedia.org/wiki/RC2
- https://people.csail.mit.edu/rivest/pubs/KRRR98.pdf
- https://datatracker.ietf.org/doc/html/rfc2268

## RC5
- https://en.wikipedia.org/wiki/RC5
- https://people.csail.mit.edu/rivest/Rivest-rc5rev.pdf

## RC6
- https://en.wikipedia.org/wiki/RC6

## 待补充 (3DES, IDEA, SM1, SM4等)

# [Asymmetric Cryptography Algorithms (Public-key cryptography)](https://en.wikipedia.org/wiki/Public-key_cryptography)

## Diffie-Hellman
- https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange
- https://ee.stanford.edu/%7Ehellman/publications/24.pdf
- https://www.geeksforgeeks.org/implementation-diffie-hellman-algorithm/

## RSA
- 建议优先参考<<算法导论>>中的相关内容
- https://en.wikipedia.org/wiki/RSA_(cryptosystem)
- http://koclab.cs.ucsb.edu/teaching/cren/project/2018/Adamczyk+Magnussen.pdf

### ECDH
- https://en.wikipedia.org/wiki/Elliptic-curve_Diffie%E2%80%93Hellman
- https://cryptobook.nakov.com/asymmetric-key-ciphers/ecdh-key-exchange

### ECDSA
- https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm

### EdDSA (ed25519)
- https://en.wikipedia.org/wiki/EdDSA
- https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf

### SM2 (国密)
- https://www.sca.gov.cn/sca/xwdt/2010-12/17/1002386/files/b791a9f908bb4803875ab6aeeb7b4e03.pdf

### 待补充

# [Checksum](https://en.wikipedia.org/wiki/Checksum)

## CRC
- https://en.wikipedia.org/wiki/Cyclic_redundancy_check
- https://github.com/RIvance/serial-comm-protocol/blob/master/include/serial/command/CRC.hpp

### MD5
- https://en.wikipedia.org/wiki/MD5
- https://datatracker.ietf.org/doc/html/rfc1321
- [王小云教授破解MD5的那篇paper](https://web.archive.org/web/20090521001714/http://www.infosec.sdu.edu.cn/uploadfile/papers/How%20to%20Break%20MD5%20and%20Other%20Hash%20Functions.pdf)

### SHA1
TODO

### SHA256
TODO

# [Error Correction Code](https://en.wikipedia.org/wiki/Error_correction_code)

## Hamming Code
- https://en.wikipedia.org/wiki/Hamming_code
- https://calhoun.nps.edu/bitstream/10945/46756/1/Hamming_1982.pdf

## Reed-Solomon Code (QR-Code 所使用的纠错算法)

# [Quantum Cryptography (可以作为拓展知识)](https://en.wikipedia.org/wiki/Quantum_cryptography)

## QKD
- https://en.wikipedia.org/wiki/Quantum_key_distribution
- http://cs.uccs.edu/~cs691/crypto/BBBSS92.pdf

## Shor's Algorithm (使用量子计算机分解质因数)
- https://sci-hub.wf/10.1109/sfcs.1994.365700
- https://authors.library.caltech.edu/2179/1/BECpra96.pdf

**Comment by Menci** [comment]
@welcome[bot] 咱们这是个什么 wiki 啊

**Comment by Backl1ght** [comment]
ctf wiki了解一下？

**Comment by RIvance** [comment]
> @welcome[bot] 咱们这是个什么 wiki 啊

一个建议而已，如果觉得不合适的话直接close掉就行

> ctf wiki了解一下？

ctf wiki上关于加密算法的文章并不详细而且很多都缺少代码实现

**Comment by Great-designer** [comment]
> ctf wiki上关于加密算法的文章并不详细而且很多都缺少代码实现

**那应该去联系ctf wiki方面**，完善文章，补充代码。
- 这里至多只能写一些交叉的内容，以及交叉内容的适当衍伸。例如：
- Diffie-Hellman、RSA（这两个在数学的数论教材里可以见到，算是通识内容）
- CRC、Hamming Code（CRC和Hamming Code在计算机学科多门课程中都有，勉强算是基础知识）
- Hash（勉强可以写进Hash的扩展内容，但至多只能提一点儿）
量子计算肯定是严重超纲了（算法导论上的多线程计算已经相当于是超纲了）；椭圆曲线也超纲了，无处可放；DES/AES/RC系列也是无处可放。

**Comment by lychees** [comment]
印象中只在 Topcoder Marathon 里做到过一些需要 cryptography 知识的题目。。

**Comment by n-WN** [comment]
没做过做需要 crypto 知识的题目，但是见到过，似乎是个好的提案

**Comment by RIvance** [comment]
@Great-designer make sense

**Comment by Enter-tainer** [comment]
@Great-designer 不过，如果有人愿意写的话，即使“超纲了”其实也问题不大

**Comment by n-WN** [comment]
我也是密码学爱好者 深入交流下?

**Comment by n-WN** [comment]
> > @WELCOME[bot] 咱们这是个什么 wiki 啊
> 
> 一个建议而已，如果觉得不合适的话直接close掉就行
> 
> > ctf wiki了解一下？
> 
> ctf wiki上关于加密算法的文章并不详细而且很多都缺少代码实现

我在尝试维护另一份密码学 wiki 上的内容, 但是那边管理者并未合并分支
