### ISSUE TITLE
[BUG] ETT页面目录出现乱码

### ISSUE THREAD

**Issue by Backl1ght** [OI-wiki/OI-wiki#4253]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![image](https://user-images.githubusercontent.com/44666321/186950435-accc185e-f08e-409f-86e4-f16fd19733f2.png)

**Comment by Great-designer** [comment]
我感觉是bot自动格式化的问题，现在bot还是会对全体改动的pr当中的ett页面中的这一句进行自动格式化调整。

可能随意merge一个经过bot自动格式化的ett页面的pr就能解决这个问题。

**Comment by Ir1d** [comment]
可能是一些零宽字符，应该 lint 后就会消除

**Comment by Great-designer** [comment]
我猜测应该修好了，等#4255 跑完应该就正常了

**Comment by Great-designer** [comment]
bot操作过了，似乎没有解决……

**Comment by Ir1d** [comment]
i see 感谢
