### ISSUE TITLE
子问题：掩码枚举

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4263]
子问题：掩码枚举

位置有可能放在《组合数学》目录下《容斥原理》之前，紧挨着容斥原理。

**Comment by Great-designer** [comment]
## 掩码枚举

### 枚举给定掩码的所有子掩码

给定一个位掩码m，您希望有效地迭代其所有子掩码s，即只设置掩码中包含的位的掩码m。

考虑基于位运算技巧的该算法的实现：

```cpp

int s = m;
while (s > 0) {
 ... you can use s ...
 s = (s-1) & m;
}

```

或者，使用更紧凑的for语句：

```cpp

for (int s=m; s; s=(s-1)&m)
 ... you can use s ...

```

在代码的变体中，将不处理等于零的子掩码。我们可以在循环之外处理它，或者使用不太优雅的设计，例如：

```cpp

for (int s=m; ; s=(s-1)&m) {
 ... you can use s ...
 if (s==0)  break;
}

```

让我们检查一下为什么上面的代码访问了所有$m$的子掩码，没有重复，并且按降序排列。

假设我们有一个当前位掩码$s$，并且我们想继续下一个位掩码。通过从掩码$s$中减去一个单位，我们将删除最右边的设置位，其右边的所有位将变为1。然后，我们删除掩码$m$中未包含的所有“额外”1位，因此不能成为子掩码的一部分。我们通过使用逐位运算 (s-1) & m 来进行此移除。因此，我们“切割”掩码$s-1$，以确定它可以取的最高值，即按降序排列的$s$之后的下一个子掩码。

因此，该算法按降序生成该掩码的所有子掩码，每次迭代仅执行两个操作。

一种特殊情况是$s=0$。在执行$s-1$之后，我们得到一个掩码，其中所有位都被设置（位表示为-1），在 (s-1) & m 之后，我们将得到$s$将等于$m$。因此，对于掩码$s=0$，请小心：如果循环不以零结束，算法可能会进入无限循环。

### 用子掩码迭代所有掩码

本算法的时间复杂度为 $O(3^n)$。

在许多问题中，尤其是使用位掩码动态编程的问题中，您希望迭代所有位掩码，对于每个掩码，迭代其所有子掩码：

```cpp

for (int m=0; m<(1<<n); ++m)
	for (int s=m; s; s=(s-1)&m)
 ... s and m ...

```

接下来证明内部循环将执行总计$O(3^n)$次迭代。

考虑第$i$位。有三种情况：
 - 它不包含在掩码m中（因此不包含在子掩码s中）。
 - 它包含在m，但不包含在s中。
 - 它包含在m和s中。

由于总共有$n$位，因此将有$3^n$个不同的组合。

另一种证法：如果掩码$m$具有$k$启用位，那么它将具有$2^k$子掩码。由于我们总共有$C_n^k$个掩码和$k$个启用位（见组合数），那么所有掩码的组合总数将为：

$$
\sum_{k=0}^n C_n^k 2^n
$$

上面的和等于使用二项式定理对 $(1+2)^n$ 的展开，因此有 $3^n$ 个组合。

### 练习题

 - [Atcoder - Close Group](https://atcoder.jp/contests/abc187/tasks/abc187_f)
 - [Codeforces - Nuclear Fusion](http://codeforces.com/problemset/problem/71/E)
 - [Codeforces - Sandy and Nuts](http://codeforces.com/problemset/problem/599/E)
 - [Uva 1439 - Exclusive Access 2](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=4185)
 - [UVa 11825 - Hackers' Crackdown](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=2925)

**Comment by Great-designer** [comment]
以上为机翻外加一些小调整。原地址见

https://github.com/e-maxx-eng/e-maxx-eng/blob/master/src/algebra/all-submasks.md

如果看不懂可以到原文出查看，然后直接进行edit。

如果认为没问题可以直接自行开一个pull request。

**Comment by ouuan** [comment]
提醒一下，这个已经有了 https://oi-wiki.org/math/bit/#%E6%A8%A1%E6%8B%9F%E9%9B%86%E5%90%88%E6%93%8D%E4%BD%9C ，只不过写的比较简略。

**Comment by Great-designer** [comment]
> 提醒一下，这个已经有了 https://oi-wiki.org/math/bit/#%E6%A8%A1%E6%8B%9F%E9%9B%86%E5%90%88%E6%93%8D%E4%BD%9C ，只不过写的比较简略。

哦这样……那目前这里有要关掉的必要吗……即标记为“已完成”？还是其他处理办法？搁置？

**Comment by ouuan** [comment]
我觉得扩充一下或者关掉都行吧 🤔

**Comment by Great-designer** [comment]
还是选择扩充了一下。
