### ISSUE TITLE
子问题：隔板原理

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4267]
子问题：隔板原理。

**Comment by Great-designer** [comment]
## 隔板原理

隔板原理（Stars and bars，直译为星条旗），或称插空原理，是解决某些组合问题的数学技术。每当您要计算对相同对象分组的方式数时，就可以使用本原理。

### 定理

将n个相同对象放入k个标记框的方法数为：

$$
C_{n+k-1}^n
$$

证明可以使用隔板将盒子分开。

例如，我们可以用$\bigstar | \bigstar \bigstar |~| \bigstar \bigstar$表示以下情况：第一个框中有一个对象，第二个框中是两个对象，第一个框为空，最后一个框中为两个对象。这是将5个对象分成4个框的一种方法。

很明显，每个分区都可以用$n$个物体和$k-1$个隔板表示，而使用$n$个物体和$k-1$个隔板的每个排列表示一个方案。因此，将$n$相同对象划分为$k$标记框的方法数量与$n$个物体和$k-1$个隔板的排列数量相同。组合数给出了我们想要的公式。

### 非负整数和的数目

这个问题是该定理的直接应用。

要计算方程的解数：

$$
x_1+x_2+\cdots+x_k=n
$$

其中

$$
x_i \ge 0
$$

同样，我们可以使用隔板原理求解。

例如，$n=4$，$k=3$情形的一个解$1+3+0=4$，可以使用$\bigstar | \bigstar \bigstar \bigstar |$表示。

容易看出这是隔板原理。因此，解的个数为$C_{n+k-1}^n$。

### 不同下界整数和的数目

这可以很容易地扩展到具有不同下限的整数和。

例如，要计算方程的解数：

$$
x_1+x_2+\cdots+x_k=n
$$

其中

$$
x_i \ge a_i
$$

令

$$
x_i^{'}=x_i-a_i
$$

得到新方程：

$$
(x_1^{'}+a_1)+(x_2^{'}+a_2)+\cdots+(x_k^{'}+a_k)=n
$$

$$
x_1+x_2+\cdots+x_k=n-a_1-a_2-\cdots-a_k
$$

其中

$$
x_i^{'}\ge 0
$$

因此，用换元将问题简化为更简单的情况，并再次应用隔板原理，可以求解这种情形。

**Comment by Great-designer** [comment]
以上为机翻外加一些小调整。原地址见

https://github.com/e-maxx-eng/e-maxx-eng/blob/master/src/combinatorics/stars_and_bars.md

我看这篇是在讲将非负整数n分拆为k个非负整数变元之和的方法数。位置可以放在排列组合之后？

如果看不懂可以到原文出查看，然后直接进行edit。

如果认为没问题可以直接自行开一个pull request。

**Comment by Enter-tainer** [comment]
@Great-designer 感觉可以直接开pr吧？为什么要comment到找个地方

**Comment by Great-designer** [comment]
> @Great-designer 感觉可以直接开pr吧？为什么要comment到这个地方

……操作比较麻烦，而且机翻的质量也一般。流水线作业的话可以先攒一波。并且如果有其他人想接盘开pr，也非常方便合作（我这里没什么意见）。

**Comment by hylwxqwq** [comment]
> > @Great-designer 感觉可以直接开pr吧？为什么要comment到这个地方
> 
> ……操作比较麻烦，而且机翻的质量也一般。流水线作业的话可以先攒一波。并且如果有其他人想接盘开pr，也非常方便合作（我这里没什么意见）。

我刚好打算开一个 PR 写这个，写了插板插空和捆绑三个基本方法，不过后面的应用可能没您这么丰富，能否考虑一起合作？

**Comment by Great-designer** [comment]
刚收了个邮件……其实直接接盘就行了。如果内容就是这些，我应该会approve，至多改点上下文和用词。

记得在译文结尾加入内容“本页面主要译自博文\[俄文标题\]\(链接\)与其英文翻译版\[英文标题\]\(链接\)。其中俄文版版权协议为balabalabalabala……”，在emaxx那个issue。

如果文章相关内容在别处出现了，记得删掉在别处的相关内容。本文隔板原理的话倒是暂时没发现在别处出现的情形。

**Comment by hylwxqwq** [comment]
> 刚收了个邮件……其实直接接盘就行了。如果内容就是这些，我应该会approve，至多改点上下文和用词。
> 
> 记得在译文结尾加入内容“本页面主要译自博文[俄文标题](链接)与其英文翻译版[英文标题](链接)。其中俄文版版权协议为balabalabalabala……”，在emaxx那个issue。
> 
> 如果文章相关内容在别处出现了，记得删掉在别处的相关内容。本文隔板原理的话倒是暂时没发现在别处出现的情形。

我打算稍微改一改这个，然后把捆绑和插空也放进去，如果可以的话我过几天开个 pr 交上去。

**Comment by hylwxqwq** [comment]
我感觉扔到排列组合里面扩充一下比较好？

差不多就是二项式定理介绍的前面或者后面那个位置放着。

因为后面多重集的组合数就要用插板法，我感觉直接加到排列组合里面阅读起来会比较连贯。

**Comment by Great-designer** [comment]
> 这个到时候是直接扔到排列组合里面去还是单独独立啊?

当然放到哪里都可以。

**Comment by Great-designer** [comment]
已经有新pull request并合并到排列组合一文中，不再作为单独文章出现，翻译部分视为完成。
