### ISSUE TITLE
[内容有误] 树哈希

### ISSUE THREAD

**Issue by fjzzq2002** [OI-wiki/OI-wiki#4270]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/graph/tree-hash/

### 我发现页面有这样的问题

给出的算法均有正确性方面的问题~

**Comment by littlefrogfromthenorth** [comment]
啥问题

**Comment by Ir1d** [comment]
https://peehs-moorhsum.blog.uoj.ac/blog/7891

**Comment by fjzzq2002** [comment]
提供一点context：在今年NOI中有一道使用树哈希的题目，使用提及的三种方法均不能通过（）

**Comment by Tiphereth-A** [comment]
fixed via #4746
