### ISSUE TITLE
[BUG] 后缀数组页面其中一个小标题在右侧目录栏中显示出错

### ISSUE THREAD

**Issue by 27rabbit-penguin** [OI-wiki/OI-wiki#4272]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![$7WG2R0$GJL%1)TJ`_BF3)8](https://user-images.githubusercontent.com/30163967/187650792-24ab5b5c-c2e6-404e-aa1e-8b3a82852d32.png)

可见右侧目录栏中有乱码，具体链接为：
https://oi-wiki.org/string/sa/#%E5%B0%86-rkidi-%E5%AD%98%E4%B8%8B%E6%9D%A5%E5%87%8F%E5%B0%91%E4%B8%8D%E8%BF%9E%E7%BB%AD%E5%86%85%E5%AD%98%E8%AE%BF%E9%97%AE

我使用的操作系统为 Win10 家庭版，浏览器为 Chrome 104.0.5112.102（正式版本） （64 位）

**Comment by CoelacanthusHex** [comment]
两个字符分别是，U+0002（，start of text）和 U+0003（，End of Text），皆为控制字符

**Comment by CoelacanthusHex** [comment]
原文的[变为91

**Comment by Great-designer** [comment]
duplicated #4253
