### ISSUE TITLE
子问题：最佳计划

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4282]
给定期限和持续时间的最佳计划

**Comment by Great-designer** [comment]
## 给定期限和持续时间的最佳计划
假设有一组作业，知道每个作业的截止时间和持续时间。作业的执行不能在结束前中断。需要创建这样一个时间表来完成最大数量的作业。

### 求解
使用贪心算法，按照截止时间对所有工作进行排序，并按降序查看它们。此外创建一个队列 q，在其中逐步放置作业并提取运行时间最少的作业。例如，可以使用 set 或 priority_queue。最初队列 q 为空。

假设正在寻找第i个工作。首先将其放入 $q$。考虑第 i 个作业的截止时间和第 i-1 个作业的截止时间之间的时间段，长度为 $T$。从 $q$ 中提取作业，按其左持续时间升序，并执行作业，直到整个段 $T$ 被填充。

如果在任何时刻提取的作业只能部分执行，直到段 $T$ 被填充，则尽可能部分执行该作业，即在 $T$ 时间内，将作业的剩余部分放回 $q$。

算法完成会得到最优解，或者是几个最优解中的一个。算法的时间复杂度为 $O(n\log n)$。

### 实现
以下函数获取作业向量，由截止时间、持续时间和作业索引组成，并计算包含最佳调度中使用作业的所有索引的向量。如果想明确地写下计划，仍然需要在截止时间之前对这些作业进行排序。

```c++

struct Job {
    int deadline, duration, idx;

    bool operator<(Job o) const {
        return deadline < o.deadline;
    }
};

vector<int> compute_schedule(vector<Job> jobs) {
    sort(jobs.begin(), jobs.end());

    set<pair<int,int>> s;
    vector<int> schedule;
    for (int i = jobs.size()-1; i >= 0; i--) {
        int t = jobs[i].deadline - (i ? jobs[i-1].deadline : 0);
        s.insert(make_pair(jobs[i].duration, jobs[i].idx));
        while (t && !s.empty()) {
            auto it = s.begin();
            if (it->first <= t) {
                t -= it->first;
                schedule.push_back(it->second);
            } else {
                s.insert(make_pair(it->first - t, it->second));
                t = 0;
            }
            s.erase(it);
        }
    }
    return schedule;
}

```

**Comment by Great-designer** [comment]
感觉可以作为贪心算法的例题。原地址：

https://github.com/e-maxx-eng/e-maxx-eng/blob/master/src/schedules/schedule-with-completion-duration.md

**Comment by WAAutoMaton** [comment]
因作者长期未响应关闭本 issue
