### ISSUE TITLE
[内容待完善] 线性基

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#4287]
### 请选择：

- [x] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/linear-algebra/basis/

### 我发现页面有这样的问题

目前 OI wiki 中 "线性基" 词条存在歧义与内容过少的问题，该词条将线性空间的线性基（Hamel 基）错误地解释为线性空间 $\operatorname{span} \\{f_i\in\\{(b_1,b_2,...,b_n):b_1,b_2,...,b_n\in\\{0,1\\}\\}:i=1,2,...,m\\}$ 上的线性基。

我认为该词条应补充介绍线性空间的线性基的定义、性质等内容，并将线性空间 $\operatorname{span} \\{f_i\in\\{(b_1,b_2,...,b_n):b_1,b_2,...,b_n\in\\{0,1\\}\\}:i=1,2,...,m\\}$, $\operatorname{span} \\{f_i\in\Bbb{R}^n:i=1,2,...,m\\}$ 上的线性基（即 OI 中所说的 "异或线性基" 和 "实数线性基"）作为其在 OI 中的应用，详细介绍构造方法与判断向量是否在线性空间中等内容。

应在 #3837 的基础上继续补充。

**Comment by Tiphereth-A** [comment]
有空的话我可以交个 PR, 不过目前我没空, 所以就开个 issue 等好心人来 fix 了 _(:з)∠)_

**Comment by Tiphereth-A** [comment]
简单抄个书, 放到 https://tifa-233.xyz/archives/hamel-basis 了

**Comment by Great-designer** [comment]
看了看，从线性空间开始讲，那么名叫“线性空间和线性基”比较合适

**Comment by Tiphereth-A** [comment]
> 看了看，从线性空间开始讲，那么名叫“线性空间和基”比较合适。

实际上 OI-wiki 已经有线性空间的内容了, 在 https://oi-wiki.org/math/linear-algebra/vector/#%E5%90%91%E9%87%8F%E7%9A%84%E6%9B%B4%E4%B8%A5%E6%A0%BC%E5%AE%9A%E4%B9%89, 但是只有定义, 所以我抄书的时候就把线性空间的一部分相关概念补上了

现在看感觉可以考虑把这段内容也移植过来?

**Comment by Tiphereth-A** [comment]
或者给线性空间单独建个页面也行

**Comment by Great-designer** [comment]
> 实际上 OI-wiki 已经有线性空间的内容了, 在 https://oi-wiki.org/math/linear-algebra/vector/#%E5%90%91%E9%87%8F%E7%9A%84%E6%9B%B4%E4%B8%A5%E6%A0%BC%E5%AE%9A%E4%B9%89
> 
> 现在看感觉可以考虑把这段内容也移植过来?

知道这个。位于《向量》的部分可以删去并转移到新位置。其他的无所谓。
