### ISSUE TITLE
移动《杨氏矩阵》至《分拆数》之后

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4301]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/young-tableau/

### 我发现页面有这样的问题

杨氏矩阵使用点表示时称Ferrers图，在分拆数中提到。

**Comment by Tiphereth-A** [comment]
反对，表示论不是组合数学的分支。可以考虑添加内部链接。

**Comment by Great-designer** [comment]
> 反对，表示论不是组合数学的分支。可以考虑添加内部链接。

至少北大冯荣权版组合数学分拆数确实用了——如果它是杨表的话，有可能只是杨表的性质

（不懂杨表）

**Comment by Tiphereth-A** [comment]
> > 反对，表示论不是组合数学的分支。可以考虑添加内部链接。
> 
> 至少北大冯荣权版组合数学分拆数确实用了——如果它是杨表的话，有可能只是杨表的性质
> 
> （不懂杨表）

所以感觉补个内部链接就行了
