### ISSUE TITLE
Add 代数系统

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4309]
### 页面英文名

未知

### 我希望能添加的内容是

在考试大纲中离散数学一栏下有“【9】代数系统的基本概念”，在目前的群论目录下没有。

希望增设《代数系统》一文，写在目前的群论目录第一篇。

### 我了解到的相关参考资料有

尹宝林《离散数学》有一节讲代数系统，顺序在“群”之前。

只是这书我手头暂时没有……

**Comment by Great-designer** [comment]
正好连半群一并补了：#4320

**Comment by Shiokiri** [comment]
我希望可以介绍一些群的定理，例如群同态基本定理、群同构定理等，这是否合适？
