### ISSUE TITLE
Add 信息论目录

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4310]
### 页面英文名

未知

### 我希望能添加的内容是

在考试大纲中有《信息论》整个分类。

•【10】熵、互信息、条件熵、相对熵的基本概念
•【10】信息复杂度的基本概念
•【10】描述复杂度的基本概念
•【10】通讯复杂度的基本概念

应该像概率论一样作为一个分类出现，其中含有若干文章。目录的位置紧挨在概率论目录之后。

### 我了解到的相关参考资料有

本人暂时没学过信息论所以不知道

**Comment by Great-designer** [comment]
到现在没人写……

对于深度学习领域而言，信息论似乎应该和概率论写到一起，作为《概率论和信息论》一个目录

**Comment by Great-designer** [comment]
## 香农熵

香农熵：获知随机变量X的值之前，对随机变量X的不确定度的度量；获知随机变量X的值之后，对获得信息量的度量。
随机变量X的取值不影响信息内容，因此香农熵是关于随机变量X取值概率p_x的函数。

$$
H(X)=H(p_1,\cdots,p_n)=-\sum_x p_x \log_2 p_x
$$

由于定义式中底数为2，香农熵的单位为比特。
根据极限：

$$
\lim_{x->0} x\log_2 x=0
$$

一个不可能事件对于香农熵没有贡献，规定概率为0时提供的香农熵为0。
香农熵的定义来源于如下性质：记与发生概率相关的信息量函数为$I(p)$，

$$
I(pq)=I(p)+I(q)
$$

当两个独立事件分别以概率p和q同时发生时，获得信息等于每个事件单独发生时获得信息之和。
满足上述等式的平滑函数只有：

$$
I(p)=\log_k p
$$

因此信息量函数必然是概率的对数，取2为底就得到香农熵。

## 二元熵

二元熵是二值随机变量的熵，定义为：

$$
H_{bin}(p)=-p\log_2 p-(1-p)\log_2 (1-p)
$$

二元熵在p为$\frac{1}{2}$时达到最大值1。
二元熵是一个凹函数，具有凹性，由琴生不等式（Jensen's inequality）可得：

$$
H_{bin}(px_1+(1-p)x_2)\geq p H_{bin}(x_1)+(1-p) H_{bin}(x_2)
$$

二元熵是严格凹的，上述不等式只在 $x_1=x_2$ 或 $p=0$ 或 $p=1$ 时取等。

## 相对熵

相对熵衡量两个概率分布在同一指标集x下的接近程度。
假设 $p(x)$ 和 $q(x)$ 是两个定义在同一指标集x上的概率分布，定义 $p(x)$ 对 $q(x)$ 的相对熵为：

$$
H(p(x)|q(x))= \sum_x p(x) \log_2 \frac{p(x)}{q(x)}=-H(x)- \sum_x p(x) \log_2 q(x)
$$

相对熵具有非负性，相对熵为0当且仅当对于所有的x均有 $p(x)=q(x)$。
假设X是一个有d个取值的随机变量，那么有：
$$
H(X)\leq \log_2 d
$$
当且仅当X是在这d个取值上的均匀分布时取等。

## 条件熵和互信息

随机变量X和Y的联合熵定义为：
$$
H(X,Y)=-\sum_{x,y} p(x,y) \log_2 p(x,y)
$$
联合熵衡量X和Y整体的不确定度。

在已知Y的条件下，X的熵定义为：
$$
H(X|Y)=H(X,Y)-H(Y)
$$
条件熵是给定Y的值的情况下，对于X的值的平均不确定度的度量。

互信息衡量随机变量X和Y拥有多少共同的信息：
$$
H(X:Y)=H(X)+H(Y)-H(X,Y)
$$
根据上述定义，可以得到等式：
$$
H(X:Y)=H(X)-H(X|Y)
$$

## 香农熵的性质

联合熵的X和Y交换位置不变，互信息的X和Y交换位置不变。
条件熵非负，互信息小于等于单个变量的信息，单个变量的信息小于等于联合熵。当Y为X的函数，即$Y=f(X)$时，已知X的条件下Y的熵为0，X和Y的互信息就是Y的熵，X的熵就是X和Y的联合熵。

香农熵具有**次可加性**：
$$
H(X,Y)\leq H(X)+H(Y)
$$
当且仅当X、Y为独立随机变量时取等。同样地，X和Y的互信息非负，当且仅当X、Y为独立随机变量时为0。条件熵小于等于无条件的熵，当且仅当独立随机变量时取等。

条件化降低熵：
$$
H(X|Y,Z)\leq H(X,Y)
$$

条件熵链式规则：
$$
H(X_1,X_2,\cdots,X_n|Y)=\sum_{i=1}^n H(X_i|Y,X_1, \cdots,X_{i-1})
$$

另外，互信息不具有次可加性。

## 数据处理不等式

马尔可夫链是一个随机变量序列 $X_1\to X_2\to\cdots$，在给定 $X_n$ 的情况下，$X_{n+1}$ 与 $ X_1,\cdots,X_{n-1}$ 独立。用概率描述是：
$$
p(X_{n+1}=x_{n+1}|X_n=x_n,\cdots,X_1=x_1)= p(X_{n+1}=x_{n+1}|X_n=x_n)
$$

香农熵具有**强次可加性**：
$$
H(X,Y,Z)+H(Y)\leq H(X,Y)+H(Y,Z)
$$
等且仅当 $Z\to Y\to X$ 构成马尔可夫链时取等。

数据处理不等式：假设 $X\to Y\to Z$ 是马尔可夫链，那么：
$$
H(X)\leq H(X:Y)\leq H(X:Z)
$$
并且，第一个不等式取等，当且仅当给定Y的情况下可以重构X。
数据处理不等式描述一个源输出的信息只能随着时间而降低。信息一旦丢失就永远丢失。

数据管道不等式：假设 $X\to Y\to Z$ 是马尔可夫链，那么
$$
H(Z:Y)\leq H(Z:X)
$$
数据管道不等式描述Z与X共享的任何信息都必须也被Z与Y共享，信息像流过管道一样从X开始经过Y到达Z。

**Comment by Great-designer** [comment]
起了一个稿

**Comment by Great-designer** [comment]
看着办

**Comment by libregd** [comment]
@Great-designer 
你考不考虑搞个math in code wiki ：专注科普各类计算机领域的数学知识以及前置数学知识？
编程总的来说还是偏实战类活动，很多教学大纲甚至都不给实验课代码，强调每个人必须自己实现和尝试。很多大学的计算机专业配置课程math占有的比例感觉差不多1/5: 线性代数，微积分/高等数学，概率论数理分析，数值分析，复变函数，数学建模，离散数学......
开个分支自己搞 ，再安排个cc-by-nc-sa 创作协议？

实际干活和兴趣的话，需要安排的数学感觉和方向关系比较大，比如个人最近在玩blender，除了必要的软件基础，很快就发现很多高级的视觉效果需要一些**计算机图形学的入门知识**的支撑：[数学在计算机图形学中的应用](http://staff.ustc.edu.cn/~lgliu/Resources/SummerSchool/USTC-summer-school.html)

**Comment by Great-designer** [comment]
已经不学数学和计算机了，没有时间和精力做这些事

**Comment by misakamikotoynu** [comment]
@Great-designer 感谢你为社区做出的伟大贡献，也希望您以后能去做一些别的事情，不要把时间花在这些社区了

**Comment by libregd** [comment]
@Great-designer 没人写就你写嘛，你又不是不会写。信息论与其等别人喂饭，不如自己做饭。
开了math in code 喊我，我会大力帮你反馈哪里看不懂的。

**Comment by Great-designer** [comment]
嗐 写这个是因为本科开课足够野。它开的课我不喜欢，我喜欢的它不讲。
信息论这种科班CS，根本就没开过，我也不会，没学过。青春年代很短暂，好用的脑子窗口期真的很短，人生是从一个精神困境走向下一个精神困境。
这段纯属自学，写了一点。看到这恰好空着，贴上来。
现在仍旧还是“我喜欢的许多事情，它不讲”，但事实上我学了也没用，对我的正经生活毫无帮助，甚至花更多时间是有害的。
所以纵使强迫我写这些，我也不会写的——我没有义务写这些，只是偶尔碰巧写一点东西罢了。
楼上说的对。写的东西成天被批评，找不痛快，这又是何苦呢。如果我要是生活很开心的话，真的在从事喜欢的事业的话，怎么可能有机会接触到此类社区呢？
我想，属于自己的年华已然过去，此生是不可能碰触自己爱过的东西了。人生毕竟还是太短，生活毕竟还是太严苛了。

**Comment by libregd** [comment]
1. oi-wiki的内容依赖于广大网友的贡献，大家更偏向在自己擅长的范围内完成，即：知之为知之，那么你自学后产出的内容会不会没有能力符合的审阅人帮你看稿呢？

我个人也有自学和写稿的习惯，非常理解希望有人帮自己看看稿件的心情，建议你可以考虑[自建博客](https://pages.github.com/) , OI-WIKI 有QQ等多种渠道可以发布你的文章，请路过的大佬帮忙看看：“既然承认计算机有科班与否的区别，那么向暂时比自己厉害的人讨教，不就是很好的思路吗？”

而且这样也更有修改和精进的余地，一篇结构优美，内容详实，娓娓道来的文章很少有一次成型的，如果目标更难一点，希望把自己会的教给别人（费曼学习法），那么修改的强度就更高了。

2. 楼上的朋友指出**内容不符合OI-Wiki** 我认为是恰当的，如果您愿意复习一下[OI-wiki的项目介绍](https://github.com/OI-wiki/OI-wiki#%E5%86%85%E5%AE%B9) ，想必能够明确，即便OI-wiki 在高端编程知识部分写得再怎么酷炫，也没有忘记“编程竞赛爱好者入门”这个初心。
> OI Wiki 致力于成为一个免费开放且持续更新的知识整合站点，大家可以在这里获取关于 **编程竞赛 (competitive programming) **有趣又实用的知识，我们为大家准备了竞赛中的基础知识、常见题型、解题思路以及常用工具等内容，帮助大家更快速深入地学习编程竞赛。

即便你再怎么声明：“信息论这种科班CS，根本就没开过，我也不会，没学过。” ，你不是也在学吗？
学习是终身的事，不是只有数学，计算机，一切高难度的事情才需要学。如果学得不开心，不快乐，那就不要学。

如果你喜欢掌握，喜欢了解，确实想探索计算机领域的内容，请从心出发，以初学者的心态撰写自己的博客，我相信抱着自己记录+教会别人的心的话，总会有网友，在搜索引擎键入“信息论 入门/进阶/魔法 教程/实战” 能够从你的分享中从中获益。

3. 题外话：网络社区也是现实的一部分，你所花费的时间，精力从来打造的都是自己。

**Comment by alphagocc** [comment]
根据
https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E6%9D%83%E5%A8%81%E6%9C%BA%E6%9E%84
OI Wiki 不是百科全书
