### ISSUE TITLE
[内容有误] 数论目录下的证明缩进错误

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4311]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

好几个页面，在下面列出

### 我发现页面有这样的问题

刚合并完之后看到的，问题应该出现在缩进。

并不是每个页面都有“证明”折叠的错误，有的页面没有。存在“证明”折叠错误的页面有：

最大公约数：https://oi-wiki.org/math/number-theory/gcd/

数论分块没有折叠问题，但是在《数论分块》中“数论分块结论”一节的证明有时候下标汉字无法正常显示（Win11 Edge），希望能尽量改写为不带汉字的版本。

欧拉函数：https://oi-wiki.org/math/number-theory/euler/

筛法：https://oi-wiki.org/math/number-theory/sieve/

拉格朗日定理没有折叠问题，但是在《拉格朗日定理》中“应用”一节的汉字与公式混排，也无法正常显示（Win11 Edge），希望能正常排好。

Stern-Brocot 树与 Farey 序列：https://oi-wiki.org/math/number-theory/stern-brocot/

**Comment by Great-designer** [comment]
@iamtwz 能麻烦您修修吗

**Comment by iamtwz** [comment]
可能和我更换了编辑器环境有关，着手解决中

> @iamtwz 能麻烦您修修吗

**Comment by iamtwz** [comment]
问题出在 Material for MkDocs 的 Admonitions 上，我错误的认为会自动识别缩进，刚刚看了下 [文档](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) 应该是必须使用四个空格，缩进的问题已经修复。

顺路给 拉格朗日定理 中的公式做了小幅度调整。

数论分块结论中的公式汉字我这里似乎是显示正常的，对大的公式块的修改可能要抄送负责「撰写、完善 OI Wiki 上的内容」的同学？

**Comment by Great-designer** [comment]
> 数论分块结论中的公式汉字我这里似乎是显示正常的，对大的公式块的修改可能要抄送负责「撰写、完善 OI Wiki 上的内容」的同学？

破案了，拖动鼠标光标选中的时候汉字就啥都看不到了，点一下空白处就会恢复。

**Comment by Great-designer** [comment]
不过最好还是不要有汉字描述在latex公式中。
