### ISSUE TITLE
Add 半群相关概念

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#4320]
### 我希望能添加的内容是

参见 https://github.com/OI-wiki/OI-wiki/pull/4317#discussion_r976534330_

### 我了解到的相关参考资料有

https://en.wikipedia.org/wiki/Semigroup

**Comment by Great-designer** [comment]
正好连代数系统一并补了：#4309

**Comment by Great-designer** [comment]
我不知道群论这块儿整理得怎么样了，但是感觉肯定会涉及文件移动，会把群论那几个文件扔到新的文件夹里。

现在我想把置换、排列、逆序数单独出来放在外面，作为公共知识（不属于线代、群论、归并排序等，因为好几个分类都用到），位置位于“快速幂”后面，“弧度制与坐标系”前面，目录叫做**置换和排列**，文件名叫做**permulation.md**，已经写得差不多了（顺便需要把《置换群》相应部分移过来）。如果我来改，肯定涉及文件移动和文件冲突。

写它的必要性是因为，写了“置换和排列”才能够写“初等变换”（也想独立出来作为一篇文章，讲与左右乘的联系，因为后面用到初等变换），初等变换里面的置换阵用到了置换，写了“初等变换”才能写后面的Smith标准型。另外，写了“置换和排列”和“初等变换”才能够写行列式。

**Comment by Great-designer** [comment]
内容基本上是在抄书（《高等代数》张禾瑞郝炳新版），顺便需要把OI Wiki上的现有内容整合一下。前面替换为《置换群》中的定义，末尾补上计算逆序数的办法是归并排序。


## 置换和排列

一个有限集合 $A$ 到自身的双射，叫做 $A$ 的一个置换。

设 $I=\{1,2,\cdots,n\}$ 是前 $n$ 个正整数构成的集合，$\sigma$ 是 $I$ 的一个置换。记：

$$
\sigma(1)=i_1\quad\sigma(2)=i_2\quad\cdots\quad\sigma(n)=i_n
$$

于是 $i_1,i_2,\cdots,i_n$ 仍然为 $1,2,\cdots,n$ 这 $n$ 个数，只是顺序有所不同。

由 $1,2,\cdots,n$ 组成的一个有序组，称为 $1,2,\cdots,n$ 的一个排列。例如把前文 $i_1,i_2,\cdots,i_n$ 叫做 $1,2,\cdots,n$ 的一个排列。

前 $n$ 个正整数 $1,2,\cdots,n$ 的不同排列共有 $n!$ 个。

## 反序和反序数

在一个排列中，如果某一个较大的数排在某一个较小的数前面，就说这两个数构成一个反序或逆序。

在一个排列里出现的反序总数叫做这个排列的反序数或逆序数。

一个排列的反序数可能是偶数也可能是奇数。有偶数个反序的排列叫做一个偶排列，有奇数个反序的排列叫做一个奇排列。

## 对换

如果把 $1,2,\cdots,n$ 的排列中，任意两个数 $i$ 和 $j$ 交换，其余数保持不动，就得到一个新排列。对于排列施加这样一个变换叫做一个对换，用 $(i,j)$ 表示。

定理：设 $i_1i_2\cdots i_n$ 和 $j_1j_2\cdots j_n$ 是 $n$ 个数码的任意两个排列，那么总可以通过一系列对换，由 $i_1i_2\cdots i_n$ 得出 $j_1j_2\cdots j_n$。

定理：每一个对换都改变排列的奇偶性。

定理：当 $n$ 至少为 $2$ 时，$n$ 个数码的奇排列与偶排列个数相等，各为 $\frac{n!}{q}$ 个。

**Comment by Tiphereth-A** [comment]
> 我不知道群论这块儿整理得怎么样了，但是感觉肯定会涉及文件移动，会把群论那几个文件扔到新的文件夹里。

目前我计划将群论那块重命名为抽象代数，然后补充介绍代数系统、半群、环、域的一些概念（主要也是抄书

目前进度在 https://github.com/Tiphereth-A/OI-wiki/tree/semigroup 最近一直没什么空写，可能要等一周左右了

**Comment by Great-designer** [comment]
> 目前进度在 https://github.com/Tiphereth-A/OI-wiki/tree/semigroup 最近一直没什么空写，可能要等一周左右了

那我就先自行改了

**Comment by Great-designer** [comment]
有进展了嘛？我发了一个https://github.com/Tiphereth-A/OI-wiki/pull/1

**Comment by Tiphereth-A** [comment]
> 有进展了嘛？

谔谔, 在写了在写了 (

**Comment by Great-designer** [comment]
催稿~
