### ISSUE TITLE
[功能请求] 增加代码块标签页功能

### ISSUE THREAD

**Issue by Cubik65536** [OI-wiki/OI-wiki#4321]
### 我遇到的问题是

很多时候由于有多个不同语言/不同版本的代码示例，Wiki 文章中有可能会出现一堆代码挨在一起的情况。在这种情况下直接找到需要的语言/版本的示例不算非常直观，读者不太关注的示例也会占据文章位置并干扰注意力。所以希望可以使用类似标签页的功能对不同版本的代码进行区分，读者也可以快速找到自己想要的版本。

### 我希望能有这样的解决方案

Material for MkDocs 有一个 Content tabs 功能，其中可以像[这样](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#grouping-other-content)对代码块进行标签分类。我认为这是最好的方案。

P.S. 我认为的该方案的缺点：会需要花很长的时间将之前的文章中的大量的示例更改为这个样式

**Comment by StudyingFather** [comment]
[OI Wiki Next](https://next.oi-wiki.org/) 中已经实现了这一功能。

也欢迎对这一功能继续提出改进建议～
