### ISSUE TITLE
[内容有误] 筛法-莫比乌斯函数实现有误

### ISSUE THREAD

**Issue by gongyisheng** [OI-wiki/OI-wiki#4341]
### 请选择：

- [x] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/number-theory/sieve/

### 我发现页面有这样的问题

筛法求莫比乌斯函数的实现有误，以python为例
```
# Python Version
def pre():
    mu[1] = 1
    for i in range(2, int(1e7 + 1)):
        if v[i] == 0:
            mu[i] = -1
            tot = tot + 1
            p[tot] = i
        j = 1
        while j <= tot and i <= 1e7 // p[j]:
            v[i * p[j]] = 1
            if i % p[j] == 0:
                mu[i * p[j]] = 0
                break
            j = j + 1
       # 此处有误，这一行应该放在while循环内,if i%p[j]==0... else...逻辑下
        mu[i * p[j]] = -mu[i]
```
此外，筛法页面的实现代码有许多缺少定义和初始化的变量，代码本身存在编译错误。以上述代码为例，缺乏mu, v, tot, p的初始化，也没有return，让初学者会有种不知所云的感觉，不知能否提个pr修改实现代码

**Comment by iamtwz** [comment]
`mu[i * p[j]] = -mu[i]` 的缩进看起来确实有问题，可以修一下

关于变量的定义和初始化问题，Python 的代码由 C++ 版本翻译而来，所以代码逻辑与 C++ 版本是保持一致的，代码质量也一定程度上取决于 C++ 版本的代码。

**Comment by gongyisheng** [comment]
那需不需要和C++一起修了？

**Comment by iamtwz** [comment]
> 那需不需要和C++一起修了？

如果能一起改了最好 2333

**Comment by gongyisheng** [comment]
@iamtwz 先提了修复莫比乌斯函数代码的PR，缺少定义和初始化的变量的问题我会之后再开个新的PR
