### ISSUE TITLE
子问题：求解线性方程组

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4344]

**Comment by Great-designer** [comment]
## 求解线性方程组的高斯方法

Given a system of $n$ linear algebraic equations (SLAE) with $m$ unknowns. You are asked to solve the system: to determine if it has no solution, exactly one solution or infinite number of solutions. And in case it has at least one solution, find any of them.

Formally, the problem is formulated as follows: solve the system:

$$\begin{align}
a_{11} x_1 + a_{12} x_2 + &\dots + a_{1m} x_m = b_1 \\
a_{21} x_1 + a_{22} x_2 + &\dots + a_{2m} x_m = b_2\\
&\vdots \\
a_{n1} x_1 + a_{n2} x_2 + &\dots + a_{nm} x_m = b_n
\end{align}$$

where the coefficients $a_{ij}$ (for $i$ from 1 to $n$, $j$ from 1 to $m$) and $b_i$ ($i$ from 1 to $n$ are known and variables $x_i$ ($i$ from 1 to $m$) are unknowns.

This problem also has a simple matrix representation:

$$Ax = b,$$

where $A$ is a matrix of size $n \times m$ of coefficients $a_{ij}$ and $b$ is the column vector of size $n$.

It is worth noting that the method presented in this article can also be used to solve the equation modulo any number p, i.e.:

$$\begin{align}
a_{11} x_1 + a_{12} x_2 + &\dots + a_{1m} x_m \equiv b_1 \pmod p \\
a_{21} x_1 + a_{22} x_2 + &\dots + a_{2m} x_m \equiv b_2 \pmod p \\
&\vdots \\
a_{n1} x_1 + a_{n2} x_2 + &\dots + a_{nm} x_m \equiv b_n \pmod p
\end{align}$$

## 高斯

Strictly speaking, the method described below should be called "Gauss-Jordan", or Gauss-Jordan elimination, because it is a variation of the Gauss method, described by Jordan in 1887.

## 概述

The algorithm is a `sequential elimination` of the variables in each equation, until each equation will have only one remaining variable. If $n = m$, you can think of it as transforming the matrix $A$ to identity matrix, and solve the equation in this obvious case, where solution is unique and is equal to coefficient $b_i$.

Gaussian elimination is based on two simple transformation:   

* It is possible to exchange two equations
* Any equation can be replaced by a linear combination of that row (with non-zero coefficient), and some other rows (with arbitrary coefficients).

In the first step, Gauss-Jordan algorithm divides the first row by $a_{11}$. Then, the algorithm adds the first row to the remaining rows such that the coefficients in the first column becomes all zeros. To achieve this, on the i-th row, we must add the first row multiplied by $- a_{i1}$. Note that, this operation must also be performed on vector $b$. In a sense, it behaves as if vector $b$ was the $m+1$-th column of matrix $A$.

As a result, after the first step, the first column of matrix $A$ will consists of $1$ on the first row, and $0$ in other rows.

Similarly, we perform the second step of the algorithm, where we consider the second column of second row. First, the row is divided by $a_{22}$, then it is subtracted from other rows so that all the second column becomes $0$ (except for the second row).

We continue this process for all columns of matrix $A$. If $n = m$, then $A$ will become identity matrix.

## 搜索旋转元素

The described scheme left out many details. At the $i$th step, if $a_{ii}$ is zero, we cannot apply directly the described method. Instead, we must first `select a pivoting row`: find one row of the matrix where the $i$th column is non-zero, and then swap the two rows.

Note that, here we swap rows but not columns. This is because if you swap columns, then when you find a solution, you must remember to swap back to correct places. Thus, swapping rows is much easier to do.

In many implementations, when $a_{ii} \neq 0$, you can see people still swap the $i$th row with some pivoting row, using some heuristics such as choosing the pivoting row with maximum absolute value of $a_{ji}$. This heuristic is used to reduce the value range of the matrix in later steps. Without this heuristic, even for matrices of size about $20$, the error will be too big and can cause overflow for floating points data types of C++.

## 特例

In the case where $m = n$ and the system is non-degenerate (i.e. it has non-zero determinant, and has unique solution), the algorithm described above will transform $A$ into identity matrix.

Now we consider the `general case`, where $n$ and $m$ are not necessarily equal, and the system can be degenerate. In these cases, the pivoting element in $i$th step may not be found. This means that on the $i$th column, starting from the current line, all contains zeros. In this case, either there is no possible value of variable $x_i$ (meaning the SLAE has no solution), or $x_i$ is an independent variable and can take arbitrary value. When implementing Gauss-Jordan, you should continue the work for subsequent variables and just skip the $i$th column (this is equivalent to removing the $i$th column of the matrix).

So, some of the variables in the process can be found to be independent. When the number of variables, $m$ is greater than the number of equations, $n$, then at least $m - n$ independent variables will be found.

In general, if you find at least one independent variable, it can take any arbitrary value, while the other (dependent) variables are expressed through it.  This means that when we work in the field of real numbers, the system potentially has infinitely many solutions. But you should remember that when there are independent variables, SLAE can have no solution at all. This happens when the remaining untreated equations have at least one non-zero constant term. You can check this by assigning zeros to all independent variables, calculate other variables, and then plug in to the original SLAE to check if they satisfy it.

## 实现

以下是Gauss-Jordan的实现。使用启发式方法选择数据透视行：在当前列中选择最大值。

函数“gauss”的输入是系统矩阵 $a$。这个矩阵的最后一列是向量 $b$。

函数返回系统 $(0, 1,\textrm{or } \infty)$ 的解数。如果至少存在一个解决方案，那么它将在向量 $ans$ 中返回。

```{.cpp file=gauss}
const double EPS = 1e-9;
const int INF = 2; // it doesn't actually have to be infinity or a big number

int gauss (vector < vector<double> > a, vector<double> & ans) {
	int n = (int) a.size();
	int m = (int) a[0].size() - 1;

	vector<int> where (m, -1);
	for (int col=0, row=0; col<m && row<n; ++col) {
		int sel = row;
		for (int i=row; i<n; ++i)
			if (abs (a[i][col]) > abs (a[sel][col]))
				sel = i;
		if (abs (a[sel][col]) < EPS)
			continue;
		for (int i=col; i<=m; ++i)
			swap (a[sel][i], a[row][i]);
		where[col] = row;

		for (int i=0; i<n; ++i)
			if (i != row) {
				double c = a[i][col] / a[row][col];
				for (int j=col; j<=m; ++j)
					a[i][j] -= a[row][j] * c;
			}
		++row;
	}

	ans.assign (m, 0);
	for (int i=0; i<m; ++i)
		if (where[i] != -1)
			ans[i] = a[where[i]][m] / a[where[i]][i];
	for (int i=0; i<n; ++i) {
		double sum = 0;
		for (int j=0; j<m; ++j)
			sum += ans[j] * a[i][j];
		if (abs (sum - a[i][m]) > EPS)
			return 0;
	}

	for (int i=0; i<m; ++i)
		if (where[i] == -1)
			return INF;
	return 1;
}
```

实现的说明：

*该函数使用两个指针-当前列 $col$ 和当前行 $row$。

*对于每个变量 $x_i$，值 $where(i)$ 是该列不为零的行。这个向量是必需的，因为一些变量可以是独立的。

*在这个实现中，当前的第 $i$ 行没有如上所述被 $a_{ii}$ 分割，因此最终矩阵不是单位矩阵（尽管分割第 $i$ 行显然有助于减少错误）。

*找到解决方案后，将其插入矩阵中，以检查系统是否至少有一个解决方案。如果测试解决方案成功，则函数返回1或 $\inf$，具体取决于是否至少有一个自变量。

## 复杂度

现在我们应该估计这个算法的复杂度。算法由 $m$ 个阶段组成，每个阶段：

*搜索并重新排列旋转行。当使用上述启发式时，这需要 $O(n + m)$ 。

*如果找到当前列中的pivot元素，则必须将此方程添加到所有其他方程中，这需要花费 $O(nm)$ 时间。

因此，算法的最终复杂度为 $O(\min (n, m) . nm)$。

在 $n=m$ 的情况下，复杂性仅为 $O(n^3)$。

请注意，当SLAE不是实数，而是模2时，系统的求解速度会更快，如下所述。

## 算法的加速

通过将算法分为两个阶段：正向和反向，可以将之前的实现速度提高两倍：

*正向阶段：与前面的实现类似，但当前行只添加到它后面的行中。因此，我们得到了一个三角形矩阵而不是对角矩阵。

*反相：当矩阵是三角形时，我们首先计算最后一个变量的值。然后插入此值以查找下一个变量的值。然后插入这两个值以查找下一个变量。

反向只需要 $O(nm)$，这比正向快得多。在前向阶段，我们将操作数减少一半，从而减少实现的运行时间。

## 求解取模SLAE

对于某些模块中的SLAE求解，我们仍然可以使用所描述的算法。然而，如果取模等于2，我们可以使用逐位运算和C++位集数据类型更有效地执行Gauss-Jordan消元：

```cpp
int gauss (vector < bitset<N> > a, int n, int m, bitset<N> & ans) {
	vector<int> where (m, -1);
	for (int col=0, row=0; col<m && row<n; ++col) {
		for (int i=row; i<n; ++i)
			if (a[i][col]) {
				swap (a[i], a[row]);
				break;
			}
		if (! a[row][col])
			continue;
		where[col] = row;

		for (int i=0; i<n; ++i)
			if (i != row && a[i][col])
				a[i] ^= a[row];
		++row;
	}
        // The rest of implementation is the same as above
}
```

由于我们使用位压缩，实现不仅更短，而且速度快32倍。

## 关于选择旋转行的不同启发法的一点说明

对于使用什么样的启发法没有一般规则。

在以前的实现中使用的启发式方法在实践中效果很好。它还提供了和“完全旋转”几乎相同的答案，即在其子矩阵的所有元素中搜索旋转行（从当前行和当前列）。

不过，您应该注意，这两种启发式都取决于原始方程的缩放比例。例如，如果其中一个等式乘以$10^6$，那么几乎可以肯定在第一步中会选择这个等式作为枢轴。这似乎很奇怪，所以改变为更复杂的启发式，称为“隐式旋转”似乎是合乎逻辑的。

隐式旋转将元素进行比较，就像两条线都被规范化了一样，这样最大的元素将是一个整体。要实现此技术，需要在每行中保持最大值（或保持每行的最大值为一，但这可能会导致累积错误的增加）。

## 改进求解算法

尽管有各种各样的启发式算法，高斯-若尔当算法仍然会在特殊矩阵中导致较大的错误，即使大小为 $50 - 100$。

因此，有时必须通过应用简单的数值方法（例如，简单迭代法）来改进得到的高斯-若尔当解。

因此，求解分为两步：首先应用高斯-若尔当算法，然后在第一步中采用以初始解为解的数值方法。

## 习题
* [Spoj - Xor Maximization](http://www.spoj.com/problems/XMAX/)
* [Codechef - Knight Moving](https://www.codechef.com/SEP12/problems/KNGHTMOV)
* [Lightoj - Graph Coloring](http://lightoj.com/volume_showproblem.php?problem=1279)
* [UVA 12910 - Snakes and Ladders](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=4775)
* [TIMUS1042 Central Heating](http://acm.timus.ru/problem.aspx?space=1&num=1042)
* [TIMUS1766 Humpty Dumpty](http://acm.timus.ru/problem.aspx?space=1&num=1766)
* [TIMUS1266 Kirchhoff's Law](http://acm.timus.ru/problem.aspx?space=1&num=1266)
* [Codeforces - No game no life](https://codeforces.com/problemset/problem/1411/G)

**Comment by Great-designer** [comment]
这个和 #4294 一起，用于补充站点的“行列式”和“高斯消元”。

（#4150 包含的最后一部分）

**Comment by Great-designer** [comment]
现在线性代数部分大概只剩下这个了，如果不写新东西的话

**Comment by Great-designer** [comment]
## 引入

高斯消元法（Gauss-Jordan elimination）是求解线性方程组的经典算法，它在当代数学中有着重要的地位和价值，是线性代数课程教学的重要组成部分。

高斯消元法除了用于线性方程组求解外，还可以用于行列式计算、求矩阵的逆，以及其他计算机和工程方面。

夏建明等人之前提出了应用图形处理器 (GPU) 加速求解线性方程组的高斯消元法，所提出的算法与基于 CPU 的算法相比较取得更快的运算速度。二是提出各种变异高斯消元法以满足特定工作的需要。

* * *

## 消元法及高斯消元法思想

### 定义

消元法是将方程组中的一方程的未知数用含有另一未知数的代数式表示，并将其带入到另一方程中，这就消去了一未知数，得到一解；或将方程组中的一方程倍乘某个常数加到另外一方程中去，也可达到消去一未知数的目的。消元法主要用于二元一次方程组的求解。

### 解释

例一：利用消元法求解二元一次线性方程组：

$$
\left\{\begin{aligned}
4x+y&=100 \notag \\
x-y&=100 \notag
\end{aligned}\right.
$$

解：将方程组中两方程相加，消元 $y$ 可得：

$5x = 200$

解得：

$x = 40$

将 $x = 40$ 代入方程组中第二个方程可得：

$y = -60$

### 消元法理论的核心

消元法理论的核心是三种初等行变换：

- 一方程乘以非零数 $k$，解不变；
- 两方程互换，解不变；
- 一方程乘以数 $k$ 加上另一方程，解不变。

### 高斯消元法思想概念

德国数学家高斯对消元法进行了思考分析，得出了如下结论：

- 在消元法中，参与计算和发生改变的是方程中各变量的系数；

- 各变量并未参与计算，且没有发生改变；

- 可以利用系数的位置表示变量，从而省略变量；

- 在计算中将变量简化省略，方程的解不变。

> 高斯在这些结论的基础上，提出了高斯消元法，首先将方程的增广矩阵利用行初等变换化为行最简形，然后以线性无关为准则对自由未知量赋值，最后列出表达方程组通解。

按照指定顺序进行消元的办法称为高斯消元法。

记单位阵为 $I$。假设 $A$ 的逆矩阵存在，那么消元的过程就是求 $A$ 的逆矩阵的过程。于是就有：

$$
Ax=Ib\implies Ix=A^{-1}b
$$

如果在等式两端，同时左乘一系列初等矩阵，使得 $A$ 变为单位阵 $I$，那么 $I$ 将同时变为 $A$ 的逆。

按照方程的观点，左乘上述三种矩阵，都是对“行”操作，即对方程操作，本质还是加减消元法。由于引入了方程换位与扩大倍数，可以保证消元的按序进行。

因为逆可能不存在，未必一定需要求逆。对于一般的矩阵 $A$，可以对 $A$ 做行变换消元，能消多少消多少，直到无法进行为止。上面说“求逆”只是为了方便理解。

### 行最简型矩阵

一个矩阵 $A$，行变换消元至无法进行，会变成：

$$
Ax=Ib\overset{\tiny B\thinspace :=\thinspace PA}{\Longrightarrow} Bx=Pb
$$

就是对 $A$ 左乘了变换 $P$，变为最终的矩阵 $B$。最终的矩阵 $B$ 一定是行最简形矩阵。行最简形矩阵是引入概念“秩”最重要的前置概念，是行变换消元得来的最终结果。

行最简形矩阵，要求在阶梯形矩阵中：

- 非零行的第一个非零元素全是 $1$。

- 非零行的第一个元素 $1$ 所在列的其余元素全为零。

也就是说，消元的顺序是，每次先从左上角，用第一个元素消这一列。要把当前行拿来消其他行上相应元素的首元素变为 $1$。不仅把下方的元素全部消成 $0$，同时也要把上方的元素也全部消成 $0$。

行最简形矩阵 $B$ 是由矩阵 $A$ 唯一确定的，行阶梯形矩阵 $B$ 的行数，即阶梯数，也是由矩阵 $A$ 唯一确定的。阶梯数也称为矩阵 $A$ 的 **秩**（rank），阶梯数越高则秩越高。读者可以把秩理解为“等级”，事实上“秩”与“等级”对应于英语的同一个单词。

## 高斯消元五步骤法

## 解释

高斯消元法在将增广矩阵化为最简形后对于自由未知量的赋值，需要掌握线性相关知识，且赋值存在人工经验的因素，使得在学习过程中有一定的困难，将高斯消元法划分为五步骤，从而提出五步骤法，内容如下：

1. 增广矩阵行初等行变换为行最简形；

2. 还原线性方程组；

3. 求解第一个变量；

4. 补充自由未知量；

5. 列表示方程组通解。

利用实例进一步说明该算法的运作情况。

## 过程

例二：利用高斯消元法五步骤法求解线性方程组：

$$
\left\{\begin{aligned}
2x_1+5x_3+6x_4&=9 \notag \\
x_3+x_4&=-4 \notag \\
2x_3+2x_4&=-8 \notag
\end{aligned}\right.
$$

### 增广矩阵行（初等）变换为行最简形

所谓增广矩阵，即为方程组系数矩阵 $A$ 与常数列 $b$ 的并生成的新矩阵，即 $(A | b)$，增广矩阵行初等变换化为行最简形，即是利用了高斯消元法的思想理念，省略了变量而用变量的系数位置表示变量，增广矩阵中用竖线隔开了系数矩阵和常数列，代表了等于符号。

$$
\left(\begin{matrix}
2 & 0 & 5 & 6 \\
0 & 0 & 1 & 1 \\
0 & 0 & 2 & 2
\end{matrix} \middle|
\begin{matrix}
9 \\
-4 \\
-8
\end{matrix} \right)
$$

$$
\xrightarrow{r_3-2r_2}
\left(\begin{matrix}
2 & 0 & 5 & 6 \\
0 & 0 & 1 & 1 \\
0 & 0 & 0 & 0
\end{matrix} \middle|
\begin{matrix}
9 \\
-4 \\
0
\end{matrix} \right)
$$

化为行阶梯形

$$
\xrightarrow{\frac{r_1}{2}}
\left(\begin{matrix}
1 & 0 & 2.5 & 3 \\
0 & 0 & 1 & 1 \\
0 & 0 & 0 & 0
\end{matrix} \middle|
\begin{matrix}
4.5 \\
-4 \\
0
\end{matrix} \right)
$$

$$
\xrightarrow{r_1-r_2 \times 2.5}
\left(\begin{matrix}
1 & 0 & 0 & 0.5 \\
0 & 0 & 1 & 1 \\
0 & 0 & 0 & 0
\end{matrix} \middle|
\begin{matrix}
14.5 \\
-4 \\
0
\end{matrix} \right)
$$

化为最简形

### 还原线性方程组

$$
\left\{\begin{aligned}
x_1+0.5x_4 &= 14.5 \notag\\
x_3+x_4 &= -4 \notag \\
\end{aligned}\right.
$$

解释

> 所谓的还原线性方程组，即是在行最简形的基础上，将之重新书写为线性方程组的形式，即将行最简形中各位置的系数重新赋予变量，中间的竖线还原为等号。

### 求解第一个变量

$$
\left\{\begin{aligned}
x_1 &= -0.5x_4+14.5\notag \\
x_3 &= -x_4-4\notag
\end{aligned}\right.
$$

解释

> 即是对于所还原的线性方程组而言，将方程组中每个方程的第一个变量，用其他量表达出来。如方程组两方程中的第一个变量 $x_1$ 和 $x_3$

### 补充自由未知量

$$
\left\{\begin{aligned}
x_1 &= -0.5x_4+14.5 \notag \\
x_2 &= x_2 \notag \\
x_3 &= -x_4-4 \notag \\
x_4 &= x_4 \notag
\end{aligned}\right.
$$

解释

> 第 3 步中，求解出变量 $x_1$ 和 $x_3$，从而说明了方程剩余的变量 $x_2$ 和 $x_4$ 不受方程组的约束，是自由未知量，可以取任意值，所以需要在第 3 步骤解得基础上进行解得补充，补充的方法为 $x_2 = x_2,x_4 = x_4$，这种解得补充方式符合自由未知量定义，并易于理解，因为是自由未知量而不受约束，所以只能自己等于自己。

### 列表示方程组的通解

$$
\begin{aligned}
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{pmatrix} &=
\begin{pmatrix} 0 \\ 1 \\ 0 \\ 0 \end{pmatrix} x_2+
\begin{pmatrix} -0.5 \\ 0 \\ -1 \\ 1 \end{pmatrix} x_4 +
\begin{pmatrix} 14.5 \\ 0 \\ -4 \\ 0 \end{pmatrix} \notag \\
&= \begin{pmatrix} 0 \\ 1 \\ 0 \\ 0 \end{pmatrix} C_1+
\begin{pmatrix} -0.5 \\ 0 \\ -1 \\ 1 \end{pmatrix} C_2 +
\begin{pmatrix} 14.5 \\ 0 \\ -4 \\ 0 \end{pmatrix} \notag
\end{aligned}
$$

其中 $C_1$ 和 $C_2$ 为任意常数。

解释

> 即在第 4 步的基础上，将解表达为列向量组合的表示形式，同时由于 $x_2$ 和 $x_4$ 是自由未知量，可以取任意值，所以在解得右边，令二者分别为任意常数 $C_1$ 和 $C_2$，即实现了对方程组的求解。

* * *

## 矩阵的等价

矩阵的 **等价** 就是矩阵的秩相同。秩相同的矩阵相互等价，秩不同的矩阵相互不等价。

只要矩阵 $A$ 与矩阵 $B$ 的秩相同，就一定存在可逆矩阵 $P$,$Q$ 使得：

$$
PAQ=B
$$

这是因为，右乘操作相当于对列操作，可以将行最简形矩阵进行列重排，再列消元，得到“标准形矩阵”，只有左上角是单位阵。由于秩相同，标准型矩阵就相同。于是根据可逆性一整理，就能整理成左乘 $P$ 右乘 $Q$ 的形式。

引出秩的概念，是“按行看”观点的完结，后文线性相关部分进入重要的“按列看”观点。

## 行列式计算

### 解释

$N \times N$ 方阵行列式（Determinant）可以理解为所有列向量所夹的几何体的有向体积

例如：

$$
\begin{vmatrix}
1 & 0 \\
0 & 1 \end{vmatrix} = 1
$$

$$
\begin{vmatrix}
1 & 2 \\
2 & 1 \end{vmatrix} = -3
$$

行列式有公式

$$
\operatorname{det}(A)=\sum_{\sigma \in S_{n}} \operatorname{sgn}(\sigma) \prod_{i=1}^{n} a_{i, \sigma(i)}
$$

其中 $S_n$ 是指长度为 $n$ 的全排列的集合，$\sigma$ 就是一个全排列，如果 $\sigma$ 的逆序对对数为偶数，则 $\operatorname{sgn}(\sigma)=1$，否则 $\operatorname{sgn}(\sigma)=−1$。

通过体积概念理解行列式不变性是一个非常简单的办法：

- 矩阵转置，行列式不变；

- 矩阵行（列）交换，行列式取反；

- 矩阵行（列）相加或相减，行列式不变；

- 矩阵行（列）所有元素同时乘以数 $k$，行列式等比例变大。

> 由此，对矩阵应用高斯消元之后，我们可以得到一个对角线矩阵，此矩阵的行列式由对角线元素之积所决定。其符号可由交换行的数量来确定（如果为奇数，则行列式的符号应颠倒）。因此，我们可以在 $O(n^3)$ 的复杂度下使用高斯算法计算矩阵。
>
> 注意，如果在某个时候，我们在当前列中找不到非零单元，则算法应停止并返回 0。

* * *

### 实现

```c++
const double EPS = 1E-9;
int n;
vector<vector<double> > a(n, vector<double>(n));

double det = 1;
for (int i = 0; i < n; ++i) {
  int k = i;
  for (int j = i + 1; j < n; ++j)
    if (abs(a[j][i]) > abs(a[k][i])) k = j;
  if (abs(a[k][i]) < EPS) {
    det = 0;
    break;
  }
  swap(a[i], a[k]);
  if (i != k) det = -det;
  det *= a[i][i];
  for (int j = i + 1; j < n; ++j) a[i][j] /= a[i][i];
  for (int j = 0; j < n; ++j)
    if (j != i && abs(a[j][i]) > EPS)
      for (int k = i + 1; k < n; ++k) a[j][k] -= a[i][k] * a[j][i];
}

cout << det;
```

## 矩阵求逆

对于方阵 $A$，若存在方阵 $A^{-1}$，使得 $A \times A^{-1} = A^{-1} \times A = I$，则称矩阵 $A$ 可逆，$A^{-1}$ 被称为它的逆矩阵。

给出 $n$ 阶方阵 $A$，求解其逆矩阵的方法如下：

1. 构造 $n \times 2n$ 的矩阵 $(A, I_n)$；
2. 用高斯消元法将其化简为最简形 $(I_n, A^{-1})$，即可得到 $A$ 的逆矩阵 $A^{-1}$。如果最终最简形的左半部分不是单位矩阵 $I_n$，则矩阵 $A$ 不可逆。

根据上文，初等行变换等价于左乘初等矩阵，那么只要矩阵 $A$ 的逆存在，将 $A$ 变为 $I$ 的变换，等价于将 $A$ 左乘一系列初等矩阵得到 $I$，左乘的一系列初等矩阵构成了矩阵 $A$ 的逆。所以，矩阵 $I$ 左乘这一系列初等矩阵会得到矩阵 $A$ 的逆，矩阵 $I$ 经过同样的变换也会变为 $A$ 的逆。

## 生成树计数

一个无向图的生成树个数为邻接矩阵度数矩阵去一行一列的行列式。

详见：[矩阵树定理](../../graph/matrix-tree.md)

例如，一个正方形图的生成树个数

$$
\begin{pmatrix}
2 & 0 & 0 & 0 \\
0 & 2 & 0 & 0 \\
0 & 0 & 2 & 0 \\
0 & 0 & 0 & 2 \end{pmatrix}-\begin{pmatrix}
0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0 \end{pmatrix}=\begin{pmatrix}
2 & -1 & 0 & -1 \\
-1 & 2 & -1 & 0 \\
0 & -1 & 2 & -1 \\
-1 & 0 & -1 & 2 \end{pmatrix}
$$

$$
\begin{vmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2 \end{vmatrix} = 4
$$

可以用高斯消元解决，时间复杂度为 $O(n^3)$。

??? note "实现"
    ```cpp
    #include <algorithm>
    #include <cassert>
    #include <cmath>
    #include <cstdio>
    #include <cstring>
    #include <iostream>
    using namespace std;
    #define MOD 100000007
    #define eps 1e-7
    
    struct matrix {
      static const int maxn = 20;
      int n, m;
      double mat[maxn][maxn];
    
      matrix() { memset(mat, 0, sizeof(mat)); }
    
      void print() {
        cout << "MATRIX " << n << " " << m << endl;
        for (int i = 0; i < n; i++) {
          for (int j = 0; j < m; j++) {
            cout << mat[i][j] << "\t";
          }
          cout << endl;
        }
      }
    
      void random(int n) {
        this->n = n;
        this->m = n;
        for (int i = 0; i < n; i++)
          for (int j = 0; j < n; j++) mat[i][j] = rand() % 100;
      }
    
      void initSquare() {
        this->n = 4;
        this->m = 4;
        memset(mat, 0, sizeof(mat));
        mat[0][1] = mat[0][3] = 1;
        mat[1][0] = mat[1][2] = 1;
        mat[2][1] = mat[2][3] = 1;
        mat[3][0] = mat[3][2] = 1;
        mat[0][0] = mat[1][1] = mat[2][2] = mat[3][3] = -2;
        this->n--;  // 去一行
        this->m--;  // 去一列
      }
    
      double gauss() {
        double ans = 1;
        for (int i = 0; i < n; i++) {
          int sid = -1;
          for (int j = i; j < n; j++)
            if (abs(mat[j][i]) > eps) {
              sid = j;
              break;
            }
          if (sid == -1) continue;
          if (sid != i) {
            for (int j = 0; j < n; j++) {
              swap(mat[sid][j], mat[i][j]);
              ans = -ans;
            }
          }
          for (int j = i + 1; j < n; j++) {
            double ratio = mat[j][i] / mat[i][i];
            for (int k = 0; k < n; k++) {
              mat[j][k] -= mat[i][k] * ratio;
            }
          }
        }
        for (int i = 0; i < n; i++) ans *= mat[i][i];
        return abs(ans);
      }
    };
    
    int main() {
      srand(1);
      matrix T;
      // T.random(2);
      T.initSquare();
      T.print();
      double ans = T.gauss();
      T.print();
      cout << ans << endl;
    }
    ```

## 高斯消元法解异或方程组

异或方程组是指形如

$$
\begin{cases}
a_{1,1}x_1 \oplus a_{1,2}x_2 \oplus \cdots \oplus a_{1,n}x_n &= b_1\\
a_{2,1}x_1 \oplus a_{2,2}x_2 \oplus \cdots \oplus a_{2,n}x_n &= b_2\\
\cdots &\cdots \\ a_{m,1}x_1 \oplus a_{m,2}x_2 \oplus \cdots \oplus a_{m,n}x_n &= b_1
\end{cases}
$$

的方程组，其中 $\oplus$ 表示“按位异或”（即 `xor` 或 C++ 中的 `^`），且式中所有系数/常数（即 $a_{i,j}$ 与 $b_i$）均为 $0$ 或 $1$。

由于“异或”符合交换律与结合律，故可以按照高斯消元法逐步消元求解。值得注意的是，我们在消元的时候应使用“异或消元”而非“加减消元”，且不需要进行乘除改变系数（因为系数均为 $0$ 和 $1$）。

注意到异或方程组的增广矩阵是 $01$ 矩阵（矩阵中仅含有 $0$ 与 $1$），所以我们可以使用 C++ 中的 `std::bitset` 进行优化，将时间复杂度降为 $O(\dfrac{n^2m}{\omega})$，其中 $n$ 为元的个数，$m$ 为方程条数，$\omega$ 一般为 $32$（与机器有关）。

参考实现：

```cpp
std::bitset<1010> matrix[2010];  // matrix[1~n]：增广矩阵，0 位置为常数

std::vector<bool> GaussElimination(
    int n, int m)  // n 为未知数个数，m 为方程个数，返回方程组的解（多解 /
                   // 无解返回一个空的 vector）
{
  for (int i = 1; i <= n; i++) {
    int cur = i;
    while (cur <= m && !matrix[cur].test(i)) cur++;
    if (cur > m) return std::vector<bool>(0);
    if (cur != i) swap(matrix[cur], matrix[i]);
    for (int j = 1; j <= m; j++)
      if (i != j && matrix[j].test(i)) matrix[j] ^= matrix[i];
  }
  std::vector<bool> ans(n + 1, 0);
  for (int i = 1; i <= n; i++) ans[i] = matrix[i].test(0);
  return ans;
}
```

## 练习题

- [Codeforces - 巫师和赌注](http://codeforces.com/contest/167/problem/E)
- [luogu - SDOI2010 外星千足虫](https://www.luogu.com.cn/problem/P2447)

**Comment by nexplorer-3e** [comment]
看原页面 comment 的说法 gauss 是解 xor 方程组的一种算法
所以是否应该将线代的高斯消元单独开一个 md
以及 线代基本概念（如初等矩阵，最简行阶梯矩阵，初等行变换等等）的现在有无开一个 intro 的计划
虽然要是能将内容合到现在有的 矩阵 然后再在矩阵上写 href 也好

**Comment by Great-designer** [comment]
> 看原页面 comment 的说法 gauss 是解 xor 方程组的一种算法

Gauss-Jordan 是**解方程组**的算法，相当于 LU 分解算法的扩展（类似于 LUP 分解算法），恰好也可以用于行列式。和是不是“xor”关系不大。

> 所以是否应该将线代的高斯消元单独开一个 md

目前已经单独开了一个 md 了。

> 以及 线代基本概念（如初等矩阵，最简行阶梯矩阵，初等行变换等等）的现在有无开一个 intro 的计划

您好，现在已经要结束了，后台剩下对角化和Jordan分解、初等变换和行列式、LU分解、Gauss-Jordan算法，共4个pr。更多的线性代数都在内积空间之后，我不知道有没有写的必要。

**初等矩阵**和**初等行变换**在初等变换和行列式，**最简行阶梯矩阵**在Gauss-Jordan算法。

对角化和Jordan分解、初等变换和行列式，这两个pr完全是线性代数基本概念，没有算法相关。LU分解和Gauss-Jordan算法有算法相关。

 > 虽然要是能将内容合到现在有的 矩阵 然后再在矩阵上写 href 也好

这个……目前内容已经非常长了。线性代数是个很复杂的玩意儿，复杂到考研和研究生都在学好几个学期的那种，真的不是只有一个矩阵这么简单。可以想象成类似于初等数论那样，是一大堆东西，光挤到一个素数页面说全是素数的性质，肯定是无法做到的。

**Comment by nexplorer-3e** [comment]
蛮好的，虽然我是想把 oiwiki 当作线代概念手册方便做题时对照着看
感谢您对社区的贡献！
________________________________
