### ISSUE TITLE
Add 范德蒙德卷积

### ISSUE THREAD

**Issue by tidongCrazy** [OI-wiki/OI-wiki#4356]
### 我希望能添加的内容是

范德蒙德卷积

### 我了解到的相关参考资料有

[1](https://www.cut-the-knot.org/arithmetic/algebra/VandermondeConvolution.shtml)

**Comment by Tiphereth-A** [comment]
先放一个参考资料
https://www.cut-the-knot.org/arithmetic/algebra/VandermondeConvolution.shtml

**Comment by Great-designer** [comment]
这看起来是生成函数的例题，在上述proof 4里面写了
