### ISSUE TITLE
[Meta] Consider to participate in Hacktoberfest event

### ISSUE THREAD

**Issue by imba-tjd** [OI-wiki/OI-wiki#4358]
https://hacktoberfest.com/

This is an annual event hosted by DigitalOcean.

In a word, once you make 4 qualified PRs in October, DO will send you a T-Shirt for free.

As the project mantainer, you can either add the hacktoberfest GitHub topic to the repo, or add hacktoberfest-accepted label to each PR.

The downside is that this may cause lots of low quality PR/spam.

What do you think?

**Comment by Great-designer** [comment]
试图翻译：

https://hacktoberfest.com/
这是由DigitalOcean主办的年度活动。
总之，一旦您在10月份获得4个合格的个人记录，DO将免费为您发送一件T恤。
作为项目管理员，您可以将hacktobeffest GitHub主题添加到repo，或者将hackto beffest接受标签添加到每个PR。
缺点是，这可能会导致大量低质量的PR/垃圾邮件。
你怎么认为？

——没看懂。——

**Comment by Xeonacid** [comment]
Hi,
We already have a "hacktoberfest" topic, and we'll keep it this year.
![image](https://user-images.githubusercontent.com/13995937/192995774-a2eb6a34-7ce8-478a-9c03-2164266078e4.png)
During the past years, not too many low-quality PRs were received.
Waiting for your contribution!

**Comment by imba-tjd** [comment]
:joy: I didn't notice that. I had searched it in this repo but got no result, so I thought you didn't know it.
