### ISSUE TITLE
[功能请求] 自动预览

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4363]
### 我遇到的问题是

对新pr的自动预览

### 我希望能有这样的解决方案

当新pr发起时bot对pr一楼进行md文件预览网址粘贴

**Comment by alphagocc** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/28982331/193079863-eb69fc73-d7d9-4227-971a-55965e6a1338.png">
ci这里就可以看吧。

另外感觉这个功能非常污染邮件列表

**Comment by Great-designer** [comment]
> 另外感觉这个功能非常污染邮件列表

只在pr发起时修改一楼就行了。pr修改时不用操作

**Comment by Enter-tainer** [comment]
我在netlify后台加了个通知，可以观察一下有没有效果

**Comment by Tiphereth-A** [comment]
> 我在netlify后台加了个通知，可以观察一下有没有效果

看起来有点 verbose, 感觉没什么必要的样子 🤔

**Comment by Great-designer** [comment]
> 我在netlify后台加了个通知，可以观察一下有没有效果

不错

**Comment by Enter-tainer** [comment]
想了想感觉好像也没什么区别，可以直接点check里面的details

**Comment by Great-designer** [comment]
> 想了想感觉好像也没什么区别，可以直接点check里面的details

还是有用的。在check正在运行的时候，新预览和旧预览都无法通过details观看，注上网址还可以在check运行时，随时查看上一个版本的旧预览。

**Comment by Enter-tainer** [comment]
@Enter-tainer 这个notification好像每次commit都会触发，确实是有点吵了...暂时先关掉了

**Comment by Great-designer** [comment]
> @Enter-tainer 这个notification好像每次commit都会触发，确实是有点吵了...暂时先关掉了

所以希望只在pull request发起的时候触发一次就够了，毕竟每次修改和部署之后使用的是覆盖办法，网址并不改变

**Comment by Tiphereth-A** [comment]
不能理解这个功能的必要性, 感觉现有的已经足够使用了, 网址格式是固定的, 看一遍就能记下来的吧 🤔

**Comment by Great-designer** [comment]
感觉点击运行完毕的preview即可完成
