### ISSUE TITLE
关于部分公式字符改为 mathtt 的讨论

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#4374]
#3757 中提到 #3344 中的修改可能可以补充格式手册, 然而似乎在得出结论之前该 PR 就已经合并了, 所以这里开个 issue 用于讨论

**Comment by Tiphereth-A** [comment]
@Great-designer 可以解释一下为什么将这个 issue 移除出迭代计划嘛 🤔

**Comment by Great-designer** [comment]
> @Great-designer 可以解释一下为什么将这个 issue 移除出迭代计划嘛 🤔

并没有移出迭代计划，而是移到了最后一行。在上半区分类全部为pull request，在下半区分类全部为Issue。

**Comment by Tiphereth-A** [comment]
> 并没有移出迭代计划，而是移到了最后一行。在上半区分类全部为pull request，在下半区分类全部为Issue。

啊这, 对不起, 我的问题 😇

**Comment by Tiphereth-A** [comment]
move to #4525
