### ISSUE TITLE
[内容有误] 并查集删除操作的实现有误

### ISSUE THREAD

**Issue by Zeng1998** [OI-wiki/OI-wiki#4379]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/dsu/#%E5%88%A0%E9%99%A4

### 我发现页面有这样的问题

删除操作的实现有误

**Comment by Tiphereth-A** [comment]
@CCXXXI

**Comment by Zeng1998** [comment]
删除操作是否还是有问题？

现在删除操作是`pa[x] = x;` 

如果删除后又继续合并呢？还是有可能成为非叶子节点，这样子虚拟节点又没了，我感觉应该是`pa[x]=一个新的虚拟节点`

**Comment by CCXXXI** [comment]
> 删除操作是否还是有问题？
> 
> 现在删除操作是`pa[x] = x;`
> 
> 如果删除后又继续合并呢？还是有可能成为非叶子节点，这样子虚拟节点又没了，我感觉应该是`pa[x]=一个新的虚拟节点`

类似 [UVA11987](https://www.luogu.com.cn/problem/UVA11987) 的情况没有问题

如果删除后又继续合并，且合并的节点不包含未删除节点，且合并后需要再次删除，确实会出问题
