### ISSUE TITLE
Add Windows 和 mac 上 CLion 的工具链配置

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#4381]
### 我希望能添加的内容是

具体参见 https://github.com/OI-wiki/OI-wiki/issues/4377#issuecomment-1269484702

**Comment by Cubik65536** [comment]
我这边有 macOS 设备，可以过段时间试着根据已有内容补充一下 macOS 相关内容

**Comment by yanboishere** [comment]
我这边也有 mac设备，立个Flag，这周有时间就更（
