### ISSUE TITLE
Add 有序队列 sorted_queue

### ISSUE THREAD

**Issue by Lyccrius** [OI-wiki/OI-wiki#4432]

**Comment by ksyx** [comment]
和 Priority queue / heap 有什么区别呢

**Comment by Lyccrius** [comment]
从字面意思上讲，“有序队列”似乎与“优先队列”这一概念很难区分，网络上不少个人博客也将 `priority_queue` 打上了“有序队列”的标签。然而在[NOI大纲](https://www.noi.cn/generic/web/viewer.html?file=/upload/resources/file/2021/04/06/152179.pdf)当中，“有序队列”是作为与“优先队列”并列的知识点出现的，那么想必其应用与实现应当与其他数据结构有着或多或少的差异。从目前本人初步搜集的资料来看，“有序队列”在脱离其相关题目的情况下，并不能用简洁明了的给出一个概念性的描述。故在此新开一个 issue ~~，等明天我期中考完试再来研究并编写吧~~ 。

**Comment by Lyccrius** [comment]
刚手滑点错不小心close来不好意思😬

**Comment by CoelacanthusHex** [comment]
@Lyccrius 既然您说可以结合题目，那么请问您能否给出几个题目作为例子，以供维护者理解呢

**Comment by Lyccrius** [comment]
以“有序队列”为关键字能找到的资料基本都是这道题：[899. 有序队列 - 力扣（Leetcode）](https://leetcode.cn/problems/orderly-queue/)  
仔细斟酌后发现，此题目中“有序队列”并不是以一种数据结构的方式出现的。  

最后的结论是：[NOI大纲](https://www.noi.cn/generic/web/viewer.html?file=/upload/resources/file/2021/04/06/152179.pdf)中提到的“有序队列”应该对应着[单调队列](https://oi-wiki.org/ds/monotonous-queue/)，CCF给它换了个名字，我以为又是个新知识点呢。

所以说其实可以更新一下[单调队列](https://oi-wiki.org/ds/monotonous-queue/)页面，这样OIer从大纲中了解到“有序队列”后，在OI-Wiki中搜索就可以索引到此页面。
