### ISSUE TITLE
[BUG] 转义字符导致 toc 乱码

### ISSUE THREAD

**Issue by huaruoji** [OI-wiki/OI-wiki#4434]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

[misc/rand-technique](https://oi-wiki.org/misc/rand-technique/#%E4%BE%8B%E5%AD%90%E7%9F%A9%E9%98%B5%E4%B8%8D%E5%90%8C%E5%85%83%E7%B4%A0%E4%B8%AA%E6%95%B0) 中有两个标题使用了 `(\*)` 对“在 OI/ICPC 中很少使用，但与 OI/ICPC 在风格等方面较为贴近的方法”进行标注，但是导致右方 toc 乱码。

![image](https://user-images.githubusercontent.com/79401001/199868376-5537d8db-6144-4b6a-a64a-36f3fa4411d7.png)

本来应该是 `(*)` 的地方变成了 `(42)`，不知道是什么原因，推测和使用 markdown 转义字符有关。

### 我确认这个问题可以这样复现

打开 [misc/rand-technique](https://oi-wiki.org/misc/rand-technique/) 页面。

环境：Windows 10 专业版 21H2，Microsoft Edge 版本 105.0.1343.42 (正式版本) (64 位)。

**Comment by Enter-tainer** [comment]
@huaruoji 思考 要不直接把这个特殊字符删掉吧 🙏

**Comment by huaruoji** [comment]
> @huaruoji 思考 要不直接把这个特殊字符删掉吧 🙏

我翻了一下好像和 #4253 其实是一样的 bug，ett 页面乱码的地方对应的源码也是用了转义字符（`\[`）

**Comment by Tiphereth-A** [comment]
我这边 Windows 11 x64 上的 Firefox 110.0 x64, Microsoft Edge 110.0.1587.57 x64 和 Google Chrome 110.0.5481.178 x64 均不存在这个 issue 和 #4253 提到的问题，也许这两个 issue 可以 close 了 🤔
