### ISSUE TITLE
Add Markdown教学

### ISSUE THREAD

**Issue by yanboishere** [OI-wiki/OI-wiki#4462]
### 页面英文名

markdown

### 我希望能添加的内容是

markdown语法的讲解（使用方法，使用场景）

**Comment by yusancky** [comment]
发表一点个人拙见：虽然 Markdown 在 OI 圈子中很实用，但互联网上已有大量完善完整的教程了，OI Wiki 没必要再赘述

**Comment by yanboishere** [comment]
诚然如此，但是我希望我们可以做到一站式学到我们所需要的知识。

**Comment by Tiphereth-A** [comment]
> 诚然如此，但是我希望我们可以做到一站式学到我们所需要的知识。

鉴于 Markdown 的学习难度和与算法竞赛的关联程度, 考虑到现在互联网上已经存在大量优质文档, 个人认为加个外链已经足够了, 比如 https://www.markdownguide.org/

**Comment by yanboishere** [comment]
可以

**Comment by Ir1d** [comment]
我感觉一时间想不到什么 OI 相关特有的 markdown 知识，现有的 markdown 资料似乎已经非常充沛了，如果后面有合适的内容可以考虑 reopen

**Comment by yanboishere** [comment]
👌
