### ISSUE TITLE
Add Compilers [RFC]

### ISSUE THREAD

**Issue by inclyc** [OI-wiki/OI-wiki#4471]
### 页面英文名

compilers

### 我希望能添加的内容是

编译器专题。包含常见的，实用的影响 OI 程序性能的优化、UB、和编译器内建、misuse、杂项

# 优化

- NRVO/RVO -- 到底什么时候会复制啊！
- 常量传播
- 循环展开
- 公共子表达式消除
- 基本块放置与对齐
- 函数内联
- 强度削减
- 自动向量化
- 标量优化简介

# UB

- 有符号整数溢出
- 求值顺序
- 修改 const

# 编译器内建

- `__builtin_assume`
- `__bultin_expect`

- `__builtin_ctz`
- `__builtin_popcount`

# misuse

## inline -- 怎么有人给所有的函数都加 inline 呢？

/* 讲解为什么 inline 通常没必要加 */

## register -- 怎么有人给所有的变量加 register 呢？

/* 讲解为什么完全没必要加 register */

# 杂项

- godbolt.org -- 如何游玩编译器
- 小心使用  `vector<bool>` !
- ... 其他（？

**Comment by inclyc** [comment]
PS：写这个主旨在于，OI 通常使用 C++ 比赛，在这里 wiki 中列出常见的，影响性能的一些和编译器相关的知识。

**这个文档应避免成为编译器教材** ，对竞赛没多大帮助的不应该有过多篇幅

--- 

是独立成一个板块还是单个文档，放在杂项里？

**Comment by Enter-tainer** [comment]
@inclyc 如果内容不是很多的话，单个文档应该就好？

**Comment by inclyc** [comment]
@Enter-tainer 正文内容有什么补充/修改的吗

**Comment by Enter-tainer** [comment]
> @Enter-tainer 正文内容有什么补充/修改的吗

感觉已经很全面了🙏

**Comment by inclyc** [comment]
Duplicate to https://github.com/OI-wiki/OI-wiki/issues/886 ?

**Comment by inclyc** [comment]
> Duplicate to #886 ?

看起来相关，但不完全相关（？

**Comment by inclyc** [comment]
> NRVO/RVO -- 到底什么时候会复制啊！

这块看起来已经有了，就不写了
