### ISSUE TITLE
[内容有误] 关于值类别的叙述有误

### ISSUE THREAD

**Issue by zclllyybb** [OI-wiki/OI-wiki#4480]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/lang/value-category/#c17-%E5%B8%A6%E6%9D%A5%E7%9A%84%E6%96%B0%E5%8F%98%E5%8C%96

### 我发现页面有这样的问题

这一部分的叙述是完全错误的。
首先，该部分将NRVO称为了RVO，并称其是标准的硬性规定。事实上，只有RVO是硬性规定。
而之后对于临时量实质化的叙述又是完全不知所云的。

**Comment by Menci** [comment]
@zclllyybb 我觉得不需要这么吹毛求疵，算法竞赛中不需要 portable 的代码，只需要了解用到的编译器（通常是 gcc）的特性和行为就可以了，更何况 nrvo 也是常用的编译器全部实现了的

**Comment by Enter-tainer** [comment]
@zclllyybb 看起来好像是代码里面给的例子不太好，如果方便的话，可以开个pr改成匿名变量的形式吗？（也就是说，举一个rvo的例子

**Comment by inclyc** [comment]
https://en.cppreference.com/w/cpp/language/copy_elision 建议参考这里重写（？
