### ISSUE TITLE
[BUG] 对内容的搜索问题

### ISSUE THREAD

**Issue by flt6** [OI-wiki/OI-wiki#4494]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

在搜索框内搜索“环”这一概念时无法找到，但是却在[路径](https://oi-wiki.org/graph/concept/#%E8%B7%AF%E5%BE%84)下属存在
![image](https://user-images.githubusercontent.com/42725841/205485244-da959321-4ffd-46ed-916f-44439cf98bcc.png)
![image](https://user-images.githubusercontent.com/42725841/205485260-58a622e4-5374-4c6a-a615-d1253d21e002.png)

### 我确认这个问题可以这样复现

在任意页面打开搜索框，以关键词`环`或`图论 环`或`环 图论`搜索。

这个问题应该与[#3664](https://github.com/OI-wiki/OI-wiki/issues/3664)类似

**Comment by Ir1d** [comment]
本页面涉及到的搜索问题终于得到了修复，赞美 https://github.com/OI-wiki/elasticsearch-config/pull/2
