### ISSUE TITLE
[内容有误] 数据结构-二叉堆内容修正

### ISSUE THREAD

**Issue by AzurIce** [OI-wiki/OI-wiki#4531]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/binary-heap/

### 我发现页面有这样的问题

「过程」一节中的三级标题「减小某个点的权值」应该是小根堆的操作（参见 [ds/heap.md](https://github.com/OI-wiki/OI-wiki/blob/84a1958fbede6cdaafb1c449ef40e3b20c2f3bdd/docs/ds/heap.md) 中以小根堆为例，对应的说明内容中的操作是减小某个点的权值），而本文是以大根堆为例，对应的应该是「增加某个点的权值」。

**Comment by AzurIce** [comment]
另外还有一些个人想法（没有做修改）：
1. 还是这个三级标题「增加某个点的权值」中的「点」或许改为「节点」更合适一些？因为文中的说明均为简称「节点」为「点」（可能是我有点强迫症）。
2. 本文的「过程」一节标题或许更改为「操作」更合适一些？
3. 或许可以统一一下所有关于堆的内容中全部以大根堆为例，或全部以小根堆为例？（[ds/heap.md](https://github.com/OI-wiki/OI-wiki/blob/84a1958fbede6cdaafb1c449ef40e3b20c2f3bdd/docs/ds/heap.md)、[ds/pairing-heap.md](https://github.com/OI-wiki/OI-wiki/blob/84a1958fbede6cdaafb1c449ef40e3b20c2f3bdd/docs/ds/pairing-heap.md)、[ds/leftist-tree.md](https://github.com/OI-wiki/OI-wiki/blob/84a1958fbede6cdaafb1c449ef40e3b20c2f3bdd/docs/ds/leftist-tree.md) 中均是以小根堆为例进行相关说明的）

**Comment by LiuZengqiang** [comment]
第2点，综合其他页面来看，基本都使用「过程」作为标题，而不是「操作」。

**Comment by AzurIce** [comment]
> 第2点，综合其他页面来看，基本都使用「过程」作为标题，而不是「操作」。

哦哦确实
