### ISSUE TITLE
[内容有误] 

### ISSUE THREAD

**Issue by WASSER2545** [OI-wiki/OI-wiki#4556]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/hash/

### 我发现页面有这样的问题

哈希表的python版本有明显bug

**Comment by alphagocc** [comment]
请问一下是什么 bug 呢？

**Comment by WASSER2545** [comment]
貌似size的自增顺序有问题，我也不清楚是不是全局变量的问题。

**Comment by Tiphereth-A** [comment]
@WASSER2545 Hi, 方便交个 PR 嘛

**Comment by WASSER2545** [comment]
@Tiphereth-A 已提交

**Comment by Tiphereth-A** [comment]
completed in #4561
