### ISSUE TITLE
[内容有误] 数据结构——并查集——路径压缩的C++实现代码有误

### ISSUE THREAD

**Issue by Chiichen** [OI-wiki/OI-wiki#4566]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/dsu/

### 我发现页面有这样的问题

![image](https://user-images.githubusercontent.com/39649411/210296682-7930cbd6-f13e-4321-bfcb-cbe6acbd28c1.png)

含路径压缩的C++实现代码与上面不含路径压缩的代码一样，python代码无误

**Comment by Tiphereth-A** [comment]
```diff
-size_t dsu::find(size_t x) { return pa[x] == x ? x : find(pa[x]); }
+size_t dsu::find(size_t x) { return pa[x] == x ? x : pa[x] = find(pa[x]); }
```
