### ISSUE TITLE
[RFC] 修订用于 OI wiki 的数学符号表

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#4587]
随着 OI wiki 规模的不断扩大以及越来越多热心贡献者的加入，一些数学符号在不同页面出现了多种写法。

如虚数单位 $\mathrm{i}$,

- 在 [math/number-theory/quad-residue.md Line 136](https://github.com/OI-wiki/OI-wiki/blob/149b590b90dc2fc46dd0193db69b0ac8f98737f0/docs/math/number-theory/quad-residue.md?plain=1#L136) 处写为 `$\mathrm{i}$`.
- 在 [math/complex.md Line 15](https://github.com/OI-wiki/OI-wiki/blob/0c5f136d93f497f0773c411e202484390b7f9d3d/docs/math/complex.md?plain=1#L15) 处写为 `$\text{i}$`.
- 在 [math/complex.md Line 347 - Line 349](https://github.com/OI-wiki/OI-wiki/blob/0c5f136d93f497f0773c411e202484390b7f9d3d/docs/math/complex.md?plain=1#L347-L349) 处和 [math/poly/tri-func.md Line 9 - Line 14](https://github.com/OI-wiki/OI-wiki/blob/58b9fe67d667d265261d733b70b90e6cf0eaefdd/docs/math/poly/tri-func.md?plain=1#L9-L14) 处写为 `$i$`.
- 在 [math/number-theory/quadratic.md Line 78](https://github.com/OI-wiki/OI-wiki/blob/149b590b90dc2fc46dd0193db69b0ac8f98737f0/docs/math/number-theory/quadratic.md?plain=1#L78) 处写为 `i`.

不同的数学符号写法可能引起混淆（如 `i` 常用作程序的循环变量），所以现在需要一份详尽的数学符号表来统一页面中的符号用法。

现行的相关标准有 [ISO 80000-2:2019](https://www.iso.org/standard/64973.html)，[GB/T 3102.11-1993](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=3DE79450D562E62D41CB6E79FF411054)。其中 GB/T 3102.11-1993 参考了 [ISO 31-11:1992](https://www.iso.org/standard/3653.html)，其为 ISO 80000-2:2019 的前身。需要注意的是这些标准 **不具有强制性**，现在在高等教育阶段的教材和论文中常见的方案是附带一份涵盖了文章使用的绝大多数符号的符号表。

此外，ISO 80000-2:2009 中部分符号在中文环境中非常少见，如 2-11.8 中规定的排列数记号为

$$
V_{n}^{k}=n^{\underline{k}}=\frac{n!}{(n-k)!}
$$

综上所述，我提议 OI wiki 应参照 ISO 80000-2:2009，结合中文环境使用习惯来制定一套应用于自身的数学符号表，并将其加入格式手册中。

**Comment by Enter-tainer** [comment]
补充一下，标准里面还规定了，pi作为常量，也应该是直立的。但是这似乎并不符合大家日常的使用习惯。且在LaTeX中，不方便搞出直立的pi。

**Comment by Great-designer** [comment]
> 补充一下，标准里面还规定了，pi作为常量，也应该是直立的。但是这似乎并不符合大家日常的使用习惯。且在LaTeX中，不方便搞出直立的pi。

在北大版印刷的数学书里面，e和i是直立的，而希腊字母pi和gamma等都不是。以这个为参考的话英文字母需要直立，希腊字母不需要。

**Comment by Great-designer** [comment]
感觉这个和译名表属于同一类事物

**Comment by Great-designer** [comment]
目前OI Wiki自己的符号表在https://oi-wiki.org/math/notation/

在参考了ISO和GB的标准之后，可以写到新位置

**Comment by Great-designer** [comment]
《格式手册》里面也有提到相关内容https://oi-wiki.org/intro/format/

可以拆分成一个二级目录，把格式手册中的符号相关单独整合出来

**Comment by Great-designer** [comment]
| 名称            | 书写                                  | 渲染效果                                |
| --------------- | ---------------------------------------- | ----------------------------------- |
| 对数  | `$\log$, $\ln$, $\lg$`                   | $\log$，$\ln$，$\lg$                  |
| 三角函数 | `$\sin$, $\cos$, $\tan$`                 | $\sin$，$\cos$，$\tan$                |
| 最大公约数和最小公倍数 | `$\gcd$, $\operatorname{lcm}$`           | $\gcd$，$\operatorname{lcm}$         |
| 小于 a 的素数 | `小于 $a$ 的素数`                             | 小于 $a$ 的素数                          |
| 省略号 | `$\cdots$, $\ldots$, $\vdots$, $\ddots$` | $\cdots$，$\ldots$，$\vdots$，$\ddots$ |
| 两个数相乘 | `$a\times b$, $a\cdot b$`                | $a\times b$，$a\cdot b$              |
| 正文中的英文 | `SPFA`                                   | SPFA                                |
| 两个数相等 | `$a=b$`                                  | $a=b$                               |
| 三下标数组 | `$f_{i,j,k}$, $f(i,j,k)$`                | $f_{i,j,k}$，$f(i,j,k)$              |
| 数集 | `$\mathbf{R}$, $\mathbf{N}^*$`           | $\mathbf{R}$，$\mathbf{N}^*$         |
| 空集 | `$\varnothing$`                          | $\varnothing$                       |
| LaTeX中的行文 | `$\textit{different}$`                   | $\textit{different}$                |

**Comment by Great-designer** [comment]
《符号表》和《格式手册》暂时整理了这些

**Comment by Great-designer** [comment]
这篇文章可以选择性参考：《LaTeX 数学公式大全》

https://www.luogu.com.cn/blog/IowaBattleship/latex-gong-shi-tai-quan?tdsourcetag=s_pctim_aiomsg

原文说“转载请在文章页面明显位置注明出处”，但显然并不需要全文，只需像查字典一样挑几个就行。

**Comment by Great-designer** [comment]
上表仅关于格式和 LaTeX 的部分暂时修订到这里。本站内部应用可能还有一堆符号尚未写进去。

看看大家的想法，有没有其他想要补充完善的部分。

**Comment by Tiphereth-A** [comment]
> 这篇文章可以选择性参考：《LaTeX 数学公式大全》
> 
> https://www.luogu.com.cn/blog/IowaBattleship/latex-gong-shi-tai-quan?tdsourcetag=s_pctim_aiomsg

没必要参考这个，KaTeX 的文档更好一些

**Comment by Great-designer** [comment]
> 没必要参考这个，KaTeX 的文档更好一些

确实，原本的链接是针对洛谷的。我上面说“希望在符号表中多介绍一些符号”也有类似的意思……希望能够多介绍介绍属于本站、体现编程竞赛特色的符号。

**Comment by untitledunrevised** [comment]
关于括号的疑问：
用 `\left(\right)` 渲染出来的括号，两边会有空格；
用 `\big(\big)` 渲染出来的括号，两边没有空格。
推荐用哪种呢？

关于内置函数的疑问：
用 `\exp{(x)}` 渲染出来的式子，exp 的右边会有空格；
用 `\exp(x)` 渲染出来的式子，exp 的右边没有空格。
推荐用哪种呢？

**Comment by Great-designer** [comment]
> 关于括号的疑问： 用 `\left(\right)` 渲染出来的括号，两边会有空格； 用 `\big(\big)` 渲染出来的括号，两边没有空格。 推荐用哪种呢？

只准使用 `\left(\right)` ，不可以使用 `\big(\big)` ，因为 `\left(\right)` 是自动适配内容大小的。

> 关于内置函数的疑问： 用 `\exp{(x)}` 渲染出来的式子，exp 的右边会有空格； 用 `\exp(x)` 渲染出来的式子，exp 的右边没有空格。 推荐用哪种呢？

推荐用 `\mathrm{e}^x` 。

**Comment by Enter-tainer** [comment]
> 推荐用 \mathrm{e}^x

exp 也是常用的写法吧，不过我还真没研究过这个空格...

**Comment by Enter-tainer** [comment]
> 不可以使用 \big(\big)

这个见仁见智了，对于比较高级的用户，手调可以出来更好看的效果，不过大部分情况还是直接left right方便
