### ISSUE TITLE
Add 在 Fork 的仓库中启用 GitHub Pages

### ISSUE THREAD

**Issue by dong628** [OI-wiki/OI-wiki#4589]
### 我希望能添加的内容是

贡献者在 Fork 仓库并且更改后，如何使用 GitHub Pages 部署，来方便地查看自己的更改。

和使用 Docker 部署不同，添加这个主要是因为 wiki 文档中有许多 Markdown 格式之外的内容（主题扩展格式），比如多种语言分栏的代码块，以及 `???+note` 之类的模板，一般的 Markdown 编辑器或者 GitHub 编辑器并不能显示效果。并且我在 [协作流程](https://oi-wiki.org/intro/htc/#%E5%8D%8F%E4%BD%9C%E6%B5%81%E7%A8%8B) 中了解到，bot会自动构建 PR 的页面，所以可以加这样一个章节到 htc 中，毕竟这种情况用 docker 部署过于麻烦了，需要自己构建镜像。

### 我了解到的相关参考资料有

我并不了解构建 gh-pages 的 bot 的运行机制，也不了解 GitHub Pages 配置时的注意事项（我只用它部署过个人博客），所以需要大家的帮助。

**Comment by Enter-tainer** [comment]
@dong628 如果你的fork开了pr，也可以考虑使用pr check列表中的 netlify preview来预览编辑效果

**Comment by dong628** [comment]
> @dong628 如果你的fork开了pr，也可以考虑使用pr check列表中的 netlify preview来预览编辑效果

LGTM，htc这方面写得不太清楚，我开个pr改一下吧，thx

**Comment by Enter-tainer** [comment]
@dong628 好的~欢迎
