### ISSUE TITLE
[建议] 建议合并多项式求逆开方除法取模对数指数三角反三角

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4605]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/poly/tri-func/

### 我发现页面有这样的问题

这些页面都很短，并且一脉相承。一口气读完是爽的，分散开来显得目录结构很拥挤。

**Comment by Great-designer** [comment]
比如，“多项式求逆”和“多项式除法/取模”两页合并，改为“多项式的四则运算”

“多项式开方”、“多项式对数指数”、“多项式三角”、“多项式反三角”四页合并，改为“多项式的函数”

或者干脆全合一块儿也行，标题暂时不知道……

**Comment by Tiphereth-A** [comment]
> 或者干脆全合一块儿也行，标题暂时不知道……

这些都是初等函数, 直接叫多项式初等函数应该就行了

**Comment by Great-designer** [comment]
> > 或者干脆全合一块儿也行，标题暂时不知道……
> 
> 这些都是初等函数, 直接叫多项式初等函数应该就行了

可以
