### ISSUE TITLE
[建议 Suggestions / Bugs]  GitHub Actions 对未修改内容仍执行 Check

### ISSUE THREAD

**Issue by liumingedwin** [OI-wiki/OI-wiki#4613]
## 请选择：
- [ ] 我正在着手修复这个问题

此问题导致 Build 时间略长，有可能降低贡献者的热情。

**Comment by Enter-tainer** [comment]
目前时间较长的check是LaTeX相关的检查，不过感觉增量的check不太好做

**Comment by CoelacanthusHex** [comment]
@liumingedwin 其实目前构建最慢的是latex

**Comment by Great-designer** [comment]
还有一个办法是进行分区，修改了哪个目录就只检查哪个目录的全部latex。虽然也不是增量检查，但肯定速度会提升。

另外，只要启用增量检查，就需要定期进行全盘检查。
