### ISSUE TITLE
Add B* search algorithm

### ISSUE THREAD

**Issue by liumingedwin** [OI-wiki/OI-wiki#4616]
### 页面英文名

bstar

### 我希望能添加的内容是

 B* 搜索算法，是一种在游戏开发广泛使用的算法，但也适用于算法竞赛。

### 我了解到的相关参考资料有

<https://en.wikipedia.org/wiki/B*>
<https://www.luogu.com.cn/blog/JHN021/ling-lei-xun-lu-suan-fa-b-suan-fa-qian-tan>

**Comment by Tiphereth-A** [comment]
https://github.com/OI-wiki/OI-wiki/pull/5105#issuecomment-1686549259
