### ISSUE TITLE
Add Code::Blocks

### ISSUE THREAD

**Issue by hhc0001** [OI-wiki/OI-wiki#4621]
### 页面英文名

Code::Blocks

### 我希望能添加的内容是

Code::Blocks（下称codeblocks）是一款开源C/C++IDE。我的老师说“这IDE手感不太好”。

Windows端口下载很便捷，直接去官网找到安装包，下载一个，在安装一下，就搞完了。

我个人感觉codeblocks手感还好，基本和隔壁几个IDE（指VS Code、Dev-C++）没什么两样。特别是界面，感觉都有点像把Dev-C++的界面移植了

### 我了解到的相关参考资料有

[百度百科上的Code::Blocks](https://baike.baidu.com/item/Code%3A%3ABlocks?fromModule=lemma_search-box)

**Comment by hhc0001** [comment]
哦对了，CodeBlocks最近已被指定为NOI官方IDE

**Comment by Great-designer** [comment]
> 哦对了，CodeBlocks最近已被指定为NOI官方IDE

那挺厉害的。（虽说我个人觉得新版devcpp更好用一些）

**Comment by hhc0001** [comment]
目前NOI上面的IDE中没有大家所熟知的那些IDE，只有Code::Blocks和另一个不知名IDE






                       
原始邮件
                       
                     

发件人："Great-designer"< ***@***.*** &gt;;

发件时间：2023/1/13 17:28

收件人："OI-wiki/OI-wiki"< ***@***.*** &gt;;

抄送人："hhc0001"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [OI-wiki/OI-wiki] Add Code::Blocks (Issue #4621)




  
哦对了，CodeBlocks最近已被指定为NOI官方IDE
  
那挺厉害的。（虽说我个人觉得新版devcpp更好用一些）

**Comment by dong628** [comment]
@hhc0001 NOI Linux上肯定没有DevC++啊（事实上VSCode和Vim也有很多人在用），Windows虽然没有统一的技术规范，但一般IDE都是DevC++。

**Comment by yanboishere** [comment]
确实现在身边很多认识的同学，大一刚集训的时候用的IDE是Code::Blocks......要不考虑一下加进去？

**Comment by Great-designer** [comment]
应该加进去，没有是不正常的

**Comment by hhc0001** [comment]
> 应该加进去，没有是不正常的

雀食

**Comment by hhc0001** [comment]
> @hhc0001 NOI Linux上肯定没有DevC++啊（事实上VSCode和Vim也有很多人在用），Windows虽然没有统一的技术规范，但一般IDE都是DevC++。

DevC++是Windows软件

**Comment by hhc0001** [comment]
> @hhc0001 NOI Linux上肯定没有DevC++啊（事实上VSCode和Vim也有很多人在用），Windows虽然没有统一的技术规范，但一般IDE都是DevC++。

而且，虽然NOI Linux有VSCode，但是CCF禁止使用VSCode编辑代码。
Vim虽然使用广泛，但是操作复杂，一个用了很久DevC++（或VSCode）的人第一次使用Vim的人可能会产生严重的“水土不服”（虽然我第一次用VSCode也有水土不服，但是几次下来习惯VSCode只用了几天）。
现在正在实验使用Code::blocks，实验结论一段时间后会出来。

**Comment by hhc0001** [comment]
> > @hhc0001 NOI Linux上肯定没有DevC++啊（事实上VSCode和Vim也有很多人在用），Windows虽然没有统一的技术规范，但一般IDE都是DevC++。
> 
> 而且，虽然NOI Linux有VSCode，但是CCF禁止使用VSCode编辑代码。 Vim虽然使用广泛，但是操作复杂，一个用了很久DevC++（或VSCode）的人第一次使用Vim的人可能会产生严重的“水土不服”（虽然我第一次用VSCode也有水土不服，但是几次下来习惯VSCode只用了几天）。 现在正在实验使用Code::blocks，实验结论一段时间后会出来。

对比一下Vim和VSCode（我个人认为的Linux编辑器之王和Windows的编辑器之王）的文章长度就知道了。

**Comment by Great-designer** [comment]
这时候不要考虑打比赛让用啥不让用啥，更多考虑程序员的平时开发工具

**Comment by hhc0001** [comment]
总结一下 CodeBlocks 目前的优缺点：

优点：

自动补全用起来是我用过的三个 IDE 中最不卡手的一个。

缺点：

有时候会出现亿点 bug，比如说缩进不对、括号没补全等。

默认是 C 文件。
