### ISSUE TITLE
Add 概率分布

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4624]
### 页面英文名

未知

### 我希望能添加的内容是

常见的概率分布，离散和连续的，从高中到考研总共9种

离散：二项分布、负二项分布、泊松分布、超几何分布

连续：均匀分布、正态分布、伽马分布、t分布、F分布

还可以介绍离散分布与生成函数的联系，连续分布与傅里叶变换的联系，二者几乎是对应的

### 我了解到的相关参考资料有

高中数学课本选修3、大学数学课本概率论与数理统计

**Comment by alphagocc** [comment]
@Great-designer 这玩意儿 oi 也不考，这玩意儿看看 wikipedia/Wolfram Knowledgebase 就行了吧

**Comment by yanboishere** [comment]
二项分布我觉得可以考虑，其他的oi也确实可能用不上......

**Comment by Great-designer** [comment]
wikipedia不要想了……对于广大墙内人士是很不方便的

**Comment by alphagocc** [comment]
根据
https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E6%9D%83%E5%A8%81%E6%9C%BA%E6%9E%84
OI Wiki 不是百科全书
