### ISSUE TITLE
[功能请求] 译名表，并统一专有名词使用

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4650]
### 我遇到的问题是

译名与专有名词不统一

### 我希望能有这样的解决方案

讨论：

行文使用外文原文方便，还是使用中文译名方便？

无论哪种方案，都需要译名表，并统一专有名词使用。

举个例子：

对于“裴蜀定理”：

- 如果使用法文原文，所有的“裴蜀定理”应当写作“Bézout定理”，其中“e”应当写作法文带闭音符的“é”。
- 如果全部使用中文，那么应当使用统一的译名，并附上译名表。

该问题源于 #4619

**Comment by HeRaNO** [comment]
有一些中文音译可能随时代变化音译名有所不同，比如 Poisson 分布可以被音译为泊松分布或帕松分布、布瓦松分布、布阿松分布、普阿松分布等等，但是现在大部分人都叫泊松分布，许多新版概率论教材也使用泊松分布的音译名（比如电子科技大学的概率论与数理统计和哈尔滨工业大学的应用随机分析）。我个人认为这个问题是随时间改变而改变的，很多音译都会随着时间而达成一种共识，进而使得译名趋同。从目前的趋势上看，确实可以采用流行的中文译名，但如果仅是为了语言学意义上的留档或者只是看起来很爽，感觉这么做的重要性不是很大，可以做，但不急。

给初学的人写「Bézout 定理」或「裴蜀定理」，他都不会知道这个定理的具体内容，因为只是一个名字罢了。但是对于学过的人来说，因为学识与见识的不同，其对译名的理解也会有一定偏差，可能会对应不上，但是我认为属于少数，因为可以通过上下文推断出来说的是什么。

并且在其他文章中出现「裴蜀定理」一词，可以把它链接到介绍裴蜀定理的文章上，而不需要再进一步说明译名的不同。这样看起来比较自然，懂的看到就懂了，不懂的点一下链接自然会明白，不太是一个很严重的问题或必需的东西。

对于所谓「译名表」，watashi 曾经是有一个较为全面的版本（[Web Archive](https://web.archive.org/web/20200225214839/http://blog.watashi.ws/tag/%E7%BF%BB%E8%A8%B3/)，原地址不可用），可以参考搬运。

**Comment by Great-designer** [comment]
如果存在一个“xx大纲”，例如高考大纲、数学竞赛大纲、考研大纲等等使用的中文译名，当然要优先使用该译名。

（OI大纲前一阵已经在本站写过了）

**Comment by HeRaNO** [comment]
这个 issue 分为两部分，就分别来讲。

关于统一专有名词使用，从大方向来说是有基础的，可以做，但是有更平滑的方式，比如做链接等等可以过渡。这个问题需要更多因为专有名词影响交流和理解的 case 讨论一下。

关于译名表，希望提上日程，可以参照 watashi 的译名表进行更新与维护。

**Comment by Great-designer** [comment]
关于译名与专有名词的修改：

随着时间的推演，译名与专有名词当然允许修改。

译名与专有名词定下来之后，可以加入译名与专有名词表，译名与专有名词修改时会全站统一修改。

修改的理由可以有很多，例如“最新版的xx大纲”使用了xx译名或专有名词，。或者表明“主流”已经使用新译名或新专有名词，等等。

**Comment by Great-designer** [comment]
译名与专有名词表可以给个出处栏，例如xx教材或者xx大纲使用该译名或专有名词，作为可靠的出处。

**Comment by HeRaNO** [comment]
建议使用事实标准（de-facto）而非大纲标准。

「大纲」，「标准」可以有很多，但是日常采用的译名是趋同的，避免造成大幅变更和理解障碍。

**Comment by hly1204** [comment]
我认为翻译名字这件事本身对于读者而言没有任何的好处, 纯粹是写的时候方便而已, 除了小说新闻等内容可能音译成汉字比较好.

**Comment by Great-designer** [comment]
> 建议使用事实标准（de-facto）而非大纲标准。

关于“大纲”我认为还是按大纲好。因为谁都可以称“自己说的是‘事实’”，却没办法否认成文的“大纲”。

例如bulbapedia永远会按照最新版游戏内置的官方译名来写。可能会有工作人员随手译的非官方译名，但一旦出了最新版的官方译名，一定会得到采用。

> 我认为翻译名字这件事本身对于读者而言没有任何的好处, 纯粹是写的时候方便而已, 除了小说新闻等内容可能音译成汉字比较好.

这个我不持意见，无论翻译或者不翻译都无所谓，只要统一了就行。

例如：
- 如果行文选用“欧拉”二字，那么整个网站除了译名表，以及每篇文章首次出现“欧拉（Euler）”以外，不应出现“Euler”。
- 如果使用“Euler”，也是一样的道理，除了译名表，以及每篇文章首次出现“欧拉（Euler）”以外，不应出现“欧拉”。

并且“欧拉（Euler）”这种加注，不应出现在标题中，只能出现在正文中。如果标题比正文要先出现，则跳过先出现的标题在首个正文处加注。并且，不允许出现“只在标题出现而不在正文出现”的情形，保证正文的首次出现必须标注。

**Comment by Great-designer** [comment]
> 或者说我换一个暂时可能没有人翻译过的人名呢

这也是常事。这得立即译一个出来，你确实没有找到（或者“考据到”）其他人的翻译，那么你必然有权首次翻译它，这是沾了大便宜。但是写文章的时候，任何缩写或者外文或者外文译名都会有注释。

一个典型的例子例如“NP问题”，并不是每位读者都知道NP是指“非多项式”这个英语单词，新人一读是不知道的。虽然老手们可能天天在使用这个词，但是它仍然有加注的必要，而且只加注一次即可，并不麻烦。

**Comment by CoelacanthusHex** [comment]
> > 建议使用事实标准（de-facto）而非大纲标准。
> 
> 关于“大纲”我认为还是按大纲好。因为谁都可以称“自己说的是‘事实’”，却没办法否认成文的“大纲”。
> 
> 例如bulbapedia永远会按照最新版游戏内置的官方译名来写。可能会有工作人员随手译的非官方译名，但一旦出了最新版的官方译名，一定会得到采用。

首先，您是不是对所谓事实标准有何误解，所谓事实标准指的是一种得到大多数人公认的，或者已经占据主导地位的标准；
其次，即使按照所谓官方译名，OI Wiki 针对多个赛事，每个赛事皆有其官方译名，请问应采用哪个官方才足够官方。

**Comment by Great-designer** [comment]
> 关于“大纲”我认为还是按大纲好。因为谁都可以称“自己说的是‘事实’”，却没办法否认成文的“大纲”。
> 
> 你确实没有找到（或者“考据到”）其他人的翻译，那么你必然有权首次翻译它

我来解释一下刚刚自己说的这两句话。当你说“这东西确实冷门，确实没有考据到其他人之前以及翻译过了”，那么你翻译错误无需负任何责任，因为你可以称“自己说的是事实”。

又例如“高斯（Gauss）”和“欧拉（Euler）”已经通用了，有人说“这东西确实冷门，确实没有考据到其他人之前以及翻译过了”，这显然是假的。

（说起来数学的“傅里叶”和政治的“傅立叶”完全是同一个姓。可见翻译是多么重要，两个通用译法可以区分两个人）

但是如果能找到一个成文的大纲里面写过了，那肯定这说的不是事实，“成文的大纲”是证据，是无法否认的。

**Comment by Great-designer** [comment]
> 所谓事实标准指的是一种得到大多数人公认的，或者已经占据主导地位的标准； 

高斯和欧拉就是少数这种情形。其他的我不敢说。

> 其次，即使按照所谓官方译名，OI Wiki 针对多个赛事，每个赛事皆有其官方译名，请问应采用哪个官方才足够官方。

理论上任意一个都可以，但最好是最新的，并且无论选用哪一种，都需要在译名表中注明“出自哪一种”。

**Comment by Great-designer** [comment]
或者这么说，如果真的是“事实、市面通行的标准”，那必然能找到出处。即使出处已经多到“找不到最权威的出处”，也必然能找到“相对权威的出处”。很多时候wiki最擅长干这个活。

**Comment by Great-designer** [comment]
讲个典故：古代立储有“立长”和“立贤”之争。“立长”是从来没有争议的，而“立贤”是有争议的，因为“贤能”的制定标准在当权者手中。

有人说“不对，贤能由民众制定或者由法典制定”，也没错，因为在那些情形，权力位于民众和法典那里。

“事实”和“大纲”之争也是这样。明文证据是不会有争议的，而人们说的事实往往不一定可靠，可靠的总能找到相关明文。

**Comment by Great-designer** [comment]
关于“大纲”这事，可以在本站自己这里找到证据，在《格式手册》https://oi-wiki.org/intro/format/

“另外，由于 LaTeX 历史原因，空集的符号应为 $\varnothing$ 而不是 $\emptyset$；由于近百年来数学符号演变，定义集合符号应使用 人民教育出版社普通高中数学教材 A 版 书写的版本，即 实数集 $\mathbf{R}$，正整数集 $\mathbf{N}^*$ 等。同理，其他的符号应按照中国国内最常使用的版本来书写，重点参照数学和信息技术课本。”

这段表述认为《人民教育出版社普通高中数学教材 A 版》是权威的，应当照此执行。

（由于近年来《人教版数学教材》偏向简单，我对此持保留意见，不肯定也不否定。）

如果《人教版数学教材》是权威的，那么各种更加高级一些的相关大纲也都是权威的（例如从难度上讲，很多地区的高考大纲事实上比数学教材困难）。无论肯定教材权威性还是否定教材权威性，这些大纲都更应该得到肯定。而且条件很宽松，只需随意按照一种、有出处即可。

**Comment by HeRaNO** [comment]
但是我建议我们的精力先放在维护内容准确性和严谨性上，比如最近最大流页面内容整体出现很大问题，这是不应该的。

当然这个 issue 确实是有一定意义的，只不过大方向上的问题更加紧迫，这个 issue 就显得不那么紧要了。

**Comment by Great-designer** [comment]
> 但是我建议我们的精力先放在维护内容准确性和严谨性上，比如最近最大流页面内容整体出现很大问题，这是不应该的。
> 
> 当然这个 issue 确实是有一定意义的，只不过大方向上的问题更加紧迫，这个 issue 就显得不那么紧要了。

我认为说得有道理。从制作难度上讲，符号表 #4587 的制作难度比译名表要容易。符号表框架很容易搭，主要工作只需要逐步往里填一些常用的记号，而译名表需要爬一遍全站再找一遍出处，相对更加麻烦。

实际操作了一下这俩难度差别确实是有，看来可以把它作为符号表的后续长期计划。

**Comment by dbxxx-oi** [comment]
> 但是我建议我们的精力先放在维护内容准确性和严谨性上，比如最近最大流页面内容整体出现很大问题，这是不应该的。
> 
> 当然这个 issue 确实是有一定意义的，只不过大方向上的问题更加紧迫，这个 issue 就显得不那么紧要了。

不能再同意，我也认为目前 OI Wiki 的内容上的问题更大，离 "Wiki" 的要求相差还比较远

**Comment by Great-designer** [comment]
作为长期问题暂时搁置。

短期可以在格式手册中注明“尽量选取市面上通行的译名和专有名词”。

**Comment by Tiphereth-A** [comment]
https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%A7%94%E5%91%98%E4%BC%9A
