### ISSUE TITLE
[BUG] 页面标题更改导致评论区匹配失败

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#4652]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

在 #4629 后, https://oi-wiki.org/misc/odt/ 的评论区从 <https://github.com/OI-wiki/gitment/discussions/792> 变为了 <https://github.com/OI-wiki/gitment/discussions/1179>. 初步猜测是由于标题更改导致匹配失败, 所以在标题更改后发新评论会另开新的评论区

**Comment by Great-designer** [comment]
一般这种情形需要管理员出手手动移动……

**Comment by diauweb** [comment]
> 一般这种情形需要管理员出手手动移动……

既然开了issue就会有人来处理 下次您看到后就不劳您费心再回复一次了

**Comment by ouuan** [comment]
> 既然开了issue就会有人来处理 下次您看到后就不劳您费心再回复一次了

本 issue 的标题并没有限定在 odt 这一个页面，所以可能会误认为是针对这一类问题的 issue。如果是针对这一个页面，显然就是要把这一个页面处理了，但没有限定的话，另一种理解是，通过更改匹配方式等手段来在以后也避免这种问题，或者检查一下是否有其他页面有同样的问题。issue body 中也没有提到，到底是要处理这一个页面，还是解决这一类问题。那么，“一般这种情形需要管理员出手手动移动”其实是有意义的回复，表达的观点是，应该每次单独处理，而非一次性解决这类问题。

**Comment by ouuan** [comment]
我把 odt 的两个 discussion 标题都改了，现在匹配的是旧的，新的一条评论就不要了。

**Comment by Tiphereth-A** [comment]
> 本 issue 的标题并没有限定在 odt 这一个页面，所以可能会误认为是针对这一类问题的 issue。如果是针对这一个页面，显然就是要把这一个页面处理了，但没有限定的话，另一种理解是，通过更改匹配方式等手段来在以后也避免这种问题，或者检查一下是否有其他页面有同样的问题。issue body 中也没有提到，到底是要处理这一个页面，还是解决这一类问题。那么，“一般这种情形需要管理员出手手动移动”其实是有意义的回复，表达的观点是，应该每次单独处理，而非一次性解决这类问题。

我是因为发现了这个页面的评论区问题所以开了这个 issue，因为我本人对 giscus 不甚了解，所以不清楚未来 OI wiki 的页面改动标题、文件名等后是否会出现类似问题，所以标题是我对该问题出现原因的一种猜测。如果可以的话当然应该设计一种稳定的映射保证可靠性，但像目前这样也是一种解决方案。
