### ISSUE TITLE
[内容有误] 将所有C形式的组合数改为dbinom形式

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4655]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/notation/

### 我发现页面有这样的问题

在《格式手册》https://oi-wiki.org/intro/format/

认为组合数应当写成`$\dbinom{n}{m}$`。

在《符号》https://oi-wiki.org/math/notation/

将组合数写成`$\binom{n}{m}$`。

目前站内存在很多 $C_n^m$ 形式的组合数写法。现想将它们逐步替换成 dbinom 形式，并且在《排列组合》页面不再用 $C_n^m$ 形式进行介绍。

**Comment by Great-designer** [comment]
在前一个issue #4587 中我暂时把组合数写成`$\dbinom{n}{m}$`。待议。

**Comment by Great-designer** [comment]
分数也是，《格式手册》推荐`$\dfrac{n}{m}$`，但大多数写的还是`$\frac{n}{m}$`

**Comment by IdkWhatIsIdk** [comment]
这两种形式主要是大小不同，个人认为行内用`$\binom{n}{m}$`和`$\frac{n}{m}$`也没有什么问题.
行外还是尽量用`$\dbinom{n}{m}$`和`$\dfrac{n}{m}$`.

**Comment by Enter-tainer** [comment]
> 行外还是尽量用$\dbinom{n}{m}$和$\dfrac{n}{m}$.

行间公式下，frac和dfrac一样

> 这两种形式主要是大小不同，个人认为行内用$\binom{n}{m}$和$\frac{n}{m}$也没有什么问题.

我也觉得，感觉改不改都行

**Comment by Great-designer** [comment]
目前使用 C 形式组合数的至少有（未必全）：

- 威尔逊定理：https://oi-wiki.org/math/number-theory/wilson/
- 排列组合：https://oi-wiki.org/math/combinatorics/combination/
- 容斥原理：https://oi-wiki.org/math/combinatorics/inclusion-exclusion-principle/
- 斐波那契数列：https://oi-wiki.org/math/combinatorics/fibonacci/
- 错位排列：https://oi-wiki.org/math/combinatorics/derangement/
