### ISSUE TITLE
[Advice] 线段树页面引入过于复杂

### ISSUE THREAD

**Issue by RDFZchenyy** [OI-wiki/OI-wiki#4665]
- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/seg/

### 我发现页面可以这样改进

线段树作为一个经典的入门数据结构，被许多人选择作为进阶学习的开端。但在 OI-Wiki 上对应线段树的页面的开头，却使用了下面这段较为复杂的引入：

> 线段树维护的信息在很多时候可以认为是满足（幺）半群的性质的信息。
>
> 一个幺半群 $M=(S,\circ ,e)$，其中 $\circ$ 为在集合 $S$ 上定义的二元运算符，幺半群具有以下性质：
> - 封闭性：$\forall x\in S$ 和 $\forall y\in S$ 有 $x\circ y\in S$。
> - 结合律：$\forall x,y,z\in S$ 有 $(x\circ y)\circ z=x\circ (y\circ z)$。
> - 存在幺元：即 $\exists e\in S$ 满足 $\forall x \in S$ 有 $e\circ x=x$，$e$ 为左幺元；或 $x\circ e=x$，$e$ 为右幺元。
> 我们观察到线段树上的信息一般满足这样的性质，一些数域上的加法与乘法自然，考虑二元的 $\max(x,y)$ 运算，此时幺元为 $-\infty$ 也满足这样的性质（一般左右幺元相同时简称为幺元）。

从我一个 OIer 初学者的角度来看，第一次涉及线段树时，便看到“幺半群”“幺元”等概念，实属过于难为初学者了。

**Comment by dong628** [comment]
一针见血的。

**Comment by IdkWhatIsIdk** [comment]
可以开一个链接到[群论](https://oi-wiki.org/math/group-theory/#%E7%BE%A4%E7%9A%84%E8%A1%8D%E7%94%9F%E7%BB%93%E6%9E%84).

**Comment by zqy2010** [comment]
其实只需要说明维护的信息满足结合律而且可以快速合并就行了，没必要提群论。

**Comment by dong628** [comment]
建议添加更简单形象的描述，并将形式化描述放入 `??? note` 模板中。

**Comment by Great-designer** [comment]
确实，这个不应该出现在这里

**Comment by IdkWhatIsIdk** [comment]
> 一个幺半群 $M=(S,\circ ,e)$，其中 $\circ$ 为在集合 $S$ 上定义的二元运算符，幺半群具有以下性质：
封闭性：$\forall x\in S$ 和 $\forall y\in S$ 有 $x\circ y\in S$。
结合律：$\forall x,y,z\in S$ 有 $(x\circ y)\circ z=x\circ (y\circ z)$。
存在幺元：即 $\exists e\in S$ 满足 $\forall x \in S$ 有 $e\circ x=x$，$e$ 为左幺元；或 $x\circ e=x$，$e$ 为右幺元。

这一段是幺半群的定义, 写在这里显得重复, 可以用[群论](https://oi-wiki.org/math/group-theory/#%E7%BE%A4%E7%9A%84%E8%A1%8D%E7%94%9F%E7%BB%93%E6%9E%84)链接代替

> 其实只需要说明维护的信息满足结合律而且可以快速合并就行了，没必要提群论。

总结: `线段树维护的信息一般需要满足结合律，并且可以快速合并。例如，一些数域上的加法或乘法，或者二元的$\max(x,y)$运算都满足这个要求。注意到这个要求与[幺半群](https://oi-wiki.org/math/group-theory/#%E7%BE%A4%E7%9A%84%E8%A1%8D%E7%94%9F%E7%BB%93%E6%9E%84)类似。`
~~好像可以开pr了~~
