### ISSUE TITLE
[RFC] 修正未在正文使用的脚注

### ISSUE THREAD

**Issue by ouuan** [OI-wiki/OI-wiki#4679]
现在有一些页面的脚注没有在正文中被使用，这存在语义和渲染结果上的问题：

- 在语义上，脚注是对正文的注解，需要有被注解的正文
- 在渲染结果上，未被使用的脚注带来了死链，也影响到了 #4668

我的建议是：

- 如果不在正文中进行标注，参考资料可以列出来，但不应作为脚注
- 不应盲目追求使用脚注，如果只是普通的参考资料，不必强行找到被标注的正文
- 如果大家觉得脚注的样式比较好，可以考虑修改一下主题，以现在脚注的样式显示正常语义的参考资料列表

**Comment by ouuan** [comment]
现有的要不就先直接把没使用的拎出来写成 h2 > ul

**Comment by ouuan** [comment]
GitHub 上未使用的脚注都不会渲染出来，感觉这个 mkdocs 主题也有问题

**Comment by ouuan** [comment]
https://babelmark.github.io/?text=test%5B%5Eref1%5D%0A%0Atest%5B%5Eref2%5D%0A%0Atest%5B%5Eref3%5D%0A%0A%5B%5Eref1%5D%3A+%5Bexample%5D(https%3A%2F%2Fexample.com)%0A%0A%5B%5Eref2%5D%3A+https%3A%2F%2Fexample.com%0A%0A%5B%5Eref3%5D%3A+%3Chttps%3A%2F%2Fexample.com%3E%0A%0A%5B%5Eref4%5D%3A+%5Bexample%5D(https%3A%2F%2Fexample.com)%0A%0A%5B%5Eref5%5D%3A+https%3A%2F%2Fexample.com%0A%0A%5B%5Eref6%5D%3A+%3Chttps%3A%2F%2Fexample.com%3E

草，这个世界真可怕（

但貌似没有会渲染出一个不存在的 backlink 的

**Comment by Great-designer** [comment]
未使用的脚注可以作为参考资料

**Comment by IdkWhatIsIdk** [comment]
“参考资料和注释”分开写
我个人觉得脚注的样式挺好的，但是不太清楚没链接的脚注怎么弄
