### ISSUE TITLE
[内容有误] 筛法一节区间符号打错

### ISSUE THREAD

**Issue by 383494** [OI-wiki/OI-wiki#4680]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/number-theory/sieve/#%E5%88%86%E5%9D%97%E7%AD%9B%E9%80%89

### 我发现页面有这样的问题

“分块筛选”第三段区间 $[a,b]$ 打成 $[a;b]$

**Comment by Tiphereth-A** [comment]
其实这个写法也是可以的，主要是用在以逗号作为小数点的地区（

**Comment by 383494** [comment]
> 其实这个写法也是可以的，主要是用在把逗号作为小数点的地区（

但是一页上几种写法都有（

**Comment by Tiphereth-A** [comment]
> 但是一页上几种写法都有（

那还是统一一下吧
