### ISSUE TITLE
[内容有误] 冗余页面

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4688]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/poly/cntt/

### 我发现页面有这样的问题

基于 #4685 的讨论，页面《快速复数论变换》是多余的。理由如下：

- OI Wiki 不是新闻的收集处：“您发现 X 博士在某个位置发布了新的算法，此时您应该观察其是否能获得广泛认可（如可作为正式比赛中的泛用优秀解法）”

该算法未得到广泛应用。

- OI Wiki 不是个人博客

该算法的《性能和应用》一节列出的应用只有一个人的提交记录。

**Comment by Great-designer** [comment]
同时，大家可以进行根据新标准的冗余页面提议，管理员可以进行批量删除。

**Comment by wlbksy** [comment]
在 https://github.com/OI-wiki/OI-wiki/issues/4685 的 RFC 完成之前，这个暂时还不需要开启。

**Comment by NachtgeistW** [comment]
> 同时，大家可以进行根据新标准的冗余页面提议，管理员可以进行批量删除。

提醒： #4685 现在只是草案。未来会有改变的可能。
在正式发布前请不要作为提删的依据。

**Comment by NachtgeistW** [comment]
> 注：这个并非已经解决而不存在了，未来有一天还是会open的

到时候我们会Reopen的，无需担心。
