### ISSUE TITLE
[功能请求] 区分中英文引号

### ISSUE THREAD

**Issue by CCXXXI** [OI-wiki/OI-wiki#4702]
### 我遇到的问题是

- 当前中英文内容中都有使用弯引号（“……”）
- 没有保证弯引号如何渲染，可能会在英文语境渲染为全角，或在中文语境渲染为半角

### 我希望能有这样的解决方案

- **格式手册**：
  - 全角语境使用直角引号（「……」）
    - [x] #4186
  - 半角语境使用垂直引号（"..."）
    - [x] #4792 
- 对现有引号进行一次手动替换以符合上述要求
  - 全角语境使用直角引号（「……」）
    - [x] #4780 
  - 半角语境使用垂直引号（"..."）
    - [x] #4704 
- **CI**：`git diff` 显示 `.md` 文件中新增了 `“` 或 `”` 则检查不通过
  - [ ] #4845

### 我觉得这些备选方案也可以接受

- 在不同语境中使用不同的字体渲染引号
- 自动替换引号
   - 利用 Bot
   - 利用 GitHub Action

**Comment by Great-designer** [comment]
> * **CI**：`git diff` 显示 `.md` 文件中新增了 `“` 或 `”` 则检查不通过
>   
>   * [ ]  [ci(check-quotes): 增加引号检查 #4845](https://github.com/OI-wiki/OI-wiki/pull/4845)
> 
> ### 我觉得这些备选方案也可以接受
> * 在不同语境中使用不同的字体渲染引号
> * 自动替换引号
>   
>   * 利用 Bot
>   * 利用 GitHub Action

我认为“引号检查”是错误的，应当动用 bot 自动替换。

因为，键盘上输入方框引号并不容易（对于大陆用户而言），为了方便用户的考虑，这项任务应当交给 bot 进行自动替换。假如用户提交了 pr，而用户并不知道如何输入方框引号或者输入过于麻烦，容易造成不必要的争论与矛盾。

**Comment by CCXXXI** [comment]
> 因为，键盘上输入方框引号并不容易（对于大陆用户而言），为了方便用户的考虑，这项任务应当交给 bot 进行自动替换。假如用户提交了 pr，而用户并不知道如何输入方框引号或者输入过于麻烦，容易造成不必要的争论与矛盾。

这些理由可以说明自动替换的好处，但能说明引号检查是错误的吗

**Comment by Great-designer** [comment]
> > 因为，键盘上输入方框引号并不容易（对于大陆用户而言），为了方便用户的考虑，这项任务应当交给 bot 进行自动替换。假如用户提交了 pr，而用户并不知道如何输入方框引号或者输入过于麻烦，容易造成不必要的争论与矛盾。
> 
> 这些理由可以说明自动替换的好处，但能说明引号检查是错误的吗

它能够说明下述逻辑：
- 什么都没有未作说明（是不好的，见之前pr/issue的其他讨论）。
- 只有自动替换未作说明。
- 只有引号检查、没有自动替换，是不好的。
- 引号检查和自动替换，两者都有。是好的。

**Comment by CCXXXI** [comment]
> 1. 什么都没有未作说明（是不好的，见之前pr/issue的其他讨论）。
> 2. 只有自动替换未作说明。
> 3. 只有引号检查、没有自动替换，是不好的。
> 4. 引号检查和自动替换，两者都有。是好的。

如果 3 比 1 更好，就不是错误的，因为至少改进了现状，这和 4 比 3 更好没有关系

**Comment by Great-designer** [comment]
> > 1. 什么都没有未作说明（是不好的，见之前pr/issue的其他讨论）。
> > 2. 只有自动替换未作说明。
> > 3. 只有引号检查、没有自动替换，是不好的。
> > 4. 引号检查和自动替换，两者都有。是好的。
> 
> 如果 3 比 1 更好，就不是错误的，因为至少改进了现状，这和 4 比 3 更好没有关系

然后 3 比 1 并非更好，因为它只检查不修改，没有解决问题，只是把成本转嫁到用户身上，为用户增加了不必要的麻烦。

这样做的结局会导致用户倾向于“逃避使用引号”而不是“正确使用引号”。

**Comment by CCXXXI** [comment]
> 只检查不修改，没有解决问题

这理由能成立的话，可以否定掉所有不带自动修复的检查了。

**Comment by Great-designer** [comment]
> > 只检查不修改，没有解决问题
> 
> 这理由能成立的话，可以否定掉所有不带自动修复的检查了。

这是“断章取义”和“滑坡谬误”。
- 断章取义：我不止说了“只检查不修改，没有解决问题”，这是建立在用户的使用成本基础上的。论点的核心在于“键盘上输入方框引号并不容易”。
- 滑坡谬误：“只检查不修改，没有解决问题”并不能“否定掉所有不带自动修复的检查”，本身根本无法自动修复的错误显然不属于此情况。类似于编译器的指出错误和自动补全，有些情形是无法自动补全的。

**Comment by CCXXXI** [comment]
> 本身根本无法自动修复的错误显然不属于此情况。

认为这类问题可以自动修复的话，给出你设想的自动修复代码。

**Comment by Tiphereth-A** [comment]
@Great-designer 有解决方案总比没有方案要好，即使它不是完美的。若是这个不完美的解决方案对解决问题有积极作用，那么我认为是可以考虑接受这个方案的。另外，坐而言不如起而行，如果您觉得有更好的解决方案，那么我很期待您的 PR，或者是可行的代码思路 :)

**Comment by Great-designer** [comment]
> > 本身根本无法自动修复的错误显然不属于此情况。
> 
> 认为这类问题可以自动修复的话，给出你设想的自动修复代码。

既然它可以check，必然可以修正，只需要把check不通过的地方文本替换即可。

**Comment by Great-designer** [comment]
作为用户，我自己难以调出直角引号，并且不愿意看到这种形式上的事情，成为阻碍我的pr合并的，管理员粗暴的懒政理由。

因此我希望，如果我的pr因为没有直角引号，无法通过check，请管理员立即对我的pr进行手动修正，以通过这个check。这个check不是强加给“难以调出直角引号”的用户的义务，不能成为这样的pr的合并阻碍。

**Comment by Great-designer** [comment]
（另注：我这里由于各种严格的环境上的原因，网络条件很差，不仅好几天登不上GitHub，一条消息发出来可能要半小时以上，我只能坐在这里干着急。如果体现出来的情绪很差或非常急躁，属于正常现象，我为此表示抱歉）

**Comment by Enter-tainer** [comment]
> 如果体现出来的情绪很差或非常急躁，属于正常现象

如果控制不了自己的情绪，建议先冷静一下😇而不是在这里发泄

**Comment by Great-designer** [comment]
> > 如果体现出来的情绪很差或非常急躁，属于正常现象
> 
> 如果控制不了自己的情绪，建议先冷静一下😇而不是在这里发泄

我并没有在这里发泄。从头到尾我都在各种拼命解释原因，回复的长度比收到质疑的长度长得多，态度已经足够好了。

我是说，发一条消息，经常需要不停点击“comment”按钮半个小时，总是受到“You can't comment at this time”的网络故障提示，这是无法改变的现状，我无法及时地回复消息，只能“坐着干着急”而已。

我不能坐视这里有人冒出来发一个很短的短句子，来否认我折腾了半天写的长篇大论，我还一条消息都发不出来，是这么个情况。

如果我坐在这里连续点击“comment”按钮半个小时，还让我“冷静一下”，我认为没有这个必要，这似乎并不是“不够冷静”，而是太冷静了，竟然可以连续点击半个小时。

**Comment by Enter-tainer** [comment]
@Great-designer 你网不好是你自己的问题😇

**Comment by Great-designer** [comment]
> @Great-designer 你网不好是你自己的问题😇

是的，这需要声明出来。我不声明，谁知道我这里糟糕的网络条件？

留着讨论list的最后一条评论是针对我的批判，还以为我对此不会有意见，我这里只是网络不好而已。

**Comment by CCXXXI** [comment]
> 只需要把check不通过的地方文本替换即可。

> Talk is cheap. Show me the code.

\- Linus Torvalds

**Comment by Great-designer** [comment]
> > 只需要把check不通过的地方文本替换即可。
> 
> > Talk is cheap. Show me the code.
> 
> - Linus Torvalds

我问chatGPT“如何看待‘你这么厉害为什么不去证明黎曼假设’这样的句子”，chatGPT认为这构成一种网暴。

**Comment by CCXXXI** [comment]
> 你这么厉害为什么不去证明黎曼假设

你是先问了 `Talk is cheap. Show me the code.` 这个句子，然后发现 ChatGPT 没有给期待的回复，于是替换为 `你这么厉害为什么不去证明黎曼假设` 来重新发问吗？

**Comment by Great-designer** [comment]
关于写代码，这不是属于我的义务。

我们好比在做一台内脏手术，需要3步：把人麻醉划开肚子，把内脏修理好，缝上肚子把人弄醒。

你说，不会做“缝上肚子把人弄醒”，但是前两步已经能做了，所以做了总比不做强。

我说，这不可以。如果是我，我醒不来、肚子缝不上，我会死。

你说，talk is cheap，有本事我来做。

我哪儿会做这个？我只能扮演用户角色，也就是即将死亡的这一方，怎么有可能给自己做手术呢？

**Comment by CCXXXI** [comment]
> 我们好比在做一台内脏手术

如果一定要用内脏手术来类别的话，现状是让机器人自动做手术比较危险，所以只做自动检查。

另外，此检查不会对患者造成伤害，更不会致死。
