### ISSUE TITLE
[内容有误] 在唯一分解整环中，素元等价于不可约元

### ISSUE THREAD

**Issue by GitPinkRabbit** [OI-wiki/OI-wiki#4710]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/number-theory/basic

### 我发现页面有这样的问题

#4077 的贡献者可能看错了上下文，从而举错了例子。因为在唯一分解整环中，素元等价于不可约元。

如果需要一个例子，则给出的整环不能是唯一分解整环，例如 $\mathbf{Z}[\sqrt{-5}]$。

个人认为不必在这里引入抽象代数中的概念，可能会让读者在阅读时产生不必要的疑惑。

**Comment by Great-designer** [comment]
赞同，建议去掉
