### ISSUE TITLE
Add 添加非递归线段树的实现

### ISSUE THREAD

**Issue by zhanhb** [OI-wiki/OI-wiki#4719]
### 页面英文名

nr-seg

### 我希望能添加的内容是

非递归线段树的介绍及代码实现

### 我了解到的相关参考资料有

https://codeforces.com/blog/entry/18051

**Comment by HeRaNO** [comment]
在 #5648 里稍微提了一下 zkw 线段树，放了一下资料，所以感觉这个可以关掉了，如果有必要的话请 reopen 一下。

实现的话，AtCoder Library 的线段树就是用非递归实现的，如果要加的话可以引用 ACL 库。
