### ISSUE TITLE
[BUG] 数据结构部分页面的评论区都变成了 /ds/seg-in-bit/ 这个页面的评论区

### ISSUE THREAD

**Issue by dbxxx-oi** [OI-wiki/OI-wiki#4758]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

数据结构部分页面的评论区都变成了 /ds/seg-in-bit/ 这个页面的评论区，如 /ds/fenwick/，/ds/seg/。

### 我确认这个问题可以这样复现

<https://oi-wiki.org/ds/seg-in-bit/>

<https://oi-wiki.org/ds/fenwick/>

<https://oi-wiki.org/ds/seg/>

**Comment by ouuan** [comment]
这个大概需要启用 giscus 的 strict mode 并批量在所有 discussion 中添加相应的 hash 才能修复，我临时把树状数组套权值线段树的评论区改了来暂时修复树状数组和线段树页面
