### ISSUE TITLE
[内容有误] 为什么LCM放在GCD下面？

### ISSUE THREAD

**Issue by SkyNet-PKN** [OI-wiki/OI-wiki#4761]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/number-theory/gcd/

### 我发现页面有这样的问题

LCM和GCD应该并列吧？我在索引找了半天找不到LCM，要不然把LCM拎出去放在索引里面，要不然将索引标题改成最大公约数&最小公倍数，然后详细页面内把“定义”这个一级标题改成“最小公倍数”

**Comment by untitledunrevised** [comment]
我自己的看法：

一个是 lcm 与 gcd 本来就是相通的，因此 lcm 实在是没有重要到需要单独拎出来单独成一个页面；然后就是也不至于把标题改成 “最大公约数 & 最小公倍数”，一是因为 lcm 远不及 gcd 应用的多，二是因为这篇 wiki 大部分内容都是在讲 gcd 和 exgcd 的；最后就是在 OI Wiki 的搜索框搜索  “最小公倍数” 或 “LCM” 是可以找到 “最大公约数” 这个页面的。

综上我认为既不需要单独拎出来，也不需要修改标题。

**Comment by Enter-tainer** [comment]
感觉 @untitledunrevised 说的挺有道理~先close啦
