### ISSUE TITLE
[功能请求] 增加语言支持

### ISSUE THREAD

**Issue by TimePrinciple** [OI-wiki/OI-wiki#4765]
### 我遇到的问题是

当前的OI WIKI只有中文内容，无法切换到英语

### 我希望能有这样的解决方案

在顶部状态栏加入`ZH/EN`，翻译现有内容。本人可以提供翻译工作支持，可以等到相关工作进行到一定量之后再上线该功能。

**Comment by Enter-tainer** [comment]
@TimePrinciple en.oi-wiki.org，另外感觉这个事情不是很有必要做，优先级比较低

**Comment by diauweb** [comment]
duplicate of #1899
