### ISSUE TITLE
[内容有误] “数学--数论--杜教筛” 一栏有关杜教筛的使用情形描述存在一定误导性

### ISSUE THREAD

**Issue by GoatGirl98** [OI-wiki/OI-wiki#4766]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/number-theory/du/

### 我发现页面有这样的问题

在 [杜教筛](https://oi-wiki.org/math/number-theory/du/) 一栏当中，最一开始提到的是 "积性函数" 。

事实上只要是**已知其狄利克雷卷积形式的数论函数**，无论该函数是否为积性函数，**都可以用杜教筛进行前缀和的求解。**  在最开头只列举积性函数可能会存在一定的误导性。

举个例子，已知 $\sum_{n|d} f(d) = g(n) = n^3+3n^2+n$  ，其中数论函数 $f(n)$ 不难推出不是积性函数，但是其前缀和完全可以使用杜教筛求出。

虽然后续有写到“杜教筛可以用于求数论函数前缀和”，但还是希望负责该版面的人员可以在这里补充并强调，只要是已知狄利克雷卷积形式的数论函数，**无论该数论函数是否为积性函数，都可以进行求解** 。使这部分的描述更严谨一些。

**Comment by Great-designer** [comment]
位于《杜教筛》开头的“积性函数”这节应该直接删了。因为在《数论基础》一文

https://oi-wiki.org/math/number-theory/basic/

的末尾，已经用一节写过了积性函数。
