### ISSUE TITLE
[内容有误] 

### ISSUE THREAD

**Issue by cubeheadsun** [OI-wiki/OI-wiki#4770]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/topic/dsu-app/

### 我发现页面有这样的问题

因为是并查集应用，所以添加一个“并查集” 在 “在加边的过程中顺便处理询问即可”中
https://github.com/OI-wiki/OI-wiki/pull/4769

**Comment by Great-designer** [comment]
请填写标题

**Comment by cubeheadsun** [comment]
怎么填写标题啊qwq

**Comment by cubeheadsun** [comment]
我只能重新开个了qwq
