### ISSUE TITLE
[BUG] 移动欧拉函数

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4771]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

欧拉函数目前的名字叫/math/number-theory/euler

由于众所周知，欧拉是数学大佬，做的事情很多，这种命名容易导致页面评论区冲突

见 #4572 #4062 

建议移动至/math/number-theory/euler-totient

**Comment by Tiphereth-A** [comment]
completed in #4961
