### ISSUE TITLE
[内容有误] 可持久化字典树例题代码不能 AC

### ISSUE THREAD

**Issue by shinzanmono** [OI-wiki/OI-wiki#4785]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/persistent-trie/

### 我发现页面有这样的问题

例题代码不能 AC

**Comment by Great-designer** [comment]
如果确有此类低级锅，恐为紧急事项

**Comment by Tiphereth-A** [comment]
https://www.luogu.com.cn/record/111726002
