### ISSUE TITLE
[BUG] 夜晚模式中无法打开图片

### ISSUE THREAD

**Issue by wxh-233** [OI-wiki/OI-wiki#4795]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![image (1)](https://user-images.githubusercontent.com/93416090/227108072-bad5dc7b-130e-4c86-b6ee-5f885fe8df8f.png)
![image](https://user-images.githubusercontent.com/93416090/227108397-93eac592-7c6f-4de7-928d-56e4a0e32d79.png)

切换至夜晚模式图片无法显示
白天模式图片正常显示

### 我确认这个问题可以这样复现

打开一个有图片的界面
调成夜晚模式

**Comment by Enter-tainer** [comment]
![Screenshot_2023-03-23-13-16-22-056_com.microsoft.emmx.jpg](https://user-images.githubusercontent.com/25521218/227110014-a62208ae-2958-4171-9fad-79937361406a.jpg)

**Comment by Tiphereth-A** [comment]
你用的哪个浏览器，版本号是什么 🤔

**Comment by WAAutoMaton** [comment]
因 bug 无法复现且作者长期未响应，关闭本 issue
