### ISSUE TITLE
Add STRASSEN算法

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4796]
### 页面英文名

STRASSEN

### 我希望能添加的内容是

这是矩阵乘法的一种分治优化办法。

### 我了解到的相关参考资料有

算法导论，或一些博客

**Comment by alphagocc** [comment]
@Great-designer 看看博客链接

**Comment by Great-designer** [comment]
博客的话，随便百度一下就有一大把：
- https://blog.csdn.net/weixin_43736127/article/details/110496581
- https://zhuanlan.zhihu.com/p/268392799
- https://blog.csdn.net/qq_30590623/article/details/83040979
- https://zhuanlan.zhihu.com/p/78657463

**Comment by Nanarikom** [comment]
感觉实践上来说算法竞赛里很少有人写 Karatsuba 乘法或者 Strassen 乘法，尤其是后者...（出题人不太可能卡立方的矩阵乘？）

**Comment by Great-designer** [comment]
> 感觉实践上来说算法竞赛里很少有人写 Karatsuba 乘法

大数乘法都用三模数FNTT搞了……

只是矩阵乘法没办法傅里叶而已

**Comment by Tiphereth-A** [comment]
<https://people.sc.fsu.edu/~jburkardt/presentations/matmul_1995_psc.pdf> p38

感觉 Strassen 算法优势不是很明显啊，而且写起来还很麻烦，算法竞赛中基本没有应用，介绍这个算法应该没什么必要 🤔

**Comment by Great-designer** [comment]
也许现在都用GPU 并行了
