### ISSUE TITLE
作者信息统计不全

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#480]
如果路径有改动，github api 统计不到之前那个路径的 commit 信息。
比如 `data-structure/ -> ds/`，然后改路径之前的统计信息都不见了。

计划的解决方案是重新统计一下，然后开个 新仓库 / branch 存每个页面的信息，到时候就不需要每次重新调用 github api 了（#424）

肯定是尽快实现，写完 ics lab 就来写这个（

对于之前没被正确统计进来的同学，十分抱歉，这个是我的疏忽

**Comment by CBW2007** [comment]
意思是在开一个名为"count"之类的文件夹专门统计作者信息？

~~反正我不会~~

**Comment by Ir1d** [comment]
@CBW2007 搞个新仓库或者新 branch ……，在那建个文件夹

**Comment by Ir1d** [comment]
找到了一个很妙的脚本 https://stackoverflow.com/a/11740682/4597306
顺便 https://github.com/isaacs/github/issues/900

**Comment by Ir1d** [comment]
之前看那个脚本统计作者的时候用户名有多个（比如 Ir1d 和 Ir1dXD），想到似乎邮箱是对的，或许可以先用邮箱去重，然后再反查用户名

```
git ls-tree -r --name-only master ./ | while read file ; do
    echo "=== $file"
    git log --follow --pretty=format:'%an %aE' -- $file | sort | uniq
done
```

ref: https://git-scm.com/docs/pretty-formats

**Comment by i-Yirannn** [comment]
资磁

**Comment by sshwy** [comment]
QAQ顺便提一下吧，快速傅里叶变换我写了一下快速傅里叶逆变换的相关证明，名单貌似咕咕了～
