### ISSUE TITLE
[内容有误] 树哈希页面中题目"[BJOI2015]树的同构"的做法一和做法二的位置反了

### ISSUE THREAD

**Issue by ZYM1111** [OI-wiki/OI-wiki#4810]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oiwiki.org/graph/tree-hash/

### 我发现页面有这样的问题

树哈希页面中题目"[BJOI2015]树的同构"的做法一和做法二的位置反了

**Comment by Great-designer** [comment]
看来需要尽快修一下
