### ISSUE TITLE
[功能请求] 两个线性空间的交

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4813]
### 我遇到的问题是

众所周知，两个线性空间的并好做，交不好做

刚刚得知可以用正交补的办法做出两个线性空间的差，这需要欧氏空间和内积的知识

（但是这学期没有矩阵课，不想做了）

从而借助QR分解可以构造两个线性空间的差，进而构造两个线性空间的交

### 我希望能有这样的解决方案

另外异或空间里没有内积，但是异或空间可以想象成2^n顶点的n维超立方体，从而垂直的概念可以引入

从而QR分解可以做，仍旧可以做异或空间下两个空间的差，也有两个空间的交

**Comment by Tiphereth-A** [comment]
求线性空间的交的做法和求并的一致，感觉没什么必要
