### ISSUE TITLE
[内容有误] 

### ISSUE THREAD

**Issue by Thaumic-Executor** [OI-wiki/OI-wiki#4837]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/tools/cmd/#%E5%9F%BA%E7%A1%80

### 我发现页面有这样的问题

关于用户chtholly，描述“ta的主目录”时用了两个不同性别的他

**Comment by Great-designer** [comment]
确实是个问题
