### ISSUE TITLE
Add 2-3树

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4839]
### 页面英文名

未知

### 我希望能添加的内容是

一种类似于AVL树的数据结构，可以与AVL树的行文构成对比。

### 我了解到的相关参考资料有

暂无

**Comment by Yegezw** [comment]
这里有两篇参考资料链接，内容是 2 - 3 树、红黑树，以及它们之间的关系
另外，《算法4》中有对 2 - 3 树和红黑树的介绍，值得一提的是，这本书的作者是红黑树的发明人
https://www.cnblogs.com/lidong422339/p/17306209.html
https://www.cnblogs.com/lidong422339/p/17307046.html
