### ISSUE TITLE
Add 线段树分裂

### ISSUE THREAD

**Issue by xiaohanlin101407** [OI-wiki/OI-wiki#4852]
### 页面英文名

segment-tree-split

### 我希望能添加的内容是

有关线段树分裂相关的实现和用途

### 我了解到的相关参考资料有

- https://www.luogu.com.cn/blog/cyffff/talk-about-segument-trees-split

**Comment by Tiphereth-A** [comment]
duplicate #2354

**Comment by Tiphereth-A** [comment]
completed in #4887
