### ISSUE TITLE
完善Trie内容& add 01字典树 

### ISSUE THREAD

**Issue by stevebraveman** [OI-wiki/OI-wiki#486]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？

01字典树

- 英文叫什么？

01trie

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by Ir1d** [comment]
@stevebraveman 大佬是希望在目录里新开个页面吗
