### ISSUE TITLE
[BUG] Toggle块中带有外部链接的Snippet无法正常显示

### ISSUE THREAD

**Issue by Craneplayz** [OI-wiki/OI-wiki#4883]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

在网站上所有可以Toggle的代码块中带有External Link的Snippet无法显示，我目前使用的是 Safari 浏览器
<img width="786" alt="image" src="https://github.com/OI-wiki/OI-wiki/assets/96546412/31320f63-a596-43cf-bbda-b00b14f323bd">

Clone下来后在Local可以显示
<img width="874" alt="image" src="https://github.com/OI-wiki/OI-wiki/assets/96546412/02c5e673-4ef6-4d93-a764-3ef6b51c13b5">

### 我确认这个问题可以这样复现

例子：
斯坦纳树 Steiner Tree 的页面
https://oiwiki.com/graph/steiner-tree/

**Comment by Enter-tainer** [comment]
应该，修好了🙏
