### ISSUE TITLE
[BUG] 例题代码无法显示

### ISSUE THREAD

**Issue by ShwStone** [OI-wiki/OI-wiki#4888]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

所有的例题代码（也就是用 `--8<-- "路径"` 表示的代码）都无法显示，包括主站和镜像站。

我注意到html源代码中完全没有代码内容，可能是在站点构建时就出了问题。

因为我不了解OI-wiki的构建过程，我没有考虑修复它。

### 我确认这个问题可以这样复现

正常使用浏览器打开网页即可复现。我尝试了多种浏览器、电脑系统版本。

**Comment by ShwStone** [comment]
![捕获](https://github.com/OI-wiki/OI-wiki/assets/90076553/0e2eec45-8de6-41cf-b0a8-45e546acd918)

**Comment by Enter-tainer** [comment]
duplicate #4883
