### ISSUE TITLE
Add Splay区间操作

### ISSUE THREAD

**Issue by limuy2022** [OI-wiki/OI-wiki#4930]
### 页面英文名

添加在原splay页面的后面

### 我希望能添加的内容是

splay以强大的区间操作而闻名，但当前OI WIKI仅仅对splay的基础操作做了解释，未解释如插入区间，删除区间，翻转区间等高级操作，这些操作在OI中也是十分重要的知识

### 我了解到的相关参考资料有

该方面资料较多，可以自行查找

**Comment by Rickyxrc** [comment]
表示强烈支持。

请问您有时间着手进行相关内容的编写并创建 pull request 吗？如果没有的话我可以帮忙。

**Comment by zzxLLLL** [comment]
> 

我最近有时间，可以提pull requests

**Comment by zzxLLLL** [comment]
> 表示强烈支持。
> 
> 请问您有时间着手进行相关内容的编写并创建 pull request 吗？如果没有的话我可以帮忙。

我最近有时间提pull requests
