### ISSUE TITLE
建议添加遗传算法和蚁群算法

### ISSUE THREAD

**Issue by Novice-hackers** [OI-wiki/OI-wiki#4948]
### 我遇到的问题是

为什么有模拟退火算法却没有遗传算法和蚁群算法？望添加！

### 我希望能有这样的解决方案

添加上去

### 我觉得这些备选方案也可以接受

把其他网站（如CSDN）上面的相关介绍的链接放过来

**Comment by wlbksy** [comment]
或者换个问题：模拟退火、梯度下降、群算法、遗传算法等近似算法是否都应该干掉？

这类问题已经逐渐淡出 OI 了

**Comment by lnw143** [comment]
没有专门用这类算法解决的题目，但是这类算法可以在一些题目中取得很好的效率和正确性

**Comment by Tiphereth-A** [comment]
OI 里用 Metaheuristic 的场合也不是很多，感觉爬山算法和模拟退火这种简单的已经足够使用了，再深入就过于 off topic 了。
