### ISSUE TITLE
将 MinGW-w64 的安装包链接从 MinGW Builds 改为 WinLibs

### ISSUE THREAD

**Issue by argvchs** [OI-wiki/OI-wiki#4951]
### 页面英文名

compiler

### 我希望能添加的内容是

https://oi.wiki/tools/compiler/#windows
https://oi.wiki/tools/compiler/#windows_3

最近似乎 MinGW-w64 下载页面多了一个部分，就是 [WinLibs](https://www.mingw-w64.org/downloads/#winlibscom)
这个 WinLibs 做的构建版本安装容易，直接选 Release 最上面的一个版本就可以
**并且顺带安装了 LLVM Clang 啊！** 其实也可以选择不顺带安装

所以想把原页面 Windows 部分的 MinGW-w64 的安装包链接从 MinGW Builds 改为 WinLibs
（并且把 LLVM 的部分增加一个下载方式？

另外可能有人觉得 WinLibs 不是官方做的不是很好，但是 MinGW Builds 也不是啊（显然是 niXman 做的）

### 我了解到的相关参考资料有

https://www.mingw-w64.org/downloads

**Comment by alphagocc** [comment]
@argvchs 欢迎 pr

**Comment by argvchs** [comment]
但是不能 PR 啊，要改图片

**Comment by argvchs** [comment]
啊我才发现图片要在 image 里改（
之前用的都是 Menci 的镜像站（因为 oi.wiki 比 oi-wiki.org 短），图片是不同域名的，以为不能在这里
但是主站是同域名的

**Comment by Menci** [comment]
@argvchs 我是全站 mirror 了一份 CDN，所以图片和其他资源文件其实还是和主站在一起

**Comment by argvchs** [comment]
我在最后 PR 前测试了一下发现 WinLibs 的版本似乎不能 `cin` `cout`？？（但是可以 `scanf` `printf`）
