### ISSUE TITLE
Add 秦九韶算法/霍纳法则

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4962]
### 我希望能添加的内容是

秦九韶算法/霍纳法则

一个很简单的内容，暂时搜索不到

### 我了解到的相关参考资料有

网上到处都是

**Comment by yyyu-star** [comment]
我正在尝试添加此项内容

**Comment by yyyu-star** [comment]
可以请问一下，这一内容应该定位到哪一页面呢，考虑添加到多项式部分，但感觉没有很适合的页面进行添加，由于该算法是一个简单的内容，因此为该内容单独添加页面也不太合适

**Comment by Tiphereth-A** [comment]
依群友讨论关闭此 PR
