### ISSUE TITLE
在工具软件中增加小熊猫C++的介绍

### ISSUE THREAD

**Issue by royqh1979** [OI-wiki/OI-wiki#4963]
### 页面英文名

redpandacpp

### 我希望能添加的内容是

小熊猫C++是一个开源、免费、跨平台的轻量级C/C++/GNU汇编集成开发环境，基于QT5.15，是Dev-C++的升级替代版，主要目标用户是C/C++编程教学和算法竞赛的师生。

希望能够在OI-Wiki的工具软件部分中增加相关介绍。

中文网站地址: https://royqh1979.gitee.io/redpandacpp/
github网址：https://github.com/royqh1979/RedPanda-CPP/

**Comment by Tiphereth-A** [comment]
已经有了
https://oi-wiki.org/tools/editor/devcpp/#%E4%BB%8B%E7%BB%8D

**Comment by royqh1979** [comment]
> 已经有了 https://oi-wiki.org/tools/editor/devcpp/#%E4%BB%8B%E7%BB%8D
> 

这个网页里涉及的是小熊猫Dev-C++，在Dev-C++基础上发展的版本，使用Delphi语言开发。

小熊猫C++是使用C++语言和QT5从头开发的**全新软件**，可以跨平台，除了在基本功能上模仿Dev-C++外，还提供了和CP Editor类似的试题集（自动测试）功能，支持使用Competitive Companion下载OJ试题等等。

**Comment by royqh1979** [comment]
感谢。已提交PR
