### ISSUE TITLE
Add 正则表达式

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#4964]
### 我希望能添加的内容是

搜了一下发现缺乏正则表达式的相关介绍

### 我了解到的相关参考资料有

略

**Comment by AtomAlpaca** [comment]
不懂就问, 正则表达式在 OI 中真的有应用吗?

**Comment by Tiphereth-A** [comment]
https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E7%99%BE%E7%A7%91%E5%85%A8%E4%B9%A6
