### ISSUE TITLE
Add 子集枚举 & 全排列 & 补充其他枚举相关

### ISSUE THREAD

**Issue by acangcang-Eliauk** [OI-wiki/OI-wiki#4991]
### 请选择：
* [x]  我正在着手修复这个问题
### 页面英文名
enumerate
### 我希望能添加的内容是
发现最重要的暴力枚举部分缺了很多东西
### 我了解到的相关参考资料有
《深入浅出》《算法程序设计竞赛》等

**Comment by acangcang-Eliauk** [comment]
> ### 请选择：
> * [x]   我正在着手修复这个问题
> 
> ### 页面英文名
> enumerate
> 
> ### 我希望能添加的内容是
> 发现最重要的暴力枚举部分缺了很多东西
> 
> ### 我了解到的相关参考资料有
> 《深入浅出》《算法程序设计竞赛》等

刚刚发现子集枚举 & 全排列都有介绍了，但是我还会补充其他枚举相关，在此对我没有查找表示歉意。

**Comment by Great-designer** [comment]
可以在补充的同时进行整理

**Comment by Great-designer** [comment]
重复的#5097 认为添加到“状压 DP”。可以深入思考
