### ISSUE TITLE
Add atcoder rating预测工具

### ISSUE THREAD

**Issue by Rickyxrc** [OI-wiki/OI-wiki#5015]
### 我希望能添加的内容是

一个tampermonkey插件，用于预测你的atcoder rating变化。

### 我了解到的相关参考资料有

https://greasyfork.org/zh-CN/scripts/369954-ac-predictor

**Comment by GoodCoder666** [comment]
可以加到 [OJ 工具](https://oi-wiki.org/tools/oj-tool/) 这里，你要不自己开个 PR 来加一下？

另外，
- ac-predictor 还有一个我汉化的版本：https://greasyfork.org/zh-CN/scripts/458528-ac-predictor-cn
- 可以把预测 CF rating 的 Carrot 也加上。

**Comment by Rickyxrc** [comment]
@GoodCoder666 好的，稍晚提交 pull request，并增加您补充的内容，十分感谢。
