### ISSUE TITLE
Add SCS 问题的描述和解法

### ISSUE THREAD

**Issue by laicz-007** [OI-wiki/OI-wiki#5075]
### 页面英文名

scs-problem

### 我希望能添加的内容是

由于网络和某些 OJ 上均有关于 SCS 问题的描述，因此请求添加关于 SCS 问题的描述和解法。

### 我了解到的相关参考资料有

https://www.techiedelight.com/shortest-common-supersequence-introduction-scs-length/

**Comment by alphagocc** [comment]
OI Wiki 不是个人博客，也不是百科全书。它不应承担特定问题的题解的功能。

OI Wiki 只收录普遍的比较有代表性的算法

不是说你看到一个题就值得写到 Wiki 上的

不会做可以到洛谷等地发帖提问
