### ISSUE TITLE
Add SCS 问题（最短超序列/最短公共父序列）

### ISSUE THREAD

**Issue by laicz-007** [OI-wiki/OI-wiki#5076]
### 页面英文名

No response

### 我希望能添加的内容是

关于 SCS 问题的描述和求解方式

### 我了解到的相关参考资料有

https://www.techiedelight.com/shortest-common-supersequence-introduction-scs-length/

**Comment by laicz-007** [comment]
稍后提交 pull request

**Comment by laicz-007** [comment]
From：ChatGPT
LCS（Longest Common Subsequence）和SCS（Shortest Common Supersequence）是两个在计算机科学中常用的字符串算法问题。

LCS是指在两个字符串中寻找最长的公共子序列。子序列是指在原序列中删除若干字符得到的新序列，而不改变其他字符的顺序。LCS问题可以用来解决字符串相似性比较、版本控制、生物信息学等领域的应用。LCS问题的解决方法有动态规划、回溯等多种算法。

SCS则是指在两个字符串中找到最短的包含这两个字符串的超序列。超序列是指包含了原序列中所有字符的新序列，可以在原序列中插入若干字符得到。SCS问题在字符串合并、文本编辑、编译器等领域有着广泛的应用。解决SCS问题的方法也包括动态规划、贪心算法等。

因此，LCS和SCS的区别在于它们的求解目标不同。LCS问题是寻找最长的公共子序列，而SCS问题是寻找最短的包含两个序列的超序列。它们在应用场景和解决方法上也有所差异。

**Comment by r-value** [comment]
> > 我还是想知道这个问题和「最长公共子序列」有什么本质上的区别
> 
> 这个区别不够明显吗？LCS 和 SCS 了

断言：两个问题本质相同，对于长度分别为N,M的两个串，其SCS=N+M-LCS，是一步非常trivial的归约。

> 解决SCS问题的方法也包括动态规划、贪心算法等

请不要引入荒谬的AIGC。

**Comment by laicz-007** [comment]
> > > 我还是想知道这个问题和「最长公共子序列」有什么本质上的区别
> > 
> > 
> > 这个区别不够明显吗？LCS 和 SCS 了
> 
> 断言：两个问题本质相同，对于长度分别为N,M的两个串，其SCS=N+M-LCS，是一步非常trivial的归约。
> 
> > 解决SCS问题的方法也包括动态规划、贪心算法等
> 
> 请不要引入荒谬的AIGC。
事实上我想描述的不是输出长度

**Comment by laicz-007** [comment]
> > > 我还是想知道这个问题和「最长公共子序列」有什么本质上的区别
> > 
> > 
> > 这个区别不够明显吗？LCS 和 SCS 了
> 
> 断言：两个问题本质相同，对于长度分别为N,M的两个串，其SCS=N+M-LCS，是一步非常trivial的归约。
> 
> > 解决SCS问题的方法也包括动态规划、贪心算法等
> 
> 请不要引入荒谬的AIGC。

邮件太慢了我现在才收到

**Comment by laicz-007** [comment]
> > > 我还是想知道这个问题和「最长公共子序列」有什么本质上的区别
> > 
> > 
> > 这个区别不够明显吗？LCS 和 SCS 了
> 
> 断言：两个问题本质相同，对于长度分别为N,M的两个串，其SCS=N+M-LCS，是一步非常trivial的归约。
> 
> > 解决SCS问题的方法也包括动态规划、贪心算法等
> 
> 请不要引入荒谬的AIGC。

Leetcode 上的输出可能的一种 SCS 是个不错的方案，我想可以输出 SCS 方案数

**Comment by Tiphereth-A** [comment]
鉴于并没有收到 <https://github.com/OI-wiki/OI-wiki/issues/5076#issuecomment-1673042162> 提到的新 PR，并且根据 <https://github.com/OI-wiki/OI-wiki/issues/5074#issuecomment-1672931490>，这个 issue 将被先行关闭。
