### ISSUE TITLE
[RFC] 是否应该移除“数学/多项式与生成函数”中“符号化方法”一文

### ISSUE THREAD

**Issue by kfc-crazy-thursday** [OI-wiki/OI-wiki#5090]
### 提案的具体内容

本人认为，该文不符合 [项目方针：OI Wiki 不是什么](https://oi-wiki.org/intro/what-oi-wiki-is-not/) 中的“OI Wiki 不是发表原创研究的场所”一项约定
原因：这个方法在 OI 中**基本没有应用**，可以找一下洛谷的 poly 题的题解里基本没有（至少笔者在写过许多 poly 的情况下，在读到此文之前没遇到过涉及到这个的文章，更没用过），熟悉 poly 的人会轻松发现这些完全可以被生成函数运算**代替**，而且网上找到的相关纸质资料基本只有文中所提到的《Analytic Combinatorics》一书
且本人在 Baidu 上以“组合数学 符号化方法”为关键词搜索，发现在本 Wiki“符号化方法”页面添加前有关符号化方法的内容的只有 2018 年发布的 [此文](https://zhuanlan.zhihu.com/p/31595840)，在此 Wiki 页面发布之后发布的相关博客内容大多复制自本文，内容也和本文很相似，**很少有独立产出的内容**，由此可见该做法属于项目方针中所说的“新理论”、“非常规做法”，且在 OI 领域中基本没有应用，因此完全没有介绍的必要

### 相关链接与参考资料

https://oi-wiki.org/intro/what-oi-wiki-is-not
https://zhuanlan.zhihu.com/p/31595840
https://wenku.baidu.com/view/2fab7c015bfb770bf78a6529647d27284a73375a.html

**Comment by untitledunrevised** [comment]
就我自己的想法，我真的不希望，至少不应该是直接草率地删除，大致理由如下：
1. 在 OI 中基本没有应用？这本质上可以认为是那些经典组合计数方法的规范且抽象的描述，而一个抽象的描述我觉得适用性更广（就像认为线段树可维护的信息构成半群那样）；
2. 可代替不代表就没有理由存在。这篇 wiki 已经非常清晰地总结了各种常见的组合方法，而一篇总结性的 wiki 是非常利于查阅的；
3. 它并不可代替：直接展示生成函数运算 和 介绍生成函数运算的应用 差别巨大，甚至就这一点而言 “符号化方法” 是使得 “？？生成函数” 有了更加广泛而清晰的应用举例；
4. 它不新，也很常规：我可以从其它跟组合数学相关的维基看到使用此类记号的地方，就我而言如此简洁的记号就说清楚了一切东西是非常有意义，且对思考问题是有很大帮助的。参考 [wiki1](https://en.wikipedia.org/wiki/Stirling_numbers_and_exponential_generating_functions_in_symbolic_combinatorics) [wiki2](https://en.wikipedia.org/wiki/Bell_number#Generating_function)

**Comment by KevinYao1224** [comment]
符号化方法是处理生成函数的一种通用性较强的体系化方法，Sequence, Multiset, Set 和 Cycle 构造的对应式子固然是生成函数运算与 Polya 定理的一种包装，然而它提供了一种模块化视角构造复杂组合结构生成函数的视角，这是非常有用的。本 wiki 中的介绍，在熟练掌握生成函数技术的前提下并不抽象，是比较清晰的。我们从来不对知识要求“不可替代性”，各种思维技巧与包装整理而成的知识体系，即使没有引入新的内容，也可以加速思考的过程，帮助我们建立更深刻的理解。也许在绝大多数题目中，这些技巧都不需要被使用，但是因此就删除这些技术，是十分愚蠢短视的。至于所谓在 OI 中的应用缺乏，只能说没有有名的例题，并不代表这种技术在 OI 中是无用的。洛谷题解区也只不过涵盖了 OI 很小的一部分，很多高妙解法、经典题目都不能在洛谷找到。关于更多资料，您可以阅读 xyix.github.io 上，组合结构符号化的相关内容，这篇文章正是与 OI-wiki 上本章节不同的一种对符号化方法的介绍，基于这种方法，作者还给出了 ZJOI 一道经典题目的更套路化、流程化的解法。文中还有很多其他例题，以及有标号体系与其他体系的生成函数的符号化方法。相信阅读这篇文章可以改变您对符号化方法的看法。您也提到了 Analytic Combination，同样可以去读，难道它不能说明符号化方法的重要性吗？

**Comment by KevinYao1224** [comment]
符号化方法是解析组合学中现有的一套体系，虽然我对此了解也并不深入，但是我可以说这绝不是所谓的原创内容、新内容，而是对一种现有的经典知识的介绍。同时我认为本文对它的介绍比较成功。

**Comment by KevinYao1224** [comment]
符号化方法是解析组合学中现有的一套体系，虽然我对此了解也并不深入，但是我可以说这绝不是所谓的原创内容、新内容，而是对一种现有的经典知识的介绍。同时我认为本文对它的介绍比较成功。

**Comment by Great-designer** [comment]
抽象和重复倒是真的。还是希望能写清楚的尽可能写清楚，能精简的精简一些。
文章位置的话，似乎直接放在《多项式与生成函数简介》一文后面更好。《符号化方法》这文章里面不少内容是《多项式与生成函数简介》一文的大量重复和解释……

**Comment by Great-designer** [comment]
> 也许在绝大多数题目中，这些技巧都不需要被使用，但是因此就删除这些技术，是十分愚蠢短视的。至于所谓在 OI 中的应用缺乏，只能说没有有名的例题，并不代表这种技术在 OI 中是无用的。

此段论述存在小问题。因为恰恰是在题目中，这些技巧已经被用过了。这篇文章的内容确实是没有问题的。例题的话，文章中也给出了很多例题，可见它确实应用并不少。

它的问题很可能在于选择了一个不太常见的“符号化方法”作为译名——高级译名在初等的做题环境中不常见，以至于“好像本文在各个地方都见不到”。它只是把一些较为简单的内容用较为复杂的方式来叙述了。

**Comment by Great-designer** [comment]
> 它并不可代替：直接展示生成函数运算 和 介绍生成函数运算的应用 差别巨大，甚至就这一点而言 “符号化方法” 是使得 “？？生成函数” 有了更加广泛而清晰的应用举例；

这个倒是完全正确的。《符号化方法》讲了应用部分，而前文《多项式与生成函数简介》应当叙述理论部分。

很有趣的是，目前理论部分讲的相对较为通俗，从理论落实到应用部分，应用部分的叙述层面语言风格上却显得高级了。这是应当考虑的问题。

**Comment by Tiphereth-A** [comment]
首先，感谢您对 OI Wiki 的关注与贡献 ❤️

我认为「符号化方法」 一文不应被移除，理由如下：

1.  「符号化方法」是基于 _Analytic Combinatorics_ 一书撰写的，而该书是 2009 年出版的[^1]，目前有超过 4k 的引用数[^2]，并不符合「原创内容」的定义。
2.  「符号化方法」是一套更加普适、系统和抽象的理论，「在 OI 中的计数题等中可被相对具体的生成函数运算代替」这一点并不能导出「符号化方法是非常规做法」的结论。若将生成函数做法视为「常规做法」，那作为生成函数的抽象，「符号化方法」不可被视为「非常规做法」。
3.  如第 2 条所说，「符号化方法」可视作生成函数的抽象，并且「符号化方法」一文中也给出了大量例题，所以「在 OI 中基本没有应用」的说法不成立。

另外，关于此类问题应在 #5045 中讨论。

如果您有不同的观点，欢迎您在 #5045 中继续跟进讨论 :)

[^1]: <https://algo.inria.fr/flajolet/Publications/books.html>
[^2]: <https://scholar.google.com/scholar?hl=zh-CN&q=ANALYTIC+COMBINATORICS>
