### ISSUE TITLE
[BUG] oi-wiki.org 及其子站 (包括status.oi-wiki.org) 均无法访问

### ISSUE THREAD

**Issue by shine-yu-student** [OI-wiki/OI-wiki#5095]
### 请选择：

- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

<img width="960" alt="屏幕截图 2023-08-18 195736" src="https://github.com/OI-wiki/OI-wiki/assets/105355837/e16d4373-c793-49a3-8915-f1625601eee7">
<img width="960" alt="屏幕截图 2023-08-18 195808" src="https://github.com/OI-wiki/OI-wiki/assets/105355837/dea5b472-352b-429d-b30d-1e492a87dddf">

请问是否存在dns劫持等情况？

**Comment by iliyian** [comment]
我也遇到了这个问题，似乎变成了德国的ip?

**Comment by r-value** [comment]
域名过期了，可以暂时先使用镜像站代替，如 oi.wiki

**Comment by YXHXianYu** [comment]
oi-wiki.com可以正常访问。
但域名过期令人担心，万一被买走了就糟糕了。

**Comment by billchenchina** [comment]
@YXHXianYu ?!

**Comment by Ir1d** [comment]
抱歉各位，之前配置的 auto renew 没有生效，现在已经付款更新了，正在等待 dns 生效

**Comment by Ir1d** [comment]
现在应该已经刷新 dns record 了，等 dns propagate 完全就会完全恢复
