### ISSUE TITLE
Add List-Based Simulated Annealing

### ISSUE THREAD

**Issue by lnw143** [OI-wiki/OI-wiki#5096]
### 页面英文名

LBSA

### 我希望能添加的内容是

堆优化模拟退火（List-Based Simulate Anneal）

### 我了解到的相关参考资料有

[List-Based Simulated Annealing Algorithm for Traveling Salesman Problem](https://www.hindawi.com/journals/cin/2016/1712630/)

**Comment by Tiphereth-A** [comment]
same as https://github.com/OI-wiki/OI-wiki/issues/4948#issuecomment-1702877096
