### ISSUE TITLE
Add 枚举子集 / 子集的子集

### ISSUE THREAD

**Issue by Hszzzx** [OI-wiki/OI-wiki#5097]
### 我希望能添加的内容是

建议添加到 状压 DP 页面。
例题：[洛谷 P5911](https://www.luogu.com.cn/problem/P5911)。

### 我了解到的相关参考资料有

暴力枚举集合并判断是否是其子集是 O(4^n) 的，但总共的子集只有 3^n 
个（可用二项式定理证明）。

O(3^n) 代码如下：
```cpp
for (int i = 1; i < (1 << n); ++i)
    for (int j = i; j; j = (j - 1) & i) 
        // Do something...
```

**Comment by Great-designer** [comment]
重复 #4991 

另外这俩都已经写了，要么调整文章结构，要么可能是非必要的
