### ISSUE TITLE
[功能请求] 题目用统一形式的链接跳转

### ISSUE THREAD

**Issue by Molmin** [OI-wiki/OI-wiki#5148]
### 我遇到的问题是

同一 OJ 的题目链接不统一，部分无法访问。

### 我希望能有这样的解决方案

用 "/problem/HDU-1001" 等链接跳转到对应题库页面，批量修改维护较为方便。

### 我觉得这些备选方案也可以接受

也可以使用特殊链接语法（例如定义语法 `[text](problem:luogu/P1001)`），编译 Markdown 时事先处理。

**Comment by Enter-tainer** [comment]
oj链接统一了会有什么明显的好处吗，似乎也不能解决链接挂掉的问题？另外可否列举一些挂掉的链接，我们可以修复一下。
