### ISSUE TITLE
[BUG] 图论从树的重心跳到树链剖分会炸

### ISSUE THREAD

**Issue by liumingedwin** [OI-wiki/OI-wiki#5168]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![image](https://github.com/OI-wiki/OI-wiki/assets/51841740/586a1daa-b60f-4eee-a537-be05e1957585)
期望链接: <https://oi.wiki/graph/hld>

### 我确认这个问题可以这样复现

至少在<https://oi.wiki>上面可以

**Comment by Enter-tainer** [comment]
什么是“会炸”？你能详细介绍一下你做了哪些操作，期望行为和实际行为是什么吗

**Comment by LeoJacob** [comment]
链接 https://oi.wiki/graph/hld 可以正常访问树链剖分相关内容，但是从该页面通过点击左侧元素进行同级的页面跳转均会出现 404。

通过链接 https://oi.wiki/graph/hld 则不会。

**Comment by Enter-tainer** [comment]
似乎 oi-wiki.org 是正常的？应该是 oi.wiki 独有的问题 cc @Menci

**Comment by liumingedwin** [comment]
现在改成了会回主页

**Comment by Menci** [comment]
我看看

**Comment by Menci** [comment]
移动端无法复现…

**Comment by HeRaNO** [comment]
https://github.com/OI-wiki/OI-wiki/assets/18643142/3db53baa-ef99-432f-bc0e-7661bc1e4d40



> 移动端无法复现…

在 PC 端 chrome 可以复现

**Comment by Menci** [comment]
@HeRaNO 我大概知道是什么问题了，是我的锅，我加个 TODO

**Comment by Menci** [comment]
Fixed in https://github.com/Menci/oi-wiki-mirror/commit/45e065d2d568f0999ec7348afd53746d8aeaa663
