### ISSUE TITLE
[内容有误] 快速幂部分的描述和代码不连贯

### ISSUE THREAD

**Issue by shenshuaijie** [OI-wiki/OI-wiki#5176]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/binary-exponentiation/#%E5%AE%9E%E7%8E%B0

### 我发现页面有这样的问题

该部分数学推导出的公式和代码并不连贯：

![Snipaste_2023-10-09_00-01-12](https://github.com/OI-wiki/OI-wiki/assets/49723559/d0a8effd-1b82-4bc8-8369-5617ddb57fcc)

对新手来说，在读懂了前述公式后，初看代码很难理解为什么是下述代码，或许可以通过另外的数学形式引入该部分代码。

下面是我一个小建议，或许可以通过这样的形式使得数学公式和代码更加连贯。

![Snipaste_2023-10-09_22-18-09](https://github.com/OI-wiki/OI-wiki/assets/49723559/7114a4a0-53fa-4480-b131-26c783c24bc0)

**Comment by yanboishere** [comment]
👍

**Comment by Great-designer** [comment]
👍

**Comment by Tiphereth-A** [comment]
Hi，方便开个 PR 嘛 ❤️

**Comment by shenshuaijie** [comment]
> Hi，方便开个 PR 嘛 ❤️

ok ， 等我这两天写一下，后面提交一下pr
