### ISSUE TITLE
[内容有误] 随机树的高度

### ISSUE THREAD

**Issue by OrigenesZhang** [OI-wiki/OI-wiki#5177]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/graph/lca/#%E6%80%A7%E8%B4%A8_1

### 我发现页面有这样的问题

> 朴素算法预处理时需要 dfs 整棵树，时间复杂度为 $O(n)$，单次查询时间复杂度为 $\Theta(n)$。但由于随机树高为 $O(\log n)$，所以朴素算法在随机树上的单次查询时间复杂度为 $O(\log n)$。

随机树高应该是 $O(\sqrt n)$. ref: [On the Height of Trees](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/C30DF2A9C26541526D847E0A0D46F2A8/S1446788700004432a.pdf/on-the-height-of-trees.pdf)

**Comment by Enter-tainer** [comment]
@OrigenesZhang 这个和随机生成的方式会有关吗，这个纸证的是，从所有可能的树里面均匀采样，期望高度是 sqrt n

**Comment by Enter-tainer** [comment]
@OrigenesZhang 不过感觉这个东西应该不必太纠结。。或许可以删了？改成 O（树高）就行

**Comment by OrigenesZhang** [comment]
> @OrigenesZhang 这个和随机生成的方式会有关吗，这个纸证的是，从所有可能的树里面均匀采样，期望高度是 sqrt n

是的。在所有$n$个点的树中（等概率）随机选取一颗跟（等概率地）随机选取一个点作为新节点的父节点知道树的大小为$n$似乎是不一样的。

**Comment by OrigenesZhang** [comment]
> @OrigenesZhang 不过感觉这个东西应该不必太纠结。。或许可以删了？改成 O（树高）就行

我也觉得不用太纠结。具体怎么处理的话看你们作为maintainer的想法吧。我是刚刚看到这个觉得有点奇怪所以提了一个issue

**Comment by Enter-tainer** [comment]
related: https://oi.wiki/contest/problemsetting/#%E7%94%9F%E6%88%90%E9%9A%8F%E6%9C%BA%E6%A0%91
