### ISSUE TITLE
[BUG]  图的存储 网页显示出问题

### ISSUE THREAD

**Issue by zhangjunCPP** [OI-wiki/OI-wiki#5178]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

https://oi-wiki.org/graph/save/ 网页渲染出错，在任何镜像站下均可复现

![uiv16iyw](https://github.com/OI-wiki/OI-wiki/assets/18643142/7554c734-7bfa-4641-8305-4e7f068409f0)
![x4ysylxs](https://github.com/OI-wiki/OI-wiki/assets/18643142/09deeb30-6401-4e73-8085-288932e0e335)
![s8qop0kt](https://github.com/OI-wiki/OI-wiki/assets/18643142/2607cdbc-35c1-453f-b6a5-e3c156a1144d)

### 我确认这个问题可以这样复现

直接点网址就看见了

**Comment by Enter-tainer** [comment]
感谢反馈，我们排查后，初步认为是第三方库 node html parser 的问题

**Comment by Enter-tainer** [comment]
@Menci 使用 https://validator.w3.org/ 排查之后发现是 broken html 导致的。broken html 产生的原因是折叠框的空行中没有补齐四个空格，导致bot自动格式化出现了错误，将模板参数漏到了代码块外面，被识别成了html标签。

此类问题已经发生了多次，之后再遇到应该首先使用 https://validator.w3.org/ 对 html 进行排查，然后关注一下代码块相关的东西。
