### ISSUE TITLE
[内容有误] 函数 `find_end` 的含义与使用方法有误

### ISSUE THREAD

**Issue by Icathian-Rain** [OI-wiki/OI-wiki#5183]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/lang/csl/algorithm/

### 我发现页面有这样的问题

```find_end：逆序查找。find_end(v.begin(), v.end(), value)。```
函数find_end的含义与使用方法有误。
正确含义为：Find last matching subsequence in a sequence. 在序列 A 中查找序列 B 最后一次出现的位置。
使用方法为：
```cpp
//查找序列 [first1, last1) 中最后一个子序列 [first2, last2)
ForwardIterator find_end (ForwardIterator first1, ForwardIterator last1,
                          ForwardIterator first2, ForwardIterator last2);
//查找序列 [first2, last2) 中，和 [first2, last2) 序列满足 pred 规则的最后一个子序列
ForwardIterator find_end (ForwardIterator first1, ForwardIterator last1,
                          ForwardIterator first2, ForwardIterator last2,
                          BinaryPredicate pred);
```

**Comment by Great-designer** [comment]
修复时可以注上cppreference出处

**Comment by HeRaNO** [comment]
@cmpute 能否说明一下您的 commit 下中 `find_end` 函数是指的哪个函数，在之后此内容应该始终没有变过 https://github.com/OI-wiki/OI-wiki/commit/a8e74808617f4296dfa5eee9dfa568aa11ab2f3a

**Comment by HeRaNO** [comment]
> > @cmpute 能否说明一下您的 commit 下中 `find_end` 函数是指的哪个函数，在之后此内容应该始终没有变过 https://github.com/OI-wiki/OI-wiki/commit/a8e74808617f4296dfa5eee9dfa568aa11ab2f3a
> 
> 我想说的可能是rfind。。
> 
> > <img alt="" width="48" src="https://opengraph.githubassets.com/cbc8f0ccaa6ea01166566f017773febfd50eccddf7d91d5af80c117f6b99af1c/OI-wiki/OI-wiki/commit/a8e74808617f4296dfa5eee9dfa568aa11ab2f3a"><img alt="" height="14" src="https://github.githubassets.com/favicons/favicon.svg"> GitHub**[Enrich algorithms · OI-wiki/OI-wiki@a8e7480](/OI-wiki/OI-wiki/commit/a8e74808617f4296dfa5eee9dfa568aa11ab2f3a)**🌟 Wiki of OI / ICPC for everyone. （某大型游戏线上攻略，内含炫酷算术魔法） - Enrich algorithms · [a8e7480](https://github.com/OI-wiki/OI-wiki/commit/a8e7480)

emmm... `rfind` 似乎是一个 `string` 下的函数，`vector` 是没有的。我在考虑要不要把这条删掉，您看怎么样？

**Comment by cmpute** [comment]
删吧，我没意见～
