### ISSUE TITLE
[RFC] 建议添加 Skype 作为 OI-Wiki 的联系方式

### ISSUE THREAD

**Issue by Hszzzx** [OI-wiki/OI-wiki#5191]
### 提案的具体内容

[Skype 官方网站](https://shiguangpu.com/)

虽然说 Skype 本意不是用来聊天的，但是是在校学生可以接触的即时通讯应用（只需邮箱即可）。

Telegram 因为众所周知的原因访问需要成本，QQ 又不是住校 OIer 能使用的（需要手机验证），如果有一种更便捷的通讯方式，大概会吸引更多的人贡献 **OI-Wiki** 吧。

**Comment by Eletary** [comment]
那matrix更好吧，也方便bridge

**Comment by Tiphereth-A** [comment]
目前看来似乎并没有足够的动力支持该 issue
