### ISSUE TITLE
[内容有误] 三分法例题部分，python代码并没有用三分法

### ISSUE THREAD

**Issue by shenshuaijie** [OI-wiki/OI-wiki#5197]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/basic/binary/#%E4%BE%8B%E9%A2%98

### 我发现页面有这样的问题

这道例题中，python给出的程序是根据函数导数的正负来判断最高点在哪一段，并不是三分法。尽管可以得到正确的答案，但是与该部分讲解内容和解题思路完全不符，希望可以做一些修改。

**Comment by HeRaNO** [comment]
这段代码貌似采用了求导之后二分导函数的方法，@LeiJinpeng 请问能否补充一下三分版本的代码？
