### ISSUE TITLE
[内容有误] bitset 页面表达需要修改

### ISSUE THREAD

**Issue by mahaoming2022** [OI-wiki/OI-wiki#5201]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/lang/csl/bitset/

### 我发现页面有这样的问题

语言粗俗，出现「艹」之类的字眼，语言个性化，于 OI-wiki 的风格不匹配，正在修改

**Comment by Great-designer** [comment]
引用原文：
> 然后发现……被加了几个剪枝的暴力艹了：[加了几个剪枝的暴力](https://loj.ac/submission/395673)

> 然而，可以手写 bitset（只需要支持左移后或起来这一种操作）压 64 位（unsigned long long）来艹掉暴力：[手写 bitset](https://loj.ac/submission/395619)

可以考虑把这些引用的代码粘贴到网站正文中（并隐藏显示），不必再跳转。如果改为“带有代码段改进”的形式则更好，先列一个最初版本，每次再把改进的部分列出来，最后列一个最优版本。
