### ISSUE TITLE
[内容有误] WBLT 页面讲解模糊不清

### ISSUE THREAD

**Issue by warrnacute** [OI-wiki/OI-wiki#5221]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/wblt/

### 我发现页面有这样的问题

WBLT 讲解模糊不清，且有许多错误。

**Comment by HeRaNO** [comment]
这个页面自从第一次提交之后就没有对内容进行实质上迭代，看看有没有人愿意贡献一下吧 😢

**Comment by AtomAlpaca** [comment]
#5290
