### ISSUE TITLE
[内容有误] 格式手册中的某链接失效

### ISSUE THREAD

**Issue by c-forrest** [OI-wiki/OI-wiki#5242]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/intro/format/#markdown-%E6%A0%BC%E5%BC%8F%E4%B8%8E%E4%B8%BB%E9%A2%98%E6%89%A9%E5%B1%95%E6%A0%BC%E5%BC%8F%E8%A6%81%E6%B1%82

### 我发现页面有这样的问题

![image](https://github.com/OI-wiki/OI-wiki/assets/41589268/e169ceb2-5375-4624-9a29-41482bb752df)

cyent 的笔记链接失效

**Comment by HeRaNO** [comment]
看起来这个库已经被删除或者转私有了，最近的 Web Archive 在 https://web.archive.org/web/20221208060207/https://cyent.github.io/markdown-with-mkdocs-material/，知乎上也有 https://zhuanlan.zhihu.com/p/56891725

感觉没有说什么具体内容，删了也好？
