### ISSUE TITLE
[BUG] workflow 中 Build LaTeX 失败

### ISSUE THREAD

**Issue by HeRaNO** [OI-wiki/OI-wiki#5269]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

https://github.com/OI-wiki/OI-wiki/blob/6bc5f824bd6ca5f59d455ce4beca683d336ed731/.github/workflows/build-pdf.yml#L42

这行需要下载一个包，但是最近 Actions 会报错，log 如下

```plain
--2023-11-14 12:36:19--  https://mirror.math.princeton.edu/pub/CTAN/fonts/cm-unicode.zip
Resolving mirror.math.princeton.edu (mirror.math.princeton.edu)... 128.112.18.21
Connecting to mirror.math.princeton.edu (mirror.math.princeton.edu)|128.112.18.21|:443... connected.
Unable to establish SSL connection.
```

在本地下载应该是不会出现 SSL connection 问题的，并且最早是 11-13 出现的问题

**Comment by Enter-tainer** [comment]
@HeRaNO 感觉换个镜像或许就行..?

**Comment by HeRaNO** [comment]
重新跑了一下，现在好像好了
