### ISSUE TITLE
[内容询问]  关于瓶颈生成树与最小瓶颈路的定义问题？

### ISSUE THREAD

**Issue by wplf** [OI-wiki/OI-wiki#5305]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/graph/mst/#%E7%93%B6%E9%A2%88%E7%94%9F%E6%88%90%E6%A0%91

### 我发现页面有这样的问题

请问瓶颈生成树与最小瓶颈树是否相同？

**Comment by HeRaNO** [comment]
个人觉得弄清楚「最小瓶颈树」的定义就知道了吧，并不是内容有误

**Comment by HeRaNO** [comment]
cc @bear-good

**Comment by wplf** [comment]
请问瓶颈生成树包含了图中的所有节点么？

**Comment by wplf** [comment]
谢谢大佬， 懂了！
最小瓶颈生成树是说这棵生成树上的瓶颈是最小的，  最小瓶颈路是两个点之间的瓶颈是最小的！

**Comment by HeRaNO** [comment]
如有进一步问题可以 reopen 这个 issue
