### ISSUE TITLE
[内容有误] 质数筛埃氏筛法改良筛至平方根有误

### ISSUE THREAD

**Issue by 2912706234** [OI-wiki/OI-wiki#5367]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/number-theory/sieve/#%E7%AD%9B%E8%87%B3%E5%B9%B3%E6%96%B9%E6%A0%B9

### 我发现页面有这样的问题

`vector<int> prime;
bool is_prime[N];

void Eratosthenes(int n) {
  is_prime[0] = is_prime[1] = false;
  for (int i = 2; i <= n; ++i) is_prime[i] = true;
  // i * i <= n 说明 i <= sqrt(n)
  for (int i = 2; i * i <= n; ++i) {
    if (is_prime[i]) {
      prime.push_back(i);
      for (int j = i * i; j <= n; j += i) is_prime[j] = false;
    }
  }
}`
这里当限制条件变为i < sqrt(n)之后虽然可以保证is_prime数组全部筛完，但是>sqrt(n)的素数无法push到prime数组里面

**Comment by HeRaNO** [comment]
@2912706234 没看懂啥意思，能再解释一下吗？

**Comment by 2912706234** [comment]
> @2912706234 没看懂啥意思，能再解释一下吗？

例如n=100，is_prime数组里面会正确地对所有的素数进行标记，但是vector prime里面只会有<= 10的素数，这里如果想要prime记录所有素数最后还是必须遍历一遍

**Comment by HeRaNO** [comment]
> > @2912706234 没看懂啥意思，能再解释一下吗？
> 
> 例如n=100，is_prime数组里面会正确地对所有的素数进行标记，但是vector prime里面只会有<= 10的素数，这里如果想要prime记录所有素数最后还是必须遍历一遍

ok got that
