### ISSUE TITLE
Add Dilworth 定理与 Mirsky 定理

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#5378]
### 我希望能添加的内容是

Dilworth 定理在 OI 中有一定的应用，如经典题目[导弹拦截](https://www.luogu.com.cn/problem/P1020)。这部分内容直接补到[序理论](https://oi-wiki.org/math/order-theory/)页面就好了。

### 我了解到的相关参考资料有

https://en.wikipedia.org/wiki/Dilworth%27s_theorem
https://brilliant.org/wiki/dilworths-theorem/

**Comment by Great-designer** [comment]
好东西
