### ISSUE TITLE
[内容有误] 汇编注释符号打错了

### ISSUE THREAD

**Issue by asdf123asdf123asdf123** [OI-wiki/OI-wiki#5386]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/lang/optimizations/#%E7%94%A8%E8%B7%B3%E8%BD%AC%E6%8C%87%E4%BB%A4%E4%BB%A3%E6%9B%BF%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8

### 我发现页面有这样的问题

`#`写成`;`了
这让我看了[例子](https://godbolt.org/z/e7b1safaW)才确定

**Comment by HeRaNO** [comment]
1. 提 issue 时请将问题简要地直接写在标题处，节省大家的时间
2. 汇编的注释可以用 `;` 也可以用 `#` 吧，不是什么 critical 的问题？

**Comment by Enter-tainer** [comment]
你如果觉得这个问题很大的话可以顺手修一下

**Comment by asdf123asdf123asdf123** [comment]
> 1. 提 issue 时请将问题简要地直接写在标题处，节省大家的时间
> 2. 汇编的注释可以用 `;` 也可以用 `#` 吧，不是什么 critical 的问题？

谢谢，我不太清楚……
