### ISSUE TITLE
[内容有误] WBLT 页面式子有误，且缺少证明

### ISSUE THREAD

**Issue by Eletary** [OI-wiki/OI-wiki#5388]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/wblt/

### 我发现页面有这样的问题

推导中给出的 γ 是错的，且没有关于 α 的证明

**Comment by AtomAlpaca** [comment]
我是 WBLT 目前版本的作者，页面中推导的过程参考了 Weight-balanced tree 的原始论文 [Binary Search Trees of Bounded Balance](https://dl.acm.org/doi/pdf/10.1145/800152.804906)，且经过了手工演算验证，应当没有问题。

没有关于 $\alpha$ 取值的证明是因为个人认为证明比较显然且自然，不过欢迎大佬进行补充。

**Comment by Eletary** [comment]
> 我是 WBLT 目前版本的作者，页面中推导的过程参考了 Weight-balanced tree 的原始论文 [Binary Search Trees of Bounded Balance](https://dl.acm.org/doi/pdf/10.1145/800152.804906)，且经过了手工演算验证，应当没有问题。
> 
> 没有关于 α 取值的证明是因为个人认为证明比较显然且自然，不过欢迎大佬进行补充。

问题不大，主要是有抄错的地方，具体来说是 \gamma_1=\rho_1+(1-\rho_1)\rho_2\rho_3，您写成了 \gamma_1=\rho_1+(1-\rho_3)\rho_2\rho_3\\

**Comment by Eletary** [comment]
然后我觉得关于合并分裂的部分还是有必要添加的，不过和该 issue 无关

**Comment by HeRaNO** [comment]
如果仅是抄错式子直接开 pr 修改 typo 即可，不需要再开 issue 讨论了。我还以为又出啥大事了。
