### ISSUE TITLE
Add 时间库相关介绍

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#5396]
### 页面英文名

time

### 我希望能添加的内容是

不知本站是否有Unix时间或POSIX时间相关的内容？2038年快要到了，到时候必然会遇到32位整数带来的“2038年问题”。

（似乎日本2025年的“昭和九十九年问题”来得更快一些，本质上都是千年虫问题翻版）

### 我了解到的相关参考资料有

去百度一下或者Goggle一下

**Comment by AtomAlpaca** [comment]
个人认为该内容和算法竞赛无关。

**Comment by HeRaNO** [comment]
如果仅添加 `clock()` 或者 `chrono` 相关介绍是可以的，ref #5392

**Comment by Tiphereth-A** [comment]
https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E7%99%BE%E7%A7%91%E5%85%A8%E4%B9%A6
