### ISSUE TITLE
Add 集合论目录

### ISSUE THREAD

**Issue by Great-designer** [OI-wiki/OI-wiki#5397]
### 页面英文名

set-theory

### 我希望能添加的内容是

其实不需要增加新内容。考虑将数学目录下主要和集合相关操作的内容：

- 二进制集合操作：https://oi-wiki.org/math/binary-set/
- 序理论：https://oi-wiki.org/math/order-theory/

挪到一个集合论子目录下。

目前组合数学目录下的容斥原理，有没有必要挪进去，暂待考究。容斥原理感觉上更像是组合数学的内容。

**Comment by Tiphereth-A** [comment]
序理论不是集合论的分支，目前来看没必要这样做。
