### ISSUE TITLE
Add NTT模数表

### ISSUE THREAD

**Issue by cbs001** [OI-wiki/OI-wiki#5405]
### 页面英文名

NTTprimetable

### 我希望能添加的内容是

NTT模数表

### 我了解到的相关参考资料有

这里博客里有一份常见的NTT模数表
https://blog.miskcoo.com/2014/07/fft-prime-table

**Comment by HeRaNO** [comment]
$998\,244\,353$ 是常用的，但其他的感觉表里也未必能囊括全，还得是看出题人心情或者自己找模数性质。况且这个表也太长了。

**Comment by Tiphereth-A** [comment]
印象里就 167772161, 469762049, 754974721, 998244353, 1004535809 这几个是最常用的，感觉在 NTT 页面里加一下这几个就够了，列整个表的话确实有点长了 🤔
