### ISSUE TITLE
[内容有误] Arbiter 2.0 还需要开栈吗？

### ISSUE THREAD

**Issue by HeRaNO** [OI-wiki/OI-wiki#5419]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/tools/judger/arbiter/

### 我发现页面有这样的问题

https://github.com/OI-wiki/OI-wiki/commit/2ab997fb5daa03fa21e7caebc857299907eae109 这个 commit 引入了

> 由于Linux运行时栈限制，如果要开无限栈，应在终端先输入`ulimit -s unlimited`后执行`arbiter`打开测评器。

但是最近我使用 Arbiter 2.0，设置内存限制为 256M 递归 $10^6$ 层，没有出现 RE 的问题。可能是 1.x 版本的 bug，但是在 2.0 修复了？

cc @ranwen

**Comment by ranwen** [comment]
感谢您的反馈，但是我现在已经AFO了😇。

我这个commit确实是在上古版本的NOI Linux下做的，当时评测如果不这么跑的话确实是会RE的。但现在NOI Linux更新了，我也不清楚他是怎么搞的，我也不想再下一个NOI Linux去检查这个问题了。

方便的话，欢迎您自己提交一个PR来修改这个描述。

关于如何验证这个情况，您可以做一下这些测试：

在终端中直接运行这个程序，观测是否会segmentation fault。确定这个程序是否本身就是会使用大量栈的。注意保持编译选项一致，避免编译器优化影响结果（例如可能进行的尾递归优化）。（我不清楚能不能直接使用arbiter编译出来的程序，可以的话直接用是更好的）

在终端中输入 `ulimit -s`，程序会输出当前环境下允许使用的栈大小。用这个命令可以检查一下NOI Linux是否是改了默认栈设置，使得所有程序都可以直接跑而不会爆栈。我本地WSL会返回8192，对应8M的默认值。

**Comment by HeRaNO** [comment]
今天重新测试了一下，不用 Arbiter 的情况如下：

![1](https://github.com/OI-wiki/OI-wiki/assets/18643142/7b25b328-1f8d-410e-88fc-40361fd5f9d0)

Arbiter 的配置如下：

![2](https://github.com/OI-wiki/OI-wiki/assets/18643142/829ec8ce-479d-476c-9fcc-f26ebb8577c6)

直接在 GUI 下启动的情况下挂掉了

![3](https://github.com/OI-wiki/OI-wiki/assets/18643142/0318c03e-08ae-4d5c-aa19-670ce027bf55)

result 文件如下

![4](https://github.com/OI-wiki/OI-wiki/assets/18643142/9565bacf-7738-46a9-a31a-a41a316eb470)

可能之前写了尾递归，但是之前测试我没有开 `-O2`，看了一下汇编不会优化，挺怪的。但是这个测试应该比较有代表性。

开了栈之后就 OK 了

![5](https://github.com/OI-wiki/OI-wiki/assets/18643142/441b6229-b19a-42e3-b7fb-b02cb120ca47)
