### ISSUE TITLE
[内容有误] trie 页面例题描述需要补充

### ISSUE THREAD

**Issue by wmsx1** [OI-wiki/OI-wiki#5454]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/string/trie/

### 我发现页面有这样的问题

在维护异或极值下的例题 BZOJ1954 最长异或路径 中，异或和应为异或。出现误导

**Comment by HeRaNO** [comment]
所有边权的异或不是异或和吗？请重新描述一下

**Comment by wmsx1** [comment]
我在搜索 xor sum 时得到的定义都是异或的和，而不是连续异或，[参考链接_题目](https://zhuanlan.zhihu.com/p/604196415?utm_id=0)，[参考链接_题目2](https://www.geeksforgeeks.org/sum-xor-possible-subsets/)。而原题的描述是异或路径，也并没有出现异或和的说明。我认为这可能是一种歧义。
@HeRaNO

**Comment by wmsx1** [comment]
我在搜索 xor sum 时得到的定义都是异或的和，而不是连续异或，[参考链接_题目](https://zhuanlan.zhihu.com/p/604196415?utm_id=0)，[参考链接_题目2](https://www.geeksforgeeks.org/sum-xor-possible-subsets/)。而原题的描述是异或路径，也并没有出现异或和的说明。我认为这可能是一种歧义。
@HeRaNO

**Comment by wmsx1** [comment]
我搜索到的题目是从数列中取一对数进行异或并加入到和中。我在之后也找到了把连续异或叫做异或和的说法。
总的来说，我认为 trie 页面中对于异或和没有给出一个定义，可能会导致歧义。

**Comment by Enter-tainer** [comment]
> 我搜索到的题目是从数列中取一对数进行异或并加入到和中。我在之后也找到了把连续异或叫做异或和的说法。
> 总的来说，我认为 trie 页面中对于异或和没有给出一个定义，可能会导致歧义。

搜索 “xor sum” 第一个就跳出来了正确答案，还被高亮了。你说你没有搜到。。我觉得不太对劲

不过我认为异或和这个描述确实不是非常直观（要不然也不会有人在stackoverflow上问异或和是什么）

**Comment by Enter-tainer** [comment]
如果你愿意补充一下这个页面的话，我觉得是ok的

**Comment by HeRaNO** [comment]
「异或和」一词我猜是从 XOR Sum 翻译过来的，XOR Sum 可以和「Plus Sum」一样形式一致地定义，只需要把求和中的代数加换成异或即可。究其是否为「OI 方言」，我感觉也不是，因为 Sum of XOR 和 XOR Sum 从其英语成分来说也是有点不一致，翻译成「异或和」我觉得没什么问题；[sum](https://dictionary.cambridge.org/dictionary/english/sum) 一词并不特指加，可以指一种计算（当然最常用的是加起来，或者说代数上的加），并且在 OI 语境中谈起异或和应该都是指这样的操作，再强调异或和是那样的操作感觉有点吹毛求疵了。究其语源我是不太清楚的，如果你愿意的话可以深入调研一下。

但回到这个问题上，我觉得题目描述没有问题，原题也是那么说的，OI Wiki 上的描述和原题描述是对齐的。

**Comment by wmsx1** [comment]
原题用的是异或路径，并且给出了说明。trie 页面中只有一个突然出现的名词，没有给出定义。虽然可以理解到是连续进行异或运算的意思，但我在搜索异或和时确实遇到了歧义。

希望可以添加说明，而不是突然出现一个未被解释的名词。

**Comment by HeRaNO** [comment]
引用一位群友：因为异或操作相当于非进位加法，所以有时候也称为异或和。感觉说得很有道理。

OI Wiki 上的是题目描述的概括版本吧，如有问题还是可以参考原题面的，并且也是一种学习过程。我觉得无可厚非。

如果你觉得改掉更好可以提交 PR。但它谈不上是错误。

**Comment by wmsx1** [comment]
是我 issue 标题写错了，页面内容是正确的，我只是想补充一下定义。

**Comment by wmsx1** [comment]
说个题外话，如果想补充页面内容，但又不需要添加一个 topic，issue 该如何选择？

**Comment by HeRaNO** [comment]
你可以修改此 issue 标题
