### ISSUE TITLE
add 编辑器 (文本编辑器 / IDE)

### ISSUE THREAD

**Issue by morainzh** [OI-wiki/OI-wiki#546]
我希望添加更多的**代码/文本**编辑工具

**Comment by MingqiHuang** [comment]
emm... 个人感觉没有必要增加太多... 几个常用且轻量的（主要是 NOI 系列赛事能用的）IDE 就足够了，如果 IDE 太多了会不会引起圣战之类的（

当然欢迎贡献页面。

**Comment by ChungZH** [comment]
我觉得现在已经够了，Vim、Emacs、VS Code、Atom 都有了。~~只不过后两个编辑器没详细讲~~

~~所以可以 close 了吧~~

**Comment by orzcyand1317** [comment]
~~你置 sublime 于何地~~

**Comment by ChungZH** [comment]
~~不开源就不写了hhh~~
