### ISSUE TITLE
[内容有误] 二分图最大权匹配费用流算法

### ISSUE THREAD

**Issue by purinliang** [OI-wiki/OI-wiki#5466]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/graph/graph-matching/bigraph-weight-match/

### 我发现页面有这样的问题

第一次去学图匹配相关的算法，看不太懂为什么最大权匹配是可以按下面的算法转化为费用流模型的：

在图中新增一个源点和一个汇点。

从源点向二分图的每个左部点连一条流量为 1，费用为 0 的边，从二分图的每个右部点向汇点连一条流量为 1，费用为 0 的边。

接下来对于二分图中每一条连接左部点 u 和右部点 v，边权为 w 的边，则连一条从 u 到 v，流量为 1，费用为 w 的边。

求这个网络的 [最大费用最大流](https://oi-wiki.org/graph/flow/min-cost/) 即可得到答案。

---

这个例子的反例很明显，因为费用流是在保证是流量最大的前提下费用最大/最小，所以很明显可以构造出下面的反例：

![图中数字表示费用](https://github.com/OI-wiki/OI-wiki/assets/68161856/47d2db64-48e8-4cb1-993c-6f4a06d1370e)

显然此图的最大流量是2，不会走那条费用为1000的边，求出的就不是最大权的匹配，此二分图最大权的匹配显然是那个权值为1000的边。

查阅评论我发现可能可以通过添加费用为0的虚拟边来保证每一个点都被充分利用到。具体的做法为：要么左部点向汇点T连接流量为1，费用为0的边，保证每个左部点都被充分利用。要么源点S向右部点都连接流量为1，费用为0的边，保证每个右部点都被充分利用。至于哪一种复杂度更好我并不清楚。也可以在左右部之间添加此类边再加上判重减少边的数量。

---

由于对图论不太熟悉，不太清楚我上面的想法是不是有误区，辛苦各位高手大佬指出一下。

**Comment by HeRaNO** [comment]
https://github.com/OI-wiki/OI-wiki/commit/64c4c02110848260f2f5d50e1a67113b90b621dc 这个 commit 引入的，费用流部分可能描述的是一个完美匹配的求解过程？cc @StudyingFather

**Comment by StudyingFather** [comment]
> [64c4c02](https://github.com/OI-wiki/OI-wiki/commit/64c4c02110848260f2f5d50e1a67113b90b621dc) 这个 commit 引入的，费用流部分可能描述的是一个完美匹配的求解过程？cc @StudyingFather
> 
> > 考虑到二分图中两个集合中的点并不总是相同，为了能应用 KM 算法解决二分图的最大权匹配，需要先作如下处理：将两个集合中点数比较少的补点，使得两边点数相同，再将不存在的边权重设为 0，这种情况下，问题就转换成求 最大权完美匹配问题，从而能应用 KM 算法求解。
> 
> 你的图中似乎不涉及这个转化？

确实应该添加类似的转化过程，我稍后开个 PR 修复一下。

**Comment by StudyingFather** [comment]
借用 [图匹配](https://oi.wiki/graph/graph-matching/graph-match/) 页面中的描述，目前给出的费用流算法实际上求的是 “最大权最大匹配”。
