### ISSUE TITLE
Add 多项式复合 O(nlog^2n) 的方法

### ISSUE THREAD

**Issue by CSPNOIP** [OI-wiki/OI-wiki#5492]
### 页面英文名

polynomial-composition

### 我希望能添加的内容是

O(nlog^2n) 时间内计算多项式复合（逆）的算法，提出快三个周了

### 我了解到的相关参考资料有

[noshi91 的原文](https://noshi91.hatenablog.com/entry/2024/03/16/224034)
[Aleph1022 的翻译](https://www.luogu.com/article/7joh5isi)
[cyffff 的多项式复合逆题解](https://www.luogu.com.cn/article/t2cijmdo)、[cyfff 的多项式复合题解](https://www.luogu.com.cn/article/qn0xklxe)
[此算法依赖于的转置原理](https://www.cnblogs.com/rainybunny/p/15755358.html)
[比较详细的解释与一份完整但是常数大的要死的代码](https://www.luogu.com.cn/article/uqcwrvo6)

**Comment by r-value** [comment]
[方针: OI-Wiki 不是新闻的收集处](https://oi.wiki/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E6%96%B0%E9%97%BB%E7%9A%84%E6%94%B6%E9%9B%86%E5%A4%84)

**Comment by HeRaNO** [comment]
这个算法与原文中提到的 SOSA '21 论文有关，也就是所谓「Bostan-Mori 算法」，这个算法的应用还有待观察和沉淀。

上面所提到的博客无法作为资料，希望进一步整理和这个算法有关的背景和前置知识。可以作为一个长期议题来添加。

**Comment by alphagocc** [comment]
@CSPNOIP 下次就有人开issue说这个已经在arxiv上挂了三天了怎么还没有

**Comment by Great-designer** [comment]
> 这个算法的应用还有待观察和沉淀。
> 
> 希望进一步整理和这个算法有关的背景和前置知识。

因为“这个算法的应用还有待观察和沉淀”，所以不添加此算法。

但是可以研究一下“该算法的背景和前置知识”是哪些：如果“背景和前置知识”较为简单，相关内容可以添加一下；如果较为复杂，则不添加。
