### ISSUE TITLE
[内容有误] 费用流中 Dinic 示例代码定义但未使用当前弧优化

### ISSUE THREAD

**Issue by CodingOIer** [OI-wiki/OI-wiki#5516]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/graph/flow/min-cost/#ssp-%E7%AE%97%E6%B3%95

### 我发现页面有这样的问题

费用流中 Dinic 示例代码定义但未使用当前弧优化。

**Comment by r-value** [comment]
原示例代码没有问题, 正确使用了当前弧优化

https://github.com/OI-wiki/OI-wiki/blob/7bdb1a93c1bab76e95a61e4e9239f58d5f6077f6/docs/graph/flow/min-cost.md?plain=1#L139
