### ISSUE TITLE
[RFC] 规范仓库内分支

### ISSUE THREAD

**Issue by gi-b716** [OI-wiki/OI-wiki#5520]
### 提案的具体内容

注意到：OI-wiki仓库有大量分支
![image](https://github.com/OI-wiki/OI-wiki/assets/78394473/9f6894eb-8bca-40ef-8a45-c6e9b7c3b10a)
经过查阅，其中不乏测试以后遗留的分支（例如 [Enter-tainer-patch-3](https://github.com/OI-wiki/OI-wiki/tree/Enter-tainer-patch-3)），建议整理一下现有的分支，并且规范以后的测试分支，让仓库变得更加规范。

**Comment by Great-designer** [comment]
支持
