### ISSUE TITLE
[RFC] 关于分支名的规范

### ISSUE THREAD

**Issue by xk2013** [OI-wiki/OI-wiki#5522]
### 提案的具体内容

- 在 fork 时发现一大堆分支，会对 fork 造成负担。
- 建议将 master 分支改名为 main。

**Comment by Marcythm** [comment]
请问您的两个 bullet points 之间是什么关系？
- 如果是递进的话，我看不出它们之间的逻辑关系（分支多和改分支名有啥关系？）；
- 如果是并列的话，那么请问第一点的解决方案是什么？第二点的理由是什么？我认为以这几行文字的内容并不能当得起 RFC 的定义。
