### ISSUE TITLE
[RFC] 再次发起(#5520 规范仓库内分支)

### ISSUE THREAD

**Issue by gi-b716** [OI-wiki/OI-wiki#5525]
### 提案的具体内容

在(#5520)标记为完成后，我再次浏览了OI-wiki的分支列表，发现了几个分支。
- [hsfzLZH1-patch-1-1](https://github.com/OI-wiki/OI-wiki/tree/hsfzLZH1-patch-1-1) 在这个分支中所做的唯一修改似乎已经经由 #4830 合并至master中了，没有必要保留，建议删除。
- [fix-render](https://github.com/OI-wiki/OI-wiki/tree/fix-render) 这个分支似乎进行了一个小更改，并且借此创建了 #5184 ，作者本人close了这个pr，不过个人认为这个修改可以同步至master，所以开启了一个pr #5526 来再次提出这项更改。这个分支可以删除。
- [tags](https://github.com/OI-wiki/OI-wiki/tree/tags) 这个分支所做的修改似乎没有合并到master过，由于本人不熟悉mkdocs，无法做出判断，建议管理员讨论后合并更改或直接删除分支。
- [shuzhouliu-geometry-add](https://github.com/OI-wiki/OI-wiki/tree/shuzhouliu-geometry-add) 同上，已经由 #4045 合并至master，可以删除。
- [Enter-tainer-patch-1](https://github.com/OI-wiki/OI-wiki/tree/Enter-tainer-patch-1) 这个分支所做的修改并没有合并至master，但这个分支更改的[.github/workflows/build-pdf-typst.yml](https://github.com/OI-wiki/OI-wiki/commit/c50ce85d548e048823e7ed7ea6ee7e3ffd4293b7#diff-77b5f19f15d8042fa4d6901469ace2ddb5698ead0168c6b6678174268a61f739)似乎已经和现在的[build-pdf-typst.yml](https://github.com/OI-wiki/OI-wiki/blob/master/.github/workflows/build-pdf-typst.yml)截然不同了。本人不了解Typst的构建，建议管理员讨论后完成最终更改或直接删除分支。

---

本人建议，未来有直接在仓库内新建分支权限的朋友们在需要新建分支进行更改的时候，最好fork仓库后更改，或者在更改后及时删除分支，保证仓库的规范。

**Comment by gi-b716** [comment]
> [fix-render](https://github.com/OI-wiki/OI-wiki/tree/fix-render) 这个分支似乎进行了一个小更改，并且借此创建了 https://github.com/OI-wiki/OI-wiki/pull/5184 ，作者本人close了这个pr，不过个人认为这个修改可以同步至master，并且会于稍后提交一个新pr完成5184的工作。这个分支可以删除。

pr已创建（ #5526 ）

**Comment by Enter-tainer** [comment]
我个人虽然觉得这不是个事，但是还是把能看到都删掉了。这个事情可能没什么规范的必要
