### ISSUE TITLE
[内容有误] 支配树页面 typo

### ISSUE THREAD

**Issue by hahaleyile** [OI-wiki/OI-wiki#5537]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/graph/dominator-tree/#%E6%95%B0%E6%8D%AE%E6%B5%81%E8%BF%AD%E4%BB%A3%E6%B3%95

### 我发现页面有这样的问题

您好，我在学习这一章内容时，发现它提到了“深度有限排序”这个词，但是其他地方都没有介绍它的内容。请问能否提供一下这个词的介绍链接或者是英文翻译，谢谢！

![image](https://github.com/OI-wiki/OI-wiki/assets/38727644/b64b05ab-910c-4e10-a418-ad553f4610d9)

**Comment by Enter-tainer** [comment]
估计是typo了？是不是深度优先排序

**Comment by hahaleyile** [comment]
> 估计是typo了？是不是深度优先排序

怀疑是，不太敢确定，因为不知道深度优先排序能不能得到逆后序

**Comment by AtomAlpaca** [comment]
> 估计是typo了？是不是深度优先排序

我的锅, 确实是 typo, 明天改一下

**Comment by hahaleyile** [comment]
OK
