### ISSUE TITLE
关于 TimSort

### ISSUE THREAD

**Issue by xk2013** [OI-wiki/OI-wiki#5538]
### 页面英文名

basic/tim-sort

### 我希望能添加的内容是

- TimSort 最坏复杂度的证明。
- 建议将 tim 排序改为 TimSort，Tim 是大写，因为是 Tim Peters 的姓氏。
- 示例代码，不太喜欢挂外链。

### 我了解到的相关参考资料有

https://xueshu.baidu.com/usercenter/paper/show?paperid=1j2000y01s7e0vp0gu0w0pj0up771916&site=xueshu_se
https://www.xueshufan.com/publication/2951137085

**Comment by r-value** [comment]
dup #5536
