### ISSUE TITLE
[RFC] helloworld中，可以添加 std::cout 写法

### ISSUE THREAD

**Issue by gavinliu266** [OI-wiki/OI-wiki#5541]
### 提案的具体内容

增加 std::cout 写法，添加注释。

### 相关链接与参考资料

https://oi-wiki.org/lang/helloworld/

**Comment by HeRaNO** [comment]
没搞懂为什么一定要 `std::cout`，原文里面已经有先 `using namespace std;` 再 `cout` 的了，对于入门已经足够了。

最近是有什么活动吗，怎么这种 issue 和 PR 特别多……
