### ISSUE TITLE
关于评论区

### ISSUE THREAD

**Issue by HeavenOJ** [OI-wiki/OI-wiki#5544]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

1. 为什么他人不在我的评论下发表评论时，我能收到邮件？
<img width="469" alt="image" src="https://github.com/OI-wiki/OI-wiki/assets/95569790/11cf19e6-c6fc-4d06-853e-72034966901f">
<img width="754" alt="image" src="https://github.com/OI-wiki/OI-wiki/assets/95569790/b793f978-045d-4460-918d-7327f7cc8bca">

2. 为什么已经发表的评论不能删除？（已经发表的评论如何删除？）

**Comment by Tiphereth-A** [comment]
1. ![](https://img.shields.io/badge/work%20as-intended-success)
2. 点一下昵称旁边的时间可以跳到 [OI-wiki/gitment](https://github.com/OI-wiki/gitment/) 中对应的评论，然后隐藏/删除即可

**Comment by Enter-tainer** [comment]
关于1，可以手动在github里面ubsubscribe整个thread
