### ISSUE TITLE
pair 中 Dijkstra 代码的错误

### ISSUE THREAD

**Issue by gavinliu266** [OI-wiki/OI-wiki#5545]
### 提案的具体内容

pair 中 Dijkstra 代码有错误，我正在修改。

### 相关链接与参考资料

https://oi-wiki.org/lang/csl/pair/

**Comment by Tiphereth-A** [comment]
不要滥用 RFC 模板，您所提出的事项远未达到其标准

**Comment by gavinliu266** [comment]
ok
