### ISSUE TITLE
[内容有误] 左偏树页面中「棘手的操作」代码在 C++17 及以上有误

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#5607]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/leftist-tree/#scoi2011%E6%A3%98%E6%89%8B%E7%9A%84%E6%93%8D%E4%BD%9C

### 我发现页面有这样的问题

开 O2 的前提下，[C++14](https://www.luogu.com.cn/record/159151974) 可以通过，但是 [C++17](https://www.luogu.com.cn/record/159151944) 和 [C++20](https://www.luogu.com.cn/record/159200885) 不可以。

**Comment by HeRaNO** [comment]
我在 Linux 上测试的结果是 C++14 没有问题，但是 C++17 和 C++20 在 `pushdown` 函数处爆栈了，感觉可能跟某种依赖 C++14 的语言标准有关。

**Comment by HeRaNO** [comment]
这个页面的很多写法也没对齐。在核心操作：合并一节中的代码和任意节点删除的代码，还有后面例题代码中的合并就不一样

**Comment by HeRaNO** [comment]
改为保留引用，[C++14](https://loj.ac/s/2066368), [C++17](https://loj.ac/s/2066369) 和 [C++20](https://loj.ac/s/2066370) 均能通过。
