### ISSUE TITLE
[内容有误] 线段树中《线段树的区间修改与懒惰标记》一节的第二张图疑似有误

### ISSUE THREAD

**Issue by H3AlO3** [OI-wiki/OI-wiki#5612]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/seg/#%E7%BA%BF%E6%AE%B5%E6%A0%91%E7%9A%84%E5%8C%BA%E9%97%B4%E4%BF%AE%E6%94%B9%E4%B8%8E%E6%87%92%E6%83%B0%E6%A0%87%E8%AE%B0

### 我发现页面有这样的问题

图中d[1]应该是70吧
![img](https://oi-wiki.org/ds/images/segt3.svg)

**Comment by H3AlO3** [comment]
又看了看好像整张图的d[p]都没有被更新，不只是d[1]的问题

**Comment by szdytom** [comment]
d[1]应该是75吧

**Comment by H3AlO3** [comment]
> d[1]应该是75吧

是的，最开始我以为它只有d[1]写错了，后来发现它d[2]也没有更新，应该是d[1]=75, d[2]=38

**Comment by H3AlO3** [comment]
> d[1]应该是75吧

是的，最开始我以为它只有d[1]写错了，后来发现它d[2]也没有更新，应该是d[1]=75, d[2]=38
