### ISSUE TITLE
[内容有误] 平衡因子定义出错

### ISSUE THREAD

**Issue by liangbm3** [OI-wiki/OI-wiki#5630]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oiwiki.org/ds/avl/

### 我发现页面有这样的问题

平衡因子应该是左子树高度减右子树高度

**Comment by HeRaNO** [comment]
参考资料 [AVL Tree - Wikipedia](https://en.wikipedia.org/wiki/AVL_tree) 中写的就是右子树高度减左子树高度，为什么要修改呢？这样是否与后文相符的呢？

这个定义从最早页面加入时就有了，@Ir1d PTAL

**Comment by liangbm3** [comment]
现在理解了，两种定义都是可以的

**Comment by liangbm3** [comment]
> 参考资料 [AVL Tree - Wikipedia](https://en.wikipedia.org/wiki/AVL_tree) 中写的就是右子树高度减左子树高度，为什么要修改呢？这样是否与后文相符的呢？
> 
> 这个定义从最早页面加入时就有了，@Ir1d PTAL

现在理解了，两种定义都是可以的
