### ISSUE TITLE
[内容有误] B树性质5多余

### ISSUE THREAD

**Issue by eleven-dimension** [OI-wiki/OI-wiki#5653]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/b-tree/

### 我发现页面有这样的问题

> 每个节点至多包含 $2k - 1$ 个键

每个节点至多 $m - 1$ 个键吧，而且这条可以用性质1和性质4推出来，没什么必要

**Comment by Tiphereth-A** [comment]
cc @Persdre 

说实话我没看懂为什么要写这条性质
