### ISSUE TITLE
搜索功能无法使用

### ISSUE THREAD

**Issue by happpybob** [OI-wiki/OI-wiki#5674]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/

### 我发现页面有这样的问题

https://oi-wiki.org/

**Comment by Enter-tainer** [comment]
@happpybob 证书过期了 正在修复

**Comment by Ir1d** [comment]
感谢反馈！ 已经修复
