### ISSUE TITLE
[BUG] 搜索功能对横线的匹配方式不合理

### ISSUE THREAD

**Issue by yaoxi-std** [OI-wiki/OI-wiki#5689]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

目标内容中含有横线时，搜索内容往往无法很好地匹配文章内容，如在搜索框中输入 `Primal Dual` 无法匹配到 `Primal-Dual`，`kd tree` 无法匹配到 `K-D Tree`，搜索 `2 sat` 无法匹配到 `2-sat`

**Comment by Ir1d** [comment]
感谢反馈！ 刚进行了更新后，似乎本问题已经得到了解决！
