### ISSUE TITLE
[BUG] author重复

### ISSUE THREAD

**Issue by gi-b716** [OI-wiki/OI-wiki#5690]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

[背包DP](https://oi-wiki.org/dp/knapsack/)拥有一个贡献者 `Odeinjul` 和一个贡献者 `odeinjul` ，他们都指向 [同样的用户](https://github.com/Odeinjul) 。不确定其他页面有没有这个问题。

### 我确认这个问题可以这样复现

查看[背包DP界面](https://oi-wiki.org/dp/knapsack/)

**Comment by HeRaNO** [comment]
https://github.com/OI-wiki/OI-wiki/blob/master/docs/dp/knapsack.md?plain=1#L1 的 Author 字段里有大写的，不太确定是不是应该去重，或者和 #5587 有关
