### ISSUE TITLE
Add 三分内容

### ISSUE THREAD

**Issue by zszfympx** [OI-wiki/OI-wiki#5715]
### 页面英文名

ternarySearch

### 我希望能添加的内容是

关于三分查找的内容，例如：简介，实现等。

### 我了解到的相关参考资料有

https://www.cnblogs.com/PJQOOO/p/4161891.html

**Comment by Tiphereth-A** [comment]
已经有了

https://oi-wiki.org/basic/binary/#%E4%B8%89%E5%88%86%E6%B3%95
