### ISSUE TITLE
[内容改进] 重写笛卡尔树的伪代码

### ISSUE THREAD

**Issue by alphagocc** [OI-wiki/OI-wiki#5738]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/cartesian-tree/#%E5%AE%9E%E7%8E%B0

### 我发现页面有这样的问题

该处伪代码不符合 OI-Wiki 格式手册中所要求的伪代码格式

**Comment by HeRaNO** [comment]
是否可以删掉伪代码部分，把伪代码变成注释加到 C++ 代码片段里？
