### ISSUE TITLE
Add 快速求二叉树最近公共祖先深度

### ISSUE THREAD

**Issue by AZZRCN** [OI-wiki/OI-wiki#5739]
### 我希望能添加的内容是

//这是一个想法
可以加一个二叉树最短公共祖先
花费O(n),dfs得到路径
比如 (root->b,b->c,b->d,d->e)
路径分别为(b:01
c:010
d:011
e:0110)

对于d,c(深度一样),可以求出d.path xor c.path,001
那么最近公共祖先的深度为2(开头0数)

对于b,c(深度不一),对于深度较浅的b,左对齐，异或，得到一个长度为b.deepth的01串(00 (1,舍去))
如果01串==0,那么代表b是b和c的最短公共祖先,最近公共祖先深度为2

下面这个例子可以针对c,e, c.path xor e.path,得到001
否则,左对齐数0,得到深度为2(也是b)

需要指出的是,路径的标记不需要特定的顺序
数0操作可以使用mingw的__builtin_...函数(我忘了),别的编译器也可以使用自己的内置函数
(老师讲这个是特殊优化过的,可以当O(1)使)
这样就可以花费O(n)得到所有最近公共祖先

### 我了解到的相关参考资料有

没有，完全是一个想法

**Comment by AZZRCN** [comment]
![10](https://github.com/user-attachments/assets/5f2bb09e-5a96-4370-b7d7-982f499c09f6)
我坚信这是对的（真）

**Comment by AZZRCN** [comment]
再插一句，root深度为1

**Comment by HeRaNO** [comment]
[OI-WIki 不是发表原创研究的场所](https://oi-wiki.org/intro/what-oi-wiki-is-not/#oi-wiki-%E4%B8%8D%E6%98%AF%E5%8F%91%E8%A1%A8%E5%8E%9F%E5%88%9B%E7%A0%94%E7%A9%B6%E7%9A%84%E5%9C%BA%E6%89%80)

而且您也没有一个解法，甚至没到「原创研究」的准入门槛。先关了。

我真诚地建议这个研究发洛谷。

**Comment by AZZRCN** [comment]
@HeRaNO 没发过，求助
