### ISSUE TITLE
[BUG] OI-wiki炸飞了，所有镜像站都上不去。

### ISSUE THREAD

**Issue by user-leo-757861** [OI-wiki/OI-wiki#5742]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

[这里](https://next.oi-wiki.org/intro/mirrors/)的所有镜像站都不行。

显然，[F.A.Q](https://oi-wiki.org/intro/faq/)看不了(

**Comment by HeRaNO** [comment]
https://status.oi-wiki.org/

**Comment by Enter-tainer** [comment]
检查自己的网络问题吧
