### ISSUE TITLE
Add 蔡勒公式

### ISSUE THREAD

**Issue by marscheng1** [OI-wiki/OI-wiki#5756]
### 页面英文名

zeller

### 我希望能添加的内容是

蔡勒公式的表达式和应用，和数学关系不大，建议放在杂项里

**Comment by Great-designer** [comment]
如果考虑到在OI领域的应用，或许还有1582年消失的10天这种经典问题。

**Comment by marscheng1** [comment]
这并不是问题，消失十天的星期是对得上的，也就是说这十天对星期几并没有影响
