### ISSUE TITLE
[内容有误] Testlib/通用/通用函数一栏函数名有误

### ISSUE THREAD

**Issue by qwertim** [OI-wiki/OI-wiki#5768]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://cms.oi-wiki.org/intro/testlib/general/#_3

### 我发现页面有这样的问题

通用函数的非成员函数一栏调用部分的最后一行应为 `quitf` 而不应为 `quitif`。

**Comment by qwertim** [comment]
![image](https://github.com/user-attachments/assets/5a8c39d6-3849-4930-82e7-f1e38794e941)

**Comment by caijianhong** [comment]
```cpp
void quitif(bool condition, TResult result, const char *format, ...) {
    if (condition) {
        FMT_TO_RESULT(format, format, message);
        quit(result, message);
    }
}
```
是真的有这个函数。close 了吧。
