### ISSUE TITLE
请求完善高精度内容

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#577]
感觉现在高精度条目里面就一个板子，是不是应该详细讲一下高精度的实现方法和注意事项？

**Comment by CBW2007** [comment]
我来写一下。不过我只会一些基础，后面的内容还需要慢慢填。

**Comment by CBW2007** [comment]
很抱歉放了鸽子，最近有些事没来得及写，很抱歉

**Comment by CBW2007** [comment]
#832 里已经写过一部分基础的了，不知道有没有其他神犇完善进阶内容？

**Comment by Ir1d** [comment]
TODO: 
- [ ] 压位高精度
- [ ] Karatsuba 乘法
- [ ] FFT 乘法

**Comment by Voileexperiments** [comment]
高精度取余呢 :thinking:

我還記得高精度取余有兩種算法來著?

**Comment by Ir1d** [comment]
(updated)
两种算法是指模int和模高精度吗？

**Comment by kawa-yoiko** [comment]
高精度除以高精度的暴力做法已经有取余了，另一个算法可能是指 FFT 除法？

**Comment by luoguyuntianming** [comment]
又或者是高精度快速幂？

**Comment by kawa-yoiko** [comment]
高精度快速幂只需要结合乘法和除以 2 运算，所以不必单独写吧

**Comment by Ir1d** [comment]
提一嘴也无妨的样子（
