### ISSUE TITLE
[内容有误] kmp 中计算前缀函数的朴素算法时间复杂度有误

### ISSUE THREAD

**Issue by JayWu1997** [OI-wiki/OI-wiki#5794]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://github.com/OI-wiki/OI-wiki/blob/master/docs/string/kmp.md#%E8%AE%A1%E7%AE%97%E5%89%8D%E7%BC%80%E5%87%BD%E6%95%B0%E7%9A%84%E6%9C%B4%E7%B4%A0%E7%AE%97%E6%B3%95

### 我发现页面有这样的问题

朴素算法的时间复杂度应为 O(n2)

**Comment by HeRaNO** [comment]
其中最多 $\mathcal{O}(n^2)$ 次字符串比较，字符串比较的复杂度为 $\mathcal{O}(n)$，合在一起 $\mathcal{O}(n^3)$
