### ISSUE TITLE
[BUG] task-list-completed 工作流有时会错误识别 task，有时会运行很久

### ISSUE THREAD

**Issue by xk2013** [OI-wiki/OI-wiki#5862]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![image](https://github.com/user-attachments/assets/d4081a18-231f-407a-857d-3aaa0043cb80)
![image](https://github.com/user-attachments/assets/00d4d70c-2a65-4446-b691-eb8694f2b104)

### 我确认这个问题可以这样复现

提交一个 PR，将“我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。”取消打勾即可复现。

**Comment by xk2013** [comment]
what?

**Comment by xk2013** [comment]
发生了什么

**Comment by xk2013** [comment]
@alphagocc

**Comment by alphagocc** [comment]
Invalid Issue

**Comment by xk2013** [comment]
ha?

**Comment by xk2013** [comment]
哪里不合规了

**Comment by xk2013** [comment]
@alphagocc

**Comment by alphagocc** [comment]
你思考一下为什么要打这个√

**Comment by xk2013** [comment]
> 你思考一下为什么要打这个√

不是，我只是说这个也是可以复现的，甚至你在 pr 里写一个有序列表都能触发

**Comment by xk2013** [comment]
oh my

**Comment by xk2013** [comment]
好像搞错了

**Comment by xk2013** [comment]
好像需要 Member 写才能触发

**Comment by xk2013** [comment]
@alphagocc

**Comment by alphagocc** [comment]
您可以加入 QQ 群 588793226 方便讨论问题
