### ISSUE TITLE
[BUG] Windows 上关闭 directwrite 之后多行公式无法正常渲染

### ISSUE THREAD

**Issue by Parsifa1** [OI-wiki/OI-wiki#5898]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

![image](https://github.com/user-attachments/assets/2cb83d49-6a24-491c-b021-13b23b3fc2f3)
如图所示，所有多行公式只能显示一半
十分困扰 不过是很小众的需求 所以如果没有兴趣可以关闭（）

### 我确认这个问题可以这样复现

由于现版本的 chrome 已经无法使用这个 flag，可以安装 Cent Browser，在 chrome://flags 界面关闭 directwrite
![image](https://github.com/user-attachments/assets/b3e21cc5-2a04-4bba-b691-f93e46983904)

**Comment by ksyx** [comment]
Turning off DirectWrite shouldn't change any behavior controllable on our side as we don't handle actual rendering... It may be better off to open a Chromium issue

**Comment by Parsifa1** [comment]
you are right.
