### ISSUE TITLE
构造介绍的疑惑

### ISSUE THREAD

**Issue by TecReaGroup** [OI-wiki/OI-wiki#5926]
构造中例3中解题为完全k分图，但是题目要求为简单连通图：不能出现环，是不是不符合题意
链接：https://oi-wiki.org/basic/construction/

**Comment by caijianhong** [comment]
简单连通图指无重边无自环的连通图？

**Comment by Tiphereth-A** [comment]
https://oi-wiki.org/graph/concept/#%E7%AE%80%E5%8D%95%E5%9B%BE
