### ISSUE TITLE
[内容请求&疑问]二叉搜索树的优化？

### ISSUE THREAD

**Issue by zhangbo1000** [OI-wiki/OI-wiki#5943]
### 写在前面

**我不知道下面这些东西放在 issue 里合不合适，如果不合适，非常抱歉，以后不会了。**

这是一种针对 BST（而不是平衡树）的优化，复杂度我证不出来，但是其在 [洛谷 P6136 普通平衡树（数据加强版）](https://www.luogu.com.cn/problem/P6136) 上[表现良好](https://www.luogu.com.cn/record/182441982)。

在此也求复杂度证明/hack。

如果最后证明它复杂度正确，那么建议加到平衡树里，否则如果管理组认为这种思路有价值的话，就放在 BST 的界面里吧。

### 正文

注意到树高度高于 $O(\log n)$ 是因为不同子树的高度差异过大，那么就容易想到通过维护以下性质来维持树大致平衡：

>永远只往较小的子树中插入**新**元素，如果即将访问的子树大小大于其兄弟，将其旋转上来而不是递归访问其。

注意特判左旋后不能右旋，反之亦然。

### 效率有关测试

对于三组随机的，包含 $1.1\times10^6$ 个插入操作的数据：

- 旋转次数都在 $10^7$ 左右（误差不超过 $2\times 10^5$）。

- （结束时，下同）左右子树高度差超过 $1$ 的节点约为 $1.1\times10^5$（误差不超过 $10^4$），超过 $4$ 的节点大约 $5\times10^3$ 个，超过 $7$ 的节点不超过 $15$ 个。

- 左右子树高度相同的节点约为 $6.05\times 10^5$ 个。

对于一组构造的，能把普通 BST 卡成 $n^2$ 的（即所有插入元素递增的）包含 $1.1\times10^6$ 个插入操作的数据：

- 旋转次数 $1099986$。

- 左右子树高度差超过 $1$ 的节点有 $5$ 个。

- 左右子树高度相同的节点约有 $4\times10^5$ 个。

代码（仅供参考）：

```cpp
#include<iostream>
#include<cstdio>
#include<cmath>
#include<vector>
#include<cstring>
#include<algorithm>
#include<queue>
#include<set>
#include<deque>
#include<map>
using namespace std;

namespace code{
	using ll=long long;
	using ull=unsigned long long;
#define F(i,x,y) for(int i=(x),__tt2__=(y);i<=__tt2__;i++)
#define R(i,x,y) for(int i=(x),__tt2__=(y);i>=__tt2__;i--)
#define _F(i,x,y) for(int i=(x),__tt2__=(y);i<__tt2__;i++)
#define _R(i,x,y) for(int i=(x),__tt2__=(y);i>__tt2__;i--)
#define debug(x) cout<<#x<<'='<<(x)<<endl
	class bst{
		class node{
		public:
			int nsize,size,val,cnt;
			node *ls,*rs;
			constexpr node(const int& _nsize=0,const int& _size=0,const int& _val=0,const int& _cnt=0,node*const _ls=nullptr,node*const _rs=nullptr):
			nsize(_nsize),size(_size),val(_val),cnt(_cnt),ls(_ls),rs(_rs){}
			using tree=node*;
			int getsize(const tree& x){
				return x==nullptr?0:x->size;
			}
			int getnsize(const tree& x){
				return x==nullptr?0:x->nsize;
			}
			void upd(tree& x){
				x->size=x->cnt+getsize(x->ls)+getsize(x->rs);
				x->nsize=1+getnsize(x->ls)+getnsize(x->rs);
			}
			void left(tree& x){
				tree p=x->rs;
				x->rs=p->ls;
				p->ls=x;
				upd(x);
				upd(p);
				x=p;
			}
			void right(tree& x){
				tree p=x->ls;
				x->ls=p->rs;
				p->rs=x;
				upd(x);
				upd(p);
				x=p;
			}
			void insert(tree& t,const int& x,char last=0){
				if(t==nullptr){t=new node(1,1,x,1,nullptr,nullptr);return;}
				while(1){
					t->size++;
					if(x==t->val){t->cnt++;return;}
					else if(x<t->val){
						if(getnsize(t->ls)>getnsize(t->rs)&&last<1){
							right(t);
							last=1;
							continue;
						}
						insert(t->ls,x);
						upd(t);
						return;
					}
					else if(x>t->val){
						if(getnsize(t->rs)>getnsize(t->ls)&&last<1){
							left(t);
							last=-1;
							continue;
						}
						insert(t->rs,x);
						upd(t);
						return;
					}
				}
			}
			void erase(tree& t,const int& x){
				t->size--;
				if(t->val==x){
					t->cnt--;
				}
				else if(x<t->val){
					erase(t->ls,x);
				}
				else {
					erase(t->rs,x);
				}
			}
			int getrank(tree& t,const int& x){
				if(t==nullptr)return 1;
				if(x<t->val)return getrank(t->ls,x);
				if(x==t->val)return getsize(t->ls)+1;
				return getsize(t->ls)+t->cnt+getrank(t->rs,x);
			}
			int findrank(tree& t,const int& x){
				if(x<=getsize(t->ls))return findrank(t->ls,x);
				if(x<=getsize(t->ls)+t->cnt)return t->val;
				return findrank(t->rs,x-getsize(t->ls)-t->cnt);
			}
			int pre(tree& t,const int& x){return findrank(t,getrank(t,x)-1);}
			int next(tree& t,const int& x){return findrank(t,getrank(t,x+1));}
		};
		using tree=node*;
		tree root;
	public:
		constexpr bst():root(nullptr){}
		constexpr bst(const bst& x):root(x.root){}
		void dbg(){
			cout<<root->getsize(root)<<' '<<root->getsize(root->ls)<<' '<<root->getsize(root->rs)<<'\n';
		}
		void insert(const int& x){root->insert(root,x);}
		void erase(const int& x){root->erase(root,x);}
		int findrank(const int& x){return root->findrank(root,x);}
		int getrank(const int& x){return root->getrank(root,x);}
		int pre(const int& x){return root->pre(root,x);}
		int next(const int& x){return root->next(root,x);}
	}a;
	int main(){
		cin.tie(0)->sync_with_stdio(0);
		int n,m,last=0,op,x,ans=0;
		cin>>n>>m;
		for(int i=0;i<n;i++){
			cin>>x;
			a.insert(x);
		}
		while(m--){
			cin>>op>>x;
			x^=last;
			switch (op){
			case 1:
				a.insert(x);
				break;
			case 2:
				a.erase(x);
				break;
			case 3:
				last=a.getrank(x);
				ans^=last;
				break;
			case 4:
				last=a.findrank(x);
				ans^=last;
				break;
			case 5:
				last=a.pre(x);
				ans^=last;
				break;
			default:
				last=a.next(x);
				ans^=last;
			}
		}
		cout<<ans;
		return 0;
	}
}
signed main(){return code::main();}
```

**Comment by ImpleLee** [comment]
https://github.com/OI-wiki/OI-wiki/blob/16f79fe5b8565af2549f796918a8f971c1efed54/docs/intro/what-oi-wiki-is-not.md?plain=1#L6-L11

**Comment by zhangbo1000** [comment]
@ImpleLee ”该做法已经被应用于其他题目中，该内容已经被用于解决编程竞赛中的某一类问题“其可以在很多题目（不涉及区间操作）中代替平衡树，复杂度无法证明，但是目前并没有找到 hack 的方法。

**Comment by ImpleLee** [comment]
> 其可以在很多题目（不涉及区间操作）中代替平衡树，复杂度无法证明，但是目前并没有找到 hack 的方法。

更广泛地来说，这些原则是在说，wiki记录的是一种成熟的广泛的实践；被用得够多才能证明它们确实有用。
“它可以用于XXX”并不代表“它已经被用于XXX”。

**Comment by Marcythm** [comment]
我认为先不论这个原则如何。首先在一切成为现实之前，你应该给出一个证明。你自己也说了「复杂度我证不出来」「如果最后证明它复杂度正确」。虽然原则性地来讲，哪怕给出了证明我也不是很认同该内容添加，但 我的直觉认为这个证明出来可能和某种平衡树是本质一样的。？我会花点时间仔细思考一下。

**Comment by Marcythm** [comment]
> 注意到树高度高于 O ( log ⁡ n ) 是因为不同子树的高度差异过大，那么就容易想到通过维护以下性质来维持树大致平衡：
> 
> > 永远只往较小的子树中插入**新**元素，如果即将访问的子树大小大于其兄弟，将其旋转上来而不是递归访问其。

另外我还有两个疑问。第一个是「递归访问其」这个话写得实在不太像一个中国人说的中国话。第二个是你一开始注意到的是高度有别，为什么后面的措施却是看子树大小？你的平衡定义标准究竟是什么，是高度还是大小？

**Comment by ImpleLee** [comment]
> 原则性地来讲，哪怕给出了证明我也不是很认同该内容添加

我赞同这个看法。这很明显是个“原创研究”。即使最后证明出了正确性/找到了相同的论文（事实上如果能证出来，我觉得找到论文的可能性很大），但OI-wiki也不该成为发表/倡导这个新实践的场所。如果它是对的，更应该做的大概是写个blog，向大家宣传，取得足够高的popularity，才可能被收录进wiki。我其实很觉得应该直接关掉这个issue。

**Comment by zhangbo1000** [comment]
@Marcythm @ImpleLee 非常感谢，这的确不是一坨该放到 wiki 的东西。

@Marcythm  “第二个是你一开始注意到的是高度有别，为什么后面的措施却是看子树大小？你的平衡定义标准究竟是什么，是高度还是大小？” 关于这一点，因为如果我们还要维护树高的话，那还不如直接写 AVL，一整个就没有意义了。

至于我为什么能写出「递归访问其」这种话，我也不知道（大雾（逃。

**Comment by Marcythm** [comment]
> 因为如果我们还要维护树高的话，那还不如直接写 AVL，一整个就没有意义了。

请恕我实在不能理解您的这个回答…独立发现前人发现过的东西就没有意义了吗？这不是对思维的提升训练吗？这不是一种证明自己吗？
所以你不是为了优化算法而创新，只是为了「搞出所谓的创新」而创新吗。。

**Comment by zhangbo1000** [comment]
@Marcythm 并非为了「搞出所谓的创新」而创新，是之前从某篇文章了解到 BST 在平均情况下接近 $O(\log n)$ 而不是 $O(n)$，于是就试图减少维护平衡的操作简化代码（虽然写到最后应该比 FHQ treap 长）。

“没有添加的价值”倒是正常，本来也是为了偷懒写的（开了 Issue 是不了解 OI Wiki，望原谅）。不过因为维护的东西很少，效率实际上应该不比很多正常的平衡树慢（至少比我自己写的有旋 treap 以及我测试用的那道题的题解中的大多数快）。
