### ISSUE TITLE
[内容有误] ”乘法逆元“中“线性求逆元”小节提到的方法需要限制p为质数

### ISSUE THREAD

**Issue by skr2005** [OI-wiki/OI-wiki#5946]
### 请选择：

- [X] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/number-theory/inverse/#%E7%BA%BF%E6%80%A7%E6%B1%82%E9%80%86%E5%85%83

### 我发现页面有这样的问题

如题，我认为这里要求p为质数时算法才能正常工作，但是介绍这个方法的时候没有先强调这一点。

如果p不为质数，那么证明过程中的“两边同时乘i^-1*j^-1”就不能保证j的逆元一定存在，那么即使模p意义下i的逆元存在（gcd=1），该算法也不能保证正确求出i的逆元。

举个实际例子，如果p=8，i=3，那么一次递归后会转为求2的逆元，但2在模8时的的乘法逆元不存在，算法不能工作。

虽然该小节后面有写“如果没有相应的逆元的时候，inv[i] 的值是未定义的。”但是我仍然认为这句话并不明晰，问题也不会只出现在不存在逆元的i上（比如i=3）。仍然有必要在介绍这个方法的时候指出限制：p为质数。

如果各位认为这是对的话，我可以着手编辑内容修正这一点

**Comment by Marcythm** [comment]
的确存在这样的问题。除开正确性，原本的写法直接使用 $i^-1 j^-1$ 而没有指出对应的模数，也是缺乏严谨的写法。
