### ISSUE TITLE
[内容有误] 页面内容不统一（关于并查集和平衡树）

### ISSUE THREAD

**Issue by zhangbo1000** [OI-wiki/OI-wiki#5950]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/ds/dsu-complexity/#%E5%85%B3%E4%BA%8E%E5%90%AF%E5%8F%91%E5%BC%8F%E5%90%88%E5%B9%B6

### 我发现页面有这样的问题

- 在 [并查集复杂度](https://oi-wiki.org/ds/dsu-complexity/#%E5%85%B3%E4%BA%8E%E5%90%AF%E5%8F%91%E5%BC%8F%E5%90%88%E5%B9%B6) 的页面中，启发式合并被等同于按节点数合并，而在 [并查集](https://oi-wiki.org/ds/dsu/#%E5%90%AF%E5%8F%91%E5%BC%8F%E5%90%88%E5%B9%B6) 中，它被表述为按照节点数**或深度**合并，也就是这两个页面对按秩合并属不属于启发式合并是不统一的。

    - 即使很多其它资料上对这一点也有争议，但同一个 wiki 还是尽可能避免吧？

- 另外，在 [可持久化平衡树](https://oi-wiki.org/ds/persistent-balanced/#%E5%8F%AF%E6%8C%81%E4%B9%85%E5%8C%96%E6%93%8D%E4%BD%9C) 页面中重复提及了可持久化数据结构和可持久化线段树。

- 在 [左偏红黑树](https://oi-wiki.org/ds/llrbt/) 页面内，前文对红黑树和左偏红黑树的定义中都称**结点**为红/黑色，而实现~~以及图片~~中却是按照颜色区分**边**？

**Comment by hhc0001** [comment]
在 [可持久化平衡树](https://oi-wiki.org/ds/persistent-balanced/#%E5%8F%AF%E6%8C%81%E4%B9%85%E5%8C%96%E6%93%8D%E4%BD%9C) 页面中提及的可持久化线段树是用来引出下文的吧

而且 [左偏红黑树](https://oi-wiki.org/ds/llrbt/) 里面有明确说明

> 我们习惯用一个节点的颜色代指它的父亲边的颜色。
