### ISSUE TITLE
Add 时间库相关介绍

### ISSUE THREAD

**Issue by ZnPdCo** [OI-wiki/OI-wiki#5965]
### 页面英文名

time

### 我希望能添加的内容是

添加 clock() 或者 chrono 相关介绍。

ref #5392

### 我了解到的相关参考资料有

https://stackoverflow.com/questions/43745361/c-time-measurement-looks-too-slow 

https://gcc.gnu.org/legacy-ml/gcc-help/2019-07/msg00068.html 

https://cplusplus.com/forum/general/187899/

**Comment by Enter-tainer** [comment]
（提示，chrono在工业上好像也不太常用

**Comment by c0nstexpr** [comment]
竞赛里面没有场景，加了也没用

**Comment by Tiphereth-A** [comment]
https://github.com/OI-wiki/OI-wiki/issues/5396#issuecomment-1925781138

**Comment by ZnPdCo** [comment]
> 竞赛里面没有场景，加了也没用。看起来是之前有个pr想把退火介绍里面的clock换成chrono，感觉适用面还是比较小的。

那我觉得应该在模拟退火加个说明。

clock非常慢，用来模拟退火非常不适合！

**Comment by Tiphereth-A** [comment]
> clock非常慢，用来模拟退火非常不适合！

<https://quick-bench.com/q/Cdv7X022M6U7ZzWfoZ_LVhJJx34>

好像还真有点差别（10%），不过这个差别相对于模拟退火来说应该是可以忽略的 🤔
