### ISSUE TITLE
[BUG] 关于 PR 与 LaTeX

### ISSUE THREAD

**Issue by Taoran-01** [OI-wiki/OI-wiki#5971]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [X] 我正在着手修复这个问题

### 我遇到了这样的问题

我在PR过程中遇见了问题：LaTeX[报错](https://github.com/OI-wiki/OI-wiki/actions/runs/11541362255/job/32123269080?pr=5970)

这是我的 [Branch](https://github.com/Taoran-01/OI-wiki/tree/Develop)，仅对 /graph/shortest-path/ 文件作修改。

### 我确认这个问题可以这样复现

将 Taoran-01/OI-wiki/tree/Develop 合并到 OI-wiki/OI-wiki/tree/master

**Comment by ksyx** [comment]
see comments in #5970
