### ISSUE TITLE
[内容改进] 增添编辑器 CP Editor 相关应用

### ISSUE THREAD

**Issue by EZ-godmoo** [OI-wiki/OI-wiki#5978]
###  请选择：
- [x] 我正在着手修复这个问题

### 我正在访问这个页面
[https://oi-wiki.org/tools/editor/cpeditor/](https://oi-wiki.org/tools/editor/cpeditor/)

### 我发现页面有这样的问题
在 CP Editor 的应用方面介绍过少

**Comment by Tiphereth-A** [comment]
我觉得用这个软件的应该会自己看官方文档，OI Wiki 这边留一点简单配置就够了 🤔
