### ISSUE TITLE
添加 rbt，B树，leafy tree，toptree

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#6]
ref: http://scaffrey.blog.uoj.ac/blog/3667#comment-8435

- [x] 红黑树
- [x] B 树
- [x] B+ 树
- [x] Leafy Tree
- [ ] Top Tree

**Comment by Enter-tainer** [comment]
我或许可以写一下 llrbt （咕咕预警

**Comment by CoelacanthusHex** [comment]
可能会写篇 b tree 和 b+ tree 上去（超级大鸽子警告

**Comment by pluveto** [comment]
怎么回事？还没有啊

**Comment by Enter-tainer** [comment]
> 怎么回事？还没有啊

@pluveto 欢迎来开一个 PR 来添加这些内容~

**Comment by william-song-shy** [comment]
还在鸽啊

**Comment by Persdre** [comment]
working on it...

**Comment by Great-designer** [comment]
这看来是祖坟级issue，留个名先：
B树和B+树是408考研当中的内容，可以在王道考研上找到，在《算法导论》上也有相应讲解……
我好像还没见过使用这两个树的题目与代码，算是见识过于浅薄了……

**Comment by CoelacanthusHex** [comment]
> 我好像还没见过使用这两个树的题目与代码，算是见识过于浅薄了……

这两个都是为磁盘优化的数据结构，在 OI 这种根本不会去操作磁盘的环境优势不明显

**Comment by Enter-tainer** [comment]
Rust标准库里面的map就是btreemap，原因是局部性比较好（

**Comment by CoelacanthusHex** [comment]
> Rust标准库里面的map就是btreemap，原因是局部性比较好（

我记得也和语言设计也有关，有人用 Java 写 BTreeMap，性能并不理想

**Comment by Great-designer** [comment]
> 我好像还没见过使用B树和B+树的题目与代码，算是见识过于浅薄了……
我见过手写avl树的，avl树代码不长。手写红黑树也见过，红黑树代码就很长了，大概12000字符左右。据说STL的map底层用的是左偏红黑树。当然，avl树和红黑树在OI Wiki上已经有了。

**Comment by Persdre** [comment]
working on b tree...

**Comment by Persdre** [comment]
working on leafy tree...

**Comment by ACHL-02** [comment]
expected ovo

**Comment by Great-designer** [comment]
祝贺
