### ISSUE TITLE
[内容有误] __gnu_pbds::tree的erase()返回值类型不正确

### ISSUE THREAD

**Issue by jiangyang404** [OI-wiki/OI-wiki#6006]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/lang/pb-ds/tree/

### 我发现页面有这样的问题

当erase()的参数是迭代器时，其返回值类型不是bool而是传入的迭代器类型

**Comment by llleixx** [comment]
看了眼 gcc 14.2.0, 13.3.0, 9.5.0 和 4.9.4 的源码，实现都是删除迭代器后返回下一个迭代器。

之后我会提个 PR 改改。
