### ISSUE TITLE
Request details of prove

### ISSUE THREAD

**Issue by XuYueming520** [OI-wiki/OI-wiki#6041]
### 我希望能添加的内容是

不知道发在添加新内容合适不合适。

我在访问这个页面：https://oi-wiki.org/ds/splay/#时间复杂度

性质 3 的证明的最后一步，\log\frac{(x+y)^2}{xy}\geq\log 4 个人感觉不是很直观，请求添加证明的细节步骤：

\log\frac{(x+y)^2}{xy}=\log(2+\frac{x}{y}+\frac{y}{x})\geq\log(2+2\sqrt{\frac{x}{y}\frac{y}{x}})=\log 4

**Comment by Tiphereth-A** [comment]
$(x-y)^2\geq 0\implies x^2+y^2\geq 2xy\implies (x+y)^2\geq 4xy$ 这种东西过于平凡了吧 🤔

**Comment by Marcythm** [comment]
个人看法是这个完全不应该造成阅读障碍（基本不等式的极其常见的形式），实在不行动手算一算也该算明白了，这样的列举展开除了节省半分钟的动脑小思考以外没什么意义
