### ISSUE TITLE
[内容有误] 【组合数性质 | 二项式推论】一处公式有误

### ISSUE THREAD

**Issue by yinpeichu2021** [OI-wiki/OI-wiki#6065]
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/combinatorics/combination/

### 我发现页面有这样的问题

【组合数性质 | 二项式推论】中，式 $(10)$ 中 $l$ 下界应为 $k$.

**Comment by yinpeichu2021** [comment]
链接应为 [这个](https://oi-wiki.org/math/combinatorics/combination/#%E7%BB%84%E5%90%88%E6%95%B0%E6%80%A7%E8%B4%A8--%E4%BA%8C%E9%A1%B9%E5%BC%8F%E6%8E%A8%E8%AE%BA)

**Comment by yinpeichu2021** [comment]
以及式 $(6)$ 的上界应为 $k$。

**Comment by Tiphereth-A** [comment]
$\binom{n}{k}$ 在 $k>n$ 或者 $k<0$ 时为 $0$，所以这两个式子都没问题
