### ISSUE TITLE
[BUG] 搜索服务器异常

### ISSUE THREAD

**Issue by TuanZiGit** [OI-wiki/OI-wiki#6069]
### 请选择：

- [X] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [ ] 我正在着手修复这个问题

### 我遇到了这样的问题

search.oi-wiki.org无法访问。
![image](https://github.com/user-attachments/assets/9232650c-f542-4758-8aa0-7bace861f0e8)
![image](https://github.com/user-attachments/assets/eb3c66ec-d4f1-41c3-ad9b-097ff90b12ed)
![image](https://github.com/user-attachments/assets/480a772e-e4e0-4fef-88a0-8de7b9e3c14f)
这里发现301到了备案页（？

### 我确认这个问题可以这样复现

访问oi-wiki任意一个节点，进行搜索

**Comment by Ir1d** [comment]
不好意思我正在施工

**Comment by Ir1d** [comment]
感谢反馈，应该已经恢复正常了！
