### ISSUE TITLE
建议修改「编辑工具」一页中的表述

### ISSUE THREAD

**Issue by GekkaSaori** [OI-wiki/OI-wiki#698]
RT. 在将源文件转换为 LaTeX 时发现「编辑工具」这一个页面主观性太强了。请求修改一下表述使得其能客观的描述，不要夹杂太多个人的喜好等因素。

cc: @LuoshuiTianyi

**Comment by LuoshuiTianyi** [comment]
我看了一下，主要是那个无可争议的顶尖编辑器是吧^_^，我改吧
@MingqiHuang

**Comment by LuoshuiTianyi** [comment]
或者还有什么地方也请指出来

**Comment by MingqiHuang** [comment]
谢谢您的修改。我可能没有解释清楚。

![default](https://user-images.githubusercontent.com/19746684/47905291-b914c280-dec1-11e8-94b9-7ef01b0d22c8.png)

我的意思是，在配置篇不宜介绍大量您自己的配置（好吧可能这句话又有语病）。不应该（至少是大量）出现「我的配置中……」这样的东西。这是最主要的问题。

我也是 Vim 用户。Vim 是一个轻量级的文本编辑器。建议回归文本编辑的本质。在一些情况下，使用 Vim 不是为了好看或装 B，而是它方便快捷就用它了。很多情况下，您并没有时间配置 Vim 插件。插件还是交给 Atom 之类的现代化的编辑器处理吧。

**Comment by LuoshuiTianyi** [comment]
应该。。。就一段是这样吧。。。。。。主要是放了我的配置所以这么说。。。我会尽量地改

其次的话，插件这种东西Vim比起现代化编辑器应该没有什么特别不同吧。。。对于不同的人群要求是不同的，有的人可能就只用这一个编辑器了，插件篇可以自行选择看或不看。。。

**Comment by LuoshuiTianyi** [comment]
@MingqiHuang

**Comment by MingqiHuang** [comment]
嘤，没关系。可能说话语气不太对。只是稍微说一下，其实 Vim 还是一个很好的文本编辑器的。

**Comment by na02f** [comment]
vim段的背景叙述可以拿到开头或结尾（单独列出）？
操作阐述过于冗长（？），太生动了，难以“15分钟上手”，（操作+note+exp.够了）
配置考虑分成“入门配置（打开高亮etc. ）”+“进阶配置（自己配置）”？全部放在一起方便手把手但不够精练大概。
