### ISSUE TITLE
合并 math/misc 与 geometry/2d 两个页面

### ISSUE THREAD

**Issue by Chrogeek** [OI-wiki/OI-wiki#808]
math/misc 中介绍的基本都是关于向量的内容……与 geometry/2d 重复

**Comment by Ir1d** [comment]
可以考虑把向量部分塞到 geo/2d 里？
misc 可能还需要用来放一些不好分类的东西？

**Comment by Ir1d** [comment]
考虑在 https://oi-wiki.org/geometry/2d/#_4 塞一个指向 math/misc 的链接？

**Comment by TrisolarisHD** [comment]
这个可不可以 close 了啊
我觉得向量放 math 里挺好的啊🤔

**Comment by HeRaNO** [comment]
当时的考虑是优化学过向量的人阅读计算几何的体验，而且向量部分基础定义较多，放在里面页面长度爆炸。数学上向量与矩阵联系很大，都可以归到线性代数里，综合考虑把向量基础放在了数学杂项里，这样写矩阵和线性代数部分的作者也可以参考向量基础了。

如果有需要的话可以考虑调整位置……

**Comment by ouuan** [comment]
已经在 #1577 fix 了吧。
