### ISSUE TITLE
中文的加粗显示有误

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#862]
![image](https://user-images.githubusercontent.com/10709657/50416311-e7c46f00-085a-11e9-96e5-ef144fa18828.png)

![image](https://user-images.githubusercontent.com/10709657/50416319-ee52e680-085a-11e9-8272-835033b76db8.png)

猜测是 css 里字体改乱了导致的

> 参与 Wiki 的编写 **需要** 一个 GitHub 账号， **不需要** 高超的 GitHub 技巧

围观地址：https://oi-wiki.org/intro/faq/#github

[![](https://api.gh-polls.com/poll/01CZJ4VNAX2T1EJ1MC35NN48SA/%E6%88%91%E8%BF%99%E9%87%8C%E6%98%BE%E7%A4%BA%E6%9C%89%E5%8A%A0%E7%B2%97)](https://api.gh-polls.com/poll/01CZJ4VNAX2T1EJ1MC35NN48SA/%E6%88%91%E8%BF%99%E9%87%8C%E6%98%BE%E7%A4%BA%E6%9C%89%E5%8A%A0%E7%B2%97/vote)
[![](https://api.gh-polls.com/poll/01CZJ4VNAX2T1EJ1MC35NN48SA/%E6%88%91%E8%BF%99%E9%87%8C%E6%98%BE%E7%A4%BA%E6%B2%A1%E5%8A%A0%E7%B2%97)](https://api.gh-polls.com/poll/01CZJ4VNAX2T1EJ1MC35NN48SA/%E6%88%91%E8%BF%99%E9%87%8C%E6%98%BE%E7%A4%BA%E6%B2%A1%E5%8A%A0%E7%B2%97/vote)

麻烦大家投票 & 回复一下自己的浏览器、系统环境，谢谢

比如我是 ubuntu 18.04 chrome 71.0.3578.98

**Comment by CBW2007** [comment]
无加粗Windows 10 Google Chrome 69.0.3497.81（正式版本） （32 位）

**Comment by MingqiHuang** [comment]
有加粗 Firefox 65.0.

附：如果您是 Firefox 用户，请打开浏览器的开发人员工具查看加粗部分所使用的字体，并建议附上截图。例如：

![2019-02-03 15-50-33](https://user-images.githubusercontent.com/19746684/52174213-d06a9100-27cb-11e9-8721-d51e005670dd.png)

**Comment by MingqiHuang** [comment]
我这边没有办法复现这个问题。在 Chromium 版本 71.0.3578.98（正式版本）Built on Ubuntu , running on Ubuntu 18.10 （64 位）也是正常加粗的。

**Comment by MingqiHuang** [comment]
2333... 我在 Chrome 71.0.3578.98（同 @Xeonacid 无加粗的版本）上显示是有加粗的，会不会是浏览器设置的问题或者是系统原因（见上方截图）

**Comment by ChungZH** [comment]
我有点怀疑是 Markdown 格式问题，看到过好多个 `** 我要加粗 **` 这样的了，这样写应该是错误的。

**Comment by MingqiHuang** [comment]
@ChungZH 大概是浏览器字体没有设置好吧。毕竟我这边没有办法复现这个问题。这种 MD 格式也应该是可以正常解析的，看 HTML 也没什么问题。

**Comment by orzcyand1317** [comment]
有加粗 macOS Mojave 10.14.3 , Safari 12.0.3
有加粗 iOS 12.1.4 , Safari 12.0.3

**Comment by Voileexperiments** [comment]
這個讓大家摸象看有沒有加粗是沒有用的,先看css `font-family`的加載順序:

![image](https://user-images.githubusercontent.com/14909989/53869104-7bbc6f00-4032-11e9-9c1a-1f5d5537f332.png)

把第一個selector的字體一個個置換掉看是哪個字體的鍋,發現是Han Heiti GB

Han Heiti GB是這樣定義的:

```
@font-face {
  font-family: "Han Heiti GB";
  src: local("Hiragino Sans GB"), local(".PingFang SC Light"), local(".PingFang-SC-Light"), local(".PingFang SC"), local("Lantinghei SC Extralight"), local(FZLTXHK--GBK1-0), local("Lantinghei SC"), local("Heiti SC Light"), local(STHeitiSC-Light), local("Heiti SC"), local("Microsoft Yahei"), local("Noto Sans CJK SC"), local("Source Han Sans SC"), local("Source Han Sans CN"), local("Droid Sans Fallback");
}
...
...
@font-face {
  font-family: "Han Heiti GB";
  font-weight: 600;
  src: local("Hiragino Sans GB W6"), local(HiraginoSansGB-W6), local(".PingFang SC Semibold"), local(".PingFang-SC-Semibold"), local("Lantinghei SC Demibold"), local(FZLTZHK--GBK1-0), local("Heiti SC Medium"), local("STHeitiSC-Medium"), local("Heiti SC"), local("Microsoft YaHei Bold"), local(MicrosoftYaHei-Bold), local("Microsoft YaHei"), local("Noto Sans CJK SC Bold"), local(NotoSansCJKsc-Bold), local("Noto Sans CJK SC"), local("Source Han Sans SC Bold"), local("SourceHanSansSC-Bold"), local("Source Han Sans CN Bold"), local("SourceHanSansCN-Bold"), local("Source Han Sans SC"), local("Source Han Sans CN");
}
```

懷疑是下面W6那堆字體的鍋,於是拔出大殺器Stylus,強行注入css:

```
html:lang(zh-Hans),
html:lang(zh-CN),
[lang*="Hans"],
[lang="zh-CN"],
article strong:lang(zh-Hans),
article strong:lang(zh-CN) {
  font-family: "My Han Heiti GB W6"
}

@font-face {
  font-family: "My Han Heiti GB";
  src: local("Hiragino Sans GB"), local(".PingFang SC Light"), local(".PingFang-SC-Light"), local(".PingFang SC"), local("Lantinghei SC Extralight"), local(FZLTXHK--GBK1-0), local("Lantinghei SC"), local("Heiti SC Light"), local(STHeitiSC-Light), local("Heiti SC"), local("Microsoft Yahei"), local("Noto Sans CJK SC"), local("Source Han Sans SC"), local("Source Han Sans CN"), local("Droid Sans Fallback");
}

@font-face {
  font-family: "My Han Heiti GB W6";
  font-weight: 600;
  src: local("Hiragino Sans GB W6"), local(HiraginoSansGB-W6), local(".PingFang SC Semibold"), local(".PingFang-SC-Semibold"), local("Lantinghei SC Demibold"), local(FZLTZHK--GBK1-0), local("Heiti SC Medium"), local("STHeitiSC-Medium"), local("Heiti SC"), local("Microsoft YaHei Bold"), local(MicrosoftYaHei-Bold), local("Microsoft YaHei"), local("Noto Sans CJK SC Bold"), local(NotoSansCJKsc-Bold), local("Noto Sans CJK SC"), local("Source Han Sans SC Bold"), local("SourceHanSansSC-Bold"), local("Source Han Sans CN Bold"), local("SourceHanSansCN-Bold"), local("Source Han Sans SC"), local("Source Han Sans CN");
}
```

就確定是W6的鍋了

看一下W6的src, wtf, `local("Microsoft YaHei")`等等的非加粗字體(`W6`,`xxxBold`和`Medium`是font weight 600用字體)是甚麼鬼,前面的一堆字體沒匹配上自動給匹配非加粗的雅黑了,那當然看不見加粗

把`local("Microsoft YaHei")`等等的刪掉就好了,像這樣:

```
@font-face {
  font-family: "Han Heiti GB";
  font-weight: 600;
  src: local("Hiragino Sans GB W6"), local(HiraginoSansGB-W6), local(".PingFang SC Semibold"), local(".PingFang-SC-Semibold"), local("Lantinghei SC Demibold"), local(FZLTZHK--GBK1-0), local("Heiti SC Medium"), local("STHeitiSC-Medium"), local("Heiti SC"), local("Microsoft YaHei Bold"), local(MicrosoftYaHei-Bold), local("Noto Sans CJK SC Bold"), local(NotoSansCJKsc-Bold), local("Source Han Sans SC Bold"), local("SourceHanSansSC-Bold"), local("Source Han Sans CN Bold"), local("SourceHanSansCN-Bold");
}
```

但是這個問題解決起來比較麻煩,因為[Han](https://github.com/ethantw/Han)的repo老久沒更了(((,然後font-face無法用css override,要改的話得fork了css本地修改,把有問題的行數改了自己分發嗯(

**Comment by Ir1d** [comment]
@Voileexperiments han.css 的确我们 fork 了一个……

**Comment by CBW2007** [comment]
发现一个可行的“解决方法”，就是将<strong>标签改成<b>标签......

**Comment by CBW2007** [comment]
有加粗：Windows 10，Firefox 66.0.3 (64 位)
![firefox控制台截图20190515](https://user-images.githubusercontent.com/42204218/57775518-c9023e80-774f-11e9-8164-78cd3238e269.png)

**Comment by StudyingFather** [comment]
系统版本：Windows 10 1803

Firefox 66.0.4 （64 位）下有加粗。

Chrome 74.0.3729.157 （64 位）下没有加粗。

**Comment by Ir1d** [comment]
感觉好像是 han.css 导致的，有问题再 reopen 吧
