### ISSUE TITLE
关于支持pjax

### ISSUE THREAD

**Issue by frank-xjh** [OI-wiki/OI-wiki#881]
我采用了jquery-pjax重写material主题，目前可以在 https://test.4leaf.top/OI-Wiki/ 预览效果，适配还有问题，主要有：

1. 加载条不显示
2. 代码复制失效
3. 评论失效

怀疑是重载函数出了问题，欢迎大家一起讨论解决！

**Comment by frank-xjh** [comment]
pjax仓库在https://github.com/frank-xjh/mkdocs-material

**Comment by frank-xjh** [comment]
qaq，我关了

**Comment by Ir1d** [comment]
@frank-xjh https://github.com/MoOx/pjax 这个有没有用？看起来好像它不需要 jQuery

**Comment by YanWQ-monad** [comment]
已经发现这 3 个 bug 的原因，及解决方法：

1. 加载条不显示
  没有加载 NProgress 的 CSS；

2. 代码复制失效
  在 `application.js` 中，有这么一句（在 `app.initialize` 函数中）：

       new r.a.Event.Listener(document, "DOMContentLoaded", function() {...}).listen()

   其中 `function() {...}` 中负责代码剪贴等初始化。
   在 pjax 中，页面加载不会触发 `DOMContentLoaded` 事件，该初始化函数也不会被调用。

   解决方法：新增监听 `pjax:end` 事件。

3. 评论失效
   参考评论加载方式：`const gitalk = new Gitalk({...})`，由于 `const` 的特性，第二个页面的 Gitalk 无法覆盖上一个页面，导致加载的是上一页的评论。

   解决方法：使用 `new Gitalk({...}).render('gitalk-container')` 来加载 Gitalk。

上面的解决方法仅供参考，因为我也没有详细阅读过项目，甚至连 `application.js` minify 之前的源码也没找到（逃...

**Comment by Ir1d** [comment]
我有点不太想搞 pjax.. 因为现在想从 mkdocs 换走..

**Comment by YanWQ-monad** [comment]
好吧... 😅😅😅

**Comment by abc1763613206** [comment]
因悬挂时间过长，暂时关闭。    
或许 ng 项目可以解决这个问题？
