### ISSUE TITLE
add 后缀数组应用

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/OI-wiki#923]
首先，十分欢迎你来给 OI WIki 开 issue，在提交之前，请花时间阅读一下这个模板的内容，谢谢合作！

- 希望添加的是什么？
后缀数组应用

- 英文叫什么？
sa-application

- 有什么参考资料？

issue 标题请写为 'add ' + 要添加的内容

**Comment by ouuan** [comment]
可以 close 了吧。
